const L=(t,o,r,v,c,q,opts,a)=>({t,o,r,v,c,q,opts,a});
window.DATA={
rafael:{label:'Rafael • Finance Ireland',weeks:[
{title:'Finance in Ireland — Foundations',focus:'Entender o ecossistema financeiro irlandês e o papel do Finance Manager.',days:[
L('Como uma subsidiária irlandesa funciona','Mapear Finance, CRO, Revenue, auditors e HQ.',['Uma subsidiária irlandesa de multinacional precisa atender simultaneamente às necessidades do grupo e às obrigações locais. O Finance Manager conecta management reporting, statutory accounts, tax, treasury, controls e stakeholders.','O ponto central não é decorar toda a legislação: é saber quem é owner de cada processo, quais são os deadlines, quais evidências suportam o controle e quando escalar para tax, legal ou auditoria.'],['statutory accounts','annual return','filing deadline','management reporting','local requirements'],'O HQ pede fechamento em D+3, mas existe uma reconciliação bancária material pendente. Como equilibraria velocidade, qualidade e comunicação do risco?','Qual descrição melhor representa o Finance Manager de uma subsidiária multinacional?',['Apenas preparar demonstrações financeiras','Conectar reporting, compliance, tax, treasury, controls e stakeholders','Apenas controlar orçamento'],1),
L('CRO, Revenue e auditoria: quem recebe o quê','Distinguir os principais interlocutores externos do Finance.',['O Companies Registration Office (CRO) concentra registros societários e annual returns. A Revenue administra impostos e obrigações fiscais. Auditores independentes desafiam demonstrações, estimativas e controles conforme o escopo aplicável.','Um Controller forte mantém um compliance calendar único, com owner, reviewer, evidência, prazo e status, evitando que accounting, tax e company secretarial trabalhem em silos.'],['Companies Registration Office','Revenue','annual return','audit trail','compliance calendar'],'Você descobre uma obrigação societária a duas semanas do prazo e ninguém se considera owner. O que faz nas próximas 24 horas?','Qual órgão está associado ao annual return societário?',['CRO','Revenue','Central Bank of Ireland'],0),
L('Management reporting vs statutory reporting','Separar objetivos, usuários e controles dos dois tipos de reporte.',['Management reporting responde às perguntas da gestão: performance, forecast, margem, cash e KPIs. Statutory reporting atende requisitos contábeis e legais externos.','Os números podem nascer do mesmo ledger, mas classificações, disclosures, materialidade, calendário e revisão são diferentes. O Controller deve conseguir reconciliar as duas visões.'],['management accounts','statutory reporting','reconciliation','disclosure','materiality'],'O P&L gerencial mostra €3,2m de EBITDA, mas reclassificações estatutárias mudam a leitura do resultado operacional. Como explicaria ao CFO?','Qual é a principal diferença entre management e statutory reporting?',['Um é interno e orientado à decisão; o outro atende requisitos externos e legais','Não existe diferença','Statutory reporting serve apenas para orçamento'],0),
L('O calendário anual do Finance','Construir visão de deadlines recorrentes.',['Um finance calendar deve integrar month-end, quarter-end, year-end, tax returns, payroll, annual return, audit, board approvals e deadlines internos do grupo.','Como o programa vai até 2028/29, datas e regras específicas devem ser validadas periodicamente. A competência duradoura é manter o calendário atualizado e ter alertas, owners e backups.'],['finance calendar','quarter-end','year-end close','board approval','recurring deadline'],'Você assume uma operação sem calendário formal. Quais cinco categorias de prazo colocaria primeiro e por quê?','Qual é a melhor prática para deadlines que podem mudar até 2028?',['Memorizar datas de 2026','Usar calendário atualizado e validar regras vigentes','Ignorar até o prazo chegar'],1),
L('Finance Manager: prioridades nos primeiros 30 dias','Pensar como líder entrando numa operação nova.',['Nos primeiros 30 dias, priorize riscos materiais: caixa, fechamento, compliance, people, systems e stakeholders. Depois procure quick wins que reduzam risco ou melhorem visibilidade.','Um erro comum de líderes novos é redesenhar tudo cedo demais. Primeiro faça process walkthroughs, entenda controles e dependências, e só depois proponha mudanças.'],['risk assessment','quick win','stakeholder map','process walkthrough','control environment'],'Você começa como Financial Controller em Dublin. O fechamento atrasa, há turnover e o CFO quer forecast melhor. Quais são suas cinco prioridades?','Qual abordagem tende a ser mais eficaz nos primeiros 30 dias?',['Redesenhar todos os processos imediatamente','Entender riscos e operação antes de mudar','Focar apenas em custo'],1)
]},
{title:'Irish Statutory Reporting',focus:'Dominar o que um Controller precisa saber sobre reporting estatutário.',days:[
L('Estrutura das demonstrações financeiras','Revisar as peças básicas e o olhar do Controller.',['Balance sheet, income statement, cash flow e notes formam uma narrativa integrada. O Controller precisa garantir consistência entre ledger, disclosures e supporting schedules.','Em entrevistas, é mais forte explicar como você assegura completeness, cut-off, reconciliations e review do que simplesmente dizer que prepara demonstrações financeiras.'],['supporting schedule','cut-off','completeness','disclosure note','trial balance'],'O audit team questiona um accrual relevante sem supporting schedule robusto. Como você responderia e corrigiria o processo?','O que mais protege a qualidade das statutory accounts?',['Supporting schedules e reconciliações robustas','Apenas apresentações bonitas','Apenas o forecast'],0),
L('Materialidade e julgamento','Aplicar materialidade com bom senso gerencial.',['Materialidade não é apenas um número. Natureza, contexto e impacto no usuário importam. Um item pequeno pode ser material se envolver fraude, compliance, covenant ou related parties.','Julgamentos relevantes devem ser consistentes, documentados e revisáveis. O Controller precisa explicar a lógica, não apenas o resultado final.'],['materiality','judgement','qualitative factor','covenant','documentation'],'Uma inconsistência de €30k é pequena para o P&L, mas envolve pagamento a parte relacionada sem aprovação. Como avaliaria a materialidade?','Materialidade depende apenas do valor?',['Sim','Não; natureza e contexto também importam','Somente se o auditor disser'],1),
L('Reconciliations como controle central','Transformar reconciliação em disciplina de fechamento.',['Reconciliations conectam o ledger a evidência externa ou supporting detail e ajudam a provar existência, completude e razoabilidade.','Um processo robusto classifica contas por risco, define owner e reviewer e monitora aging de reconciling items, com escalation para itens antigos ou materiais.'],['account reconciliation','reconciling item','aging','reviewer','evidence'],'Há 18 reconciling items com mais de 90 dias. Como você os priorizaria e eliminaria?','Qual item NÃO representa boa prática de reconciliação?',['Owner e reviewer definidos','Evidência de suporte','Itens antigos sem explicação'],2),
L('Year-end close e audit readiness','Preparar a operação para auditoria sem caos.',['Audit readiness começa antes do auditor chegar. PBC list, lead schedules, contracts, reconciliations e memos de julgamento precisam ter owners e prazos.','O Finance Manager coordena qualidade, timing e comunicação para evitar que o time trabalhe apenas reagindo a solicitações.'],['PBC list','lead schedule','audit readiness','audit request','management memo'],'A auditoria envia uma PBC list extensa três semanas antes do fieldwork. Como organizaria prioridades e owners?','Quando começa audit readiness?',['No dia do fieldwork','Durante o ano, com documentação e owners','Depois da emissão das contas'],1),
L('Board e governance do reporting','Entender o fluxo de revisão e aprovação.',['Relatórios externos passam por camadas de preparação, revisão, challenge e aprovação. A governança depende de clareza sobre quem prepara, revisa e dá sign-off.','Uma boa board pack destaca decisões, riscos, exceções e ações necessárias. Detalhe operacional deve apoiar, não esconder, a mensagem executiva.'],['board pack','governance','sign-off','review layer','exception reporting'],'Você precisa levar uma issue contábil sensível ao board. Como estruturaria um slide de decisão?','Um bom board pack deve enfatizar:',['Decisões, riscos e exceções','Todos os detalhes operacionais','Somente histórico'],0)
]},
{title:'Irish Tax for Finance Leaders',focus:'Entender responsabilidades, processos e riscos tributários sem virar tax specialist.',days:[
L('Mapa tributário: CT, VAT e payroll taxes','Construir visão executiva do tax footprint.',['Para um Finance leader, a pergunta é: quais tributos afetam a entidade, quem prepara, quem revisa, quais sistemas alimentam a apuração e onde estão os riscos?','Corporation Tax, VAT e payroll taxes têm processos distintos, mas todos dependem de dados confiáveis, reconciliações e controles de mudança.'],['tax footprint','corporation tax','VAT','payroll taxes','tax compliance'],'Você encontra três planilhas manuais alimentando obrigações fiscais. Qual risco investigaria primeiro e como reduziria dependência manual?','Qual é a melhor responsabilidade do Finance Manager sobre tax?',['Ser o único especialista técnico','Garantir governance, dados, controls e escalation','Ignorar porque existe consultor externo'],1),
L('VAT — visão de processo','Entender input/output VAT e controles.',['VAT é altamente transacional. Erros de master data, tax codes, invoice quality e cross-border treatment podem se multiplicar rapidamente.','O Controller deve entender onde o VAT nasce no processo e quais reports e reconciliations detectam desvios antes do filing.'],['input VAT','output VAT','VAT code','tax determination','VAT reconciliation'],'Após uma mudança de ERP, o VAT payable cai 40% sem mudança de vendas. Como estruturaria a investigação?','Qual sinal exige investigação imediata?',['VAT muda fortemente sem explicação de negócio','Número de funcionários fica igual','O mês tem 30 dias'],0),
L('Corporation Tax — visão gerencial','Separar accounting profit, taxable profit e cash tax.',['Accounting profit e taxable profit não são necessariamente iguais. Adjustments, losses, allowances e timing differences criam a ponte entre contabilidade e base fiscal.','Finance deve acompanhar tax provision, cash tax forecast e documentação das posições materiais, mesmo quando o cálculo técnico é feito por especialistas.'],['taxable profit','tax provision','cash tax','temporary difference','tax adjustment'],'O forecast de cash tax sobe €1m sem mudança no EBITDA. Que perguntas faria ao tax team?','Accounting profit e taxable profit são sempre iguais?',['Sim','Não','Somente em multinacionais'],1),
L('Transfer Pricing e intercompany','Conectar política, documentação e execução.',['Transfer Pricing falha quando a política existe no papel, mas pricing, invoices, contracts e true-ups não seguem o desenho.','Finance precisa conectar ERP, forecasts, target margins, intercompany agreements e documentação para garantir execução consistente.'],['intercompany','arm’s length','true-up','transfer pricing policy','target margin'],'A entidade irlandesa termina o ano fora da target margin. Como coordenaria o true-up e quais áreas envolveria?','O maior risco de TP operacional é:',['Política não executada no ERP/faturamento','Ter contrato assinado','Ter forecast mensal'],0),
L('Tax governance e controles','Criar uma tax control framework enxuta.',['Tax governance define owner, review, evidence, escalation e sign-off. Terceirizar a declaração não terceiriza a responsabilidade de controle da empresa.','Boas perguntas de liderança tratam de data lineage, reconciliations, exception reports, changes in law e evidência de review.'],['tax governance','sign-off','data lineage','exception report','escalation'],'Consultor externo prepara a declaração, mas não existe reconciliação entre return e GL. Você aceita o filing? O que exige antes?','Terceirizar uma apuração elimina a responsabilidade de controle da empresa?',['Sim','Não','Apenas em VAT'],1)
]},
{title:'Treasury & Working Capital',focus:'Aplicar experiência de treasury e working capital ao contexto EMEA.',days:[
L('Cash visibility','Estruturar forecast de caixa confiável.',['Cash visibility começa com bank balances, expected collections, payables, tax, payroll e intercompany flows.','O valor do forecast está na acurácia, ownership e processo de challenge. Um modelo detalhado sem explicação de desvios não gera confiança.'],['cash visibility','cash forecast','liquidity','bank balance','forecast accuracy'],'Seu cash forecast erra €2m todos os meses. Como identificaria os drivers do erro e melhoraria accountability?','O melhor indicador de qualidade do cash forecast é:',['Acurácia e explicação dos desvios','Quantidade de abas','Número de bancos'],0),
L('Working capital drivers','Conectar DSO, DPO e inventory com decisões.',['Working capital é operacional. Finance influencia crédito, collections, payment terms, inventory e intercompany settlement.','Uma boa análise separa efeito estrutural de efeito temporário e quantifica impacto em cash conversion.'],['DSO','DPO','inventory days','collections','payment terms'],'Receita cresce 5%, mas AR cresce 25%. Qual análise faria primeiro e quem envolveria?','AR crescendo muito acima da receita normalmente sinaliza:',['Melhora de collections','Pressão em DSO/collections','Menor necessidade de caixa'],1),
L('Intercompany funding','Entender funding como decisão financeira e de governance.',['Intercompany loans exigem documentação, pricing, approvals e monitoramento. Treasury e tax precisam trabalhar juntos.','Finance acompanha maturity, interest accrual, FX exposure, cash needs e compliance das condições aprovadas.'],['intercompany loan','maturity','interest accrual','FX exposure','approval matrix'],'HQ propõe funding em USD para uma entidade com receitas em EUR. Quais riscos e mitigadores avaliaria?','Funding em moeda diferente da geração de caixa cria principalmente:',['FX exposure','Menos governança','Nenhum risco'],0),
L('Banking controls','Reforçar controles sobre pagamentos e acessos.',['Banking controls cobrem segregation of duties, maker-checker, access reviews, payment limits e incident response.','Fraude de pagamento é risco de alto impacto. Exceções de acesso precisam ser temporárias, aprovadas e monitoradas.'],['maker-checker','segregation of duties','bank mandate','payment limit','access review'],'Um gerente pede acesso emergencial para criar e aprovar pagamentos. Como responderia sem bloquear a operação?','Qual princípio reduz risco de fraude?',['Uma pessoa controla todo o fluxo','Segregation of duties','Compartilhar senhas'],1),
L('Treasury story para entrevistas','Converter experiência técnica em narrativa executiva.',['Em entrevistas, evite listar tarefas. Conte o problema, decisão, stakeholders, impacto e controle implantado.','Use números quando possível: redução de funding, melhora de forecast accuracy, renegociação de terms ou redução de risco.'],['business impact','cash optimization','funding cost','working capital initiative','control enhancement'],'Escreva uma história STAR curta sobre um projeto de cash/treasury que você liderou.','Uma boa resposta de entrevista enfatiza:',['Somente responsabilidades','Problema, ação, impacto e aprendizado','Apenas ferramentas'],1)
]}
]},
viviane:{label:'Viviane • Irish Payroll',weeks:[
{title:'Irish Payroll — Foundations',focus:'Entender o ciclo de payroll e a lógica gross-to-net.',days:[
L('Gross to net','Entender a lógica básica entre salário bruto e líquido.',['Payroll transforma remuneração contratual em net pay após impostos, contribuições e outras deductions.','A primeira habilidade é explicar gross-to-net de forma simples e identificar earnings, statutory deductions e voluntary deductions.'],['gross pay','net pay','deduction','earning','payslip'],'Um empregado diz que o salário bruto está correto, mas o líquido caiu €300. Qual seria sua sequência de investigação?','Net pay é:',['Gross pay menos deductions aplicáveis','O mesmo que gross pay','Apenas bonus'],0),
L('PAYE, USC e PRSI — visão geral','Distinguir os três componentes principais.',['PAYE é o mecanismo de retenção de Income Tax sobre remuneração. USC e PRSI são componentes distintos, com regras próprias.','O objetivo até 2028/29 é dominar a lógica e aprender a validar rates e thresholds vigentes, porque podem mudar.'],['PAYE','USC','PRSI','tax credit','rate band'],'Um funcionário pergunta por que aparecem três linhas fiscais diferentes no payslip. Como explicaria em inglês simples?','PAYE, USC e PRSI são:',['Três componentes distintos do payroll','O mesmo imposto com nomes diferentes','Benefícios voluntários'],0),
L('PPSN e employee setup','Entender dados essenciais para configurar um empregado.',['Employee setup depende de dados pessoais, employment details, payroll frequency, bank details e informação fiscal apropriada.','PPSN é importante, mas payroll também precisa de controles de qualidade, effective dates e privacidade sobre master data.'],['PPSN','employee master data','starter','bank details','pay frequency'],'Você recebe um new starter com bank details e endereço, mas sem informação fiscal suficiente. O que valida antes do payroll?','Qual é um risco importante de master data incorreto?',['Pagamento/imposto incorreto','Mais férias automaticamente','Nenhum'],0),
L('RPN e payroll data','Entender a função do Revenue Payroll Notification.',['O RPN fornece informações relevantes para o tratamento PAYE do empregado. Payroll deve trabalhar com a informação vigente e tratar exceções conforme a regra aplicável.','O fluxo mental é: employee data → Revenue information → payroll calculation → submission → payslip/payment.'],['RPN','Revenue Payroll Notification','tax credit','rate band','payroll calculation'],'O payroll system não retorna informação fiscal atualizada para um starter. Que controles aplica antes do pagamento?','O RPN está relacionado principalmente a:',['Informações usadas no cálculo PAYE','Controle de estoque','Annual return do CRO'],0),
L('O ciclo mensal de payroll','Visualizar inputs, processing, review, payment e reporting.',['Um payroll robusto começa com cut-off claro, seguido de processamento, pre-payroll validation, approvals, payment, submissions e reconciliation.','Mudanças recebidas fora do cut-off precisam de governance e exception log para evitar erros silenciosos.'],['payroll cut-off','payroll run','pre-payroll validation','approval','exception log'],'HR envia 20 salary changes depois do cut-off. Como você trataria?','Um payroll calendar ajuda principalmente a:',['Definir prazos e responsabilidades','Substituir o payroll system','Eliminar approvals'],0)
]},
{title:'PAYE / USC / PRSI in Practice',focus:'Aprender o processo e os controles, sem decorar taxas que podem mudar.',days:[
L('Tax credits e rate bands','Entender por que dois empregados com mesmo gross podem ter net diferente.',['Tax credits e rate bands influenciam o PAYE individual. Por isso, mesmo gross salary não significa necessariamente o mesmo net pay.','Payroll não deve adivinhar a situação fiscal. Deve usar a informação correta disponível e explicar ao empregado quando a diferença vem de tax basis.'],['tax credit','rate band','standard rate','marginal rate','tax basis'],'Dois empregados ganham €60k, mas têm PAYE diferente. Como explica a diferença?','Dois empregados com o mesmo gross sempre terão o mesmo PAYE?',['Sim','Não','Somente se forem casados'],1),
L('Emergency basis','Entender quando falta informação fiscal apropriada.',['Quando a informação fiscal correta não está disponível, regras de emergency basis podem ser aplicáveis.','Operacionalmente, payroll deve reconhecer a exceção, aplicar a regra vigente, documentar e orientar o empregado sobre próximos passos sem prometer ajustes fora de seu controle.'],['emergency tax','emergency basis','missing RPN','employee query','tax correction'],'Um starter recebe net abaixo do esperado por emergency basis. Como responde sem prometer algo que depende da Revenue?','A melhor resposta ao empregado é:',['Explicar a causa e orientar próximos passos','Alterar manualmente sem base','Ignorar'],0),
L('PRSI categories','Entender que PRSI depende da situação do empregado.',['PRSI não é uma única regra para todos. Classes e tratamento podem variar conforme categoria de emprego e circunstâncias.','A competência importante é identificar quando a classificação precisa ser revista e validar tabelas vigentes.'],['PRSI class','insurable employment','employee contribution','employer contribution','classification'],'Um empregado muda de situação contratual. Que informação de payroll você revisa imediatamente?','PRSI deve ser tratado como:',['Uma regra única e imutável','Uma contribuição com classes e regras específicas','Um benefício voluntário'],1),
L('USC checks','Criar controles simples sobre USC.',['USC depende de rendimentos e bands aplicáveis. Payroll deve validar parâmetros do sistema e reconciliar valores calculados.','Variance analysis contra o mês anterior e year-to-date ajuda a detectar anomalias antes do pagamento.'],['USC band','threshold','year-to-date','variance','payroll parameter'],'USC total aumenta 30% sem headcount, bonus ou salary increase. O que você investiga?','Qual controle ajuda a detectar erro em USC?',['Variance analysis','Ignorar o mês anterior','Comparar com estoque'],0),
L('Explicando payslip em inglês','Ganhar confiança para responder employee queries.',['Uma resposta profissional é curta, clara e não defensiva: confirmar a dúvida, explicar a lógica conhecida e dizer o próximo passo.','Evite jargão excessivo. Payroll é também employee service e precisa construir confiança.'],['payslip query','deduction','tax basis','year-to-date','I will review'],'Responda em inglês: “My net pay is lower this month. Did payroll make a mistake?”','Uma boa resposta de payroll deve ser:',['Clara, factual e orientada ao próximo passo','Defensiva','Cheia de jargão'],0)
]},
{title:'Employee Lifecycle',focus:'Dominar os pontos de payroll do new starter ao leaver.',days:[
L('New starter checklist','Montar um checklist de admissão.',['Starter setup exige dados completos, approval, effective date, payroll eligibility e informação fiscal adequada.','Um checklist consistente reduz missing pay, duplicate pay, bank errors e tax issues.'],['new starter','effective date','employee ID','starter checklist','payroll eligibility'],'Um colaborador começa amanhã e HR envia os dados hoje. O que é must-have para entrar na folha?','O maior benefício de um starter checklist é:',['Consistência e redução de erros','Mais emails','Eliminar approvals'],0),
L('Salary changes e retroactivity','Tratar alterações com effective date e evidência.',['Salary changes precisam de autorização, effective date e controle de retroactivity.','Mudanças retroativas aumentam risco e precisam aparecer claramente no payroll variance analysis e no audit trail.'],['salary change','effective date','retroactive pay','approval','variance'],'HR envia aumento retroativo de três meses sem approval anexada. Você processa? Explique.','Antes de processar alteração salarial, payroll precisa de:',['Approval e effective date','Apenas pedido verbal','Nada'],0),
L('Leave e payroll','Entender como leave afeta pagamento e reporting.',['Annual leave, sick leave e family-related leave podem ter tratamentos diferentes conforme law, policy e circumstances.','Payroll precisa conectar HR data, effective dates e regra vigente antes de calcular paid ou unpaid leave.'],['annual leave','sick leave','maternity leave','paid leave','unpaid leave'],'Um empregado está em leave, mas recebe bonus no mesmo mês. Que dados e políticas você valida?','Leave deve ser processado com base em:',['HR data, policy e regra vigente','Suposição','Preferência verbal do empregado'],0),
L('Leavers e final pay','Fechar corretamente o ciclo do empregado.',['Final pay pode incluir salário proporcional, deductions e outros valores devidos conforme política e regra aplicável.','O leaver precisa ser cessado corretamente no payroll e em sistemas relacionados, com termination date consistente.'],['leaver','final pay','cessation','unused leave','termination date'],'Funcionário sai no dia 17 e tem férias acumuladas. Quais informações você coleta antes do final pay?','Um leaver exige principalmente:',['Final calculation + cessation controls','Apenas retirar do email','Nenhuma ação'],0),
L('Employee queries','Estruturar atendimento eficiente.',['Employee queries devem ter SLA, categorização, owner e histórico. Isso ajuda a distinguir dúvida pontual de problema sistêmico.','Um bom Payroll Specialist identifica se o root cause está em payroll calculation, HR master data, tax information ou communication.'],['employee query','SLA','root cause','case log','resolution'],'Você recebe 25 tickets sobre a mesma deduction. O que isso sugere e qual seria sua próxima ação?','Muitos tickets iguais podem indicar:',['Problema sistêmico ou comunicação falha','Coincidência sem importância','Necessidade de ignorar'],0)
]},
{title:'Payroll Controls & Reconciliation',focus:'Construir confiabilidade, controles e linguagem de entrevista.',days:[
L('Pre-payroll validation','Detectar erros antes do pagamento.',['Pre-payroll checks procuram outliers: variações grandes de net, duplicate payments, negative pay, missing starters/leavers e bonus inesperado.','O objetivo é impedir que um erro detectável chegue ao banco e ao empregado.'],['pre-payroll validation','outlier','duplicate payment','negative net','exception report'],'Um funcionário aparece com net 4x maior que no mês anterior. Como você investiga antes de aprovar?','Pre-payroll validation serve para:',['Detectar exceções antes do pagamento','Substituir HR','Criar contratos'],0),
L('Payroll reconciliation','Reconciliar payroll register, bank e GL.',['Payroll reconciliation conecta o que foi calculado, pago e contabilizado.','Diferenças precisam ter owner, explicação e resolução. Um payroll “fechado” sem reconciliação é um processo incompleto.'],['payroll register','bank reconciliation','GL interface','payroll journal','reconciling item'],'Payroll register = €1.2m e banco = €1.18m. Quais hipóteses você testa primeiro?','Payroll reconciliation conecta:',['Payroll, payment e accounting','Somente férias','Somente headcount'],0),
L('Variance analysis','Explicar movimentos mês a mês.',['Variance analysis separa movimento esperado de exceção. Headcount, bonus, overtime, salary increases, leavers e one-offs são drivers comuns.','Uma boa explicação é quantificada, reconciliável e orientada ao que precisa de ação.'],['payroll variance','headcount movement','bonus','one-off','driver'],'Payroll sobe 12%. Monte uma explicação com três drivers possíveis e como validaria cada um.','Uma boa variance explanation é:',['Quantificada e ligada a drivers','“Subiu porque subiu”','Sem números'],0),
L('Payroll controls e fraud risk','Entender riscos de acesso e master data.',['Mudanças de bank details, salary e employee master data são áreas sensíveis e precisam de evidência e segregação.','Controles típicos incluem maker-checker, access review, change reports e independent approval.'],['maker-checker','access review','bank detail change','master data','approval evidence'],'O mesmo usuário consegue alterar bank details e liberar pagamento. Qual risco existe e que controle você implementa?','Qual controle reduz esse risco?',['Segregation of duties','Senha compartilhada','Sem revisão'],0),
L('Payroll interview story','Transformar experiência em narrativa profissional.',['Mesmo sem experiência irlandesa prévia, você pode demonstrar domínio de payroll process, controls, employee service e learning agility.','Use exemplos concretos de volume, deadline, error prevention, reconciliation, stakeholder management e melhoria de processo.'],['payroll cycle','accuracy','deadline','stakeholder','continuous improvement'],'Prepare uma resposta de 60 segundos em inglês para: “Tell me about your payroll experience and why Ireland?”','Uma boa resposta de entrevista deve enfatizar:',['Impacto, processo e aprendizado','Só título do cargo','Somente salário'],0)
]}
]}}
};