import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {LESSON_MODULES} from '../src/learning/lessonModules.ts';
import {ACCA_A1_MODEL_ID,ACCA_A1_MODEL_SLUG,ACCA_A2_MODEL_ID,ACCA_A2_MODEL_SLUG,ACCA_B3_MODEL_ID,ACCA_B3_MODEL_SLUG,ACCA_B4_MODEL_ID,ACCA_B4_MODEL_SLUG,ACCA_B5_MODEL_ID,ACCA_B5_MODEL_SLUG,ACCA_B6_MODEL_ID,ACCA_B6_MODEL_SLUG,ACCA_B7_MODEL_ID,ACCA_B7_MODEL_SLUG,ACCA_B8_MODEL_ID,ACCA_B8_MODEL_SLUG,ACCA_B9_MODEL_ID,ACCA_B9_MODEL_SLUG,ACCA_B10_MODEL_ID,ACCA_B10_MODEL_SLUG,ACCA_B11_MODEL_ID,ACCA_B11_MODEL_SLUG,ACCA_B12_MODEL_ID,ACCA_B12_MODEL_SLUG,LOCAL_MODEL_LESSONS,curriculumModelPreviewEnabled,isLocalModelLesson,localModelCodeFor} from '../src/learning/localModelLessonRegistry.ts';
import {ACCA_A1_MODEL_MODULE,ACCA_A1_PREMIUM_AUDIO_OUTLINE,ACCA_A1_PROFESSOR_GUIDE,localModelLessonFor} from '../src/learning/localModelLessonModules.ts';
import {ACCA_A2_MODEL_MODULE,ACCA_A2_PREMIUM_AUDIO_OUTLINE,ACCA_A2_PROFESSOR_GUIDE,localModelA2For} from '../src/learning/localModelLessonA2.ts';
import {ACCA_B3_MODEL_MODULE,ACCA_B3_PREMIUM_AUDIO_OUTLINE,ACCA_B3_PROFESSOR_GUIDE,localModelB3For} from '../src/learning/localModelLessonB3.ts';
import {ACCA_B4_MODEL_MODULE,ACCA_B4_PREMIUM_AUDIO_OUTLINE,ACCA_B4_PROFESSOR_GUIDE,localModelB4For} from '../src/learning/localModelLessonB4.ts';
import {ACCA_B5_MODEL_MODULE,ACCA_B5_PREMIUM_AUDIO_OUTLINE,ACCA_B5_PROFESSOR_GUIDE,localModelB5For} from '../src/learning/localModelLessonB5.ts';
import {ACCA_B6_MODEL_MODULE,ACCA_B6_PREMIUM_AUDIO_OUTLINE,ACCA_B6_PROFESSOR_GUIDE,localModelB6For} from '../src/learning/localModelLessonB6.ts';
import {ACCA_B7_MODEL_MODULE,ACCA_B7_PREMIUM_AUDIO_OUTLINE,ACCA_B7_PROFESSOR_GUIDE,localModelB7For} from '../src/learning/localModelLessonB7.ts';
import {ACCA_B8_MODEL_MODULE,ACCA_B8_PREMIUM_AUDIO_OUTLINE,ACCA_B8_PROFESSOR_GUIDE,localModelB8For} from '../src/learning/localModelLessonB8.ts';
import {ACCA_B9_MODEL_MODULE,ACCA_B9_PREMIUM_AUDIO_OUTLINE,ACCA_B9_PROFESSOR_GUIDE,localModelB9For} from '../src/learning/localModelLessonB9.ts';
import {ACCA_B10_MODEL_MODULE,ACCA_B10_PREMIUM_AUDIO_OUTLINE,ACCA_B10_PROFESSOR_GUIDE,localModelB10For} from '../src/learning/localModelLessonB10.ts';
import {ACCA_B11_MODEL_MODULE,ACCA_B11_PREMIUM_AUDIO_OUTLINE,ACCA_B11_PROFESSOR_GUIDE,localModelB11For} from '../src/learning/localModelLessonB11.ts';
import {ACCA_B12_MODEL_MODULE,ACCA_B12_PREMIUM_AUDIO_OUTLINE,ACCA_B12_PROFESSOR_GUIDE,localModelB12For} from '../src/learning/localModelLessonB12.ts';
import {loadReviewedRuntimeModuleFor} from '../src/learning/loadReviewedRuntimeModule.ts';
const models=[ACCA_A1_MODEL_MODULE,ACCA_A2_MODEL_MODULE,ACCA_B3_MODEL_MODULE,ACCA_B4_MODEL_MODULE,ACCA_B5_MODEL_MODULE,ACCA_B6_MODEL_MODULE,ACCA_B7_MODEL_MODULE,ACCA_B8_MODEL_MODULE,ACCA_B9_MODEL_MODULE,ACCA_B10_MODEL_MODULE,ACCA_B11_MODEL_MODULE,ACCA_B12_MODEL_MODULE];
test('twelve local ACCA models require exact identity and explicit Preview',()=>{
 assert.equal(curriculumModelPreviewEnabled('?curriculumPreview=1'),true);assert.equal(curriculumModelPreviewEnabled(''),false);
 assert.deepEqual(LOCAL_MODEL_LESSONS.map(x=>x.sequence),[1,2,3,4,5,6,7,8,9,10,11,12]);assert.ok(LOCAL_MODEL_LESSONS.every(x=>x.origin==='local-model'));
 assert.equal(localModelCodeFor('finance',{id:ACCA_A1_MODEL_ID,slug:ACCA_A1_MODEL_SLUG}),'A1');assert.equal(localModelCodeFor('finance',{id:ACCA_A2_MODEL_ID,slug:ACCA_A2_MODEL_SLUG}),'A2');assert.equal(localModelCodeFor('finance',{id:ACCA_B3_MODEL_ID,slug:ACCA_B3_MODEL_SLUG}),'B3');assert.equal(localModelCodeFor('finance',{id:ACCA_B4_MODEL_ID,slug:ACCA_B4_MODEL_SLUG}),'B4');assert.equal(localModelCodeFor('finance',{id:ACCA_B5_MODEL_ID,slug:ACCA_B5_MODEL_SLUG}),'B5');assert.equal(localModelCodeFor('finance',{id:ACCA_B6_MODEL_ID,slug:ACCA_B6_MODEL_SLUG}),'B6');assert.equal(localModelCodeFor('finance',{id:ACCA_B7_MODEL_ID,slug:ACCA_B7_MODEL_SLUG}),'B7');assert.equal(localModelCodeFor('finance',{id:ACCA_B8_MODEL_ID,slug:ACCA_B8_MODEL_SLUG}),'B8');assert.equal(localModelCodeFor('finance',{id:ACCA_B9_MODEL_ID,slug:ACCA_B9_MODEL_SLUG}),'B9');assert.equal(localModelCodeFor('finance',{id:ACCA_B10_MODEL_ID,slug:ACCA_B10_MODEL_SLUG}),'B10');assert.equal(localModelCodeFor('finance',{id:ACCA_B11_MODEL_ID,slug:ACCA_B11_MODEL_SLUG}),'B11');assert.equal(localModelCodeFor('finance',{id:ACCA_B12_MODEL_ID,slug:ACCA_B12_MODEL_SLUG}),'B12');
 assert.equal(isLocalModelLesson('finance',{id:ACCA_A2_MODEL_ID,slug:ACCA_A1_MODEL_SLUG}),false);assert.equal(isLocalModelLesson('english',{id:ACCA_A2_MODEL_ID,slug:ACCA_A2_MODEL_SLUG}),false);
});
for(const m of models)test(m.title+' has the complete written shape and sitting gate',()=>{
 assert.equal(m.track,'finance');assert.equal(m.sections.length,4);assert.equal(m.terms.length,6);assert.equal(m.practiceExercises?.length,3);assert.equal(m.checkpoint.length,5);assert.equal(m.caseStudy.reviewChecks.length,4);assert.ok(m.visual.rows.length>=4);assert.match(m.scope,/selected exam sitting/i);assert.match(m.scope,/not ACCA approval|not an ACCA-approved course/i);
 for(const s of m.sections)assert.ok(s.paragraphs.join(' ').split(/\s+/).length>70);
});
test('B9 and B10 calculations and current syllabus boundaries reconcile',()=>{
 assert.equal(ACCA_B9_MODEL_MODULE.title,'ACCA FR B9 · Reporting financial and non-financial performance');
 assert.deepEqual(ACCA_B9_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ifrs-5','ifrs-18','ias-8','ias-33','ifrs-s1']);
 assert.match(ACCA_B9_MODEL_MODULE.caseStudy.modelAnswer,/CU40,000 loss/);assert.match(ACCA_B9_MODEL_MODULE.caseStudy.modelAnswer,/2,150,000/);assert.match(ACCA_B9_MODEL_MODULE.caseStudy.modelAnswer,/41\.86 cents/);assert.match(ACCA_B9_MODEL_MODULE.caseStudy.modelAnswer,/37\.06 cents/);assert.match(ACCA_B9_MODEL_MODULE.caseStudy.modelAnswer,/5\.58 cents loss/);
 assert.equal(ACCA_B10_MODEL_MODULE.title,'ACCA FR B10 · Revenue');assert.deepEqual(ACCA_B10_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ifrs-15']);
 assert.match(ACCA_B10_MODEL_MODULE.caseStudy.modelAnswer,/CU540 to the handset and CU540 to service/);assert.match(ACCA_B10_MODEL_MODULE.caseStudy.modelAnswer,/cumulative revenue CU675/);assert.match(ACCA_B10_MODEL_MODULE.caseStudy.modelAnswer,/CU405/);assert.match(ACCA_B10_MODEL_MODULE.caseStudy.modelAnswer,/closing cost asset of CU81/);
});
test('B11 and B12 calculations and current syllabus boundaries reconcile',()=>{
 assert.equal(ACCA_B11_MODEL_MODULE.title,'ACCA FR B11 · Government grants');assert.deepEqual(ACCA_B11_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ias-20']);
 assert.match(ACCA_B11_MODEL_MODULE.caseStudy.modelAnswer,/CU100,000 depreciation/);assert.match(ACCA_B11_MODEL_MODULE.caseStudy.modelAnswer,/CU20,000 grant income/);assert.match(ACCA_B11_MODEL_MODULE.caseStudy.modelAnswer,/closing deferred income is CU80,000/);assert.match(ACCA_B11_MODEL_MODULE.caseStudy.modelAnswer,/closing PPE is CU320,000/);
 assert.equal(ACCA_B12_MODEL_MODULE.title,'ACCA FR B12 · Foreign currency transactions');assert.deepEqual(ACCA_B12_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ias-21']);
 assert.match(ACCA_B12_MODEL_MODULE.caseStudy.modelAnswer,/CU80,000/);assert.match(ACCA_B12_MODEL_MODULE.caseStudy.modelAnswer,/CU86,000/);assert.match(ACCA_B12_MODEL_MODULE.caseStudy.modelAnswer,/CU6,000 exchange loss/);assert.match(ACCA_B12_MODEL_MODULE.caseStudy.modelAnswer,/CU2,000 exchange gain/);
});
test('reviewed loader keeps all twelve models in separate exact lazy paths',async()=>{
 assert.equal(localModelLessonFor('finance',{id:ACCA_A1_MODEL_ID,slug:ACCA_A1_MODEL_SLUG}),ACCA_A1_MODEL_MODULE);assert.equal(localModelA2For('finance',{id:ACCA_A2_MODEL_ID,slug:ACCA_A2_MODEL_SLUG}),ACCA_A2_MODEL_MODULE);assert.equal(localModelB3For('finance',{id:ACCA_B3_MODEL_ID,slug:ACCA_B3_MODEL_SLUG}),ACCA_B3_MODEL_MODULE);assert.equal(localModelB4For('finance',{id:ACCA_B4_MODEL_ID,slug:ACCA_B4_MODEL_SLUG}),ACCA_B4_MODEL_MODULE);assert.equal(localModelB5For('finance',{id:ACCA_B5_MODEL_ID,slug:ACCA_B5_MODEL_SLUG}),ACCA_B5_MODEL_MODULE);assert.equal(localModelB6For('finance',{id:ACCA_B6_MODEL_ID,slug:ACCA_B6_MODEL_SLUG}),ACCA_B6_MODEL_MODULE);assert.equal(localModelB7For('finance',{id:ACCA_B7_MODEL_ID,slug:ACCA_B7_MODEL_SLUG}),ACCA_B7_MODEL_MODULE);assert.equal(localModelB8For('finance',{id:ACCA_B8_MODEL_ID,slug:ACCA_B8_MODEL_SLUG}),ACCA_B8_MODEL_MODULE);assert.equal(localModelB9For('finance',{id:ACCA_B9_MODEL_ID,slug:ACCA_B9_MODEL_SLUG}),ACCA_B9_MODEL_MODULE);assert.equal(localModelB10For('finance',{id:ACCA_B10_MODEL_ID,slug:ACCA_B10_MODEL_SLUG}),ACCA_B10_MODEL_MODULE);assert.equal(localModelB11For('finance',{id:ACCA_B11_MODEL_ID,slug:ACCA_B11_MODEL_SLUG}),ACCA_B11_MODEL_MODULE);assert.equal(localModelB12For('finance',{id:ACCA_B12_MODEL_ID,slug:ACCA_B12_MODEL_SLUG}),ACCA_B12_MODEL_MODULE);
 assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_A1_MODEL_ID,slug:ACCA_A1_MODEL_SLUG}),ACCA_A1_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_A2_MODEL_ID,slug:ACCA_A2_MODEL_SLUG}),ACCA_A2_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B3_MODEL_ID,slug:ACCA_B3_MODEL_SLUG}),ACCA_B3_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B4_MODEL_ID,slug:ACCA_B4_MODEL_SLUG}),ACCA_B4_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B5_MODEL_ID,slug:ACCA_B5_MODEL_SLUG}),ACCA_B5_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B6_MODEL_ID,slug:ACCA_B6_MODEL_SLUG}),ACCA_B6_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B7_MODEL_ID,slug:ACCA_B7_MODEL_SLUG}),ACCA_B7_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B8_MODEL_ID,slug:ACCA_B8_MODEL_SLUG}),ACCA_B8_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B9_MODEL_ID,slug:ACCA_B9_MODEL_SLUG}),ACCA_B9_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B10_MODEL_ID,slug:ACCA_B10_MODEL_SLUG}),ACCA_B10_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B11_MODEL_ID,slug:ACCA_B11_MODEL_SLUG}),ACCA_B11_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B12_MODEL_ID,slug:ACCA_B12_MODEL_SLUG}),ACCA_B12_MODEL_MODULE);
 assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_A2_MODEL_ID,slug:ACCA_A1_MODEL_SLUG}),null);
 const entry=fs.readFileSync('src/learning/loadReviewedRuntimeModule.ts','utf8');assert.match(entry,/import\('\.\/localModelLessonModules\.ts'\)/);assert.match(entry,/import\('\.\/localModelLessonA2\.ts'\)/);assert.match(entry,/import\('\.\/localModelLessonB3\.ts'\)/);assert.match(entry,/import\('\.\/localModelLessonB4\.ts'\)/);assert.match(entry,/import\('\.\/localModelLessonB5\.ts'\)/);assert.match(entry,/import\('\.\/localModelLessonB6\.ts'\)/);assert.match(entry,/import\('\.\/localModelLessonB7\.ts'\)/);assert.match(entry,/import\('\.\/localModelLessonB8\.ts'\)/);assert.match(entry,/import\('\.\/localModelLessonB9\.ts'\)/);assert.match(entry,/import\('\.\/localModelLessonB10\.ts'\)/);assert.match(entry,/import\('\.\/localModelLessonB11\.ts'\)/);assert.match(entry,/import\('\.\/localModelLessonB12\.ts'\)/);
});
test('English Golden Lesson retains contextual grammar practice',()=>{const xs=LESSON_MODULES.english.practiceExercises??[];assert.deepEqual(xs.map(x=>x.id),['eng-grammar-p1','eng-grammar-p2','eng-grammar-p3']);assert.match(xs[0].answer,/was waiting.*called/i);});
test('both Professor and Premium Audio references remain offline',()=>{
 for(const audio of [ACCA_A1_PREMIUM_AUDIO_OUTLINE,ACCA_A2_PREMIUM_AUDIO_OUTLINE,ACCA_B3_PREMIUM_AUDIO_OUTLINE,ACCA_B4_PREMIUM_AUDIO_OUTLINE,ACCA_B5_PREMIUM_AUDIO_OUTLINE,ACCA_B6_PREMIUM_AUDIO_OUTLINE,ACCA_B7_PREMIUM_AUDIO_OUTLINE,ACCA_B8_PREMIUM_AUDIO_OUTLINE,ACCA_B9_PREMIUM_AUDIO_OUTLINE,ACCA_B10_PREMIUM_AUDIO_OUTLINE,ACCA_B11_PREMIUM_AUDIO_OUTLINE,ACCA_B12_PREMIUM_AUDIO_OUTLINE]){assert.equal(audio.status,'outline_only_no_generation');assert.match(audio.preservation,/No existing Premium Audio/i);}
 for(const guide of [ACCA_A1_PROFESSOR_GUIDE,ACCA_A2_PROFESSOR_GUIDE,ACCA_B3_PROFESSOR_GUIDE,ACCA_B4_PROFESSOR_GUIDE,ACCA_B5_PROFESSOR_GUIDE,ACCA_B6_PROFESSOR_GUIDE,ACCA_B7_PROFESSOR_GUIDE,ACCA_B8_PROFESSOR_GUIDE,ACCA_B9_PROFESSOR_GUIDE,ACCA_B10_PROFESSOR_GUIDE,ACCA_B11_PROFESSOR_GUIDE,ACCA_B12_PROFESSOR_GUIDE]){assert.equal(guide.status,'offline_authored_not_live');assert.match(guide.evidenceBoundary,/must never enter|Only actual integrated session turns/i);}
 for(const path of ['src/learning/localModelLessonRegistry.ts','src/learning/localModelLessonModules.ts','src/learning/localModelLessonA2.ts','src/learning/localModelLessonB3.ts','src/learning/localModelLessonB4.ts','src/learning/localModelLessonB5.ts','src/learning/localModelLessonB6.ts','src/learning/localModelLessonB7.ts','src/learning/localModelLessonB8.ts','src/learning/localModelLessonB9.ts','src/learning/localModelLessonB10.ts','src/learning/localModelLessonB11.ts','src/learning/localModelLessonB12.ts','src/learning/loadReviewedRuntimeModule.ts']){const raw=fs.readFileSync(path,'utf8');for(const banned of ['supabase.','fetch(','.insert(','.update(','functions.invoke','connectProfessor(','PremiumAudioPanel'])assert.ok(!raw.includes(banned),path+': '+banned);}
});
test('application labels local models honestly and excludes them by default',()=>{const raw=fs.readFileSync('src/App.tsx','utf8');assert.match(raw,/curriculumModelPreviewEnabled\(window.location.search\)/);assert.match(raw,/Model · local/);assert.match(raw,/Local preview · no providers/);});
