import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {LESSON_MODULES} from '../src/learning/lessonModules.ts';
import {ACCA_A1_MODEL_ID,ACCA_A1_MODEL_SLUG,ACCA_A2_MODEL_ID,ACCA_A2_MODEL_SLUG,ACCA_A3_MODEL_ID,ACCA_A3_MODEL_SLUG,ACCA_A4_MODEL_ID,ACCA_A4_MODEL_SLUG,ACCA_B1_MODEL_ID,ACCA_B1_MODEL_SLUG,ACCA_B2_MODEL_ID,ACCA_B2_MODEL_SLUG,ACCA_B3_MODEL_ID,ACCA_B3_MODEL_SLUG,ACCA_B4_MODEL_ID,ACCA_B4_MODEL_SLUG,ACCA_B5_MODEL_ID,ACCA_B5_MODEL_SLUG,ACCA_B6_MODEL_ID,ACCA_B6_MODEL_SLUG,ACCA_B7_MODEL_ID,ACCA_B7_MODEL_SLUG,ACCA_B8_MODEL_ID,ACCA_B8_MODEL_SLUG,ACCA_B9_MODEL_ID,ACCA_B9_MODEL_SLUG,ACCA_B10_MODEL_ID,ACCA_B10_MODEL_SLUG,ACCA_B11_MODEL_ID,ACCA_B11_MODEL_SLUG,ACCA_B12_MODEL_ID,ACCA_B12_MODEL_SLUG,ACCA_C1_MODEL_ID,ACCA_C1_MODEL_SLUG,ACCA_C2_MODEL_ID,ACCA_C2_MODEL_SLUG,ACCA_C3_MODEL_ID,ACCA_C3_MODEL_SLUG,ACCA_C4_MODEL_ID,ACCA_C4_MODEL_SLUG,ACCA_D1_MODEL_ID,ACCA_D1_MODEL_SLUG,ACCA_D2_MODEL_ID,ACCA_D2_MODEL_SLUG,ACCA_E_MODEL_ID,ACCA_E_MODEL_SLUG,LOCAL_MODEL_LESSONS,isLocalModelLesson,localModelCodeFor} from '../src/learning/localModelLessonRegistry.ts';
import {curriculumModelPreviewEnabled,curriculumPreviewBuildEnabled,LEARNING_HUB_PREVIEW_BRANCH,LEARNING_HUB_AUDIO_PREVIEW_BRANCH} from '../src/config/curriculumPreview.ts';
import {ACCA_A1_MODEL_MODULE,ACCA_A1_PREMIUM_AUDIO_OUTLINE,ACCA_A1_PROFESSOR_GUIDE,localModelLessonFor} from '../src/learning/localModelLessonModules.ts';
import {ACCA_A2_MODEL_MODULE,ACCA_A2_PREMIUM_AUDIO_OUTLINE,ACCA_A2_PROFESSOR_GUIDE,localModelA2For} from '../src/learning/localModelLessonA2.ts';
import {ACCA_A3_MODEL_MODULE,ACCA_A3_PREMIUM_AUDIO_OUTLINE,ACCA_A3_PROFESSOR_GUIDE,localModelA3For} from '../src/learning/localModelLessonA3.ts';
import {ACCA_A4_MODEL_MODULE,ACCA_A4_PREMIUM_AUDIO_OUTLINE,ACCA_A4_PROFESSOR_GUIDE,localModelA4For} from '../src/learning/localModelLessonA4.ts';
import {ACCA_B1_MODEL_MODULE,ACCA_B1_PREMIUM_AUDIO_OUTLINE,ACCA_B1_PROFESSOR_GUIDE,localModelB1For} from '../src/learning/localModelLessonB1.ts';
import {ACCA_B2_MODEL_MODULE,ACCA_B2_PREMIUM_AUDIO_OUTLINE,ACCA_B2_PROFESSOR_GUIDE,localModelB2For} from '../src/learning/localModelLessonB2.ts';
import {ACCA_B3_MODEL_MODULE,ACCA_B3_PREMIUM_AUDIO_OUTLINE,ACCA_B3_PROFESSOR_GUIDE,localModelB3For} from '../src/learning/localModelLessonB3.ts';
import {ACCA_B4_MODEL_MODULE,ACCA_B4_PREMIUM_AUDIO_OUTLINE,ACCA_B4_PROFESSOR_GUIDE,localModelB4For} from '../src/learning/localModelLessonB4.ts';
import {ACCA_B5_MODEL_MODULE,ACCA_B5_PREMIUM_AUDIO_OUTLINE,ACCA_B5_PROFESSOR_GUIDE,localModelB5For} from '../src/learning/localModelLessonB5.ts';
import {ACCA_B6_MODEL_MODULE,ACCA_B6_PREMIUM_AUDIO_OUTLINE,ACCA_B6_PROFESSOR_GUIDE,localModelB6For} from '../src/learning/localModelLessonB6.ts';
import {ACCA_B7_MODEL_MODULE,ACCA_B7_PREMIUM_AUDIO_OUTLINE,ACCA_B7_PROFESSOR_GUIDE,localModelB7For} from '../src/learning/localModelLessonB7.ts';
import {ACCA_B8_MODEL_MODULE,ACCA_B8_PREMIUM_AUDIO_OUTLINE,ACCA_B8_PROFESSOR_GUIDE,localModelB8For} from '../src/learning/localModelLessonB8.ts';
import {ACCA_B9_MODEL_MODULE,ACCA_B9_PREMIUM_AUDIO_OUTLINE,ACCA_B9_PROFESSOR_GUIDE,localModelB9For} from '../src/learning/localModelLessonB9.ts';
import {ACCA_B10_MODEL_MODULE,ACCA_B10_PREMIUM_AUDIO_OUTLINE,ACCA_B10_PROFESSOR_GUIDE,localModelB10For} from '../src/learning/localModelLessonB10.ts';
import {ACCA_B11_MODEL_MODULE,ACCA_B11_PREMIUM_AUDIO_OUTLINE,ACCA_B11_PROFESSOR_GUIDE,localModelB11For} from '../src/learning/localModelLessonB11.ts';
import {ACCA_B12_MODEL_MODULE,ACCA_B12_PREMIUM_AUDIO_OUTLINE,ACCA_B12_PROFESSOR_GUIDE,localModelB12For} from '../src/learning/localModelLessonB12.ts';
import {ACCA_C1_MODEL_MODULE,ACCA_C1_PREMIUM_AUDIO_OUTLINE,ACCA_C1_PROFESSOR_GUIDE,localModelC1For} from '../src/learning/localModelLessonC1.ts';
import {ACCA_C2_MODEL_MODULE,ACCA_C2_PREMIUM_AUDIO_OUTLINE,ACCA_C2_PROFESSOR_GUIDE,localModelC2For} from '../src/learning/localModelLessonC2.ts';
import {ACCA_C3_MODEL_MODULE,ACCA_C3_PREMIUM_AUDIO_OUTLINE,ACCA_C3_PROFESSOR_GUIDE,localModelC3For} from '../src/learning/localModelLessonC3.ts';
import {ACCA_C4_MODEL_MODULE,ACCA_C4_PREMIUM_AUDIO_OUTLINE,ACCA_C4_PROFESSOR_GUIDE,localModelC4For} from '../src/learning/localModelLessonC4.ts';
import {ACCA_D1_MODEL_MODULE,ACCA_D1_PREMIUM_AUDIO_OUTLINE,ACCA_D1_PROFESSOR_GUIDE,localModelD1For} from '../src/learning/localModelLessonD1.ts';
import {ACCA_D2_MODEL_MODULE,ACCA_D2_PREMIUM_AUDIO_OUTLINE,ACCA_D2_PROFESSOR_GUIDE,localModelD2For} from '../src/learning/localModelLessonD2.ts';
import {ACCA_E_MODEL_MODULE,ACCA_E_PREMIUM_AUDIO_OUTLINE,ACCA_E_PROFESSOR_GUIDE,localModelEFor} from '../src/learning/localModelLessonE.ts';
import {loadReviewedRuntimeModuleFor} from '../src/learning/loadReviewedRuntimeModule.ts';
const models=[ACCA_A1_MODEL_MODULE,ACCA_A2_MODEL_MODULE,ACCA_A3_MODEL_MODULE,ACCA_A4_MODEL_MODULE,ACCA_B1_MODEL_MODULE,ACCA_B2_MODEL_MODULE,ACCA_B3_MODEL_MODULE,ACCA_B4_MODEL_MODULE,ACCA_B5_MODEL_MODULE,ACCA_B6_MODEL_MODULE,ACCA_B7_MODEL_MODULE,ACCA_B8_MODEL_MODULE,ACCA_B9_MODEL_MODULE,ACCA_B10_MODEL_MODULE,ACCA_B11_MODEL_MODULE,ACCA_B12_MODEL_MODULE,ACCA_C1_MODEL_MODULE,ACCA_C2_MODEL_MODULE,ACCA_C3_MODEL_MODULE,ACCA_C4_MODEL_MODULE,ACCA_D1_MODEL_MODULE,ACCA_D2_MODEL_MODULE,ACCA_E_MODEL_MODULE];
test('twenty-three local ACCA models require exact identity and the isolated Preview gate',()=>{
 assert.equal(curriculumModelPreviewEnabled('?curriculumPreview=1'),true);assert.equal(curriculumModelPreviewEnabled('',false),false);assert.equal(curriculumModelPreviewEnabled('',true),true);assert.equal(curriculumModelPreviewEnabled('?curriculumPreview=0',true),false);assert.equal(curriculumModelPreviewEnabled('?curriculumPreview=1',false),true);
 assert.equal(curriculumPreviewBuildEnabled({VERCEL_ENV:'preview',VERCEL_GIT_COMMIT_REF:LEARNING_HUB_PREVIEW_BRANCH}),true);
 assert.equal(curriculumPreviewBuildEnabled({VERCEL_ENV:'preview',VERCEL_GIT_COMMIT_REF:LEARNING_HUB_AUDIO_PREVIEW_BRANCH}),true);
 for(const environment of [{VERCEL_ENV:'production',VERCEL_GIT_COMMIT_REF:LEARNING_HUB_PREVIEW_BRANCH},{VERCEL_ENV:'production',VERCEL_GIT_COMMIT_REF:LEARNING_HUB_AUDIO_PREVIEW_BRANCH},{VERCEL_ENV:'preview',VERCEL_GIT_COMMIT_REF:'main'},{}])assert.equal(curriculumPreviewBuildEnabled(environment),false);
 assert.deepEqual(LOCAL_MODEL_LESSONS.map(x=>x.sequence),Array.from({length:23},(_,i)=>i+1));assert.ok(LOCAL_MODEL_LESSONS.every(x=>x.origin==='local-model'));
 assert.equal(localModelCodeFor('finance',{id:ACCA_A1_MODEL_ID,slug:ACCA_A1_MODEL_SLUG}),'A1');assert.equal(localModelCodeFor('finance',{id:ACCA_A2_MODEL_ID,slug:ACCA_A2_MODEL_SLUG}),'A2');assert.equal(localModelCodeFor('finance',{id:ACCA_A3_MODEL_ID,slug:ACCA_A3_MODEL_SLUG}),'A3');assert.equal(localModelCodeFor('finance',{id:ACCA_A4_MODEL_ID,slug:ACCA_A4_MODEL_SLUG}),'A4');assert.equal(localModelCodeFor('finance',{id:ACCA_B1_MODEL_ID,slug:ACCA_B1_MODEL_SLUG}),'B1');assert.equal(localModelCodeFor('finance',{id:ACCA_B2_MODEL_ID,slug:ACCA_B2_MODEL_SLUG}),'B2');assert.equal(localModelCodeFor('finance',{id:ACCA_B3_MODEL_ID,slug:ACCA_B3_MODEL_SLUG}),'B3');assert.equal(localModelCodeFor('finance',{id:ACCA_B4_MODEL_ID,slug:ACCA_B4_MODEL_SLUG}),'B4');assert.equal(localModelCodeFor('finance',{id:ACCA_B5_MODEL_ID,slug:ACCA_B5_MODEL_SLUG}),'B5');assert.equal(localModelCodeFor('finance',{id:ACCA_B6_MODEL_ID,slug:ACCA_B6_MODEL_SLUG}),'B6');assert.equal(localModelCodeFor('finance',{id:ACCA_B7_MODEL_ID,slug:ACCA_B7_MODEL_SLUG}),'B7');assert.equal(localModelCodeFor('finance',{id:ACCA_B8_MODEL_ID,slug:ACCA_B8_MODEL_SLUG}),'B8');assert.equal(localModelCodeFor('finance',{id:ACCA_B9_MODEL_ID,slug:ACCA_B9_MODEL_SLUG}),'B9');assert.equal(localModelCodeFor('finance',{id:ACCA_B10_MODEL_ID,slug:ACCA_B10_MODEL_SLUG}),'B10');assert.equal(localModelCodeFor('finance',{id:ACCA_B11_MODEL_ID,slug:ACCA_B11_MODEL_SLUG}),'B11');assert.equal(localModelCodeFor('finance',{id:ACCA_B12_MODEL_ID,slug:ACCA_B12_MODEL_SLUG}),'B12');assert.equal(localModelCodeFor('finance',{id:ACCA_C1_MODEL_ID,slug:ACCA_C1_MODEL_SLUG}),'C1');assert.equal(localModelCodeFor('finance',{id:ACCA_C2_MODEL_ID,slug:ACCA_C2_MODEL_SLUG}),'C2');assert.equal(localModelCodeFor('finance',{id:ACCA_C3_MODEL_ID,slug:ACCA_C3_MODEL_SLUG}),'C3');assert.equal(localModelCodeFor('finance',{id:ACCA_C4_MODEL_ID,slug:ACCA_C4_MODEL_SLUG}),'C4');assert.equal(localModelCodeFor('finance',{id:ACCA_D1_MODEL_ID,slug:ACCA_D1_MODEL_SLUG}),'D1');assert.equal(localModelCodeFor('finance',{id:ACCA_D2_MODEL_ID,slug:ACCA_D2_MODEL_SLUG}),'D2');assert.equal(localModelCodeFor('finance',{id:ACCA_E_MODEL_ID,slug:ACCA_E_MODEL_SLUG}),'E');
 assert.equal(isLocalModelLesson('finance',{id:ACCA_A2_MODEL_ID,slug:ACCA_A1_MODEL_SLUG}),false);assert.equal(isLocalModelLesson('english',{id:ACCA_A2_MODEL_ID,slug:ACCA_A2_MODEL_SLUG}),false);
});
for(const m of models)test(m.title+' has the complete written shape and sitting gate',()=>{
 assert.equal(m.track,'finance');assert.equal(m.sections.length,4);assert.equal(m.terms.length,6);assert.equal(m.practiceExercises?.length,3);assert.equal(m.checkpoint.length,5);assert.equal(m.caseStudy.reviewChecks.length,4);assert.ok(m.visual.rows.length>=4);assert.match(m.scope,/selected exam sitting/i);assert.match(m.scope,/not ACCA approval|not an ACCA-approved course/i);
 for(const s of m.sections)assert.ok(s.paragraphs.join(' ').split(/\s+/).length>70);
});
test('A3, A4, B1 and B2 close the recovered foundation runtime gap',()=>{
 assert.deepEqual(ACCA_A3_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','conceptual-framework']);assert.match(ACCA_A3_MODEL_MODULE.caseStudy.modelAnswer,/CU120/);assert.match(ACCA_A3_MODEL_MODULE.caseStudy.modelAnswer,/CU210/);
 assert.deepEqual(ACCA_A4_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ifrs-foundation','due-process','conceptual-framework','acca-ethics']);assert.match(ACCA_A4_MODEL_MODULE.caseStudy.modelAnswer,/financing meeting creates a self-interest and bias threat/i);
 assert.deepEqual(ACCA_B1_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ias-16']);assert.match(ACCA_B1_MODEL_MODULE.caseStudy.modelAnswer,/Capitalise CU980/);assert.match(ACCA_B1_MODEL_MODULE.caseStudy.modelAnswer,/CU99/);assert.match(ACCA_B1_MODEL_MODULE.caseStudy.modelAnswer,/CU49/);
 assert.deepEqual(ACCA_B2_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ias-38','ias-36']);assert.match(ACCA_B2_MODEL_MODULE.caseStudy.modelAnswer,/total pre-capitalisation expense of CU150/);assert.match(ACCA_B2_MODEL_MODULE.caseStudy.modelAnswer,/Capitalise CU60/);assert.match(ACCA_B2_MODEL_MODULE.caseStudy.modelAnswer,/Closing carrying amount is CU57/);
});
test('B9 and B10 calculations and current syllabus boundaries reconcile',()=>{
 assert.equal(ACCA_B9_MODEL_MODULE.title,'ACCA FR B9 · Reporting financial and non-financial performance');
 assert.deepEqual(ACCA_B9_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ifrs-5','ifrs-18','ias-8','ias-33','ifrs-s1']);
 assert.match(ACCA_B9_MODEL_MODULE.caseStudy.modelAnswer,/CU40,000 loss/);assert.match(ACCA_B9_MODEL_MODULE.caseStudy.modelAnswer,/2,150,000/);assert.match(ACCA_B9_MODEL_MODULE.caseStudy.modelAnswer,/41\.86 cents/);assert.match(ACCA_B9_MODEL_MODULE.caseStudy.modelAnswer,/37\.06 cents/);assert.match(ACCA_B9_MODEL_MODULE.caseStudy.modelAnswer,/5\.58 cents loss/);
 assert.equal(ACCA_B10_MODEL_MODULE.title,'ACCA FR B10 · Revenue');assert.deepEqual(ACCA_B10_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ifrs-15']);
 assert.match(ACCA_B10_MODEL_MODULE.caseStudy.modelAnswer,/CU540 to the handset and CU540 to service/);assert.match(ACCA_B10_MODEL_MODULE.caseStudy.modelAnswer,/cumulative revenue CU675/);assert.match(ACCA_B10_MODEL_MODULE.caseStudy.modelAnswer,/CU405/);assert.match(ACCA_B10_MODEL_MODULE.caseStudy.modelAnswer,/closing cost asset of CU81/);
});
test('B11 and B12 calculations and current syllabus boundaries reconcile',()=>{
 assert.equal(ACCA_B11_MODEL_MODULE.title,'ACCA FR B11 · Government grants');assert.deepEqual(ACCA_B11_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ias-20']);
 assert.match(ACCA_B11_MODEL_MODULE.caseStudy.modelAnswer,/CU100,000 depreciation/);assert.match(ACCA_B11_MODEL_MODULE.caseStudy.modelAnswer,/CU20,000 grant income/);assert.match(ACCA_B11_MODEL_MODULE.caseStudy.modelAnswer,/closing deferred income is CU80,000/);assert.match(ACCA_B11_MODEL_MODULE.caseStudy.modelAnswer,/closing PPE is CU320,000/);
 assert.equal(ACCA_B12_MODEL_MODULE.title,'ACCA FR B12 · Foreign currency transactions');assert.deepEqual(ACCA_B12_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ias-21']);
 assert.match(ACCA_B12_MODEL_MODULE.caseStudy.modelAnswer,/CU80,000/);assert.match(ACCA_B12_MODEL_MODULE.caseStudy.modelAnswer,/CU86,000/);assert.match(ACCA_B12_MODEL_MODULE.caseStudy.modelAnswer,/CU6,000 exchange loss/);assert.match(ACCA_B12_MODEL_MODULE.caseStudy.modelAnswer,/CU2,000 exchange gain/);
});
test('C1 and C2 calculations and current syllabus boundaries reconcile',()=>{
 assert.equal(ACCA_C1_MODEL_MODULE.title,'ACCA FR C1 · Limitations of financial statements');assert.deepEqual(ACCA_C1_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','acca-interpretation','conceptual-framework','ifrs-10']);
 assert.match(ACCA_C1_MODEL_MODULE.caseStudy.modelAnswer,/50\.7 days/);assert.match(ACCA_C1_MODEL_MODULE.caseStudy.modelAnswer,/111\.5 days/);assert.match(ACCA_C1_MODEL_MODULE.caseStudy.modelAnswer,/6\.5 days/);assert.match(ACCA_C1_MODEL_MODULE.caseStudy.modelAnswer,/CU50,000 sale/);
 assert.equal(ACCA_C2_MODEL_MODULE.title,'ACCA FR C2 · Accounting ratios and trends');assert.deepEqual(ACCA_C2_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','acca-interpretation','acca-fr-technical','conceptual-framework']);
 assert.match(ACCA_C2_MODEL_MODULE.caseStudy.modelAnswer,/gross margin fell from 40\.0% to 35\.0%/);assert.match(ACCA_C2_MODEL_MODULE.caseStudy.modelAnswer,/asset turnover rose from 1\.14 times to 1\.25 times/);assert.match(ACCA_C2_MODEL_MODULE.caseStudy.modelAnswer,/receivable days worsened from 36\.5 to 43\.8/);assert.match(ACCA_C2_MODEL_MODULE.caseStudy.modelAnswer,/interest cover fell from 6\.00 to 3\.75 times/);
});
test('C3 and C4 calculations and current syllabus boundaries reconcile',()=>{
 assert.equal(ACCA_C3_MODEL_MODULE.title,'ACCA FR C3 · Limitations of interpretation techniques');assert.deepEqual(ACCA_C3_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','acca-interpretation','acca-cashflows','ias-33']);
 assert.match(ACCA_C3_MODEL_MODULE.caseStudy.modelAnswer,/operating margin unchanged at 12\.0%/);assert.match(ACCA_C3_MODEL_MODULE.caseStudy.modelAnswer,/95\.8%.*43\.1%/);assert.match(ACCA_C3_MODEL_MODULE.caseStudy.modelAnswer,/CU1\.00.*CU0\.75/);assert.match(ACCA_C3_MODEL_MODULE.caseStudy.modelAnswer,/25\.0% decline/);
 assert.equal(ACCA_C4_MODEL_MODULE.title,'ACCA FR C4 · Not-for-profit and public sector entities');assert.deepEqual(ACCA_C4_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ipsasb-framework','ipsasb-handbook']);
 assert.match(ACCA_C4_MODEL_MODULE.caseStudy.modelAnswer,/10\.0% to 5\.0%/);assert.match(ACCA_C4_MODEL_MODULE.caseStudy.modelAnswer,/CU200.*CU190/);assert.match(ACCA_C4_MODEL_MODULE.caseStudy.modelAnswer,/1\.33 to 0\.71/);assert.match(ACCA_C4_MODEL_MODULE.caseStudy.modelAnswer,/6,480 to 8,160/);
});
test('D1 and D2 calculations and current syllabus boundaries reconcile',()=>{
 assert.equal(ACCA_D1_MODEL_MODULE.title,'ACCA FR D1 · Single entity financial statements');assert.deepEqual(ACCA_D1_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ifrs-18','ias-7']);
 assert.match(ACCA_D1_MODEL_MODULE.caseStudy.modelAnswer,/Operating profit is CU300/);assert.match(ACCA_D1_MODEL_MODULE.caseStudy.modelAnswer,/total comprehensive income is CU274/);assert.match(ACCA_D1_MODEL_MODULE.caseStudy.modelAnswer,/total equity CU1,584/);assert.match(ACCA_D1_MODEL_MODULE.caseStudy.modelAnswer,/closing cash CU220/);
 assert.equal(ACCA_D2_MODEL_MODULE.title,'ACCA FR D2 · Consolidated financial statements');assert.deepEqual(ACCA_D2_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','ifrs-10','ifrs-3','ias-28','ias-36','ifrs-5','acca-consolidation','acca-goodwill','acca-fair-value-goodwill']);
 assert.match(ACCA_D2_MODEL_MODULE.caseStudy.modelAnswer,/Full goodwill is CU90/);assert.match(ACCA_D2_MODEL_MODULE.caseStudy.modelAnswer,/adjusted post-acquisition profit CU78/);assert.match(ACCA_D2_MODEL_MODULE.caseStudy.modelAnswer,/Closing NCI is CU179\.6/);assert.match(ACCA_D2_MODEL_MODULE.caseStudy.modelAnswer,/Group retained earnings are therefore CU932\.4/);
});
test('E capstone maps the four current employability and technology capabilities',()=>{
 assert.equal(ACCA_E_MODEL_MODULE.title,'ACCA FR E · Employability and technology skills');assert.deepEqual(ACCA_E_MODEL_MODULE.sources.map(x=>x.id),['acca-fr-syllabus','acca-practice-platform']);
 assert.match(ACCA_E_MODEL_MODULE.caseStudy.modelAnswer,/CU4\.80m/);assert.match(ACCA_E_MODEL_MODULE.caseStudy.modelAnswer,/34\.79%/);assert.match(ACCA_E_MODEL_MODULE.caseStudy.modelAnswer,/8\.75%/);assert.match(ACCA_E_MODEL_MODULE.caseStudy.modelAnswer,/16\.80%/);
});
test('reviewed loader keeps all twenty-three models in separate exact lazy paths',async()=>{
 assert.equal(localModelLessonFor('finance',{id:ACCA_A1_MODEL_ID,slug:ACCA_A1_MODEL_SLUG}),ACCA_A1_MODEL_MODULE);assert.equal(localModelA2For('finance',{id:ACCA_A2_MODEL_ID,slug:ACCA_A2_MODEL_SLUG}),ACCA_A2_MODEL_MODULE);assert.equal(localModelA3For('finance',{id:ACCA_A3_MODEL_ID,slug:ACCA_A3_MODEL_SLUG}),ACCA_A3_MODEL_MODULE);assert.equal(localModelA4For('finance',{id:ACCA_A4_MODEL_ID,slug:ACCA_A4_MODEL_SLUG}),ACCA_A4_MODEL_MODULE);assert.equal(localModelB1For('finance',{id:ACCA_B1_MODEL_ID,slug:ACCA_B1_MODEL_SLUG}),ACCA_B1_MODEL_MODULE);assert.equal(localModelB2For('finance',{id:ACCA_B2_MODEL_ID,slug:ACCA_B2_MODEL_SLUG}),ACCA_B2_MODEL_MODULE);assert.equal(localModelB3For('finance',{id:ACCA_B3_MODEL_ID,slug:ACCA_B3_MODEL_SLUG}),ACCA_B3_MODEL_MODULE);assert.equal(localModelB4For('finance',{id:ACCA_B4_MODEL_ID,slug:ACCA_B4_MODEL_SLUG}),ACCA_B4_MODEL_MODULE);assert.equal(localModelB5For('finance',{id:ACCA_B5_MODEL_ID,slug:ACCA_B5_MODEL_SLUG}),ACCA_B5_MODEL_MODULE);assert.equal(localModelB6For('finance',{id:ACCA_B6_MODEL_ID,slug:ACCA_B6_MODEL_SLUG}),ACCA_B6_MODEL_MODULE);assert.equal(localModelB7For('finance',{id:ACCA_B7_MODEL_ID,slug:ACCA_B7_MODEL_SLUG}),ACCA_B7_MODEL_MODULE);assert.equal(localModelB8For('finance',{id:ACCA_B8_MODEL_ID,slug:ACCA_B8_MODEL_SLUG}),ACCA_B8_MODEL_MODULE);assert.equal(localModelB9For('finance',{id:ACCA_B9_MODEL_ID,slug:ACCA_B9_MODEL_SLUG}),ACCA_B9_MODEL_MODULE);assert.equal(localModelB10For('finance',{id:ACCA_B10_MODEL_ID,slug:ACCA_B10_MODEL_SLUG}),ACCA_B10_MODEL_MODULE);assert.equal(localModelB11For('finance',{id:ACCA_B11_MODEL_ID,slug:ACCA_B11_MODEL_SLUG}),ACCA_B11_MODEL_MODULE);assert.equal(localModelB12For('finance',{id:ACCA_B12_MODEL_ID,slug:ACCA_B12_MODEL_SLUG}),ACCA_B12_MODEL_MODULE);assert.equal(localModelC1For('finance',{id:ACCA_C1_MODEL_ID,slug:ACCA_C1_MODEL_SLUG}),ACCA_C1_MODEL_MODULE);assert.equal(localModelC2For('finance',{id:ACCA_C2_MODEL_ID,slug:ACCA_C2_MODEL_SLUG}),ACCA_C2_MODEL_MODULE);assert.equal(localModelC3For('finance',{id:ACCA_C3_MODEL_ID,slug:ACCA_C3_MODEL_SLUG}),ACCA_C3_MODEL_MODULE);assert.equal(localModelC4For('finance',{id:ACCA_C4_MODEL_ID,slug:ACCA_C4_MODEL_SLUG}),ACCA_C4_MODEL_MODULE);assert.equal(localModelD1For('finance',{id:ACCA_D1_MODEL_ID,slug:ACCA_D1_MODEL_SLUG}),ACCA_D1_MODEL_MODULE);assert.equal(localModelD2For('finance',{id:ACCA_D2_MODEL_ID,slug:ACCA_D2_MODEL_SLUG}),ACCA_D2_MODEL_MODULE);assert.equal(localModelEFor('finance',{id:ACCA_E_MODEL_ID,slug:ACCA_E_MODEL_SLUG}),ACCA_E_MODEL_MODULE);
 const loadedA1=await loadReviewedRuntimeModuleFor('finance',{id:ACCA_A1_MODEL_ID,slug:ACCA_A1_MODEL_SLUG});
 assert.ok(loadedA1);assert.equal(loadedA1.id,ACCA_A1_MODEL_MODULE.id);assert.equal(loadedA1.track,'finance');assert.equal(loadedA1.deepLesson?.course.kind,'acca');assert.equal(loadedA1.sections.length,6);
 const loadedA2=await loadReviewedRuntimeModuleFor('finance',{id:ACCA_A2_MODEL_ID,slug:ACCA_A2_MODEL_SLUG});
 assert.ok(loadedA2);assert.equal(loadedA2.id,ACCA_A2_MODEL_MODULE.id);assert.equal(loadedA2.track,'finance');assert.equal(loadedA2.deepLesson?.course.kind,'acca');assert.equal(loadedA2.sections.length,6);
 assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_A3_MODEL_ID,slug:ACCA_A3_MODEL_SLUG}),ACCA_A3_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_A4_MODEL_ID,slug:ACCA_A4_MODEL_SLUG}),ACCA_A4_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B1_MODEL_ID,slug:ACCA_B1_MODEL_SLUG}),ACCA_B1_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B2_MODEL_ID,slug:ACCA_B2_MODEL_SLUG}),ACCA_B2_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B3_MODEL_ID,slug:ACCA_B3_MODEL_SLUG}),ACCA_B3_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B4_MODEL_ID,slug:ACCA_B4_MODEL_SLUG}),ACCA_B4_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B5_MODEL_ID,slug:ACCA_B5_MODEL_SLUG}),ACCA_B5_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B6_MODEL_ID,slug:ACCA_B6_MODEL_SLUG}),ACCA_B6_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B7_MODEL_ID,slug:ACCA_B7_MODEL_SLUG}),ACCA_B7_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B8_MODEL_ID,slug:ACCA_B8_MODEL_SLUG}),ACCA_B8_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B9_MODEL_ID,slug:ACCA_B9_MODEL_SLUG}),ACCA_B9_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B10_MODEL_ID,slug:ACCA_B10_MODEL_SLUG}),ACCA_B10_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B11_MODEL_ID,slug:ACCA_B11_MODEL_SLUG}),ACCA_B11_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_B12_MODEL_ID,slug:ACCA_B12_MODEL_SLUG}),ACCA_B12_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_C1_MODEL_ID,slug:ACCA_C1_MODEL_SLUG}),ACCA_C1_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_C2_MODEL_ID,slug:ACCA_C2_MODEL_SLUG}),ACCA_C2_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_C3_MODEL_ID,slug:ACCA_C3_MODEL_SLUG}),ACCA_C3_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_C4_MODEL_ID,slug:ACCA_C4_MODEL_SLUG}),ACCA_C4_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_D1_MODEL_ID,slug:ACCA_D1_MODEL_SLUG}),ACCA_D1_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_D2_MODEL_ID,slug:ACCA_D2_MODEL_SLUG}),ACCA_D2_MODEL_MODULE);assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_E_MODEL_ID,slug:ACCA_E_MODEL_SLUG}),ACCA_E_MODEL_MODULE);
 assert.equal(await loadReviewedRuntimeModuleFor('finance',{id:ACCA_A2_MODEL_ID,slug:ACCA_A1_MODEL_SLUG}),null);
 const entry=fs.readFileSync('src/learning/loadReviewedRuntimeModule.ts','utf8');for(const file of ['Modules','A2','A3','A4','B1','B2','B3','B4','B5','B6','B7','B8','B9','B10','B11','B12','C1','C2','C3','C4','D1','D2','E'])assert.match(entry,new RegExp("import\\('\\./localModelLesson"+file+"\\.ts'\\)"));
});
test('English Golden Lesson retains contextual grammar practice',()=>{const xs=LESSON_MODULES.english.practiceExercises??[];assert.deepEqual(xs.map(x=>x.id),['eng-grammar-p1','eng-grammar-p2','eng-grammar-p3']);assert.match(xs[0].answer,/was waiting.*called/i);});
test('both Professor and Premium Audio references remain offline',()=>{
 for(const audio of [ACCA_A1_PREMIUM_AUDIO_OUTLINE,ACCA_A2_PREMIUM_AUDIO_OUTLINE,ACCA_A3_PREMIUM_AUDIO_OUTLINE,ACCA_A4_PREMIUM_AUDIO_OUTLINE,ACCA_B1_PREMIUM_AUDIO_OUTLINE,ACCA_B2_PREMIUM_AUDIO_OUTLINE,ACCA_B3_PREMIUM_AUDIO_OUTLINE,ACCA_B4_PREMIUM_AUDIO_OUTLINE,ACCA_B5_PREMIUM_AUDIO_OUTLINE,ACCA_B6_PREMIUM_AUDIO_OUTLINE,ACCA_B7_PREMIUM_AUDIO_OUTLINE,ACCA_B8_PREMIUM_AUDIO_OUTLINE,ACCA_B9_PREMIUM_AUDIO_OUTLINE,ACCA_B10_PREMIUM_AUDIO_OUTLINE,ACCA_B11_PREMIUM_AUDIO_OUTLINE,ACCA_B12_PREMIUM_AUDIO_OUTLINE,ACCA_C1_PREMIUM_AUDIO_OUTLINE,ACCA_C2_PREMIUM_AUDIO_OUTLINE,ACCA_C3_PREMIUM_AUDIO_OUTLINE,ACCA_C4_PREMIUM_AUDIO_OUTLINE,ACCA_D1_PREMIUM_AUDIO_OUTLINE,ACCA_D2_PREMIUM_AUDIO_OUTLINE,ACCA_E_PREMIUM_AUDIO_OUTLINE]){assert.equal(audio.status,'outline_only_no_generation');assert.match(audio.preservation,/No existing Premium Audio/i);}
 for(const guide of [ACCA_A1_PROFESSOR_GUIDE,ACCA_A2_PROFESSOR_GUIDE,ACCA_A3_PROFESSOR_GUIDE,ACCA_A4_PROFESSOR_GUIDE,ACCA_B1_PROFESSOR_GUIDE,ACCA_B2_PROFESSOR_GUIDE,ACCA_B3_PROFESSOR_GUIDE,ACCA_B4_PROFESSOR_GUIDE,ACCA_B5_PROFESSOR_GUIDE,ACCA_B6_PROFESSOR_GUIDE,ACCA_B7_PROFESSOR_GUIDE,ACCA_B8_PROFESSOR_GUIDE,ACCA_B9_PROFESSOR_GUIDE,ACCA_B10_PROFESSOR_GUIDE,ACCA_B11_PROFESSOR_GUIDE,ACCA_B12_PROFESSOR_GUIDE,ACCA_C1_PROFESSOR_GUIDE,ACCA_C2_PROFESSOR_GUIDE,ACCA_C3_PROFESSOR_GUIDE,ACCA_C4_PROFESSOR_GUIDE,ACCA_D1_PROFESSOR_GUIDE,ACCA_D2_PROFESSOR_GUIDE,ACCA_E_PROFESSOR_GUIDE]){assert.equal(guide.status,'offline_authored_not_live');assert.match(guide.evidenceBoundary,/must never enter|Only actual integrated session turns/i);}
 for(const path of ['src/learning/localModelLessonRegistry.ts','src/learning/localModelLessonModules.ts','src/learning/localModelLessonA2.ts','src/learning/localModelLessonA3.ts','src/learning/localModelLessonA4.ts','src/learning/localModelLessonB1.ts','src/learning/localModelLessonB2.ts','src/learning/localModelLessonB3.ts','src/learning/localModelLessonB4.ts','src/learning/localModelLessonB5.ts','src/learning/localModelLessonB6.ts','src/learning/localModelLessonB7.ts','src/learning/localModelLessonB8.ts','src/learning/localModelLessonB9.ts','src/learning/localModelLessonB10.ts','src/learning/localModelLessonB11.ts','src/learning/localModelLessonB12.ts','src/learning/localModelLessonC1.ts','src/learning/localModelLessonC2.ts','src/learning/localModelLessonC3.ts','src/learning/localModelLessonC4.ts','src/learning/localModelLessonD1.ts','src/learning/localModelLessonD2.ts','src/learning/localModelLessonE.ts','src/learning/loadReviewedRuntimeModule.ts']){const raw=fs.readFileSync(path,'utf8');for(const banned of ['supabase.','fetch(','.insert(','.update(','functions.invoke','connectProfessor(','PremiumAudioPanel'])assert.ok(!raw.includes(banned),path+': '+banned);}
});
test('application labels reviewed self-study models honestly behind the isolated Preview gate',()=>{const app=fs.readFileSync('src/App.tsx','utf8'),config=fs.readFileSync('vite.config.ts','utf8');assert.match(app,/curriculumPreviewRuntimeEnabled/);assert.match(config,/curriculumPreviewBuildEnabled\(process.env\)/);assert.match(config,/__LEARNING_HUB_CURRICULUM_PREVIEW__/);assert.match(app,/Reviewed self-study/);assert.match(app,/Account-synced · reviewed unit/);});
