import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const files={finance:'quality/drafts/p1-finance-revenue.json',payroll:'quality/drafts/p1-payroll-submission.json',english:'quality/drafts/p1-english-meetings.json'} as const;
const lessons=Object.fromEntries(Object.entries(files).map(([k,p])=>[k,JSON.parse(fs.readFileSync(p,'utf8'))])) as Record<keyof typeof files,any>;
const allowedHosts=new Set(['www.ifrs.org','www.frc.org.uk','www.revenue.ie','learnenglish.britishcouncil.org']);
for(const [track,lesson] of Object.entries(lessons))test(`${track}: full P1 draft has the complete authored learning shape but stays unpublished`,()=>{
 assert.equal(lesson.status,'full_draft_not_published_to_database');assert.equal(lesson.track,track);assert.equal(lesson.roadmapSequence,2);assert.equal(lesson.sections.length,4);assert.equal(lesson.vocabulary.length,6);assert.equal(lesson.workshops.length,3);assert.equal(lesson.checkpoint.length,5);assert.equal(lesson.workedCase.reviewChecks.length,4);assert.ok(lesson.learningObjectives.length>=5);assert.ok(lesson.assessmentBoundaries.length>=6);assert.match(lesson.publicationGate,/separate database publication\/deployment decision/i);
 for(const source of lesson.officialSources){const u=new URL(source.url);assert.equal(u.protocol,'https:');assert.ok(allowedHosts.has(u.hostname),u.hostname);assert.ok(source.supports.length>30);}
 for(const q of lesson.checkpoint){assert.equal(q.options.length,4);assert.ok(Number.isInteger(q.correctIndex)&&q.correctIndex>=0&&q.correctIndex<4);assert.ok(q.explanation.length>20);}
});
test('finance draft separates billing, transfer evidence and Irish FRS 102 statutory basis',()=>{const s=JSON.stringify(lessons.finance);assert.match(s,/invoice date.*not.*determine|invoice.*does not.*determine/i);assert.match(s,/transfer of control/i);assert.match(s,/FRS 102/i);assert.match(s,/group.*local|local.*group/i);assert.match(s,/1 January 2026/i);assert.match(s,/five-step model/i);});
test('finance worked arithmetic is internally consistent and never drives the recognition logic before the facts',()=>{const c=lessons.finance.workedCase;assert.equal(c.numericExtension.contractPrice,108);assert.equal(c.numericExtension.allocatedHardware+c.numericExtension.allocatedSupport,108);assert.equal(c.numericExtension.allocatedHardware,90);assert.equal(c.numericExtension.allocatedSupport,18);assert.match(c.stage1Task,/Before seeing any amounts/i);});
test('payroll draft anchors 2026 RPN, continuous Employment ID, pay date and correction without embedding current tax rates',()=>{const raw=fs.readFileSync(files.payroll,'utf8');assert.match(raw,/2025 RPN.*not.*2026|2025.*RPN.*should not.*2026/i);assert.match(raw,/continuous.*Employment ID|Employment ID.*continuous/i);assert.match(raw,/on or before.*pay date|pay date.*on or before/i);assert.match(raw,/payroll software or ROS/i);assert.doesNotMatch(raw,/€\s*\d/);assert.doesNotMatch(raw,/\b\d+(?:\.\d+)?%/);});
test('payroll assessment never converts an identity or missing-RPN problem directly into an invented tax amount',()=>{const p=lessons.payroll;assert.match(p.scope,/does not calculate current PAYE, USC or PRSI rates/i);assert.match(p.workedCase.modelAnswer,/cannot conclude the correct tax amount/i);assert.match(p.assessmentBoundaries.join(' '),/Identity\/control failure versus tax-calculation conclusion/i);});
test('English draft requires natural clarification and repair while protecting accent, help and self-correction',()=>{const e=lessons.english;const all=JSON.stringify(e);assert.match(all,/clarify before disagreeing/i);assert.match(all,/accent/i);assert.match(all,/help.*request|clarification request/i);assert.match(all,/self-correction|self-corrected/i);assert.match(all,/valid UK|UK.*US|US.*UK/i);assert.match(e.workedCase.alternateValidForms,/exact model phrases/i);});
test('draft files are inert content: no migration, seed, network client or persistence instruction is embedded',()=>{for(const p of Object.values(files)){const raw=fs.readFileSync(p,'utf8');for(const banned of ['supabase.from(','.insert(','.update(','functions.invoke','fetch("https://api.openai.com','CREATE TABLE','ALTER TABLE'])assert.ok(!raw.includes(banned),`${p}: ${banned}`);}});
