import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {p1PremiumAudioGate} from '../quality/candidates/p1-premium-audio-gate.ts';
import {p1SlugFor} from '../src/learning/p1RuntimeRegistry.ts';

const ids={finance:'11111111-1111-4111-8111-111111111111',payroll:'22222222-2222-4222-8222-222222222222',english:'33333333-3333-4333-8333-333333333333'};
const requestTrack={finance:'rafael_finance',payroll:'viviane_payroll',english:'english_academy'} as const;
const profile={finance:'rafael_finance',payroll:'viviane_payroll',english:'rafael_finance'} as const;
const exposure={version:'v2',monthStart:'2026-09-01',protectedReservationUsd:4,activeReservationUsd:4,uncertainReservationUsd:0,staleReservationUsd:0,activeCount:1,uncertainCount:0,staleCount:0,knownPendingCostUsd:0,knownPendingCount:0} as any;
function input(track:keyof typeof ids,overrides:Record<string,unknown>={}){const learnerTrack=requestTrack[track];return {profileTrack:profile[track],requestedTrack:learnerTrack,requestedLessonId:ids[track],resolvedLesson:{id:ids[track],slug:p1SlugFor(track),learnerTrack,isPublished:true,contentVersion:2},cachedStoragePath:null,scriptWords:500,usageRows:[{feature:'professor_evaluation',estimated_cost_usd:2}],exposure,aiHardCapUsd:130,premiumAudioCapUsd:20,...overrides} as any;}
for(const track of ['finance','payroll','english'] as const)test(`${track}: exact published P1 identity produces versioned cache path and pre-provider claim`,()=>{const r=p1PremiumAudioGate(input(track));assert.equal(r.action,'claim-before-provider');if(r.action!=='claim-before-provider')return;assert.equal(r.lessonId,ids[track]);assert.equal(r.lessonSlug,p1SlugFor(track));assert.equal(r.expectedPath,`lessons/${ids[track]}/commentary-v2.mp3`);assert.deepEqual(r.claimKey,{lessonId:ids[track],contentVersion:2,audioType:'commentary'});assert.ok(r.reservationUsd>=0.10);assert.ok(r.estimatedCostUsd>0);});
test('exact cache hit bypasses a new reservation while a stale-version cache fails closed',()=>{const path=`lessons/${ids.finance}/commentary-v2.mp3`;const hit=p1PremiumAudioGate(input('finance',{cachedStoragePath:path}));assert.equal(hit.action,'serve-cache');assert.equal(hit.reservationUsd,0);assert.throws(()=>p1PremiumAudioGate(input('finance',{cachedStoragePath:`lessons/${ids.finance}/commentary-v1.mp3`})),/cache_identity_mismatch/);});
test('global and premium subcaps block before a claim/provider action',()=>{const global=p1PremiumAudioGate(input('finance',{aiHardCapUsd:6}));assert.equal(global.action,'blocked');if(global.action==='blocked')assert.equal(global.reason,'global_ai_budget_reached');const premium=p1PremiumAudioGate(input('finance',{aiHardCapUsd:130,premiumAudioCapUsd:2.01}));assert.equal(premium.action,'blocked');if(premium.action==='blocked')assert.equal(premium.reason,'premium_audio_budget_reached');});
test('protected Professor exposure participates in the global P1 audio decision',()=>{const near={...exposure,protectedReservationUsd:128,activeReservationUsd:128};const r=p1PremiumAudioGate(input('finance',{usageRows:[],exposure:near,aiHardCapUsd:128.05,premiumAudioCapUsd:20}));assert.equal(r.action,'blocked');if(r.action==='blocked')assert.equal(r.reason,'global_ai_budget_reached');});
test('wrong account, lesson id, slug, publication state or content version fails before any generation decision',()=>{for(const value of [input('finance',{profileTrack:'viviane_payroll'}),input('finance',{requestedLessonId:ids.payroll}),input('finance',{resolvedLesson:{...input('finance').resolvedLesson,slug:p1SlugFor('payroll')}}),input('finance',{resolvedLesson:{...input('finance').resolvedLesson,isPublished:false}}),input('finance',{resolvedLesson:{...input('finance').resolvedLesson,contentVersion:0}})])assert.throws(()=>p1PremiumAudioGate(value));});
test('English P1 audio retains its own lesson id and never substitutes current Golden Lesson identity',()=>{const golden='f455a740-f50f-4eb7-95a7-9e4129ca4a68';const r=p1PremiumAudioGate(input('english'));assert.equal(r.lessonId,ids.english);assert.notEqual(r.lessonId,golden);assert.ok(!r.expectedPath.includes(golden));});
test('candidate is pure and current P1 UI still blocks provider mounting',()=>{const source=fs.readFileSync('supabase/functions/_shared/p1-premium-audio-gate.ts','utf8');for(const banned of ['fetch(','createClient(','functions.invoke','LiveKitAPI','openai.com','.insert(','.update(','.delete(','.rpc('])assert.ok(!source.includes(banned),banned);assert.ok(source.includes('Pure gate'));const app=fs.readFileSync('src/App.tsx','utf8');assert.ok(app.includes('p1-interactive-gate'));assert.ok(app.includes("interactiveLessonSupported &&"));});
test('reviewed Edge candidate orders budget -> claim -> source recheck -> TTS and keys all storage by lesson/version',()=>{const source=fs.readFileSync('supabase/functions/premium-lesson-audio/index.ts','utf8');const budget=source.indexOf('premiumAudioBudgetDecision('),claim=source.indexOf('claim_premium_audio_generation_v1'),recheck=source.indexOf('audio_source_changed',source.indexOf('const {data:latestLesson')),tts=source.indexOf('https://api.openai.com/v1/audio/speech');assert.ok(budget>=0&&claim>budget&&recheck>claim&&tts>recheck);assert.ok(source.includes('`lessons/${lessonId}/commentary-v${version}.mp3`'));assert.ok(source.includes('.eq("is_published",true)'));});
