import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {buildPublicationPack} from '../scripts/build-p1-publication-pack.mjs';
const pack=buildPublicationPack();const tracks=['finance','payroll','english'] as const;
test('publication pack covers exactly the three P1 drafts without publishing any lesson',()=>{assert.equal(pack.status,'generated_offline_unpublished_no_database_ids');assert.deepEqual(Object.keys(pack.targets).sort(),[...tracks].sort());for(const track of tracks){const t=pack.targets[track];assert.equal(t.lesson.sequence,2);assert.equal(t.lesson.is_published,false);assert.equal(t.lesson.content_version,1);assert.equal(t.terms.length,6);assert.ok(t.sources.length>=3);assert.equal(t.resolve.expected_current_lesson_sequence,1);assert.equal(t.resolve.require_target_sequence_free,true);assert.equal(t.resolve.require_target_slug_free,true);}});
test('module lookup uses stable slugs rather than generated database UUIDs',()=>{const expected={finance:['finance-ireland-v2','ifrs-reporting'],payroll:['irish-payroll-v2','gross-to-net'],english:['english-academy','spoken-fluency']};for(const track of tracks){const r=pack.targets[track].resolve;assert.deepEqual([r.course_slug,r.module_slug],expected[track]);assert.equal('module_id' in r,false);assert.equal('lesson_id' in r,false);}});
test('generated lesson rows match the real lessons schema fields while child rows wait for the future resolved lesson id',()=>{const required=['slug','title','subtitle','sequence','week_number','day_number','estimated_minutes','level','learning_objectives','technical_brief_pt','manager_commentary_pt','worked_example_pt','ireland_overlay_pt','global_core_pt','common_mistakes_pt','interview_angle_pt','source_last_reviewed','content_version','is_published'];for(const track of tracks){const row=pack.targets[track].lesson;for(const key of required)assert.ok(Object.prototype.hasOwnProperty.call(row,key),`${track}:${key}`);assert.equal('module_id' in row,false);for(const s of pack.targets[track].sources)assert.equal('lesson_id' in s,false);for(const term of pack.targets[track].terms)assert.equal('lesson_id' in term,false);}});
test('all source and term rows are deterministic, ordered and complete',()=>{for(const track of tracks){const t=pack.targets[track];assert.deepEqual(t.sources.map((x:any)=>x.sequence),t.sources.map((_x:any,i:number)=>i+1));assert.deepEqual(t.terms.map((x:any)=>x.sequence),[1,2,3,4,5,6]);for(const s of t.sources){assert.equal(s.source_type,'official');assert.match(s.url,/^https:\/\//);assert.ok(s.publisher.length>3&&s.note.length>30);}for(const term of t.terms)for(const key of ['term_en','translation_pt','definition_en','example_en'])assert.ok(term[key].length>1);}});
test('offline interactive success is recorded without converting the pack into publication authorization',()=>{const gate=pack.interactivePublicationGate;assert.equal(pack.version,'p1-publication-pack-3');assert.equal(gate.status,'offline_contracts_verified_runtime_deploy_still_blocked');assert.equal(gate.offlineVerifiedRun,34855724352);assert.ok(gate.verifiedOffline.length>=5);assert.ok(gate.stillRequiredBeforeIsPublishedTrue.length>=5);assert.match(gate.notAuthorization,/not authorization/i);for(const track of tracks)assert.equal(pack.targets[track].lesson.is_published,false);});
test('builder has no database client, write primitive, migration or deployment side effect',()=>{const source=fs.readFileSync('scripts/build-p1-publication-pack.mjs','utf8');for(const banned of ['createClient(','.insert(','.update(','.delete(','apply_migration','functions.invoke','fetch('])assert.ok(!source.includes(banned),banned);assert.match(source,/No database write performed/);});
