import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const files={finance:'quality/drafts/p1-finance-leases.json',payroll:'quality/drafts/p1-payroll-pay-bases.json',english:'quality/drafts/p1-english-variances.json'} as const;
const lessons=Object.fromEntries(Object.entries(files).map(([k,p])=>[k,JSON.parse(fs.readFileSync(p,'utf8'))])) as Record<keyof typeof files,any>;
const allowedHosts=new Set(['www.ifrs.org','www.frc.org.uk','www.revenue.ie','learnenglish.britishcouncil.org']);
for(const [track,lesson] of Object.entries(lessons))test(`${track}: sequence 3 P1 draft is structurally complete and still unpublished`,()=>{
 assert.equal(lesson.status,'full_draft_not_published_to_database');assert.equal(lesson.track,track);assert.equal(lesson.roadmapSequence,3);assert.equal(lesson.sections.length,4);assert.equal(lesson.vocabulary.length,6);assert.equal(lesson.workshops.length,3);assert.equal(lesson.checkpoint.length,5);assert.equal(lesson.workedCase.reviewChecks.length,4);assert.ok(lesson.learningObjectives.length>=5);assert.ok(lesson.assessmentBoundaries.length>=7);assert.match(lesson.publicationGate,/separate database publication\/deployment decision/i);
 for(const source of lesson.officialSources){const u=new URL(source.url);assert.equal(u.protocol,'https:');assert.ok(allowedHosts.has(u.hostname),u.hostname);assert.ok(source.supports.length>35);}
 for(const q of lesson.checkpoint){assert.equal(q.options.length,4);assert.ok(Number.isInteger(q.correctIndex)&&q.correctIndex>=0&&q.correctIndex<4);assert.ok(q.explanation.length>25);}
});
test('finance lease arithmetic keeps the liability and ROU bridges independently consistent',()=>{const c=lessons.finance.workedCase.calculation;assert.equal(c.initialLeaseLiability,98.04);assert.equal(c.initialRouAsset,98.04);assert.equal(Number((c.initialLeaseLiability+c.year1Interest-c.year1CashPayment).toFixed(2)),c.closingLeaseLiability);assert.equal(Number((c.initialRouAsset-c.year1Depreciation).toFixed(2)),c.closingRouAsset);assert.notEqual(c.closingLeaseLiability,c.closingRouAsset);});
test('finance draft keeps IFRS 16, modification controls and revised FRS 102 2026 proportionality separate',()=>{const raw=fs.readFileSync(files.finance,'utf8');assert.match(raw,/IFRS 16/i);assert.match(raw,/lease modification/i);assert.match(raw,/right-of-use asset/i);assert.match(raw,/lease liability/i);assert.match(raw,/1 de janeiro de 2026|1 January 2026/i);assert.match(raw,/short-term/i);assert.match(raw,/low-value/i);assert.match(raw,/not.*identical|não.*idêntic/i);});
test('payroll pay-base arithmetic deliberately rejects one-base thinking',()=>{const c=lessons.payroll.workedCase.calculation;assert.equal(c.grossPay,4000);assert.equal(c.employeePensionContribution,200);assert.equal(c.payForIncomeTax,3800);assert.equal(c.payForUSC,4000);assert.equal(c.payForEmployeePRSI,4000);assert.notEqual(c.payForIncomeTax,c.payForUSC);assert.notEqual(c.payForIncomeTax,c.payForEmployeePRSI);});
test('payroll draft contains no current statutory rates and never converts bases into invented final deductions',()=>{const raw=fs.readFileSync(files.payroll,'utf8');assert.doesNotMatch(raw,/\b\d+(?:\.\d+)?%/);assert.match(raw,/No RPN values, Income Tax\/USC rates or PRSI class are supplied/i);assert.match(raw,/cannot|não.*calcula|não.*fornece/i);assert.match(lessons.payroll.scope,/does not calculate an employee's final statutory liabilities/i);assert.match(lessons.payroll.assessmentBoundaries.join(' '),/Pay-base error versus final deduction\/rate error/i);});
test('English variance case reconciles amount, percentage and drivers without pretending to assess finance knowledge',()=>{const c=lessons.english.workedCase.calculation;assert.equal(Number((c.actual-c.plan).toFixed(1)),c.varianceAmount);assert.equal(Number(((c.varianceAmount/c.plan)*100).toFixed(1)),c.variancePctOfPlan);assert.equal(Number((c.priceDriver+c.volumeDriver+c.timingDriver).toFixed(1)),c.varianceAmount);assert.match(lessons.english.scope,/does not assess IFRS\/payroll knowledge/i);assert.match(lessons.english.assessmentBoundaries.join(' '),/Numerical-language accuracy versus underlying Finance expertise/i);});
test('English draft protects precise by/to and percentage-point language without exact-phrase grading',()=>{const raw=fs.readFileSync(files.english,'utf8');assert.match(raw,/increased by/i);assert.match(raw,/increased to/i);assert.match(raw,/percentage point/i);assert.match(raw,/Exact model phrases are not required/i);assert.match(raw,/accent/i);assert.match(raw,/self-correct/i);});
test('sequence 3 draft files are inert authored content with no persistence or provider side effect',()=>{for(const p of Object.values(files)){const raw=fs.readFileSync(p,'utf8');for(const banned of ['supabase.from(','.insert(','.update(','functions.invoke','fetch("https://api.openai.com','CREATE TABLE','ALTER TABLE'])assert.ok(!raw.includes(banned),`${p}:${banned}`);}});
