import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {startProfessorAtomically,ProfessorStartupError} from '../server/professor-start.ts';
const input={lessonId:'synthetic',mode:'chapter_conversation',roomName:'lh-synthetic',validationMode:true};
const good={allowed:true,session_id:'session',reservation_id:'reservation',room_name:'validation:lh-synthetic',quality_tier:'premium',validation_mode:true,max_session_seconds:1200,monthly_budget_usd:110,global_ai_cap_usd:130,reservation_usd:4,reserved_before_usd:0,reserved_after_usd:4,global_committed_before_usd:0};
test('one atomic RPC, no reserve-then-insert sequence and no raw callback in DB arguments',async()=>{let calls=0;let args:any;const r=await startProfessorAtomically({rpc:async(name,a)=>{calls++;assert.equal(name,'start_professor_session_atomic');args=a;return{data:good,error:null}}},input);assert.equal(calls,1);assert.equal(args.p_callback_hash,createHash('sha256').update(r.persistence.callbackToken).digest('hex'));assert.ok(!JSON.stringify(args).includes(r.persistence.callbackToken));assert.equal(r.budget.qualityTier,'premium');});
for(const [reason,status] of [['request_already_started',409],['professor_session_already_active',409],['professor_monthly_budget_reached',429],['professor_start_rate_limited',429]] as const){test(`rejects ${reason} without fallback`,async()=>{let calls=0;await assert.rejects(()=>startProfessorAtomically({rpc:async()=>{calls++;return{data:{allowed:false,reason},error:null}}},input),(e:unknown)=>e instanceof ProfessorStartupError&&e.status===status);assert.equal(calls,1);});}
test('unknown backend failure does not leak details or start paid service',async()=>{await assert.rejects(()=>startProfessorAtomically({rpc:async()=>({data:null,error:{message:'private database detail'}})},input),/professor_budget_guard_unavailable/);});
test('malformed budget response is rejected',async()=>{await assert.rejects(()=>startProfessorAtomically({rpc:async()=>({data:{...good,reservation_usd:null},error:null})},input),/guard/);});
test('premium policy is not silently downgraded',async()=>{await assert.rejects(()=>startProfessorAtomically({rpc:async()=>({data:{...good,quality_tier:'standard'},error:null})},input),/persistence/);});
