import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {createSharedPreflights} from '../quality/candidates/professor-shared-preflights.ts';
import {createAdmissionVault,AdmissionVaultUnavailable} from '../quality/candidates/professor-admission-vault.ts';
import {createSharedProfessorRoutes} from '../quality/candidates/professor-shared-routes.ts';
const env={VERCEL_ENV:'preview',VERCEL_GIT_COMMIT_REF:'feat/professor-experience-2026-09-13'};
function fixture(){
 const snapshot:any={receipt:{requestId:randomUUID(),userId:randomUUID(),mode:'chapter_conversation',reference:{id:randomUUID(),sha256:'a'.repeat(64),version:'p1-reference-candidate-v1',identity:{lessonId:randomUUID(),moduleId:randomUUID(),courseId:randomUUID(),lessonSlug:'fixture',contentVersion:1,requestedTrack:'rafael_finance',studyTrack:'finance',sequence:2}}},callbackToken:'b'.repeat(64),roomName:'validation:lh-'+randomUUID(),lessonContext:{technicalBrief:'PRIVATE'}};
 const scope={referenceId:snapshot.receipt.reference.id,userId:snapshot.receipt.userId,requestId:snapshot.receipt.requestId};
 return {snapshot,scope,vault:createAdmissionVault('v1',{v1:randomBytes(32)})};
}
test('stores ciphertext only with exact scope and consumes via separate service RPC',async()=>{const f=fixture();let sealed='';const db={rpc:async(name:string,args:any)=>{if(name==='put_professor_preflight_v1'){sealed=args.p_sealed;assert.equal(args.p_user_id,f.scope.userId);return {data:true};}assert.equal(name,'consume_professor_preflight_v1');return {data:sealed};}};const s=createSharedPreflights(db,f.vault);await s.put(f.snapshot);assert.doesNotMatch(sealed,/PRIVATE|callbackToken/);assert.deepEqual(await s.consume(f.scope),f.snapshot);});
for(const failure of ['lost','missing','tampered'])test(`consume ${failure} fails without another RPC`,async()=>{const f=fixture();let calls=0;const s=createSharedPreflights({rpc:async()=>{calls++;if(failure==='lost')throw Error('private');return {data:failure==='missing'?null:'tampered'};}},f.vault);await assert.rejects(()=>s.consume(f.scope),AdmissionVaultUnavailable);assert.equal(calls,1);});
test('shared route uses fresh auth before consume and start, strips private state',async()=>{const f=fixture();let auth=0,consumes=0,starts=0;const route=createSharedProfessorRoutes({env,serviceDb:{},store:{put:async()=>{},consume:async()=>{consumes++;return f.snapshot;}},makeClient:()=>({auth:{getUser:async()=>{auth++;return {data:{user:{id:f.scope.userId}}};}},rpc:async()=>{starts++;return {data:{allowed:false,reason:'professor_monthly_budget_reached'}};}})});const r=await route('/professor/start','Bearer fixture',{referenceId:f.scope.referenceId,requestId:f.scope.requestId});assert.equal(r.status,200);assert.equal(auth,2);assert.equal(consumes,1);assert.equal(starts,1);assert.doesNotMatch(JSON.stringify(r),/PRIVATE|callback/);});
test('invalid bearer and overposting never consume',async()=>{const f=fixture();let consumed=0;const route=createSharedProfessorRoutes({env,serviceDb:{},store:{put:async()=>{},consume:async()=>{consumed++;return f.snapshot;}},makeClient:()=>{throw Error();}});assert.equal((await route('/professor/start',null,{})).status,401);assert.equal((await route('/professor/start','Bearer fixture',{referenceId:f.scope.referenceId,requestId:f.scope.requestId,draft:'private'})).status,400);assert.equal(consumed,0);});
