import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const completion=fs.readFileSync('supabase/migrations/20260913153700_lh_professor_completion_integrity.sql','utf8');
const memory=fs.readFileSync('supabase/functions/professor-memory-context/index.ts','utf8');
const outcome=fs.readFileSync('src/professor/sessionOutcome.ts','utf8');
test('validation sessions finalize as abandoned specifically to isolate durable learning state',()=>{assert.ok(completion.includes("v_status:=case when v_validation or not v_has_learner then 'abandoned' else 'completed' end"));assert.ok(completion.includes("if e is not null and v_has_learner and not v_validation then"));});
test('Error Bank, spaced reviews and competency updates remain inside the not-validation block',()=>{const guard=completion.indexOf('if e is not null and v_has_learner and not v_validation then');const errorBank=completion.indexOf('insert into public.user_error_bank',guard);const spaced=completion.indexOf('insert into public.spaced_reviews',guard);const scores=completion.indexOf('insert into public.user_competency_scores',guard);const blockEnd=completion.indexOf('insert into lh_internal.professor_completion_receipts',guard);assert.ok(guard>0&&errorBank>guard&&spaced>errorBank&&scores>spaced&&blockEnd>scores);});
test('Professor memory reads only this callback-authenticated user and completed sessions, excluding validation-abandoned sessions by construction',()=>{assert.ok(memory.includes('.eq("user_id", current.user_id)'));assert.ok(memory.includes('.eq("status", "completed")'));assert.ok(memory.includes('callback_token_hash'));assert.ok(!memory.includes(".eq(\"status\", \"abandoned\")"));});
test('validation feedback UI deliberately recognizes isolated abandoned completion without converting it to mastery',()=>{assert.ok(outcome.includes("const validationFinalized=row.status==='abandoned'&&id.validation"));assert.ok(outcome.includes("if(row.status==='abandoned'&&!id.validation)return emptySessionOutcome(id,'stopped')"));const ui=fs.readFileSync('src/components/SessionOutcomePanel.tsx','utf8');assert.ok(ui.includes('does not confirm any update to mastery, Error Bank or reviews'));});
test('validation protocol checks the isolation explicitly rather than assuming it from a successful session',()=>{const protocol=JSON.parse(fs.readFileSync('quality/golden-lesson-validation-protocol.json','utf8'));assert.ok(protocol.commonChecks.some((x:string)=>/does not update mastery, Error Bank or spaced reviews/i.test(x)));assert.ok(protocol.postSessionAudit.some((x:string)=>/isolation from learning state/i.test(x)));});
