import {ACCA_FR_SYLLABUS_SOURCE} from './accaFrSyllabusCoverage.ts';
import {DEEP_LESSON_SCHEMA_VERSION,LEARN_TEXT_EVIDENCE_ID,type DeepLessonContract,type ProgressivePracticeItem} from './deepLessonContract.ts';
import {ACCA_A1_MODEL_ID,ACCA_A1_MODEL_SLUG} from './localModelLessonRegistry.ts';

const sources=[
 {id:'acca-syllabus',label:'ACCA · Financial Reporting syllabus and study guide, September 2026 to June 2027',url:ACCA_FR_SYLLABUS_SOURCE.url,use:'Authoritative boundary for local A1: official outcomes A1a and A1b only, plus the compulsory CBE structure.',reviewedOn:'2026-09-24'},
 {id:'ifrs-framework',label:'IFRS Foundation · Conceptual Framework for Financial Reporting',url:'https://www.ifrs.org/issued-standards/list-of-standards/conceptual-framework/',use:'Authority, purpose and structure of the Conceptual Framework and the objective of general purpose financial reporting.',reviewedOn:'2026-09-24'},
 {id:'acca-framework-article',label:'ACCA · The Conceptual Framework for Financial Reporting',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/professional-exams-study-resources/strategic-business-reporting/technical-articles/conceptual-framework.html',use:'ACCA-aligned explanation of the Framework, primary users, resource decisions and stewardship.',reviewedOn:'2026-09-24'},
] as const;

export const DEEP_ACCA_A1={
 identity:{lessonId:ACCA_A1_MODEL_ID,slug:ACCA_A1_MODEL_SLUG,code:'A1',title:'Purpose, users and the need for a conceptual framework',sitting:ACCA_FR_SYLLABUS_SOURCE.sitting},
 scope:{
  included:[
   'Official A1a: meaning, purpose and role of a conceptual framework for financial reporting.',
   'Official A1b: why a framework is needed and the disadvantages of developing requirements without one.',
   'The objective, primary users, resource decisions and stewardship that give the Framework its direction.',
   'Authority boundaries: a Framework supports reasoning but does not override a specific IFRS Accounting Standard.',
   'ACCA-style explanation and application of A1a–A1b in objective and constructed-response practice.',
  ],
  nextUnitBoundary:[
   'Relevance, materiality, faithful representation, comparability, verifiability, timeliness and understandability belong to local A2 (official A1c–A1g).',
   'Recognition, derecognition and measurement belong to local A3.',
   'Regulatory institutions and standard-setting due process belong to local A4.',
  ],
  disclaimer:'Original Learning Hub material mapped to ACCA Financial Reporting for September 2026 to June 2027. It is not an ACCA publication or past-exam question.',
 },
 prerequisites:[
  'Recognise that published financial statements serve people outside management.',
  'Distinguish an investor, lender or supplier decision from an internal management decision.',
  'Be ready to separate a principle supplied by the syllabus from an assumption introduced by the learner.',
 ],
 teachingBlocks:[
  {
   id:'a1-framework-map',title:'1. What a conceptual framework is—and is not',minutes:8,outcomeIds:['A1a'],purpose:'Build an accurate definition before discussing benefits.',sourceIds:['acca-syllabus','ifrs-framework'],
   body:[
    'A conceptual framework is a coherent system of objectives and connected concepts that guides financial reporting. “Coherent” matters: the concepts are meant to work as a system, not as independent slogans. The reporting objective provides direction; later concepts help the standard setter and preparers reason about useful information. The Framework is therefore the intellectual foundation beneath individual requirements, not a list of journal entries.',
    'The Framework has several audiences. It helps the International Accounting Standards Board develop Standards using connected concepts. It helps preparers develop consistent accounting policies when no specific Standard directly applies. It helps users understand and interpret requirements, and it gives reviewers a transparent basis for challenging a judgement. These roles explain why conceptual knowledge is practical even though the Framework does not calculate an answer by itself.',
    'A specific IFRS Accounting Standard remains authoritative for a transaction within its scope. Management cannot reject that requirement because a preferred interpretation of the Framework produces higher profit or a smoother trend. In an exam answer, state the hierarchy explicitly: search for and apply the specific requirement first; use the relevant policy hierarchy and Framework concepts only within the boundary permitted by IFRS requirements.',
    'The Framework is not a Standard and is not the whole regulatory system. It does not create company-law filing dates, conduct an audit, enforce reporting or replace professional judgement. Calling it “the rule book for every transaction” overstates its authority; calling it “optional theory” understates its role. A precise answer positions it between those two errors.',
    'Imagine a new digital service arrangement. The finance director cannot immediately recall a transaction-specific requirement. The disciplined response is not to open the Framework at a convenient paragraph and choose the highest-profit treatment. The team must first complete a scoped search for applicable Standards and interpretations. Only after establishing a genuine gap can it use the accounting-policy hierarchy and Framework concepts to support a policy that represents the transaction consistently.',
    'A useful mental model is a map. The map establishes the destination and relationships between routes; a specific Standard is a valid instruction for a particular road. The map assists when the route is uncertain, but it does not authorise the driver to ignore a road closure. This model preserves both the practical value and the authority boundary of the Framework.',
   ],
   stopAndThink:{prompt:'A Standard applies, but management dislikes its effect on profit. Can the Framework replace it?',expected:'No. Apply the specific Standard. The Framework supports coherent standard setting and bounded policy judgement; it does not override applicable requirements.'},
  },
  {
   id:'a1-objective',title:'2. Start with users and resource decisions',minutes:8,outcomeIds:['A1a'],purpose:'Connect the Framework to the objective that gives its concepts direction.',sourceIds:['ifrs-framework','acca-framework-article'],
   body:[
    'General purpose financial reporting aims to provide financial information about the reporting entity that is useful to existing and potential investors, lenders and other creditors when they make decisions about providing resources to the entity. An answer that says only “to provide useful information” is incomplete. Useful to whom, and for what decision, are part of the objective.',
    'Resource decisions include buying, selling or holding equity or debt instruments; providing or settling loans and other credit; and exercising voting or other rights that influence management’s use of resources. A potential shareholder considering an investment and a bank considering a facility may read the same statements, but they can emphasise different risks. The report supplies a common information base rather than a bespoke answer to every question.',
    'These investors, lenders and other creditors are primary users because they usually cannot require a reporting entity to prepare a private report tailored to their needs. Management is not in the primary-user group because it can normally access detailed internal information. Employees, regulators, customers and the public may also find financial statements useful, but general purpose reports are not designed to satisfy every specialised information request.',
    'Users need information about the entity’s economic resources, claims against it and changes in those resources and claims. They consider performance and cash-flow evidence when assessing prospects for future net cash inflows. They also assess stewardship: how efficiently and effectively management has used and protected the resources entrusted to it. Stewardship is not limited to fraud detection and is not proved by one year of high profit.',
    'Financial statements do not provide an exact valuation of the entity, guarantee a dividend or promise repayment of a loan. Users combine reporting information with contracts, market conditions, forecasts and their own assumptions. This boundary prevents overclaiming. The objective is decision-useful information, not a prediction service that removes uncertainty.',
    'A reliable exam chain is user → resource decision → information need → reporting implication. For a potential lender: identify the credit decision, then discuss resources, claims, performance, cash generation and uncertainty relevant to repayment. For an investor: identify the buy, sell or hold decision, then connect returns, risks and stewardship to the information. Starting with a user makes the analysis purposeful.',
    'Internal dashboards and private lender packs can be valuable without being general purpose reports. A daily margin dashboard is designed for management; a covenant forecast supplied under a lending agreement is tailored to that bank. The annual financial statements address common information needs of the primary-user group. The distinction concerns purpose and access, not whether one document is more important than another.',
   ],
   stopAndThink:{prompt:'Complete the chain for a potential lender: user → decision → information need.',expected:'Potential lender → whether and on what terms to provide credit → resources, claims, performance, cash-flow prospects and uncertainties relevant to repayment.'},
  },
  {
   id:'a1-framework-roles',title:'3. How the Framework improves connected decisions',minutes:7,outcomeIds:['A1a','A1b'],purpose:'Explain concrete benefits for standard setting, preparation and review.',sourceIds:['acca-syllabus','ifrs-framework'],
   body:[
    'The first benefit is internal coherence. A standard setter can test a proposed requirement against an articulated reporting objective and connected concepts. Similar economic phenomena are less likely to receive unrelated treatments merely because projects occurred at different times. Coherence does not mean identical accounting for genuinely different economics; it means that differences should have a reason that fits the same conceptual system.',
    'The second benefit is efficiency. Each project does not need to recreate first principles from nothing. Debate can begin from a shared objective and vocabulary, allowing attention to focus on the features that make a transaction distinctive. Efficiency is not automatic speed: difficult issues still require evidence, consultation and judgement. The Framework reduces repeated conceptual work without eliminating careful analysis.',
    'The third benefit is transparency and accountability. A conclusion can be explained and challenged against public concepts rather than defended as preference. If two treatments are proposed, the reasoning can identify which better serves the reporting objective and why. Auditors, users and other stakeholders can examine that reasoning even when judgement remains.',
    'For preparers, the Framework supports consistent policy development within the applicable hierarchy when no specific requirement directly addresses a transaction. It discourages result-first reasoning such as “choose whatever gives the strongest profit”. A policy needs a defensible connection to the economic phenomenon and the reporting objective, not merely to management’s incentive.',
    'For users, a coherent foundation improves interpretability. Users can understand that requirements are intended to contribute to a connected objective rather than represent a collection of unrelated conventions. The Framework does not make every Standard simple, but it makes the basis for the system more intelligible and provides language for discussing strengths and limitations.',
    'A high-quality answer does not simply repeat the word consistency. It distinguishes coherent development, efficient reasoning, transparent judgement and improved understanding. It also recognises the limit: broad concepts can point in a direction without mechanically resolving every dispute.',
   ],
   stopAndThink:{prompt:'Give two different benefits of the Framework without saying “it makes things consistent” twice.',expected:'For example: it gives standard setters a common basis for developing requirements, and it makes preparer judgements transparent and challengeable when a gap exists.'},
  },
  {
   id:'a1-why-needed',title:'4. What goes wrong without a framework',minutes:8,outcomeIds:['A1b'],purpose:'Evaluate the disadvantages of isolated case-by-case development.',sourceIds:['acca-syllabus','acca-framework-article'],
   body:[
    'Without a framework, requirements can accumulate as responses to individual problems. One project may prioritise legal form, another industry practice and another a political compromise. Over time, economically similar transactions can receive incompatible treatments while different transactions may be forced into the same answer. The problem is not simply untidy language; it is reduced usefulness and confidence in the reporting system.',
    'Gaps become harder to resolve because no shared objective tells the preparer what a defensible policy is trying to achieve. A result-first choice can fill the vacuum: maximise profit, minimise volatility or copy a competitor. Those criteria reflect incentives, not a public reporting objective. Judgement becomes difficult to explain and easier to manipulate.',
    'Contradictions also increase complexity. Preparers must learn unrelated exceptions, users struggle to understand why similar events look different, and standard setters spend time repairing interactions between requirements. Detailed rules can appear precise while the system becomes harder to maintain. Precision at paragraph level does not guarantee coherence at system level.',
    'Disconnected bright lines can create structuring opportunities. If a minor contractual change moves an arrangement across an arbitrary threshold and produces a dramatically different result, management may design the contract around the line rather than its commercial substance. A Framework cannot prevent all structuring, but it gives the standard setter a basis for testing whether a distinction reflects a meaningful economic difference.',
    'Lack of a common language weakens accountability. One party may call information useful, another conservative and another accurate, yet none shares a definition or objective against which to test the claim. Disagreement becomes a contest of preferences. A conceptual foundation does not end disagreement, but it makes the competing reasons visible and reviewable.',
    'A framework also has limits, and acknowledging them strengthens the evaluation. Concepts are broad; trade-offs, costs and uncertainty remain; legal environments differ; and reasonable people may disagree. The comparison is therefore not “perfect framework versus flawed rules”. It is a coherent, explainable foundation versus a system forced to invent its objectives afresh in every case.',
    'When the requirement uses “discuss”, balance matters. State the disadvantage, explain its consequence for preparers or users, and avoid claiming that a Framework guarantees one correct answer. A well-structured paragraph might say: disconnected rules can create arbitrary distinctions; similar economics then appear different; users cannot compare the underlying resource effects; a common conceptual basis reduces, but cannot eliminate, that risk.',
   ],
   stopAndThink:{prompt:'Why can a detailed rule system still be weak if it has no common conceptual base?',expected:'Individual rules may be precise yet contradict one another, leave gaps, create arbitrary boundaries and encourage transaction structuring because no shared objective disciplines the system.'},
  },
  {
   id:'a1-boundaries',title:'5. Boundaries that prevent overclaiming',minutes:7,outcomeIds:['A1a','A1b'],purpose:'Distinguish the Framework from Standards, regulation and automatic answers.',sourceIds:['ifrs-framework','acca-syllabus'],
   body:[
    'The Framework supports the development and interpretation of reporting requirements, but it is not itself a substitute for every Standard. This is the most important authority boundary. In a scenario, never write that management may override an applicable Standard because its preferred treatment seems more relevant or prudent. The Framework helps explain and connect requirements; it does not grant a general exemption from them.',
    'It is also not the complete regulatory architecture. Company law, securities regulation, stock-exchange rules, audit, enforcement and filing systems can all influence reporting quality. Those topics matter, but they answer different questions. Local A4 examines regulation and standard setting. Keeping that boundary protects A1 from becoming a vague survey of institutions.',
    'The Framework does not eliminate professional judgement. Concepts need application to facts, and facts may be incomplete or uncertain. Two careful analysts can disagree about a new arrangement. The value of the Framework is that each must expose the reasoning, assumptions and connection to the reporting objective. Judgement becomes disciplined rather than invisible.',
    'The Framework does not promise neutral economic consequences. A faithful application can affect reported profit, covenants, remuneration or taxes. Those consequences may be important to stakeholders, but management preference for an outcome is not the reporting objective. Result-driven selection undermines the legitimacy of the judgement.',
    'Nor does the Framework make financial statements complete for every decision. General purpose reports address common information needs and users bring other sources. A lender may still request forecasts; an investor may use industry data; management uses internal operational reports. The Framework helps design useful general purpose reporting, not a universal database.',
    'Use boundaries positively in an answer. Instead of writing only what the Framework cannot do, connect the limitation to its proper role: it cannot override a Standard, but it supports coherent standard setting and bounded gap-filling; it cannot remove judgement, but it provides a transparent basis for judgement; it cannot meet every private need, but it focuses reporting on common primary-user decisions.',
   ],
   stopAndThink:{prompt:'Name two things the Framework cannot do and pair each with what it does contribute.',expected:'Example: it cannot override a Standard, but it supports coherent requirements; it cannot remove judgement, but it makes the basis for judgement transparent.'},
  },
  {
   id:'a1-exam-method',title:'6. Turn A1 knowledge into an ACCA answer',minutes:7,outcomeIds:['A1a','A1b'],purpose:'Practise concise explanation, application and evaluation without drifting into A2.',sourceIds:['acca-syllabus'],
   body:[
    'Begin by reading the verb. “Describe” needs accurate features; “explain” needs cause and consequence; “discuss” or “evaluate” needs supported judgement, often including a limitation. A list of benefits may answer a describe requirement but will be thin for an evaluation. Match the depth of each point to the verb and marks.',
    'For a framework-role point, use claim → mechanism → consequence. Claim: a common framework improves coherence. Mechanism: requirements are developed against a shared objective and concepts. Consequence: similar economic phenomena are less likely to receive arbitrary, unrelated treatment. This is stronger than writing “the Framework improves consistency” with no explanation.',
    'For a scenario, use principle → fact → effect → conclusion. Principle: the Framework does not override an applicable Standard. Fact: the controller rejects a Standard because it lowers profit. Effect: the proposed choice is result-driven and outside the Framework’s role. Conclusion: apply the Standard; use Framework-based judgement only within the permitted hierarchy.',
    'Keep local A2 material out of an A1 answer unless the requirement asks for it. Relevance, faithful representation and enhancing qualitative characteristics are important, but they are official outcomes A1c–A1g and are developed next. Mentioning every Framework chapter does not earn marks when the requirement asks why a conceptual framework is needed.',
    'Objective-test questions often use absolute distractors: “always”, “guarantees”, “removes all judgement”, “overrides any Standard”. Test each word against the boundary. The best answer is usually precise rather than grand. In a multi-select item, evaluate every option independently; do not stop when one true statement appears.',
    'Self-mark point by point. Award a mark only when the answer states a defensible idea and, where required, explains or applies it. Do not award yourself a mark for repeating the same idea using “uniformity”, “consistency” and “comparability”. Record the missing reasoning—not merely the topic—in the Error Bank after the final incorrect attempt.',
   ],
   stopAndThink:{prompt:'Repair this one-line answer: “A framework is needed for consistency.”',expected:'A common framework gives standard setters a shared objective and connected concepts, reducing arbitrary differences between requirements for similar economic phenomena and making the basis for judgement explainable.'},
  },
 ],
 timedExamTask:{id:'a1-exam-oriel',title:'Oriel Systems · original timed written practice',originality:'Original syllabus-aligned Learning Hub practice. It is not an ACCA past-exam question and is not represented as an actual FR Section C task.'},
 sources,
} as const;

export const DEEP_ACCA_A1_LEARN_TEXT=DEEP_ACCA_A1.teachingBlocks.flatMap(block=>[block.title,block.purpose,...block.body,block.stopAndThink.prompt,block.stopAndThink.expected]);
const evidence=(objectiveIds:readonly string[],outcomeIds:readonly string[])=>({objectiveIds,outcomeIds,record:'item-result' as const,errorBank:'after-final-incorrect' as const});

const practice:readonly ProgressivePracticeItem[]=[
 {id:'a1-practice-1',prompt:'Which statement most accurately describes the Conceptual Framework?',progression:'retrieve',sourceBucket:'current',responseMode:'single-select',estimatedMinutes:2,options:[{id:'a',label:'A Standard containing an accounting treatment for every transaction.'},{id:'b',label:'A coherent system of objectives and concepts that guides financial reporting.'},{id:'c',label:'A national enforcement code.'},{id:'d',label:'An optional management forecast.'}],evaluation:{kind:'selection',correctOptionIds:['b'],explanation:'B is correct. The Framework is a connected conceptual foundation; it is not a transaction-by-transaction Standard or an enforcement code.'},evidence:evidence(['a1-obj-role'],['A1a'])},
 {id:'a1-practice-2',prompt:'A specific IFRS Accounting Standard applies, but management prefers the Framework-based result. What should the entity do?',progression:'apply',sourceBucket:'current',responseMode:'single-select',estimatedMinutes:2,options:[{id:'a',label:'Use the Framework because it is higher authority.'},{id:'b',label:'Choose whichever treatment gives higher profit.'},{id:'c',label:'Apply the specific Standard.'},{id:'d',label:'Ask users to vote on the accounting policy.'}],evaluation:{kind:'selection',correctOptionIds:['c'],explanation:'Apply the specific Standard. The Framework cannot override an applicable Standard.'},evidence:evidence(['a1-obj-role'],['A1a'])},
 {id:'a1-practice-3',prompt:'Identify the primary user and resource decision: a bank is considering a three-year facility.',progression:'explain',sourceBucket:'current',responseMode:'short-text',estimatedMinutes:3,hints:['Name both the user and the decision.'],evaluation:{kind:'rubric',criteria:[{id:'a1-p3-user',description:'Identifies the bank/potential lender as a primary user.',points:1},{id:'a1-p3-decision',description:'Identifies whether and on what terms to provide credit.',points:1},{id:'a1-p3-info',description:'Connects the decision to resources, claims, performance or cash-flow prospects.',points:1}],modelAnswer:'The potential lender is a primary user deciding whether and on what terms to provide credit. It needs information about resources, claims, performance, cash-flow prospects and uncertainties relevant to repayment.'},evidence:evidence(['a1-obj-users'],['A1a'])},
 {id:'a1-practice-4',prompt:'Select every genuine benefit of a conceptual framework.',progression:'apply',sourceBucket:'current',responseMode:'multi-select',estimatedMinutes:3,options:[{id:'a',label:'A common basis for developing connected requirements.'},{id:'b',label:'Removal of all professional judgement.'},{id:'c',label:'A transparent basis for policy reasoning when a genuine gap exists.'},{id:'d',label:'A guarantee that reporting has no political or practical constraints.'},{id:'e',label:'A shared language for explaining and challenging conclusions.'}],evaluation:{kind:'selection',correctOptionIds:['a','c','e'],explanation:'A, C and E are benefits. A framework disciplines judgement; it does not remove judgement or every practical constraint.'},evidence:evidence(['a1-obj-need'],['A1b'])},
 {id:'a1-practice-5',prompt:'Explain two disadvantages of developing reporting requirements case by case without a framework.',progression:'explain',sourceBucket:'current',responseMode:'extended-text',estimatedMinutes:5,hints:['Use disadvantage → consequence.','Do not repeat “inconsistent” in two forms.'],evaluation:{kind:'rubric',criteria:[{id:'a1-p5-one',description:'Explains one valid disadvantage and consequence.',points:2},{id:'a1-p5-two',description:'Explains a distinct second disadvantage and consequence.',points:2}],modelAnswer:'Disconnected projects can create contradictions or arbitrary distinctions, causing similar economics to be reported differently. Gaps have no shared objective for policy development, making result-driven choices harder to challenge. Bright lines can also encourage transaction structuring, while unrelated exceptions increase preparation and interpretation complexity.'},evidence:evidence(['a1-obj-need'],['A1b'])},
 {id:'a1-practice-6',prompt:'Management receives a daily margin dashboard; a bank receives a private covenant forecast; investors receive annual statements. Which is the clearest general purpose report, and why?',progression:'apply',sourceBucket:'current',responseMode:'short-text',estimatedMinutes:4,evaluation:{kind:'rubric',criteria:[{id:'a1-p6-report',description:'Identifies the annual financial statements.',points:1},{id:'a1-p6-common',description:'Explains that they address common needs of primary users unable to demand tailored reports.',points:2},{id:'a1-p6-boundary',description:'Explains why the internal dashboard and private forecast are tailored reports.',points:1}],modelAnswer:'The annual statements are the clearest general purpose report because they provide a common information base for primary users who cannot demand bespoke reports. The dashboard is internal management information and the covenant forecast is tailored to a particular lender agreement.'},evidence:evidence(['a1-obj-users'],['A1a'])},
 {id:'a1-practice-7',prompt:'Evaluate: “A conceptual framework is unnecessary because detailed rules always give one neutral answer.”',progression:'integrate',sourceBucket:'current',responseMode:'extended-text',estimatedMinutes:6,hints:['Challenge “always” and “neutral”.','Include one limitation of the Framework.'],evaluation:{kind:'rubric',criteria:[{id:'a1-p7-coherence',description:'Explains why connected concepts improve coherence.',points:1},{id:'a1-p7-gaps',description:'Explains gaps, contradictions or structuring risk without a framework.',points:1},{id:'a1-p7-judgement',description:'Rejects the claim that detailed rules remove all judgement.',points:1},{id:'a1-p7-limit',description:'Acknowledges that the Framework also requires judgement and does not guarantee one answer.',points:1}],modelAnswer:'Detailed rules cannot anticipate every transaction and may conflict or create arbitrary boundaries when developed without a common objective. A Framework gives standard setters and preparers a coherent and transparent basis for reasoning, reducing gaps and structuring opportunities. It does not remove judgement or guarantee one answer, but it makes the judgement accountable rather than result-driven.'},evidence:evidence(['a1-obj-role','a1-obj-need'],['A1a','A1b'])},
 {id:'a1-practice-8',prompt:'Write one applied paragraph responding to a controller who selects an unaddressed accounting policy solely because it maximises current-year profit.',progression:'transfer',sourceBucket:'current',responseMode:'extended-text',estimatedMinutes:5,evaluation:{kind:'rubric',criteria:[{id:'a1-p8-search',description:'Requires a scoped search for applicable Standards first.',points:1},{id:'a1-p8-framework',description:'Explains the Framework’s bounded gap-filling role.',points:1},{id:'a1-p8-profit',description:'Rejects profit maximisation as the reporting objective.',points:1},{id:'a1-p8-conclusion',description:'Reaches a supported conclusion linked to transparent policy reasoning.',points:1}],modelAnswer:'The controller must first establish whether an IFRS Accounting Standard addresses the transaction. If a genuine gap remains, the applicable policy hierarchy and Framework can support a coherent policy. Maximising current-year profit is a management incentive, not the objective of general purpose reporting, so the proposed basis is not defensible. The policy should be documented by reference to the transaction’s economics and the reporting objective.'},evidence:evidence(['a1-obj-role','a1-obj-need'],['A1a','A1b'])},
];

const workedExamples:DeepLessonContract['workedExamples']=[
 {id:'a1-example-authority',title:'A Standard applies but profit falls',scenario:['Harbour Tech enters a transaction covered by a specific Standard.','The required treatment reduces profit; the finance director prefers a different result drawn from a broad Framework concept.'],estimatedMinutes:7,steps:[{id:'a1-ex1-scope',action:'Establish scope',reasoning:'The first question is whether a specific requirement addresses the transaction.',result:'The Standard applies.'},{id:'a1-ex1-authority',action:'Apply the authority boundary',reasoning:'The Framework does not override a specific Standard.',result:'Management cannot substitute the preferred treatment.'},{id:'a1-ex1-conclude',action:'Conclude without overreach',reasoning:'Economic consequences do not change the reporting hierarchy.',result:'Apply the Standard and document the scoped analysis.'}],conclusion:'A Framework-based preference cannot displace an applicable requirement.',transferPrompt:'What fact would have to change before bounded Framework-based policy judgement becomes relevant?'},
 {id:'a1-example-gap',title:'A genuinely new transaction',scenario:['Liffey Labs launches a novel service arrangement.','A documented search finds no Standard or interpretation that directly addresses the exact issue.','Two policies are proposed: one mirrors the economics; the other merely produces higher profit.'],estimatedMinutes:8,steps:[{id:'a1-ex2-search',action:'Validate the gap',reasoning:'Framework reasoning begins only after a defensible search for applicable requirements.',result:'The documented facts support a genuine gap.'},{id:'a1-ex2-objective',action:'Identify the reporting purpose',reasoning:'The policy should serve general purpose reporting, not management’s desired result.',result:'Profit maximisation is rejected as the selection criterion.'},{id:'a1-ex2-compare',action:'Compare policies transparently',reasoning:'Use the applicable hierarchy and connected concepts to analyse the economic phenomenon.',result:'Select and document the policy that has the defensible conceptual basis.'}],conclusion:'The Framework disciplines gap-filling; it is not permission for result-first accounting.',transferPrompt:'How would your conclusion change if a Standard were later found to cover the transaction?'},
 {id:'a1-example-users',title:'Three reports, three decisions',scenario:['Management requests a daily margin dashboard.','A bank requests a tailored thirteen-week cash forecast under a facility negotiation.','Potential investors use the annual financial statements.'],estimatedMinutes:7,steps:[{id:'a1-ex3-users',action:'Name each user',reasoning:'Purpose depends on who needs the information and the access they possess.',result:'Management, one bank and potential investors have different access.'},{id:'a1-ex3-decisions',action:'Name each decision',reasoning:'The dashboard supports operations; the forecast supports one credit negotiation; the statements support common resource decisions.',result:'Only the statements are designed as general purpose reporting.'},{id:'a1-ex3-boundary',action:'Avoid a value judgement',reasoning:'Tailored reports can be important without becoming general purpose reports.',result:'Classify by purpose and access, not by perceived importance.'}],conclusion:'General purpose reporting provides a common base to primary users who cannot demand bespoke information.',transferPrompt:'Why is management not a primary user even though it uses financial information every day?'},
];

const examTasks:DeepLessonContract['examTasks']=[
 {id:'a1-guided-docklands',title:'Docklands Media · guided A1 boundary case',scenario:['A Standard directly covers one transaction, but the controller wants a higher-profit Framework treatment.','A genuinely new arrangement has no directly applicable requirement after a documented search.','The controller claims detailed rules remove all judgement and make a conceptual framework unnecessary.'],requirements:[{id:'a1-guided-a',prompt:'Explain the proper role of the Framework in the two transactions.',marks:5},{id:'a1-guided-b',prompt:'Evaluate the controller’s claim that no framework is needed.',marks:5}],totalMarks:10,timeLimitMinutes:12,markingGuide:[{id:'a1-g1',criterion:'Specific Standard applies to the first transaction.',marks:1},{id:'a1-g2',criterion:'Framework cannot override it.',marks:1},{id:'a1-g3',criterion:'Documented gap permits bounded policy reasoning.',marks:1},{id:'a1-g4',criterion:'Profit maximisation is rejected as the objective.',marks:1},{id:'a1-g5',criterion:'Policy basis must be transparent and connected to reporting purpose.',marks:1},{id:'a1-g6',criterion:'Common framework improves coherence.',marks:1},{id:'a1-g7',criterion:'Case-by-case rules can create contradictions.',marks:1},{id:'a1-g8',criterion:'Gaps can invite result-driven judgement.',marks:1},{id:'a1-g9',criterion:'Bright lines can invite structuring.',marks:1},{id:'a1-g10',criterion:'Framework guides but does not remove all judgement.',marks:1}],modelAnswer:'For the covered transaction, Docklands must apply the specific Standard; the Framework cannot replace an applicable requirement because management prefers the profit effect. For the genuinely unaddressed arrangement, the documented search establishes the boundary for using the applicable policy hierarchy and Framework concepts. The policy should reflect a defensible reporting purpose, not maximise profit. The controller’s wider claim is weak: isolated rule development can produce contradictions, gaps and arbitrary bright lines, while a shared objective makes conclusions coherent and challengeable. The Framework does not guarantee one mechanical answer, but it disciplines judgement.'},
 {id:'a1-exam-oriel',title:'Oriel Systems · original timed written practice',scenario:['Oriel’s finance director says a conceptual framework is unnecessary because rules always provide one answer.','She proposes that any genuine gap should be filled by the policy with the highest current-year profit.','A separate transaction is covered by a Standard, but she wants the Framework to override it.','A potential lender is deciding whether to provide a three-year facility; management says the annual statements guarantee repayment.'],requirements:[{id:'a1-exam-a',prompt:'Discuss why a conceptual framework is needed and the disadvantages of developing requirements without one.',marks:6},{id:'a1-exam-b',prompt:'Apply the Framework’s role and the reporting objective to Oriel’s proposed treatments and lender claim.',marks:4}],totalMarks:10,timeLimitMinutes:18,markingGuide:[{id:'a1-e1',criterion:'Shared objective supports coherent requirements.',marks:1},{id:'a1-e2',criterion:'Framework improves transparent and accountable judgement.',marks:1},{id:'a1-e3',criterion:'Disconnected rules can contradict or create arbitrary distinctions.',marks:1},{id:'a1-e4',criterion:'Gaps can invite result-driven policies.',marks:1},{id:'a1-e5',criterion:'Bright lines can encourage structuring or complexity.',marks:1},{id:'a1-e6',criterion:'Framework guides but does not eliminate judgement.',marks:1},{id:'a1-e7',criterion:'Rejects profit maximisation as the reporting objective.',marks:1},{id:'a1-e8',criterion:'States that the Framework cannot override the Standard.',marks:1},{id:'a1-e9',criterion:'Identifies the potential lender and credit decision.',marks:1},{id:'a1-e10',criterion:'Explains that statements inform but do not guarantee repayment.',marks:1}],modelAnswer:'A conceptual framework provides a shared reporting objective and connected concepts, supporting coherent requirements and transparent judgements. Without it, projects can create contradictions, arbitrary distinctions, gaps and structuring opportunities. It does not eliminate judgement, but makes the reasoning accountable. Oriel cannot fill a genuine gap simply by maximising profit; it must first confirm the gap and use the applicable hierarchy and Framework to develop a defensible policy. It also cannot override a Standard that applies. The potential lender is a primary user deciding whether and on what terms to provide credit. Annual statements contribute information about resources, claims and performance, but they do not guarantee future repayment.'},
];

const revisionTargets:DeepLessonContract['revisionTargets']=[
 {id:'a1-revision-1',prompt:'Define a conceptual framework without calling it a Standard.',objectiveIds:['a1-obj-role'],successCriterion:'A coherent system of objectives and connected concepts guiding financial reporting.',revisitAfterDays:[1,7,30],estimatedMinutes:1},
 {id:'a1-revision-2',prompt:'State the authority boundary when a specific Standard applies.',objectiveIds:['a1-obj-role'],successCriterion:'Apply the Standard; the Framework does not override it.',revisitAfterDays:[1,7,30],estimatedMinutes:1},
 {id:'a1-revision-3',prompt:'Name the primary-user group and one resource decision.',objectiveIds:['a1-obj-users'],successCriterion:'Existing/potential investors, lenders or other creditors plus a buy/sell/hold, credit or rights decision.',revisitAfterDays:[1,7,30],estimatedMinutes:1},
 {id:'a1-revision-4',prompt:'Explain why management is not a primary user.',objectiveIds:['a1-obj-users'],successCriterion:'Management can normally access tailored internal information.',revisitAfterDays:[1,7,30],estimatedMinutes:1},
 {id:'a1-revision-5',prompt:'Give three distinct benefits of a framework.',objectiveIds:['a1-obj-need'],successCriterion:'Examples: coherence, efficiency, transparent judgement, shared language and interpretability.',revisitAfterDays:[1,7,30],estimatedMinutes:1},
 {id:'a1-revision-6',prompt:'Give three risks of having no framework.',objectiveIds:['a1-obj-need'],successCriterion:'Examples: contradictions, gaps, arbitrary distinctions, complexity and structuring.',revisitAfterDays:[1,7,30],estimatedMinutes:1},
 {id:'a1-revision-7',prompt:'Explain one limitation of a framework.',objectiveIds:['a1-obj-need'],successCriterion:'It requires judgement and cannot guarantee one answer or remove practical constraints.',revisitAfterDays:[1,7,30],estimatedMinutes:1},
 {id:'a1-revision-8',prompt:'Build one principle → fact → effect → conclusion point.',objectiveIds:['a1-obj-transfer'],successCriterion:'Four linked moves using an A1 authority or no-framework fact.',revisitAfterDays:[1,7,30],estimatedMinutes:2},
];

const audioScript=[
 {id:'a1-audio-open',kind:'opening' as const,title:'Three envelopes',estimatedMinutes:1.5,script:'It is eight thirty on Monday at Merrion Works. The finance manager finds three envelopes on her desk. The first is from a potential investor asking for the annual financial statements. The second is from a bank asking for a tailored cash forecast before it decides whether to offer a facility. The third is an internal note from the operations director asking for yesterday’s margin by product. All three requests involve financial information, but only one document is designed as general purpose financial reporting. Pause and identify each user, the decision each one faces, and whether that user can demand tailored information. The investor is considering whether to provide resources by buying shares and cannot normally command a bespoke report. The bank is also making a resource decision, but this forecast is a privately negotiated information request. Management can obtain the operational detail it needs. The distinction is purpose and access, not importance. Keep that in mind, because a conceptual framework begins with the reporting objective rather than with a favourite document or number.'},
 {id:'a1-audio-map',kind:'explanation' as const,title:'The city with no map',estimatedMinutes:2,script:'Now imagine that every district of a growing city designs its streets without a shared map. One district names roads by colour, another by numbers, and a third changes direction whenever a local business asks. Each sign can be very precise. Together, the network is confusing. A driver can follow an individual sign and still end up far from the intended destination. Financial reporting faces a similar risk when requirements are developed only as isolated answers to individual transactions. One project may focus on legal labels, another on industry custom and another on a desired short-term result. Similar economics can receive unrelated treatment. Gaps appear, and no shared objective explains how to reason through them. A conceptual framework supplies the map: an objective and connected concepts that guide standard setting and bounded policy judgement. It does not dictate every turn. Difficult questions still require evidence and judgement. Its contribution is that the judgement starts from a public purpose and can be challenged. Standard setters gain a common basis for connected requirements. Preparers gain a disciplined basis for a genuine gap. Users gain a system whose reasoning can be understood. Reviewers gain something firmer than personal preference against which to test a conclusion. Pause and give one benefit for each group without repeating the word consistency.'},
 {id:'a1-audio-case',kind:'worked-example' as const,title:'Two folders and one dangerous shortcut',estimatedMinutes:2.5,script:'The Merrion Works controller brings two folders. Folder Blue contains a transaction directly covered by an IFRS Accounting Standard. The required treatment reduces this year’s profit. Folder Green contains a novel arrangement; after a documented search, the team finds no requirement that directly addresses the exact issue. The controller offers one shortcut for both folders: choose the treatment that gives the strongest profit and cite the Framework. Diagnose the error before continuing. Folder Blue has the clearest answer. Apply the Standard. The Framework is not higher authority and cannot replace an applicable requirement because the commercial result is inconvenient. Folder Green needs more care. The documented search matters because a preparer should not announce a gap merely because the correct requirement is hard to find. If the gap is genuine, the applicable accounting-policy hierarchy and Framework concepts can support a policy. But the objective is not profit maximisation. The team must analyse the economic phenomenon and document why the policy serves general purpose reporting. The Framework makes judgement accountable; it does not give management permission to choose the prettiest number. Now reverse one fact. Suppose a Standard is discovered after the Green policy has been drafted. The boundary changes. The team must apply the requirement and reassess the draft. That is why an exam answer should state the search and authority steps explicitly rather than jumping straight to a conceptual slogan. There is a second trap in Folder Green. One accountant copies the policy used by a competitor and calls that consistency. Comparable practice may be useful evidence, but copying is not a conceptual justification. The competitor may have different facts, may have identified another requirement, or may itself be wrong. Merrion must explain its own search, the substance of its arrangement and the purpose served by the selected policy. Another accountant proposes waiting until the transaction becomes common. That avoids a decision rather than supporting one. Reporting still needs a timely, documented policy for the current event. The Framework cannot manufacture certainty, but it provides a disciplined route through uncertainty. Pause again: state the fact that activates Framework-based judgement, the criterion that must not drive the answer, and the evidence that makes the conclusion reviewable.'},
 {id:'a1-audio-users',kind:'dialogue' as const,title:'What does the lender actually need?',estimatedMinutes:1.5,script:'Listen to a short exchange. The managing director says, “We made a profit, so the annual report guarantees the bank will be repaid.” The finance manager replies, “The potential lender is a primary user, but the statements are an information base, not a guarantee.” The director asks, “Then what is the point?” The answer is a chain. User: the potential lender. Decision: whether and on what terms to provide credit. Information need: resources, claims, performance, cash-flow prospects and uncertainty relevant to repayment. Reporting implication: provide the general purpose information required by the reporting system without pretending it predicts the future with certainty. The lender will combine that information with forecasts, contracts, security and market evidence. Investors use the same statements for buy, sell, hold or voting decisions, but may emphasise returns and stewardship. Stewardship asks how management has used and protected resources, not merely whether profit rose. Consider the operations director too. She uses financial information, but management can request a dashboard by product, location or hour. That access explains why management is not classified with primary users; it does not imply that management information is less valuable. Likewise, an employee or regulator may use the statements, but the reporting objective is not designed around every specialised question those groups might ask. General purpose means a common base for the primary-user group, not information for no one in particular. Pause and say the four-link chain aloud for a potential investor.'},
 {id:'audio-case-drill',kind:'retrieval-pause' as const,title:'Boardroom challenge',estimatedMinutes:1.5,script:'A board member now makes four claims. Claim one: “A framework is a rule book with an entry for every transaction.” Repair it: the Framework is a coherent system of objectives and concepts, not a Standard for every transaction. Claim two: “Detailed rules remove judgement, so no framework is needed.” Repair it: rules cannot anticipate every event and disconnected development can create contradictions, gaps and arbitrary boundaries. Claim three: “If there is a gap, higher profit is the best policy.” Repair it: management’s result preference is not the objective of general purpose reporting; the policy needs a defensible basis within the applicable hierarchy. Claim four: “The annual statements guarantee an investor’s return.” Repair it: they provide decision-useful information to primary users, who combine it with other evidence and assumptions. Close your notes and reproduce all four repairs. If you can name the error but cannot explain the consequence, the knowledge is not yet exam-ready.'},
 {id:'a1-audio-close',kind:'transfer' as const,title:'Build the marked point',estimatedMinutes:1,script:'Finish with one marked paragraph. Principle: the Framework does not override an applicable Standard. Fact: Merrion’s controller wants a different treatment because the Standard reduces profit. Effect: the proposed choice is result-driven and outside the Framework’s role. Conclusion: apply the Standard and reserve Framework-based policy judgement for a genuine gap within the permitted hierarchy. That four-move structure turns knowledge into application. Your final retrieval has five lines: define the Framework; name the primary users and one decision; give two distinct benefits; give two disadvantages without a Framework; state one limitation. Write the five lines before returning to Learn. Local A2 will address qualitative characteristics. Do not import them into this answer merely to sound comprehensive. A precise answer that respects the unit boundary is stronger than a long answer that changes the subject.'},
] as const;

export const DEEP_ACCA_A1_CONTRACT:DeepLessonContract={
 schemaVersion:DEEP_LESSON_SCHEMA_VERSION,
 editorial:{status:'deep-reviewed',depthVersion:'acca-a1-local-scope-2026-09-24',reviewedOn:'2026-09-24'},
 course:{kind:'acca',qualification:'ACCA',paper:'Financial Reporting (FR)',sitting:ACCA_FR_SYLLABUS_SOURCE.sitting},
 curriculum:{provider:'ACCA',framework:'Financial Reporting syllabus and study guide',version:ACCA_FR_SYLLABUS_SOURCE.sitting,outcomeIds:['A1a','A1b'],sourceUrl:ACCA_FR_SYLLABUS_SOURCE.url},
 prerequisites:DEEP_ACCA_A1.prerequisites,
 objectives:[
  {id:'a1-obj-role',statement:'Describe the meaning, purpose, users and authority boundary of the financial-reporting conceptual framework.',evidenceIds:[LEARN_TEXT_EVIDENCE_ID,'a1-practice-1','a1-practice-2','a1-example-authority','a1-exam-oriel'],level:'understand'},
  {id:'a1-obj-users',statement:'Connect the objective of general purpose reporting to primary users, resource decisions and stewardship.',evidenceIds:[LEARN_TEXT_EVIDENCE_ID,'a1-practice-3','a1-practice-6','a1-example-users','a1-exam-oriel'],level:'apply'},
  {id:'a1-obj-need',statement:'Evaluate benefits of a shared framework and disadvantages of disconnected case-by-case development.',evidenceIds:[LEARN_TEXT_EVIDENCE_ID,'a1-practice-4','a1-practice-5','a1-practice-7','a1-guided-docklands'],level:'evaluate'},
  {id:'a1-obj-transfer',statement:'Write a concise ACCA-style principle–fact–effect–conclusion response while respecting the A1/A2 boundary.',evidenceIds:['a1-practice-8','a1-guided-docklands','a1-exam-oriel','a1-revision-8'],level:'create'},
 ],
 workload:{totalMinutes:90,phases:[
  {id:'a1-phase-learn',kind:'learn',title:'Six deep teaching blocks and embedded retrieval',plannedMinutes:17,evidenceIds:[LEARN_TEXT_EVIDENCE_ID]},
  {id:'a1-phase-examples',kind:'worked-example',title:'Three worked reasoning chains',plannedMinutes:22,evidenceIds:workedExamples.map(item=>item.id)},
  {id:'a1-phase-practice',kind:'practice',title:'Eight progressive items',plannedMinutes:30,evidenceIds:practice.map(item=>item.id)},
  {id:'a1-phase-exam',kind:'exam',title:'Guided and timed written application',plannedMinutes:12,evidenceIds:['a1-guided-docklands']},
  {id:'a1-phase-revision',kind:'revision',title:'Closed-book retrieval',plannedMinutes:9,evidenceIds:revisionTargets.map(item=>item.id)},
 ],paceNote:'The 90-minute core counts authored Learn reading, worked reasoning, item attempts, one guided written case and retrieval. The independent 10-minute Audio episode is an alternative recap and is not added to the core.'},
 workedExamples,
 practice:{items:practice,attemptsBeforeReveal:2},
 misconceptions:[
  {id:'a1-mis-1',misconception:'The Framework is a Standard that supplies an accounting treatment for every transaction.',correction:'It is a coherent conceptual foundation. Specific Standards remain authoritative.',diagnosticPrompt:'Explain the difference between a Framework and a Standard.',objectiveIds:['a1-obj-role']},
  {id:'a1-mis-2',misconception:'The Framework may override a Standard if management considers the result more useful.',correction:'It cannot displace a specific applicable requirement.',diagnosticPrompt:'What is wrong with a result-driven override?',objectiveIds:['a1-obj-role']},
  {id:'a1-mis-3',misconception:'Management is a primary user because it uses financial information.',correction:'Management normally has access to tailored internal information; primary users cannot demand it.',diagnosticPrompt:'Explain why use of information alone does not make management a primary user.',objectiveIds:['a1-obj-users']},
  {id:'a1-mis-4',misconception:'A framework removes all judgement and guarantees one answer.',correction:'It disciplines and exposes judgement but does not eliminate it.',diagnosticPrompt:'State one benefit and one limitation of framework-based reasoning.',objectiveIds:['a1-obj-need']},
  {id:'a1-mis-5',misconception:'A detailed rule system cannot be inconsistent.',correction:'Individually precise rules can conflict, leave gaps or create arbitrary boundaries when developed without a shared objective.',diagnosticPrompt:'Explain system-level incoherence despite paragraph-level precision.',objectiveIds:['a1-obj-need']},
 ],
 examTasks,
 revisionTargets,
 audioEpisode:{format:'authored-script',title:'The map, the rule and the resource decision',editorialGoal:'Rebuild A1 through a fresh Merrion Works case, authority decisions and retrieval rather than narrating Learn.',estimatedMinutes:10,distinctiveElements:['A new three-envelope narrative','Two-folder authority decision','Spoken boardroom repair drill','Final five-line closed-book transfer'],segments:audioScript},
 completion:{itemLevelEvidenceRequired:true,requirements:[
  {id:'a1-complete-learn',targetIds:[LEARN_TEXT_EVIDENCE_ID],rule:'view'},
  {id:'a1-complete-examples',targetIds:workedExamples.map(item=>item.id),rule:'view'},
  {id:'a1-complete-practice',targetIds:practice.map(item=>item.id),rule:'attempt'},
  {id:'a1-complete-guided',targetIds:['a1-guided-docklands'],rule:'submit'},
  {id:'a1-complete-timed',targetIds:['a1-exam-oriel'],rule:'submit'},
  {id:'a1-complete-retrieval',targetIds:revisionTargets.map(item=>item.id),rule:'meet-threshold',minimum:.75},
 ]},
 acca:{examTechnique:['Read the verb and marks before drafting.','Use claim → mechanism → consequence for explanation.','Use principle → fact → effect → conclusion for application.','State the Framework/Standard authority boundary explicitly.','Keep official A1c–A1g qualitative-characteristic content in local A2.','Self-mark distinct points; do not award repeated synonyms.'],constructedResponseTaskIds:['a1-guided-docklands','a1-exam-oriel']},
};
