import {ACCA_FR_SYLLABUS_SOURCE} from './accaFrSyllabusCoverage.ts';
import {DEEP_LESSON_SCHEMA_VERSION,LEARN_TEXT_EVIDENCE_ID,type DeepLessonContract,type ProgressivePracticeItem} from './deepLessonContract.ts';
import {ACCA_A2_MODEL_ID,ACCA_A2_MODEL_SLUG} from './localModelLessonRegistry.ts';

export const DEEP_ACCA_A2={
 identity:{lessonId:ACCA_A2_MODEL_ID,slug:ACCA_A2_MODEL_SLUG,code:'A2',title:'Qualitative characteristics and the cost constraint'},
 scope:{
  included:['Official A1c: relevance and faithful representation.','Official A1d: why formal compliance may still fail faithful representation.','Official A1e: understandability and verifiability.','Official A1f: comparability and timeliness.','Official A1g: preserving comparability when an accounting policy changes.','Prudence, substance and the pervasive cost constraint as connected Framework concepts.'],
  nextUnitBoundary:['The meaning and need for a conceptual framework are completed in local A1.','Recognition, derecognition and measurement are reserved for local A3.','No qualitative characteristic can override an applicable IFRS Accounting Standard.'],
  disclaimer:'Original Learning Hub material mapped to ACCA Financial Reporting for September 2026 to June 2027. It is not an ACCA publication or past-exam question.',
 },
 teachingBlocks:[
  {id:'acca-a2-fundamental',title:'1. Usefulness needs both fundamental characteristics',outcomeIds:['A1c'],purpose:'Apply relevance and faithful representation as a sequence, not a vocabulary list.',sourceIds:['acca-syllabus','ifrs-framework'],body:[
   'Relevant information is capable of making a difference to a primary-user decision because it has predictive value, confirmatory value or both. Predictive value does not mean that the entity publishes a forecast: historical and current information can be an input to a user’s own expectation. Confirmatory value provides feedback on an earlier evaluation. The same item can perform both roles.',
   'Materiality is an entity-specific aspect of relevance. Omitting, misstating or obscuring information is material when it could reasonably be expected to influence decisions made by primary users of that entity’s general purpose financial reports. Nature, magnitude or both can matter. A percentage is a screening tool, not an automatic conclusion.',
   'Faithful representation asks whether the selected economic phenomenon is depicted completely, neutrally and free from error. Completeness includes the descriptions and explanations needed to understand the phenomenon. Neutrality rejects slant towards a preferred reaction. Freedom from error concerns the selection and application of the process; it does not promise perfect precision in every estimate.',
   'The characteristics work together. A perfectly counted number about an irrelevant phenomenon is not useful. A highly relevant estimate can also fail if management omits a major assumption or uses a biased process. Start with the user decision and relevant phenomenon; then test whether the depiction is complete, neutral and produced without error in the selected process.',
   'Uncertainty is not automatically an error. If a warranty outflow is uncertain, a supportable probability-weighted estimate may be more faithful than a precisely counted figure that ignores a confirmed defect. Explain the method, inputs, limitations and uncertainty instead of using apparent precision to hide judgement.',
  ],stopAndThink:{prompt:'Why can a precisely counted historical amount still be less useful than a transparent estimate?',expected:'The count may omit the relevant current phenomenon. A supportable estimate can be more relevant and faithfully represented when its method, evidence and uncertainty are explained.'}},
  {id:'a2-materiality-prudence',title:'2. Materiality, neutrality and prudence under pressure',outcomeIds:['A1c'],purpose:'Prevent mechanical thresholds and deliberate conservatism from replacing judgement.',sourceIds:['ifrs-framework','ifrs-materiality'],body:[
   'Materiality belongs to the entity’s circumstances and the information needs of primary users as a group. A small related-party payment may matter by nature; a large routine balance may matter mainly by magnitude. Obscuring also matters: material information can technically appear in a report yet be hidden by boilerplate, scattered placement or an overwhelming volume of immaterial detail.',
   'Neutrality means that information is selected and presented without bias designed to secure a preferred response. It does not require equal emphasis for every fact. A material uncertainty may need prominence; hiding it would bias the overall depiction. Conversely, highlighting only favourable non-standard measures can shape the user’s reaction.',
   'Prudence supports neutrality through caution under uncertainty. It does not permit deliberate understatement of assets or income, overstatement of liabilities or expenses, or hidden reserves. Asymmetric evidence may lead to different outcomes in a particular requirement, but “always choose the lowest asset” is not the definition of prudence.',
   'Substance helps identify what must be represented. A legal label can be incomplete when the rights, obligations and economic effects tell a different story. In an exam case, use only the supplied facts; do not invent a detailed accounting treatment. Explain which features require faithful depiction and then remain subject to the applicable Standard.',
   'A disciplined materiality point follows information → user decision → nature/magnitude → consequence. Avoid writing that something is material only because it is over five per cent. Explain who could be influenced, why the information changes their assessment and what omission or obscuring would prevent them from seeing.',
  ],stopAndThink:{prompt:'A small payment involves a director-controlled company. Can management dismiss it because it is below a numerical threshold?',expected:'No. The relationship may make the information material by nature. Assess the entity-specific primary-user decision before reaching the reporting conclusion.'}},
  {id:'a2-compliance-boundary',title:'3. Formal compliance is necessary but may not be sufficient',outcomeIds:['A1d'],purpose:'Evaluate the whole depiction rather than treating a checklist as proof.',sourceIds:['acca-syllabus','ifrs-framework'],body:[
   'Applying an IFRS Accounting Standard is mandatory when it addresses the transaction. However, completing visible checklist steps does not automatically prove that the resulting communication faithfully represents the economic phenomenon. The amount, classification, description, aggregation and surrounding explanation work together as one depiction.',
   'A note may use the required label while omitting the uncertainty that gives the amount meaning. A transaction may be recorded under the correct heading while favourable facts are prominent and adverse facts are buried. A technically included disclosure may be obscured by generic wording. Those weaknesses concern completeness or neutrality even though isolated compliance boxes appear ticked.',
   'This principle is not a licence to override a Standard. The repair is to apply the applicable requirements and assess whether the financial statements need the complete, neutral explanation required to represent the phenomenon. The Framework guides the analysis of the depiction; it does not authorise a preferred alternative measurement simply because management calls it more faithful.',
   'Use three questions: what phenomenon does the report claim to depict; which facts are needed to understand it; and does selection or presentation favour a desired conclusion? Then identify evidence. “The report is misleading” earns little without the omitted fact, biased wording or process error that supports the conclusion.',
   'For an estimate, freedom from error is assessed in the process and description. A correctly applied, supportable method can yield a range of possible outcomes. Calling the result exact when the outcome remains uncertain creates a description error even if the spreadsheet has no formula error.',
  ],stopAndThink:{prompt:'A model is recalculated correctly, but the report calls its uncertain output exact and omits the main assumption. Is the depiction faithfully represented?',expected:'Not fully. The process may be free from calculation error, but the description is incomplete and potentially biased because material uncertainty and assumptions are omitted.'}},
  {id:'acca-a2-enhancing',title:'4. Enhance useful information: comparability, verifiability, timeliness and understandability',outcomeIds:['A1e','A1f'],purpose:'Use enhancing characteristics after the fundamental tests.',sourceIds:['acca-syllabus','ifrs-framework'],body:[
   'Comparability helps users identify similarities and differences between items, periods and entities. It is not uniformity. Making unlike phenomena look alike does not improve comparability. Consistency—the use of the same methods over time or across items—can help, but it is a means rather than the objective.',
   'Verifiability gives users assurance that information faithfully represents what it claims to represent. Direct verification can involve observing an amount, such as counting cash. Indirect verification checks inputs and then recalculates the output using the same method. Independent knowledgeable observers need reasonable consensus about the depiction; they need not predict one identical uncertain outcome.',
   'Timeliness means information reaches users while it can influence decisions. Delay can make an otherwise strong analysis less useful, but speed cannot cure an incomplete or biased depiction. The reporting team should use the best supportable information available by the deadline and explain uncertainty rather than choose between reckless speed and indefinite delay.',
   'Understandability comes from clear classification, characterisation and presentation for reasonably knowledgeable and diligent users. Complexity is not a reason to omit relevant information. Layer the explanation: give the nature and headline effect, then method, key drivers and uncertainty. Remove immaterial clutter that obscures the important matter.',
   'Enhancing characteristics cannot rescue information that fails a fundamental characteristic. An observable amount may be easy to verify but irrelevant because it measures the wrong phenomenon. A very timely number may still be biased. First establish relevance and faithful representation; then compare alternatives using the enhancements.',
  ],stopAndThink:{prompt:'Method X is observable but omits a confirmed condition. Method Y estimates that condition transparently. Does X win because it is easier to verify?',expected:'No. Verifiability cannot rescue an incomplete or less relevant depiction. Test the fundamental characteristics first.'}},
  {id:'a2-policy-change',title:'5. Preserve comparability when an accounting policy changes',outcomeIds:['A1g'],purpose:'Distinguish comparability from mechanical consistency and explain the transition information users need.',sourceIds:['acca-syllabus','ifrs-framework'],body:[
   'A valid accounting policy change does not automatically destroy comparability. Preserving a weaker policy merely because it was used last year can reduce useful information. Comparability asks whether users can identify similarities and differences; consistency helps only when the underlying method remains appropriate.',
   'Users need to separate an economic change from a method change. Explain the nature of the policy change, why it occurred and its effect. Apply the comparative or transition treatment required by the applicable Standard or policy-change requirements. The exact mechanics depend on the authoritative requirement; do not invent them from the Framework.',
   'An unexplained old-basis comparative can mislead because a movement may combine business performance with a change in method. Transparent transition information creates a bridge between periods. Where the applicable requirements permit or require a specific treatment, follow them and describe limitations or impracticability only when supported by the facts.',
   'Comparability also applies across entities, but different economics may justify different policies. Never assume that two companies must report identically merely because they share an industry label. Identify the relevant transactions, methods and disclosures before judging whether a difference obstructs comparison or reveals a real difference.',
   'A strong exam point is specific: principle, policy-change fact, user effect and correction. “Comparability is reduced” is only a label. Explain that the user cannot tell whether the movement arose from performance or method, then require the nature, reason, effect and applicable transition information.',
  ],stopAndThink:{prompt:'Does comparability prohibit every accounting policy change?',expected:'No. A valid change can improve reporting. Comparability is protected by transparent nature, reason and effect plus the transition or comparative treatment required in the circumstances.'}},
  {id:'a2-cost-exam',title:'6. Resolve trade-offs, cost and exam recommendations',outcomeIds:['A1c','A1d','A1e','A1f','A1g'],purpose:'Reach a supported recommendation without using cost or a characteristic as an override.',sourceIds:['ifrs-framework','acca-syllabus'],body:[
   'Providing and using information has costs: systems, data collection, controls, assurance, analysis and complexity. The benefits of information should justify those costs. Cost is a pervasive constraint considered in standard setting; it is not a slogan that lets management omit required or material information because preparation is inconvenient.',
   'Trade-offs are context-specific. A timely estimate may be less precise but still faithfully represented when the method and uncertainty are supportable. A highly detailed note may increase completeness yet reduce understandability if immaterial data obscures the key matter. Describe the trade-off and explain why the chosen balance still passes the fundamental tests.',
   'Use a decision order. First, identify the primary-user decision and relevant phenomenon. Second, eliminate alternatives that are not relevant or faithfully represented. Third, compare the surviving alternatives using comparability, verifiability, timeliness and understandability. Fourth, consider cost within authoritative requirements. Finally, state the conclusion and missing evidence.',
   'In objective questions, distrust absolutes: “verifiability requires one exact estimate”, “prudence always selects the lowest asset”, “comparability prohibits changes” and “cost overrides any Standard”. In written practice, name the characteristic only once, then spend the mark explaining its connection to the fact and user effect.',
   'A recommendation should remain conditional when the scenario omits a required fact. State what can be concluded and what evidence would change the answer. That is stronger than inventing certainty. The Framework supports structured judgement; authoritative Standards determine the accounting treatment when they apply.',
  ],stopAndThink:{prompt:'State the five-step order for comparing two reporting alternatives.',expected:'User decision and phenomenon; fundamental-characteristic screen; enhancing-characteristic comparison; cost within requirements; supported conclusion and missing evidence.'}},
 ],
 sources:[
  {id:'acca-syllabus',label:'ACCA · Financial Reporting syllabus and study guide, September 2026 to June 2027',url:ACCA_FR_SYLLABUS_SOURCE.url,use:'Official A1c–A1g outcomes and exam boundary.',reviewedOn:'2026-09-24'},
  {id:'ifrs-framework',label:'IFRS Foundation · Conceptual Framework for Financial Reporting',url:'https://www.ifrs.org/issued-standards/list-of-standards/conceptual-framework/',use:'Qualitative characteristics, prudence and cost constraint.',reviewedOn:'2026-09-24'},
  {id:'ifrs-materiality',label:'IFRS Foundation · IFRS Practice Statement 2: Making Materiality Judgements',url:'https://www.ifrs.org/issued-standards/list-of-standards/materiality-practice-statement/',use:'Entity-specific materiality and obscuring information.',reviewedOn:'2026-09-24'},
 ],
} as const;

export const DEEP_ACCA_A2_LEARN_TEXT=DEEP_ACCA_A2.teachingBlocks.flatMap(block=>[block.title,block.purpose,...block.body,block.stopAndThink.prompt,block.stopAndThink.expected]);
const ev=(objectiveIds:readonly string[],outcomeIds:readonly string[])=>({objectiveIds,outcomeIds,record:'item-result' as const,errorBank:'after-final-incorrect' as const});
const practice:readonly ProgressivePracticeItem[]=[
 {id:'acca-a2-q1',prompt:'Which are the two fundamental qualitative characteristics?',progression:'retrieve',sourceBucket:'current',responseMode:'single-select',estimatedMinutes:2,options:[{id:'a',label:'Relevance and faithful representation'},{id:'b',label:'Comparability and timeliness'},{id:'c',label:'Prudence and consistency'},{id:'d',label:'Cost and verifiability'}],evaluation:{kind:'selection',correctOptionIds:['a'],explanation:'Relevance and faithful representation are fundamental; the other four named characteristics enhance useful information.'},evidence:ev(['a2-obj-fundamental'],['A1c'])},
 {id:'acca-a2-q2',prompt:'Does estimation uncertainty automatically mean an estimate is not free from error?',progression:'explain',sourceBucket:'current',responseMode:'single-select',estimatedMinutes:2,options:[{id:'a',label:'Yes, every estimate contains an error.'},{id:'b',label:'No, if a suitable process is applied without error and uncertainty is described.'},{id:'c',label:'Only when management dislikes the result.'}],evaluation:{kind:'selection',correctOptionIds:['b'],explanation:'Freedom from error concerns the process and description; it is not a promise of a perfectly certain outcome.'},evidence:ev(['a2-obj-fundamental'],['A1c'])},
 {id:'a2-practice-materiality',prompt:'A €20,000 payment to a director-controlled company is below a routine percentage. Explain the materiality analysis.',progression:'apply',sourceBucket:'current',responseMode:'short-text',estimatedMinutes:4,evaluation:{kind:'rubric',criteria:[{id:'m1',description:'Rejects automatic threshold conclusion.',points:1},{id:'m2',description:'Explains materiality by nature of the relationship.',points:1},{id:'m3',description:'Connects to a primary-user decision.',points:1}],modelAnswer:'The percentage is only a screen. The director relationship can make the payment material by nature because it may affect users’ stewardship assessment. Evaluate nature and magnitude in the entity’s circumstances before applying the detailed reporting requirement.'},evidence:ev(['a2-obj-fundamental'],['A1c'])},
 {id:'a2-practice-compliance',prompt:'A note contains the required label but calls an uncertain estimate exact and omits the main assumption. Evaluate faithful representation.',progression:'apply',sourceBucket:'current',responseMode:'extended-text',estimatedMinutes:5,evaluation:{kind:'rubric',criteria:[{id:'c1',description:'Explains why the label/checklist is not sufficient.',points:1},{id:'c2',description:'Applies completeness.',points:1},{id:'c3',description:'Applies neutrality or description error.',points:1},{id:'c4',description:'Proposes an evidence-based repair.',points:1}],modelAnswer:'Formal labelling does not make the whole depiction faithful. Omitting the main assumption makes it incomplete, and describing an uncertain output as exact can bias or misdescribe the information. Retain the supportable estimate but explain the method, assumption and uncertainty under the applicable requirements.'},evidence:ev(['a2-obj-compliance'],['A1d'])},
 {id:'a2-practice-verify',prompt:'Select all examples of indirect verification of a model.',progression:'apply',sourceBucket:'current',responseMode:'multi-select',estimatedMinutes:3,options:[{id:'a',label:'Check source inputs.'},{id:'b',label:'Recalculate using the documented method.'},{id:'c',label:'Assume the answer is correct because it is timely.'},{id:'d',label:'Inspect approval and version controls.'}],evaluation:{kind:'selection',correctOptionIds:['a','b','d'],explanation:'Indirect verification checks inputs and recalculates or tests the method and controls. Timeliness alone is not verification.'},evidence:ev(['a2-obj-enhancing'],['A1e'])},
 {id:'acca-a2-q4',prompt:'Which statement best distinguishes comparability from consistency?',progression:'explain',sourceBucket:'current',responseMode:'single-select',estimatedMinutes:2,options:[{id:'a',label:'Comparability means identical policies in all circumstances.'},{id:'b',label:'Comparability is the objective; consistency can help achieve it.'},{id:'c',label:'Consistency prohibits policy changes.'}],evaluation:{kind:'selection',correctOptionIds:['b'],explanation:'Comparability reveals similarities and differences. Consistency is one means, not mechanical uniformity.'},evidence:ev(['a2-obj-enhancing'],['A1f'])},
 {id:'a2-practice-change',prompt:'A valid policy changes, but the old-basis comparative is unexplained. Write a four-mark response.',progression:'integrate',sourceBucket:'current',responseMode:'extended-text',estimatedMinutes:6,evaluation:{kind:'rubric',criteria:[{id:'p1',description:'States that comparability does not prohibit a valid change.',points:1},{id:'p2',description:'Explains the user cannot separate economic from method change.',points:1},{id:'p3',description:'Requires nature, reason and effect.',points:1},{id:'p4',description:'Requires the applicable transition/comparative treatment without inventing it.',points:1}],modelAnswer:'Comparability does not freeze a policy forever. Without explanation, users cannot distinguish performance from the effect of the method change. The entity should explain the nature, reason and effect of the change and apply the transition or comparative treatment required by the applicable requirements.'},evidence:ev(['a2-obj-policy'],['A1g'])},
 {id:'a2-practice-cost',prompt:'Why is “the disclosure is costly” not enough to omit material information?',progression:'explain',sourceBucket:'current',responseMode:'short-text',estimatedMinutes:3,evaluation:{kind:'rubric',criteria:[{id:'k1',description:'Recognises cost as a pervasive constraint.',points:1},{id:'k2',description:'States it is not a management override of requirements.',points:1},{id:'k3',description:'Connects benefit to user decision and materiality.',points:1}],modelAnswer:'Cost is considered against likely information benefits, particularly in standard setting, but management cannot use inconvenience as a general override. Apply the authoritative requirements and assess the material information users need.'},evidence:ev(['a2-obj-transfer'],['A1c','A1d'])},
 {id:'a2-practice-methods',prompt:'Method X is observable but omits a confirmed defect. Method Y estimates the defect using checked engineering evidence and explains uncertainty. Recommend a method.',progression:'transfer',sourceBucket:'current',responseMode:'extended-text',estimatedMinutes:6,evaluation:{kind:'rubric',criteria:[{id:'x1',description:'Screens alternatives using relevance.',points:1},{id:'x2',description:'Applies completeness and neutral estimation.',points:1},{id:'x3',description:'Explains indirect verification.',points:1},{id:'x4',description:'Concludes subject to the applicable Standard.',points:1}],modelAnswer:'Method X’s observability cannot compensate for omitting a confirmed relevant condition. Method Y better depicts the current phenomenon if its evidence and assumptions are neutrally selected and disclosed. Reviewers can verify inputs and recalculate the method. Use the treatment required by the applicable Standard, with transparent uncertainty.'},evidence:ev(['a2-obj-fundamental','a2-obj-enhancing','a2-obj-transfer'],['A1c','A1e'])},
];

const examples:DeepLessonContract['workedExamples']=[
 {id:'a2-example-defect',title:'Observable history versus a current defect',scenario:['Method X uses paid claims and ignores a confirmed defect.','Method Y includes the defect through a documented estimate.'],estimatedMinutes:8,steps:[{id:'d1',action:'Identify the phenomenon',reasoning:'The current obligation includes the confirmed defect.',result:'X omits a relevant condition.'},{id:'d2',action:'Test representation',reasoning:'Y can be complete and neutral if evidence and uncertainty are explained.',result:'Estimation does not automatically make Y erroneous.'},{id:'d3',action:'Enhance and conclude',reasoning:'Inputs and method can be indirectly verified before the deadline.',result:'Y is conceptually stronger, subject to the Standard.'}],conclusion:'Easy verification cannot rescue the wrong phenomenon.',transferPrompt:'What if the engineering evidence were unreviewed?'},
 {id:'a2-example-policy',title:'A valid policy change with a broken bridge',scenario:['A policy validly changes this year.','The prior period remains on the old basis with no reason or effect.'],estimatedMinutes:7,steps:[{id:'p1',action:'Reject uniformity',reasoning:'Comparability does not prohibit a better valid policy.',result:'The change itself is not automatically defective.'},{id:'p2',action:'Identify user effect',reasoning:'Users cannot separate method change from performance.',result:'The comparison is weakened.'},{id:'p3',action:'Build the bridge',reasoning:'Nature, reason, effect and applicable transition information explain the movement.',result:'Users can make a more meaningful comparison.'}],conclusion:'Transparent transition protects comparability without freezing accounting policy.',transferPrompt:'Why must the exact transition mechanics come from the applicable requirement?'},
 {id:'a2-example-layer',title:'Make a complex estimate understandable',scenario:['A material estimate has three drivers and a range of possible outcomes.','Management proposes removing it because users will find it difficult.'],estimatedMinutes:7,steps:[{id:'u1',action:'Retain relevant complexity',reasoning:'Understandability does not justify omission.',result:'Keep the material estimate.'},{id:'u2',action:'Layer the explanation',reasoning:'Nature and headline first; method, drivers and uncertainty next.',result:'Diligent users receive a navigable explanation.'},{id:'u3',action:'Remove clutter',reasoning:'Immaterial boilerplate can obscure the key matter.',result:'Clarity improves without hiding uncertainty.'}],conclusion:'Organisation, not deletion, is the response to material complexity.',transferPrompt:'Which evidence would support indirect verification of the estimate?'},
];

const revisions:DeepLessonContract['revisionTargets']=[
 {id:'a2-rev-1',prompt:'Define predictive and confirmatory value using one item.',objectiveIds:['a2-obj-fundamental'],successCriterion:'One item can inform expectations and provide feedback on an earlier assessment.',revisitAfterDays:[1,7,30],estimatedMinutes:1.5},
 {id:'a2-rev-2',prompt:'State the three features of faithful representation and apply one to an estimate.',objectiveIds:['a2-obj-fundamental'],successCriterion:'Complete, neutral and free from error plus a fact-based application.',revisitAfterDays:[1,7,30],estimatedMinutes:1.5},
 {id:'a2-rev-3',prompt:'Explain why compliance with a label may still be incomplete.',objectiveIds:['a2-obj-compliance'],successCriterion:'The whole depiction may omit or obscure facts needed to understand the phenomenon.',revisitAfterDays:[1,7,30],estimatedMinutes:1.5},
 {id:'a2-rev-4',prompt:'Contrast direct and indirect verification.',objectiveIds:['a2-obj-enhancing'],successCriterion:'Observe directly versus check inputs and recalculate the method.',revisitAfterDays:[1,7,30],estimatedMinutes:1.5},
 {id:'a2-rev-5',prompt:'Distinguish comparability, consistency and uniformity.',objectiveIds:['a2-obj-enhancing'],successCriterion:'Comparability is the objective; consistency can help; uniformity can hide real differences.',revisitAfterDays:[1,7,30],estimatedMinutes:1.5},
 {id:'a2-rev-6',prompt:'Give the policy-change bridge in four elements.',objectiveIds:['a2-obj-policy'],successCriterion:'Nature, reason, effect and applicable transition/comparative information.',revisitAfterDays:[1,7,30],estimatedMinutes:1.5},
];

const audio=[
 {id:'a2-audio-open',kind:'opening' as const,title:'The board receives two numbers',estimatedMinutes:1.5,script:'At Halcyon Appliances, two teams estimate the cost of a confirmed product defect. Team X uses last year’s paid claims because the amount is observable. Team Y uses checked engineering evidence, expected repair costs and probabilities, then explains the range and uncertainty. X looks precise; Y looks uncertain. The chair asks which number is more useful. Do not answer “the most accurate” yet. First identify the phenomenon and the user decision. A lender assessing future cash outflows needs information about the current defect, not simply a perfect count of last year. Relevance therefore screens the alternatives before easy verification becomes decisive. Now ask whether Y can faithfully represent an uncertain obligation. It can, if the method is appropriate, evidence is neutrally selected, the process is applied without error and the uncertainty is described. Uncertainty is not automatically an error. An investor could use the same estimate to revise expectations of margin and cash flow; later claims could also confirm or challenge that earlier assessment. One item can therefore have predictive and confirmatory value. If the defect threatens a flagship product, its nature may influence users even before the final amount is known. A mechanical percentage cannot answer that judgement on its own. The information could also be obscured if it appears only inside generic boilerplate. Relevance asks what can affect the decision and whether the report lets the user see it. Pause and state why X can be verifiable yet incomplete.'},
 {id:'a2-audio-fundamental',kind:'explanation' as const,title:'Two gates, not two labels',estimatedMinutes:2,script:'Think of relevance and faithful representation as two gates. At the first gate, ask whether the information can make a difference to a primary-user decision. It may help predict future cash or confirm an earlier expectation. Materiality belongs here and is entity-specific. A small payment to a director-controlled company can matter by nature even when a routine percentage is low. Information can also be obscured rather than literally omitted. At the second gate, ask whether the chosen phenomenon is depicted completely, neutrally and free from error. Complete does not mean infinite pages; it means the descriptions needed to understand the matter. Neutral does not mean equal emphasis for favourable and adverse facts; it means no slant towards management’s desired response. Free from error does not mean a future outcome is known. It means the selected process and description contain no errors or omissions. A spreadsheet can recalculate perfectly while the report still misdescribes its output as exact. Pause and repair this claim: if a number is relevant, it is automatically useful.'},
 {id:'a2-audio-compliance',kind:'worked-example' as const,title:'The checklist that passed',estimatedMinutes:1.5,script:'Halcyon’s reporting checklist shows a tick beside the estimate note. The right label appears and the amount agrees to the spreadsheet. Yet the note omits the confirmed defect, hides the most sensitive assumption and says the amount is exact. Has formal compliance proved faithful representation? No. Applying the Standard remains mandatory, but the depiction is the whole communication, not the label alone. The omitted defect and assumption can make it incomplete. False precision can misdescribe uncertainty and bias the user’s interpretation. The repair is not to invent a different measurement from the Framework. Apply the authoritative requirement and provide the complete, neutral explanation it requires. In an exam answer, identify the exact omission and its effect instead of declaring vaguely that the report is misleading.'},
 {id:'a2-audio-enhance',kind:'explanation' as const,title:'Four enhancers in the right order',estimatedMinutes:2,script:'Only after information passes the fundamental gates should enhancing characteristics compare the surviving alternatives. Comparability helps users see similarities and differences; it is not forced uniformity. Consistency can help but should not freeze a poor policy. Verifiability can be direct, such as counting cash, or indirect, such as checking engineering inputs and recalculating the model. Knowledgeable independent observers need reasonable consensus about the depiction, not one identical prediction. Timeliness asks whether information arrives while it can influence the decision. Speed does not cure bias, but indefinite delay can destroy usefulness. Understandability asks for clear classification and presentation for a diligent user. Complexity is organised, not deleted. At Halcyon, Y can be indirectly verified, completed before the deadline and explained in layers. X cannot win merely because last year’s claims are easy to count. Pause and put the order into words: fundamental screen first, enhancements second.'},
 {id:'a2-audio-policy',kind:'worked-example' as const,title:'The broken comparison',estimatedMinutes:1.5,script:'Now Halcyon validly changes an accounting policy. The draft shows this year on the new basis, last year on the old basis, and no explanation. The finance director says comparability prohibits the change, so either cancel it or ignore it. Both choices are wrong. Comparability is the goal of identifying similarities and differences; consistency is only one tool. A valid change may improve reporting. The problem is the missing bridge. Users cannot tell whether the movement comes from performance or from method. Explain the nature of the change, why it occurred and its effect, then apply the transition or comparative treatment required by the authoritative requirements. Do not invent those mechanics from the Framework. Imagine revenue appears to rise by ten per cent, but four points arise only from the new method. Without the bridge, a user may treat all ten points as economic growth. Transparent transition information separates the two effects. It also lets the user compare the entity with a peer only after checking whether their underlying transactions and policies are actually comparable. Uniform presentation can hide real differences just as inconsistent presentation can hide similarities. Pause and give one sentence on principle, fact, user effect and correction.'},
 {id:'audio-case-drill',kind:'retrieval-pause' as const,title:'Five claims to repair',estimatedMinutes:1,script:'Repair five claims aloud. One: a small item is never material. Repair: nature, magnitude or both can influence primary users. Two: prudence always means the lowest asset. Repair: prudence is neutral caution, not deliberate understatement. Three: every uncertain estimate contains an error. Repair: a supportable process and honest description can be free from error even when the outcome is uncertain. Four: comparability prohibits policy changes. Repair: transparent valid changes can preserve or improve comparison. Five: cost lets management ignore any disclosure. Repair: cost is a pervasive constraint, not a general override of applicable requirements or material information. If a repair lacks the user effect, say it again with the decision in view.'},
 {id:'a2-audio-close',kind:'transfer' as const,title:'Recommendation',estimatedMinutes:.5,script:'Close with the decision order. Identify the user and phenomenon. Eliminate alternatives that fail relevance or faithful representation. Compare the survivors using the four enhancing characteristics. Consider cost within authoritative requirements. State the supported conclusion and missing evidence. For Halcyon, the transparent current estimate is conceptually stronger than the precise historical count, subject to the applicable Standard. Do not award yourself a mark merely for naming relevance, verifiability or cost. Each characteristic needs a fact and a consequence for the user. If information is missing, state the conditional conclusion and the evidence required instead of inventing certainty. Finally, remember the boundary from A1: Framework concepts organise the judgement, but an applicable Standard remains authoritative. Write the Halcyon recommendation from memory, then add one sentence explaining how your answer would change if the engineering evidence were not checked, before reopening Learn.'},
] as const;

export const DEEP_ACCA_A2_CONTRACT:DeepLessonContract={
 schemaVersion:DEEP_LESSON_SCHEMA_VERSION,editorial:{status:'deep-reviewed',depthVersion:'acca-a2-depth-2026-09-24',reviewedOn:'2026-09-24'},
 course:{kind:'acca',qualification:'ACCA',paper:'Financial Reporting (FR)',sitting:ACCA_FR_SYLLABUS_SOURCE.sitting},
 curriculum:{provider:'ACCA',framework:'Financial Reporting syllabus and study guide',version:ACCA_FR_SYLLABUS_SOURCE.sitting,outcomeIds:['A1c','A1d','A1e','A1f','A1g'],sourceUrl:ACCA_FR_SYLLABUS_SOURCE.url},
 prerequisites:['Complete local A1 or explain the reporting objective and Framework authority boundary.','Identify a primary user and resource decision before evaluating information.'],
 objectives:[
  {id:'a2-obj-fundamental',statement:'Apply relevance, materiality and faithful representation to a user decision.',evidenceIds:[LEARN_TEXT_EVIDENCE_ID,'acca-a2-q2','a2-practice-materiality','a2-example-defect'],level:'apply'},
  {id:'a2-obj-compliance',statement:'Evaluate the whole depiction beyond formal checklist compliance.',evidenceIds:[LEARN_TEXT_EVIDENCE_ID,'a2-practice-compliance','acca-a2-case'],level:'evaluate'},
  {id:'a2-obj-enhancing',statement:'Use understandability, verifiability, comparability and timeliness after the fundamental screen.',evidenceIds:[LEARN_TEXT_EVIDENCE_ID,'a2-practice-verify','acca-a2-q4','a2-example-layer'],level:'apply'},
  {id:'a2-obj-policy',statement:'Explain how a valid policy change preserves comparability.',evidenceIds:[LEARN_TEXT_EVIDENCE_ID,'a2-practice-change','a2-example-policy'],level:'apply'},
  {id:'a2-obj-transfer',statement:'Compare reporting alternatives and reach a cost-aware recommendation subject to the applicable Standard.',evidenceIds:['a2-practice-cost','a2-practice-methods','a2-exam-river'],level:'evaluate'},
 ],
 workload:{totalMinutes:92,phases:[
  {id:'a2-phase-learn',kind:'learn',title:'Six teaching blocks',plannedMinutes:12,evidenceIds:[LEARN_TEXT_EVIDENCE_ID]},
  {id:'a2-phase-examples',kind:'worked-example',title:'Three worked comparisons',plannedMinutes:22,evidenceIds:examples.map(item=>item.id)},
  {id:'a2-phase-practice',kind:'practice',title:'Nine progressive items',plannedMinutes:33,evidenceIds:practice.map(item=>item.id)},
  {id:'a2-phase-case',kind:'exam',title:'Integrated marked case',plannedMinutes:16,evidenceIds:['acca-a2-case']},
  {id:'a2-phase-revision',kind:'revision',title:'Closed-book retrieval',plannedMinutes:9,evidenceIds:revisions.map(item=>item.id)},
 ],paceNote:'The 92-minute core excludes the alternative 10-minute Audio episode.'},
 workedExamples:examples,practice:{items:practice,attemptsBeforeReveal:2},
 misconceptions:[
  {id:'a2-mis-1',misconception:'A precise number is automatically more relevant.',correction:'Precision cannot rescue the wrong phenomenon.',diagnosticPrompt:'Compare a precise historical count with a supportable current estimate.',objectiveIds:['a2-obj-fundamental']},
  {id:'a2-mis-2',misconception:'Every estimate violates freedom from error.',correction:'An appropriate process and honest description can be free from error despite outcome uncertainty.',diagnosticPrompt:'Separate estimation uncertainty from a process error.',objectiveIds:['a2-obj-fundamental']},
  {id:'a2-mis-3',misconception:'A checklist proves faithful representation.',correction:'The complete, neutral depiction must be evaluated.',diagnosticPrompt:'Name an omission that a label cannot cure.',objectiveIds:['a2-obj-compliance']},
  {id:'a2-mis-4',misconception:'Comparability means no policy may change.',correction:'A transparent valid change can improve reporting.',diagnosticPrompt:'Give the four-part policy-change bridge.',objectiveIds:['a2-obj-policy']},
  {id:'a2-mis-5',misconception:'Cost overrides any difficult reporting requirement.',correction:'Cost is a constraint, not a general management override.',diagnosticPrompt:'Explain how to discuss cost without inventing an exemption.',objectiveIds:['a2-obj-transfer']},
 ],
 examTasks:[
  {id:'acca-a2-case',title:'North Quay warranty estimate · guided case',scenario:['A confirmed defect is omitted from an observable historical-claims method.','A probability-weighted alternative uses checked engineering evidence and can explain sensitivity.','Both can meet the deadline; the second requires twelve additional staff-hours.','The note uses a required label but calls the uncertain output exact.'],requirements:[{id:'a2-case-a',prompt:'Recommend a method using fundamental and enhancing characteristics.',marks:8},{id:'a2-case-b',prompt:'Evaluate compliance, uncertainty and cost.',marks:4}],totalMarks:12,timeLimitMinutes:16,markingGuide:[{id:'a2-c1',criterion:'Identifies the confirmed defect as relevant.',marks:1},{id:'a2-c2',criterion:'Explains why the historical method is incomplete.',marks:1},{id:'a2-c3',criterion:'Applies neutral estimation.',marks:1},{id:'a2-c4',criterion:'Explains freedom from error correctly.',marks:1},{id:'a2-c5',criterion:'Applies indirect verification.',marks:1},{id:'a2-c6',criterion:'Applies timeliness.',marks:1},{id:'a2-c7',criterion:'Applies understandability.',marks:1},{id:'a2-c8',criterion:'Concludes subject to the Standard.',marks:1},{id:'a2-c9',criterion:'Formal label is not sufficient.',marks:1},{id:'a2-c10',criterion:'False precision weakens the description.',marks:1},{id:'a2-c11',criterion:'Cost is weighed against user benefit.',marks:1},{id:'a2-c12',criterion:'Does not invent a cost exemption.',marks:1}],modelAnswer:'Use the current-condition method if it complies with the applicable Standard. It includes the confirmed defect and can be complete and neutral when evidence, probabilities and uncertainty are explained. Inputs and method can be indirectly verified, and both methods are timely. The required label does not cure omission or false precision. Twelve staff-hours is a cost, but the facts do not show that it outweighs the benefit of representing a material current condition.'},
  {id:'a2-exam-river',title:'Riverlight plc · timed integrated practice',scenario:['A small director-connected payment is omitted below a percentage.','A model is recalculated correctly but its uncertainty is hidden.','A valid policy changes with no reason, effect or transition explanation.'],requirements:[{id:'a2-r-a',prompt:'Evaluate the usefulness of the payment and estimate information.',marks:6},{id:'a2-r-b',prompt:'Explain the comparability problem and repair.',marks:4}],totalMarks:10,timeLimitMinutes:18,markingGuide:[{id:'r1',criterion:'Materiality by nature.',marks:1},{id:'r2',criterion:'Primary-user decision.',marks:1},{id:'r3',criterion:'Completeness of estimate.',marks:1},{id:'r4',criterion:'Neutrality/false precision.',marks:1},{id:'r5',criterion:'Freedom from error is process-based.',marks:1},{id:'r6',criterion:'Indirect verification.',marks:1},{id:'r7',criterion:'Change not automatically prohibited.',marks:1},{id:'r8',criterion:'Explains user comparison problem.',marks:1},{id:'r9',criterion:'Nature, reason and effect.',marks:1},{id:'r10',criterion:'Applicable transition information.',marks:1}],modelAnswer:'The relationship may make the payment material by nature for users assessing stewardship, so a percentage alone is not decisive. The model’s correct recalculation supports its process, but hidden uncertainty makes the depiction incomplete and potentially biased. Reviewers can test inputs and method without knowing one exact outcome. The policy change is not prohibited; the missing explanation prevents users separating performance from method. Provide nature, reason, effect and the transition information required by the applicable requirements.'},
 ],
 revisionTargets:revisions,
 audioEpisode:{format:'authored-script',title:'The precise wrong number',editorialGoal:'Use one evolving estimate and policy-change case to retrieve the characteristics in decision order.',estimatedMinutes:10,distinctiveElements:['Halcyon Appliances narrative','Two-gate fundamental screen','Spoken five-claim repair drill','Policy-change bridge'],segments:audio},
 completion:{itemLevelEvidenceRequired:true,requirements:[{id:'a2-complete-learn',targetIds:[LEARN_TEXT_EVIDENCE_ID],rule:'view'},{id:'a2-complete-examples',targetIds:examples.map(item=>item.id),rule:'view'},{id:'a2-complete-practice',targetIds:practice.map(item=>item.id),rule:'attempt'},{id:'a2-complete-case',targetIds:['acca-a2-case'],rule:'submit'},{id:'a2-complete-timed',targetIds:['a2-exam-river'],rule:'submit'},{id:'a2-complete-revision',targetIds:revisions.map(item=>item.id),rule:'meet-threshold',minimum:.8}]},
 acca:{examTechnique:['Fundamental screen before enhancing comparison.','Name the user decision before materiality.','For estimates, distinguish process error from outcome uncertainty.','For policy changes, give nature, reason, effect and applicable transition information.','Do not use Framework concepts to override a Standard.'],constructedResponseTaskIds:['acca-a2-case','a2-exam-river']},
};
