import {DEEP_LESSON_SCHEMA_VERSION,LEARN_TEXT_EVIDENCE_ID,type DeepLessonContract,type ProgressivePracticeItem} from './deepLessonContract.ts';
import type {LessonSection,LessonSource} from './lessonModules.ts';
import {PAYROLL_IDENTITIES} from './localPayrollLessonRegistry.ts';

const sources:readonly LessonSource[]=[
 {id:'revenue-paye-guide',label:'Revenue · Guide to Pay As You Earn (PAYE)',url:'https://www.revenue.ie/en/employing-people/becoming-an-employer-and-ongoing-obligations/guide-to-paye/index.aspx',supports:'Employer deduction and on-or-before pay-date reporting boundary.',reviewedOn:'2026-09-24'},
 {id:'revenue-pay-details',label:'Revenue · What employee pay details do you include?',url:'https://www.revenue.ie/en/employing-people/becoming-an-employer-and-ongoing-obligations/information-on-payroll-submission/what-employee-pay-details-do-you-include.aspx',supports:'Gross pay and distinct Income Tax, USC and PRSI pay fields, pension/PHB treatment and employer PRSI reporting.',reviewedOn:'2026-09-24'},
 {id:'revenue-pension',label:'Revenue · Tax relief on pension contributions',url:'https://www.revenue.ie/en/jobs-and-pensions/pension/relief/index.aspx',supports:'Qualifying pension relief is for Income Tax; no employee pension relief from USC or PRSI.',reviewedOn:'2026-09-24'},
 {id:'revenue-receipts',label:'Revenue · Income earned in 2025 but paid in 2026',url:'https://www.revenue.ie/en/employing-people/becoming-an-employer-and-ongoing-obligations/transitional-arrangements/income-earned.aspx',supports:'PAYE receipts basis, pay-date RPN and reporting boundary.',reviewedOn:'2026-09-24'},
];

const sections:readonly LessonSection[]=[
 {id:'p2-gross-pay',title:'1. Build gross pay from supported inputs',paragraphs:[
  'Gross pay is the starting record before deductions. Revenue’s payroll-submission guidance includes wages, salary, notional pay, bonus, overtime, holiday pay and commission paid in the period. The payroll professional should not treat “basic salary” as the complete gross figure when approved variable items or notional pay also belong to the pay period.',
  'Build an input register before calculating. For each item, capture employee and employment identity, pay date, earning code, amount, source, approval, period earned, period paid and whether the item is cash or notional pay. A plausible email or spreadsheet value is not enough when ownership or cut-off is unclear.',
  'The pay date controls the payroll reporting event. Revenue explains that PAYE operates on a receipts basis: a payment made in a later year is handled using the RPN and rate bands for the year of payment, even when the work was performed earlier. This unit teaches the control; it does not reproduce annual rates or replace current official guidance.',
  'Use a reconciliation: opening fixed pay plus approved additions minus supported reversals equals gross pay before deductions. Investigate differences by code and source. Never force the gross total to match an expected net amount; that reverses the evidence chain and can hide a missing earning or deduction.',
 ],supportPt:'Monte o bruto com entradas aprovadas e data de pagamento. Não ajuste o bruto para “bater” com um líquido esperado.',sourceIds:['revenue-pay-details','revenue-receipts']},
 {id:'p2-bases',title:'2. Keep the statutory pay bases separate',paragraphs:[
  'One gross amount does not mean one identical statutory base. Revenue asks employers to report gross pay and separate pay figures for Income Tax, USC and PRSI. The correct operational habit is to carry distinct fields through the calculation and retain the rule or source behind every difference.',
  'For Income Tax pay, Revenue’s payroll-submission guidance says that regular employee payments to an approved pension or superannuation fund are excluded where the employer grants the allowable relief. PAYE is operated on total taxable pay. Eligibility, limits and scheme treatment must be confirmed from current official information and the payroll configuration; this lesson does not infer qualification from a label such as “pension”.',
  'For USC, Revenue says to use gross pay before employee pension contributions are deducted, subject to the exclusions and rules in current guidance. For PRSI, Revenue says to include gross pay, notional pay or benefits in kind where applicable and that employee payments to approved pension arrangements remain fully chargeable for PRSI. A deduction that reduces Income Tax pay therefore does not automatically reduce USC or PRSI pay.',
  'Permanent Health Benefit contributions can have a similar base distinction: Revenue instructs employers to deduct qualifying contributions for Income Tax but not for USC or PRSI. The lesson is not to memorise one shortcut; it is to map each item to each base using current official rules and evidence.',
  'Base differences must be explainable on the payslip and in the audit trail. Store the earning or deduction code, applicable rule reference, configuration result and review evidence. If the basis is uncertain, hold the conclusion for review rather than copying last month’s treatment without checking whether the employee, scheme or official rule changed.',
 ],supportPt:'Bruto, base de Income Tax, base de USC e base de PRSI são campos distintos. Uma contribuição pode reduzir uma base e não as outras.',sourceIds:['revenue-pay-details','revenue-pension']},
 {id:'p2-statutory',title:'3. Apply supplied statutory outputs without inventing rates',paragraphs:[
  'The PAYE system covers Income Tax, employee PRSI, USC and LPT deduction at source where applicable. The employer operates the deductions each time the employee is paid and reports pay and deductions on or before the pay date. Unit 1 established the identity, RPN and pay-date chain; Unit 2 connects that chain to the gross-to-net record.',
  'For training calculations, this unit supplies statutory outputs rather than asking the learner to recreate live tax rates. In real processing, current RPN data, software configuration, official thresholds, PRSI class and current Revenue or Department of Social Protection material must be used. A neat manual percentage is not evidence that the live payroll result is correct.',
  'Employee PRSI is a deduction from employee pay. Employer PRSI is an employer cost and must not be subtracted from the employee’s net pay. Revenue requires both amounts in the payroll submission, but their economic positions differ. Confusing them creates a materially wrong payslip even when the total employer cost is correctly calculated elsewhere.',
  'LPT is deducted only where applicable through the RPN information. Never invent an LPT deduction from an old payslip or a personal message. Use the relevant payroll notification and preserve the evidence that the deduction belongs to this employee, employment and pay event.',
  'Reconcile statutory outputs to the payroll engine and submission fields. A reviewer should be able to trace gross and bases, RPN/version or system evidence, tax outputs, PRSI class, submission result and any exception. This is a control objective, not a substitute for the live software calculation.',
 ],supportPt:'Use RPN e configuração atual. Employer PRSI é custo do empregador, não desconto do líquido do empregado.',sourceIds:['revenue-paye-guide','revenue-pay-details']},
 {id:'p2-other-deductions',title:'4. Distinguish statutory, authorised and employer-only items',paragraphs:[
  'After statutory deductions, payroll may include employee pension contributions, union subscriptions, repayments, benefit-related deductions or other items. A deduction needs a legal, contractual, scheme or employee-authorisation basis as applicable. The payroll file should show the amount, frequency, start and end conditions, priority, approval and owner.',
  'Do not assume every deduction changes taxable pay. First classify the item; then map its treatment separately for Income Tax, USC and PRSI; finally decide whether it reduces cash net pay. One item can affect these dimensions differently. The payroll code must reflect the supported classification rather than the display label alone.',
  'Employer-only items belong in the total employment cost or reporting trail but not in the arithmetic that reduces the employee’s cash. Employer PRSI is the clearest example in this unit. If a payslip presents an employer item for information, the presentation must not imply that it was taken from the employee.',
  'Net-pay deductions also need reasonableness and privacy controls. A valid deduction for one employee must not be copied to another. Sensitive source documents should be accessed only by authorised roles, and the payslip should display enough description for the employee to understand the movement without exposing unnecessary personal data.',
 ],supportPt:'Classifique cada item em três dimensões: efeito nas bases, efeito no líquido e posição empregado/empregador.',sourceIds:['revenue-pay-details','revenue-pension']},
 {id:'p2-bridge',title:'5. Reconcile the gross-to-net bridge',paragraphs:[
  'The core bridge is gross cash pay, adjusted for cash additions and deductions to arrive at net cash pay. Notional pay can affect statutory bases without adding the same cash to the payment. Employer costs sit outside the employee net bridge. Keep these layers visible rather than forcing every reported amount into one subtraction.',
  'For a supplied-results exercise: gross pay €3,500; employee pension €175; Income Tax €520; USC €110; employee PRSI €140; authorised union deduction €20. Net cash pay is €2,535. If employer PRSI is supplied as €450, total employer cost may use that information, but employee net remains €2,535 because employer PRSI is not an employee deduction.',
  'Reconcile in two directions. From inputs to net: prove every earning and deduction. From net back to inputs: explain the movement from prior period by changed gross items, base treatment, statutory outputs and other deductions. A difference should have a code-level explanation, not the generic phrase “tax changed”.',
  'Use a control total for the whole run: sum employee gross, each statutory deduction, other deductions, net pay and employer cost fields. Compare payroll register, payment file and payroll submission. Unit 7 develops month-end handoff in depth; here the learner practises the employee-level evidence chain.',
 ],supportPt:'No exemplo fornecido: 3.500 − 175 − 520 − 110 − 140 − 20 = 2.535. Employer PRSI não reduz o líquido.',sourceIds:['revenue-pay-details']},
 {id:'p2-explain',title:'6. Explain a payslip without giving unsupported tax advice',paragraphs:[
  'An employee query should start with the payslip facts: gross components, statutory deductions, authorised deductions and net payment. Explain which fields changed and which source or payroll notification was used. Do not promise a refund, interpret personal tax entitlement beyond the evidence or disclose another employee’s information.',
  'Use a boundary sentence when the answer depends on Revenue or a scheme: “I can explain the payroll inputs and deductions shown here. The personal tax outcome or relief eligibility may need to be confirmed through Revenue or the relevant provider.” This remains helpful while avoiding unsupported advice.',
  'A clear explanation can follow gross → distinct bases → statutory deductions → other authorised deductions → net. If one item remains under review, say exactly which one and give a deadline. “Your pay is correct” is not an explanation; “the overtime is included, the pension contribution reduces the Income Tax pay field on the supplied configuration but not USC or PRSI, and the remaining query is the union deduction authorisation” is testable.',
  'Close the query with evidence and ownership. Record what was checked, what was shared with the employee, any correction route and the next update. The aim is not merely to answer once; it is to leave a controlled record that supports the employee and the payroll audit trail.',
 ],supportPt:'Explique entradas e descontos do contracheque, mas não invente direito tributário pessoal. Diga o que depende de Revenue ou do provedor.',sourceIds:['revenue-paye-guide','revenue-pay-details','revenue-pension']},
];

export const DEEP_PAYROLL_UNIT_2_LEARN_TEXT=sections.flatMap(section=>[section.title,...section.paragraphs,section.supportPt]);
const ev=(objectiveIds:readonly string[],errorBank:'after-final-incorrect'|'confirmed-only'='after-final-incorrect')=>({objectiveIds,record:'item-result' as const,errorBank});
const practice:readonly ProgressivePracticeItem[]=[
 {id:'p2-practice-1',prompt:'Which item belongs in gross pay before deductions?',progression:'retrieve',sourceBucket:'current',responseMode:'multi-select',estimatedMinutes:2,options:[{id:'a',label:'Salary'},{id:'b',label:'Approved overtime paid this period'},{id:'c',label:'Employer PRSI deducted from net'},{id:'d',label:'Commission paid this period'}],evaluation:{kind:'selection',correctOptionIds:['a','b','d'],explanation:'Revenue includes salary, overtime and commission paid in gross pay. Employer PRSI is an employer cost, not an employee net deduction.'},evidence:ev(['p2-obj-gross'])},
 {id:'p2-practice-2',prompt:'A qualifying employee pension contribution is relieved for Income Tax in the supplied configuration. Does that automatically reduce USC and PRSI pay?',progression:'explain',sourceBucket:'current',responseMode:'single-select',estimatedMinutes:2,options:[{id:'a',label:'Yes, every statutory base is identical.'},{id:'b',label:'No. Revenue states no employee pension relief from USC or PRSI.'},{id:'c',label:'Only when net pay is low.'}],evaluation:{kind:'selection',correctOptionIds:['b'],explanation:'Keep bases separate. The supplied qualifying contribution may reduce Income Tax pay, but not USC or PRSI pay.'},evidence:ev(['p2-obj-bases'])},
 {id:'p2-practice-3',prompt:'Classify employer PRSI in the gross-to-net bridge.',progression:'retrieve',sourceBucket:'current',responseMode:'single-select',estimatedMinutes:2,options:[{id:'a',label:'Employee deduction from net pay.'},{id:'b',label:'Employer cost and payroll-submission field, not an employee net deduction.'},{id:'c',label:'Employee pension contribution.'}],evaluation:{kind:'selection',correctOptionIds:['b'],explanation:'Employer PRSI is paid by the employer and must not reduce employee cash net pay.'},evidence:ev(['p2-obj-statutory'])},
 {id:'p2-practice-4',prompt:'Calculate net cash pay from supplied values: gross €3,500; pension €175; PAYE €520; USC €110; employee PRSI €140; union €20.',progression:'apply',sourceBucket:'current',responseMode:'calculation',estimatedMinutes:4,evaluation:{kind:'answer-key',acceptedAnswers:['2535','€2,535','2,535'],explanation:'€3,500 − €175 − €520 − €110 − €140 − €20 = €2,535.'},evidence:ev(['p2-obj-bridge'])},
 {id:'p2-practice-5',prompt:'The same case supplies employer PRSI of €450. Recalculate employee net pay.',progression:'apply',sourceBucket:'current',responseMode:'short-text',estimatedMinutes:2,evaluation:{kind:'answer-key',acceptedAnswers:['€2,535; employer PRSI does not reduce employee net pay.','2535'],explanation:'Net stays €2,535. Employer PRSI belongs outside the employee deduction bridge.'},evidence:ev(['p2-obj-bridge','p2-obj-statutory'])},
 {id:'p2-practice-6',prompt:'Build the four-field basis map for gross €3,500 and a supplied qualifying employee pension contribution of €175. No other base adjustments are supplied.',progression:'apply',sourceBucket:'current',responseMode:'extended-text',estimatedMinutes:5,evaluation:{kind:'rubric',criteria:[{id:'b1',description:'Gross pay €3,500.',points:1},{id:'b2',description:'Income Tax pay €3,325 subject to the supplied qualifying treatment.',points:1},{id:'b3',description:'USC pay €3,500 on supplied facts.',points:1},{id:'b4',description:'PRSI pay €3,500 on supplied facts.',points:1},{id:'b5',description:'States that live eligibility and configuration need official confirmation.',points:1}],modelAnswer:'Gross €3,500; Income Tax pay €3,325 on the supplied qualifying treatment; USC pay €3,500; PRSI pay €3,500. Confirm the scheme, current rules and payroll configuration in live processing.'},evidence:ev(['p2-obj-bases'])},
 {id:'p2-practice-7',prompt:'An overtime item was earned in December but paid in January. What date controls this PAYE reporting event?',progression:'apply',sourceBucket:'current',responseMode:'short-text',estimatedMinutes:3,evaluation:{kind:'rubric',criteria:[{id:'d1',description:'Identifies January pay date/receipts basis.',points:1},{id:'d2',description:'Uses the relevant-year RPN and bands.',points:1},{id:'d3',description:'Reports on or before pay date.',points:1}],modelAnswer:'The January payment date controls. Use the RPN and applicable information for the year of payment and report on or before that pay date.'},evidence:ev(['p2-obj-gross'])},
 {id:'p2-practice-8',prompt:'Write a controlled employee explanation of the supplied pension-base difference.',progression:'transfer',sourceBucket:'current',responseMode:'extended-text',estimatedMinutes:4,evaluation:{kind:'rubric',criteria:[{id:'e1',description:'Explains gross and pension amount.',points:1},{id:'e2',description:'Explains distinct bases without quoting invented rates.',points:1},{id:'e3',description:'States the live-source boundary.',points:1}],modelAnswer:'Your gross pay is €3,500 and the employee pension contribution is €175. On the supplied approved treatment it reduces the Income Tax pay field, but not the USC or PRSI pay fields. I can explain the payroll configuration; personal relief eligibility should be confirmed through the current official or scheme route.'},evidence:ev(['p2-obj-explain'],'confirmed-only')},
 {id:'p2-practice-9',prompt:'A deduction labelled “loan” appears without authorisation or an owner. What should payroll do?',progression:'integrate',sourceBucket:'current',responseMode:'short-text',estimatedMinutes:3,evaluation:{kind:'rubric',criteria:[{id:'l1',description:'Does not process solely from the label.',points:1},{id:'l2',description:'Requests legal/contractual/authorisation evidence and owner.',points:1},{id:'l3',description:'Escalates before pay cut-off.',points:1}],modelAnswer:'Hold the unsupported conclusion, obtain the applicable authorisation and ownership evidence, confirm amount and timing, and escalate before cut-off. Do not copy a prior employee deduction.'},evidence:ev(['p2-obj-deductions'])},
 {id:'p2-practice-10',prompt:'Name the employee-level records needed to explain a net-pay movement.',progression:'explain',sourceBucket:'current',responseMode:'extended-text',estimatedMinutes:4,evaluation:{kind:'rubric',criteria:[{id:'r1',description:'Gross components and sources.',points:1},{id:'r2',description:'Distinct statutory bases and RPN/configuration evidence.',points:1},{id:'r3',description:'Statutory and other deductions.',points:1},{id:'r4',description:'Net, owners and exceptions.',points:1}],modelAnswer:'Retain gross components and approvals, distinct Income Tax/USC/PRSI bases, RPN or configuration evidence, statutory outputs, authorised deductions, employer-only items, net payment and exception ownership.'},evidence:ev(['p2-obj-bridge'])},
];

const examples:DeepLessonContract['workedExamples']=[
 {id:'p2-example-bases',title:'One gross amount, three statutory bases',scenario:['Gross pay €3,500.','Supplied qualifying employee pension contribution €175.','No other base adjustments supplied.'],estimatedMinutes:8,steps:[{id:'x1',action:'Record gross',reasoning:'Gross precedes deductions.',result:'€3,500.'},{id:'x2',action:'Map Income Tax pay',reasoning:'The supplied qualifying pension treatment reduces this field.',calculation:'€3,500 − €175',result:'€3,325.'},{id:'x3',action:'Map USC and PRSI pay',reasoning:'Employee pension relief is not supplied for USC or PRSI.',result:'€3,500 for each on the supplied facts.'}],conclusion:'Separate bases by rule and evidence; do not infer live eligibility from the exercise.',transferPrompt:'How would an unapproved or non-qualifying item change the evidence needed?'},
 {id:'p2-example-net',title:'Gross-to-net without employer-cost leakage',scenario:['Gross €3,500; pension €175; PAYE €520; USC €110; employee PRSI €140; union €20.','Employer PRSI €450 is shown separately.'],estimatedMinutes:8,steps:[{id:'n1',action:'Identify employee deductions',reasoning:'Only employee-side cash deductions reduce net.',result:'€965 total deductions.'},{id:'n2',action:'Calculate net',reasoning:'Subtract supported employee deductions from gross cash pay.',calculation:'3,500 − 175 − 520 − 110 − 140 − 20',result:'€2,535.'},{id:'n3',action:'Position employer PRSI',reasoning:'It is an employer cost and submission field.',result:'Do not subtract €450 from employee net.'}],conclusion:'Employee net is €2,535; employer cost is analysed separately.',transferPrompt:'What control would detect employer PRSI incorrectly mapped as an employee deduction?'},
 {id:'p2-example-query',title:'Explain a payslip without unsupported advice',scenario:['Employee asks why pension reduced one field but not two others.','Payroll has confirmed the supplied scheme configuration but not the employee’s wider personal tax position.'],estimatedMinutes:7,steps:[{id:'q1',action:'State payslip facts',reasoning:'Begin with visible amounts and configuration.',result:'Name gross, contribution and three bases.'},{id:'q2',action:'Explain the rule boundary',reasoning:'Qualifying contribution treatment differs by statutory base.',result:'Income Tax field differs; USC/PRSI do not on supplied facts.'},{id:'q3',action:'Protect advice boundary',reasoning:'Personal entitlement may require Revenue/provider confirmation.',result:'Offer the correct route and a follow-up owner.'}],conclusion:'Explain payroll evidence clearly while separating it from personal tax advice.',transferPrompt:'How would you respond if the employee disputes scheme eligibility rather than the payslip arithmetic?'},
];

const revisions:DeepLessonContract['revisionTargets']=[
 {id:'p2-rev-1',prompt:'List items that can form gross pay in this unit.',objectiveIds:['p2-obj-gross'],successCriterion:'Salary/wages plus supported overtime, bonus, commission, holiday and notional pay as applicable.',revisitAfterDays:[1,7,30],estimatedMinutes:1.5},
 {id:'p2-rev-2',prompt:'Explain why one gross amount can create different statutory bases.',objectiveIds:['p2-obj-bases'],successCriterion:'Each item is mapped separately to Income Tax, USC and PRSI under current rules.',revisitAfterDays:[1,7,30],estimatedMinutes:1.5},
 {id:'p2-rev-3',prompt:'Place employee and employer PRSI in the bridge.',objectiveIds:['p2-obj-statutory'],successCriterion:'Employee PRSI reduces net; employer PRSI is employer cost, not an employee deduction.',revisitAfterDays:[1,7,30],estimatedMinutes:1.5},
 {id:'p2-rev-4',prompt:'Rebuild the supplied €3,500 to €2,535 net bridge.',objectiveIds:['p2-obj-bridge'],successCriterion:'All six employee deductions included; employer PRSI excluded.',revisitAfterDays:[1,7,30],estimatedMinutes:2},
 {id:'p2-rev-5',prompt:'Give the boundary sentence for an employee query.',objectiveIds:['p2-obj-explain'],successCriterion:'Explain payroll inputs/deductions; route personal entitlement to Revenue/provider as needed.',revisitAfterDays:[1,7,30],estimatedMinutes:1.5},
];

const audio=[
 {id:'p2-audio-1',kind:'opening' as const,title:'The net pay that looked too low',estimatedMinutes:1,script:'An employee says her net pay is too low because the employer PRSI shown on the payroll report must have been taken from her pay. Your task is to reconstruct the bridge before agreeing or disagreeing. The supplied facts are gross pay of three thousand five hundred euro, an employee pension contribution of one hundred seventy-five, PAYE of five hundred twenty, USC of one hundred ten, employee PRSI of one hundred forty and an authorised union deduction of twenty. Employer PRSI is four hundred fifty. Pause and decide which amounts belong inside the employee net calculation.'},
 {id:'p2-audio-2',kind:'worked-example' as const,title:'Rebuild the bridge',estimatedMinutes:2,script:'Start with gross cash pay of three thousand five hundred. Subtract the employee pension contribution, PAYE, USC, employee PRSI and union deduction. The deductions total nine hundred sixty-five, so net cash pay is two thousand five hundred thirty-five. Do not subtract employer PRSI. It is reported and forms part of employer cost, but it is not an employee deduction. Now move one layer back. Gross pay is not necessarily the Income Tax, USC and PRSI pay figure. On the supplied qualifying pension treatment, the Income Tax pay field is three thousand three hundred twenty-five. USC and PRSI pay remain three thousand five hundred because no employee pension relief from those bases is supplied. In live payroll, confirm current official rules, scheme eligibility, RPN and configuration rather than turning this example into a rate calculator.'},
 {id:'p2-audio-3',kind:'retrieval-pause' as const,title:'Classify before calculating',estimatedMinutes:1,script:'Classify four new items. Overtime approved and paid this period belongs in gross. A notional benefit may enter gross and statutory bases even though the same cash is not added to the payment. An employer contribution or employer PRSI belongs to the employer layer and must not automatically reduce employee cash. A deduction labelled loan cannot be processed from its label alone; payroll needs the applicable authorisation, amount, timing and owner. Pause after each item and name three dimensions: effect on statutory bases, effect on employee net and employee-versus-employer position. Now add an employee pension contribution. Do not say simply that it is “pre-tax”. Ask which approved scheme, whether relief is operated through payroll, and which statutory base is being discussed. On the supplied facts it changes the Income Tax pay field but does not reduce USC or PRSI pay. The label on a spreadsheet is not enough. A reviewer needs the source rule, configuration and employee-specific evidence. This three-dimensional classification prevents the most common bridge error: treating every item as either fully deductible everywhere or irrelevant everywhere.'},
 {id:'p2-audio-4',kind:'dialogue' as const,title:'Explain the payslip',estimatedMinutes:1,script:'EMPLOYEE: Why did my pension reduce taxable pay but not the other deductions? PAYROLL: Your gross pay is three thousand five hundred and your employee pension contribution is one hundred seventy-five. On the supplied approved configuration, it reduces the Income Tax pay field, but Revenue guidance does not give employee pension relief from USC or PRSI. EMPLOYEE: Does that mean the tax is definitely right? PAYROLL: I can confirm the payroll inputs, the RPN used and the configured calculation. Your wider personal relief position may need confirmation through Revenue or the scheme provider. I will send the payslip bridge and the evidence reference today. Notice that the answer is useful without promising a personal tax conclusion.'},
 {id:'p2-audio-5',kind:'transfer' as const,title:'New pay-date case',estimatedMinutes:1,script:'An employee earned overtime in December and receives it in January. Explain the processing boundary in forty-five seconds. Use the January pay date, the relevant-year RPN and current configuration, include the overtime in the supported gross input and report on or before payment. Then add a union deduction with no authorisation. Do not guess: flag the missing evidence, name the owner and protect cut-off. Finish by rebuilding gross, distinct statutory bases, employee deductions, employer-only items and net in that order. Your answer succeeds when another payroll professional can reproduce every step from the evidence trail. Try a second version for an employee. Begin with the payslip facts, explain that pay date controls the processing event, and identify the specific deduction still under review. Do not quote a tax rate from memory or promise a refund. State what payroll can verify today, what needs Revenue or provider confirmation, who owns the check and when the next update will arrive. The technical calculation and the service explanation should tell the same evidence-based story.'},
] as const;

export const DEEP_PAYROLL_UNIT_2_CONTRACT:DeepLessonContract={
 schemaVersion:DEEP_LESSON_SCHEMA_VERSION,editorial:{status:'deep-reviewed',depthVersion:'payroll-p2-depth-2026-09-24',reviewedOn:'2026-09-24'},
 course:{kind:'payroll',jurisdiction:'Ireland',effectivePeriod:'Official sources reviewed 2026-09-24; live rules and RPN required at processing time'},
 curriculum:{provider:'Revenue source-aligned local curriculum',framework:'Irish Payroll gross-to-net evidence chain',version:'2026-09-24 source snapshot',outcomeIds:['p2-gross','p2-bases','p2-statutory','p2-deductions','p2-bridge','p2-explain'],sourceUrl:sources[1].url},
 prerequisites:['Complete Payroll Unit 1 identity, RPN and pay-date workflow.','Distinguish employee identity, employment ID and pay event.'],
 objectives:[
  {id:'p2-obj-gross',statement:'Build gross pay from supported fixed, variable and notional inputs for the pay date.',evidenceIds:[LEARN_TEXT_EVIDENCE_ID,'p2-practice-1','p2-practice-7'],level:'apply'},
  {id:'p2-obj-bases',statement:'Reconcile gross, Income Tax pay, USC pay and PRSI pay without assuming they are identical.',evidenceIds:[LEARN_TEXT_EVIDENCE_ID,'p2-practice-2','p2-practice-6','p2-example-bases'],level:'analyse'},
  {id:'p2-obj-statutory',statement:'Position statutory outputs and distinguish employee PRSI from employer PRSI.',evidenceIds:['p2-practice-3','p2-practice-5','p2-example-net'],level:'apply'},
  {id:'p2-obj-deductions',statement:'Process only supported authorised deductions and classify employer-only items separately.',evidenceIds:[LEARN_TEXT_EVIDENCE_ID,'p2-practice-9'],level:'apply'},
  {id:'p2-obj-bridge',statement:'Rebuild and explain an employee-level gross-to-net bridge.',evidenceIds:['p2-practice-4','p2-practice-10','p2-example-net','p2-case'],level:'analyse'},
  {id:'p2-obj-explain',statement:'Explain a payslip and preserve the boundary between payroll evidence and personal tax advice.',evidenceIds:['p2-practice-8','p2-example-query','p2-case'],level:'create'},
 ],
 workload:{totalMinutes:84,phases:[
  {id:'p2-phase-learn',kind:'learn',title:'Six operational teaching blocks',plannedMinutes:12,evidenceIds:[LEARN_TEXT_EVIDENCE_ID]},
  {id:'p2-phase-examples',kind:'worked-example',title:'Three worked evidence chains',plannedMinutes:23,evidenceIds:examples.map(item=>item.id)},
  {id:'p2-phase-practice',kind:'practice',title:'Ten progressive items',plannedMinutes:31,evidenceIds:practice.map(item=>item.id)},
  {id:'p2-phase-case',kind:'other',title:'Integrated payroll review',plannedMinutes:10,evidenceIds:['p2-case']},
  {id:'p2-phase-revision',kind:'revision',title:'Closed-book retrieval',plannedMinutes:8,evidenceIds:revisions.map(item=>item.id)},
 ],paceNote:'The 84-minute core uses supplied fictional outputs and excludes the alternative 6-minute Audio episode. No live tax rate is embedded.'},
 workedExamples:examples,practice:{items:practice,attemptsBeforeReveal:2},
 misconceptions:[
  {id:'p2-mis-1',misconception:'Basic salary is always the full gross pay.',correction:'Approved variable and notional items may also form gross for the period.',diagnosticPrompt:'Name the supported additions missing from basic salary.',objectiveIds:['p2-obj-gross']},
  {id:'p2-mis-2',misconception:'Every deduction reduces every statutory base.',correction:'Map Income Tax, USC and PRSI separately.',diagnosticPrompt:'Explain the supplied pension-base difference.',objectiveIds:['p2-obj-bases']},
  {id:'p2-mis-3',misconception:'Employer PRSI is taken from employee net pay.',correction:'It is an employer cost and separate submission amount.',diagnosticPrompt:'Rebuild net with employer PRSI shown separately.',objectiveIds:['p2-obj-statutory']},
  {id:'p2-mis-4',misconception:'A deduction label is sufficient authority to process it.',correction:'Evidence, amount, timing, basis and owner are required.',diagnosticPrompt:'List the controls missing from an unsupported loan deduction.',objectiveIds:['p2-obj-deductions']},
 ],
 examTasks:[{id:'p2-case',title:'Grand Canal Services · controlled gross-to-net review',scenario:['Gross inputs supplied: salary €3,100, overtime €250 and bonus €150.','Employee pension €175 has a supplied qualifying Income Tax treatment.','Supplied statutory outputs: PAYE €520, USC €110, employee PRSI €140.','Union deduction €20 is authorised. Employer PRSI €450 is supplied separately.','The employee asks why bases differ and whether employer PRSI reduced net.'],requirements:[{id:'p2-case-a',prompt:'Build gross, the three supplied bases and net pay.',marks:6},{id:'p2-case-b',prompt:'Explain the result and evidence boundary to the employee.',marks:4}],totalMarks:10,timeLimitMinutes:10,markingGuide:[{id:'m1',criterion:'Gross €3,500.',marks:1},{id:'m2',criterion:'Income Tax pay €3,325 on supplied treatment.',marks:1},{id:'m3',criterion:'USC pay €3,500.',marks:1},{id:'m4',criterion:'PRSI pay €3,500.',marks:1},{id:'m5',criterion:'Net €2,535.',marks:1},{id:'m6',criterion:'Employer PRSI excluded from net.',marks:1},{id:'m7',criterion:'Explains distinct bases.',marks:1},{id:'m8',criterion:'Uses supplied outputs without inventing rates.',marks:1},{id:'m9',criterion:'Explains employer-cost boundary.',marks:1},{id:'m10',criterion:'Routes personal eligibility question appropriately.',marks:1}],modelAnswer:'Gross is €3,500. On the supplied qualifying pension treatment, Income Tax pay is €3,325; USC and PRSI pay remain €3,500. Net is €3,500 − €175 − €520 − €110 − €140 − €20 = €2,535. Employer PRSI of €450 is an employer cost and does not reduce employee net. Explain the current payroll inputs, RPN/configuration and supplied rule treatment; route wider personal relief eligibility to Revenue or the provider.'}],
 revisionTargets:revisions,
 audioEpisode:{format:'authored-script',title:'The deduction that was not the employee’s',editorialGoal:'Rebuild a new gross-to-net case, base map and employee explanation without narrating Learn or embedding live rates.',estimatedMinutes:6,distinctiveElements:['Fictional supplied-output bridge','Employee-versus-employer classification drill','Payslip dialogue','Pay-date transfer case'],segments:audio},
 completion:{itemLevelEvidenceRequired:true,requirements:[{id:'p2-complete-learn',targetIds:[LEARN_TEXT_EVIDENCE_ID],rule:'view'},{id:'p2-complete-examples',targetIds:examples.map(item=>item.id),rule:'view'},{id:'p2-complete-practice',targetIds:practice.map(item=>item.id),rule:'attempt'},{id:'p2-complete-case',targetIds:['p2-case'],rule:'submit'},{id:'p2-complete-revision',targetIds:revisions.map(item=>item.id),rule:'meet-threshold',minimum:.8}]},
 payroll:{sourceSnapshotOn:'2026-09-24',liveRatePolicy:'official-source-required',operationalChecks:['Use current RPN and pay-date evidence.','Keep gross, Income Tax pay, USC pay and PRSI pay as distinct fields.','Never deduct employer PRSI from employee net.','Require evidence and authority for every non-statutory deduction.','Do not infer a live tax rate from fictional training outputs.']},
};

export const DEEP_PAYROLL_UNIT_2={lessonId:PAYROLL_IDENTITIES.P2.id,title:'Unit 2 · Gross pay, taxable bases and deductions',goal:'Build an evidence-backed gross-to-net bridge while keeping statutory bases and employer items separate.',scope:'Irish Payroll operational training using official source boundaries and fictional supplied outputs. No live rates or personal tax advice.',sections,sources,contract:DEEP_PAYROLL_UNIT_2_CONTRACT,learnText:DEEP_PAYROLL_UNIT_2_LEARN_TEXT};
