import {ENGLISH_E1_MODEL_ID,ENGLISH_P1_MODEL_ID} from './localEnglishLessonRegistry.ts';
import {VIVIANE_ENGLISH_IDENTITIES} from './vivianeEnglishLessonRegistry.ts';

export type GrammarConcept={
 id:string;title:string;form:string;when:string;why:string;how:string;
 examples:readonly [string,string];contrast:string;
};

const story:readonly GrammarConcept[]=[
 {id:'past-simple',title:'Past simple',form:'I went / she arrived',when:'Use it for a completed event at a finished time, or for the next event in a story.',why:'The listener needs the sequence of what happened, without treating every action as a continuing background.',how:'Use the past form: regular verbs take -ed; irregular verbs have their own form. Questions and negatives use did + base verb.',examples:['Nora got off the bus and walked towards Riverside Court.','Did she find the community centre? She did, but the talk had started.'],contrast:'“She went” moves the story forward; “she was going” presents an action already in progress.'},
 {id:'past-continuous',title:'Past continuous',form:'I was looking / they were waiting',when:'Use it for an action in progress at a past moment, often as the background to a shorter event.',why:'It lets the listener see what was unfolding when something else happened.',how:'Use was or were + verb-ing. The short event commonly appears in the past simple.',examples:['Nora was standing under a tree when Sam spoke to her.','The rain was getting heavier while she was walking.'],contrast:'“Sam spoke” is the event; “Nora was standing” is the scene in progress.'},
 {id:'past-perfect',title:'Past perfect',form:'I had saved / she had started',when:'Use it when an earlier event matters to a later moment in a past story.',why:'It makes the order clear when the story does not simply follow the order in which events occurred.',how:'Use had + past participle. Once the order is clear, ordinary past simple often carries the rest of the story.',examples:['Nora had selected the wrong Riverside before she reached the houses.','The talk had already started when she arrived.'],contrast:'You do not need past perfect for every earlier sentence; use it where the relationship helps the listener.'},
 {id:'story-sequence',title:'Link events and their result',form:'when / after / because / in the end',when:'Use time and result links to show how one detail leads to another.',why:'A listener can follow the turning point and understand why the ending matters.',how:'Choose the link that expresses the real relationship. “Because” gives a cause; “when” locates an event in time.',examples:['When Nora checked the street name, she realised she had chosen the wrong place.','In the end, the organiser added a clearer landmark to the event page.'],contrast:'Do not use a cause word if the audio only gives a sequence. Preserve what is known.'},
 {id:'follow-up',title:'Ask a connected follow-up',form:'How did…? / What happened next?',when:'Use it after someone gives a detail that invites a genuine question.',why:'A focused question shows that you followed the story and keeps the exchange natural.',how:'In a past-simple question, use did + subject + base verb. Ask about the detail the speaker actually mentioned.',examples:['How did Nora realise she was at the wrong Riverside?','Did Sam come to the exhibition later?'],contrast:'“Did you went?” is incorrect; after did, say “Did you go?”'},
];

const meeting:readonly GrammarConcept[]=[
 {id:'embedded-questions',title:'Embedded questions',form:'Could you confirm when the file was approved?',when:'Use an opening phrase when you need a clear question in a meeting without sounding abrupt.',why:'It requests evidence while leaving room for the other person to clarify the source.',how:'After the opening, keep statement word order: when the file was approved, not when was the file approved.',examples:['Could we confirm which report you are comparing?','Do we know whether the mapping changed?'],contrast:'Direct: “When was it approved?” Embedded: “Could you confirm when it was approved?”'},
 {id:'modal-requests',title:'Modal requests',form:'could / would',when:'Use a modal when asking for a check, explanation or action in a shared task.',why:'The request stays precise while respecting the other person’s role.',how:'Use could or would + subject + base verb in the opening question.',examples:['Could you walk me through the final upload?','Would you check the approval time before we decide?'],contrast:'Politeness does not require a long apology; include the evidence or action you need.'},
 {id:'evidence',title:'Facts and possible causes',form:'confirmed / may have',when:'Use a direct statement for confirmed evidence and a modal when the cause is still open.',why:'A plausible explanation should not become a conclusion before the checks are complete.',how:'Use may have + past participle for a possible earlier cause; state the confirmed fact separately.',examples:['The two reports used different cut-off times.','The journal may have caused the difference, but the mapping file also changed.'],contrast:'“The journal caused it” claims more than “The journal may have caused it.”'},
 {id:'playback',title:'Check understanding',form:'Just to check, I will…',when:'Use a short playback before closing a decision or handing over work.',why:'It makes the owner, evidence and deadline easy for the team to correct.',how:'Summarise the confirmed action, then ask whether you captured it correctly.',examples:['Just to check, I will reconcile the reports and send the exceptions by three.','Have I captured the next step correctly?'],contrast:'“Do you understand?” tests the person. A concrete playback tests the shared decision.'},
 {id:'future-action',title:'Commit to the next action',form:'I will reconcile / we will decide',when:'Use will for an action you take on now, a promise, or a decision after the evidence arrives.',why:'An explicit next step prevents a meeting from ending with an unresolved “we will investigate”.',how:'Use will + base verb and name the owner, object and time when known.',examples:['I will reconcile the journals before the next update.','We will decide after Theo validates the mapping.'],contrast:'Do not promise a conclusion when you can only promise the next check.'},
];

const plans:readonly GrammarConcept[]=[
 {id:'arrangement',title:'Present continuous for arrangements',form:'We are meeting at two',when:'Use it for a future plan already arranged with another person.',why:'It tells the listener that the time or place is already agreed.',how:'Use am/is/are + verb-ing with a future time or context.',examples:['Ciara and Viviane are meeting by the canal at two.','We are taking the bus together on Saturday.'],contrast:'A present-continuous arrangement differs from an action happening right now; the future time supplies the meaning.'},
 {id:'intention',title:'Going to for an intention',form:'I am going to bring a coat',when:'Use it for a plan or intention decided before you speak.',why:'It distinguishes a prior intention from a decision made in the moment.',how:'Use am/is/are going to + base verb.',examples:['I am going to bring a coat for the walk.','We are going to check the forecast before leaving.'],contrast:'“I am going to check” presents a plan; “I will check” can be a decision made now.'},
 {id:'decision',title:'Will for a decision now',form:'I will check the forecast',when:'Use it for an immediate decision, promise or offer.',why:'It shows what you decide or undertake at the moment of speaking.',how:'Use will + base verb; will does not change for he, she or they.',examples:['It looks cloudy. I will check the forecast.','I will message you when I get there.'],contrast:'Will is not a universal replacement for every arranged future event.'},
 {id:'condition',title:'If and a real possibility',form:'If it rains, we will meet inside',when:'Use a first conditional for a realistic future condition and its result.',why:'It gives the group a clear alternative without treating the condition as certain.',how:'Use if + present simple for the condition and will + base verb for the result.',examples:['If it rains, we will go to the indoor market.','We will walk by the canal if it stays dry.'],contrast:'After if, say “if it rains”, not “if it will rain”, for this meaning.'},
 {id:'suggestion',title:'Could for an alternative',form:'We could go to the market',when:'Use it to suggest one option while leaving the choice open.',why:'It lets both speakers adapt the plan naturally.',how:'Use could + base verb, then clarify when or why the alternative would help.',examples:['If the weather changes, we could go to the indoor market.','Could we meet at the station instead?'],contrast:'“We could” offers an option; “we will” states a decision or strong expectation.'},
];

export function grammarConceptsFor(lessonId:string):readonly GrammarConcept[]{
 if(lessonId===ENGLISH_E1_MODEL_ID||lessonId===VIVIANE_ENGLISH_IDENTITIES.VE1.id)return story;
 if(lessonId===ENGLISH_P1_MODEL_ID)return meeting;
 if(lessonId===VIVIANE_ENGLISH_IDENTITIES.VE2.id)return plans;
 return [];
}
