import type { StudyTrack } from './teachingPacks';

export type LessonSource={id:string;label:string;url:string;supports:string;reviewedOn:string};
export type LessonSection={id:string;title:string;paragraphs:readonly string[];supportPt:string;sourceIds:readonly string[]};
export type CheckpointQuestion={id:string;prompt:string;options:readonly string[];correctIndex:number;explanation:string;reviewSection:string};
export type LessonModule={
 track:StudyTrack;lessonId:string;title:string;goal:string;scope:string;sections:readonly LessonSection[];
 terms:readonly {term:string;meaning:string;pt:string;example:string}[];
 visual:{title:string;note:string;headers:readonly [string,string,string];rows:readonly (readonly [string,string,string])[];question:string;answer:string};
 caseStudy:{title:string;scenario:readonly string[];task:string;hints:readonly [string,string];modelAnswer:string;reviewChecks:readonly string[];transfer:string};
 checkpoint:readonly CheckpointQuestion[];sources:readonly LessonSource[];
};
const reviewedOn='2026-09-13';
const source=(id:string,label:string,url:string,supports:string):LessonSource=>({id,label,url,supports,reviewedOn});
// Original authored foundations. Tax amounts are supplied fictional inputs, never a live calculator.
// These modules are not imported by the voice worker and do not publish scores to the learner record.
export const LESSON_MODULES:Readonly<Record<StudyTrack,LessonModule>>={
 finance:{
  track:'finance',lessonId:'b3639582-3c32-4147-a4b3-84237d11a66e',title:'IFRS 18, Group Reporting & Irish Statutory Accounts',
  goal:'Build a profit bridge, distinguish a management measure from an IFRS subtotal, and scope the reporting work before changing a system.',
  scope:'Written foundation: IFRS 18 presentation and reporting-basis scoping. Not a complete consolidation, statutory-accounts, transition or MPM-disclosure course. Figures are original fictional examples; classification assumptions are stated.',
  sections:[
   {id:'fin-presentation',title:'1. Start with the reporting question',paragraphs:[
    'IFRS 18 replaces IAS 1 for annual periods beginning on or after 1 January 2027; early application is permitted. It focuses on presentation and disclosure, including defined profit-or-loss subtotals, management-defined performance measures and the grouping of information. A presentation change is not, by itself, a new tax or a change in the underlying transaction.',
    'For this lesson, imagine a controller receiving a request to rebuild a report. First separate three questions: what happened in the business, how the ledger records it, and where the report presents it. Reclassifying a line between categories should not silently create another expense. A useful control is to reconcile the total before and after the mapping change and investigate differences rather than accepting a visually cleaner report.'
   ],supportPt:'Separe o fato econômico, o registro no razão e a apresentação. Uma reclassificação não deve criar uma nova despesa nem esconder uma diferença de conciliação.',sourceIds:['ifrs-overview']},
   {id:'fin-bridge',title:'2. Read the bridge, not just the bottom line',paragraphs:[
    'Operating profit aggregates the operating category. Profit before financing and income taxes adds the investing category to operating profit. Category decisions require the facts, including whether investing in assets or providing finance to customers is a main business activity; do not reuse a manufacturer example as a universal rule for a bank.',
    'Assume a fictional non-financial entity whose classification has already been assessed: revenue 1,000, operating expenses 760, investing income 12, financing expense 32 and income tax 55. Operating profit is 240; profit before financing and income taxes is 252; profit for the period is 165. There are no discontinued operations in this exercise. Explain each transition aloud: 240 plus 12, then less 32 and 55. The three figures answer different questions.',
    'An original implementation exercise: select five material ledger accounts, record the proposed category, the supporting facts and the reviewer. Test the mapping using the same ledger extract for both presentations. Flag exceptions for review; a plausible account name alone does not settle the classification.'
   ],supportPt:'Neste exemplo, 240 é o resultado operacional, 252 é o subtotal anterior a financiamento e imposto de renda, e 165 é o lucro final. O cálculo depende das classificações assumidas, não de uma regra universal por nome de conta.',sourceIds:['ifrs-terms']},
   {id:'fin-mpm',title:'3. Challenge an adjusted performance headline',paragraphs:[
    'An MPM is a qualifying subtotal of income and expenses used in public communication outside the financial statements to convey management’s view of the performance of the entity as a whole, excluding measures specified by IFRS. The label “adjusted”, an internal KPI or a ratio is not enough on its own to meet that definition.',
    'Original example: a public investor presentation highlights adjusted operating profit of 260, while operating profit is 240. Management adds back a cost of 20. Before accepting the headline, ask what the adjustment represents, where the measure is communicated and why management uses it. If the definition is met, the applicable disclosure requirements must be assessed. Calling a cost “one-off” does not erase it from the IFRS subtotal.',
    'For this foundation, write a transparent bridge of 240 + 20 = 260 and identify the missing disclosure information. This short bridge is not a complete MPM note. A manager-level answer distinguishes the required reported figure, the separate management measure and the evidence still needed, rather than choosing whichever number appears stronger.'
   ],supportPt:'Uma medida ajustada não substitui automaticamente o subtotal IFRS. Apresente a ponte e avalie a definição antes de classificar o indicador como MPM. Esta atividade não prepara a nota explicativa completa.',sourceIds:['ifrs-terms','ifrs-overview']},
   {id:'fin-basis',title:'4. Separate the group package from the local reporting basis',paragraphs:[
    'An Irish entity is not automatically an IFRS preparer. FRS 102 applies to entities not applying adopted IFRS, FRS 101 or FRS 105. FRS 101 is a reduced-disclosure framework for qualifying individual financial statements; it is not simply another name for every set of IFRS group accounts.',
    'Original scoping exercise: the parent requests an IFRS group package while a subsidiary prepares local statutory accounts under another eligible framework. Create two columns: group requirements and statutory requirements. Confirm the actual basis, entity eligibility, reporting period, policy differences and who approves each output. A shared ledger can support two outputs, but an identical report heading does not prove their recognition, measurement and disclosure requirements are identical.',
    'The FRC’s current FRS 102 page also lists adapted-format amendments effective from 1 January 2027. Do not infer from the IFRS 18 headline that every FRS 102 entity has adopted all IFRS 18 requirements. Check the relevant standard and the entity’s chosen format. This lesson identifies the scoping decision; it does not determine an entity’s legal eligibility or prepare its statutory filing.',
    'Your practical deliverable is a small implementation register: reporting output, applicable basis, affected data mapping, unresolved question, owner and next check. This turns a standards discussion into a controlled project without pretending that a presentation exercise resolves consolidation, audit or filing obligations.'
   ],supportPt:'O pacote para a matriz e as demonstrações estatutárias locais podem ter bases diferentes. Confirme a base de cada entrega antes de replicar políticas, layouts ou divulgações.',sourceIds:['frc-frameworks','frc102']}
  ],
  terms:[
   {term:'Operating profit',meaning:'Result of the income and expenses classified as operating.',pt:'Resultado operacional',example:'Operating profit is 240 under the classifications assumed here.'},
   {term:'Profit bridge',meaning:'A reconciliation showing how one performance amount leads to another.',pt:'Ponte ou conciliação do resultado',example:'The bridge explains the difference between 240 and 165.'},
   {term:'Management-defined performance measure',meaning:'An income-and-expense subtotal assessed against the IFRS 18 MPM definition.',pt:'Medida de desempenho definida pela administração',example:'We must assess the public adjusted subtotal before calling it an MPM.'},
   {term:'Reporting basis',meaning:'The accounting framework applicable to the particular financial statements.',pt:'Base de elaboração das demonstrações',example:'Confirm the statutory reporting basis before copying the group format.'},
   {term:'Reclassification',meaning:'Moving an item to another presentation category without assuming a new underlying transaction.',pt:'Reclassificação',example:'The reclassification should reconcile to the same source ledger.'},
   {term:'Control owner',meaning:'The person responsible for performing or maintaining a specified control.',pt:'Responsável pelo controle',example:'Assign a control owner to review mapping exceptions.'}
  ],
  visual:{title:'Read the profit bridge',note:'Fictional amounts in the same unit. Category decisions are assumptions, not general rules. Subtotals must not be added together as if they were separate income.',headers:['Line','Amount','Role in this example'],rows:[['Revenue','1,000','Operating income'],['Operating expenses','(760)','Operating expense'],['Operating profit','240','First subtotal'],['Investing income','12','Assumed investing category'],['Profit before financing and income taxes','252','Second subtotal'],['Financing expense','(32)','Assumed financing category'],['Income tax','(55)','Tax'],['Profit for the period','165','Final result']],question:'Would moving the 12 between categories create another 12 of total profit?',answer:'No. A presentation-only move can change an intermediate subtotal, but does not itself create more income. Reconcile the final total and reassess whether the classification is appropriate.'},
  caseStudy:{title:'A CFO asks for one number — and two reporting outputs',scenario:[
   'Fictional non-financial entity, with the same classification assumptions as the worked example: revenue 1,500; operating expenses 1,120; investing income 20; financing expense 50; income tax 70. No discontinued operation.',
   'The public investor deck highlights adjusted operating profit after adding back a litigation expense of 20 already included in operating expenses. The parent requests an IFRS group package. The local statutory reporting basis has not yet been confirmed.'
  ],task:'Calculate the three profit figures and the adjusted headline. Draft a short CFO response distinguishing what is known from what still needs review, and propose one mapping control.',hints:['Calculate operating profit before applying the management adjustment.','Separate the public adjusted measure from the IFRS subtotal, and the group output from statutory-basis scoping.'],modelAnswer:'Operating profit is 380. Adding investing income of 20 gives 400 before financing and income taxes. After financing of 50 and tax of 70, profit is 280. The adjusted operating headline is 400 (380 + 20); its numerical equality with the other subtotal does not make the definitions identical. Assess whether the public measure meets the MPM definition and review its required disclosures; do not remove the litigation cost from IFRS operating profit solely because management calls it exceptional. Confirm the local statutory basis separately from the group package. Document account-to-category mappings and have an independent reviewer reconcile both outputs to the ledger.',reviewChecks:['380 operating; 400 before financing/tax; 280 final profit.','Adjusted operating profit of 400 remains a separately defined measure.','MPM and statutory-basis conclusions are conditional on the required facts.','A concrete mapping, reconciliation and review control is proposed.'],transfer:'Now explain the same issue to a systems analyst without assuming they know IFRS terminology.'},
  checkpoint:[
   {id:'fin-check-1',prompt:'Under the worked-example assumptions, which is profit before financing and income taxes?',options:['165','240','252','1,012'],correctIndex:2,explanation:'240 operating profit + 12 investing income = 252. Financing and income tax follow this subtotal in the example.',reviewSection:'fin-bridge'},
   {id:'fin-check-2',prompt:'Which fact pattern most directly calls for an MPM-definition assessment?',options:['An internal headcount ratio.','A public adjusted subtotal of income and expenses conveying management’s entity-wide performance view.','Every subtotal already specified by IFRS.','Any number described as important.'],correctIndex:1,explanation:'The public adjusted subtotal has relevant MPM characteristics. Assess the full definition and exclusions rather than relying on its name.',reviewSection:'fin-mpm'},
   {id:'fin-check-3',prompt:'The subsidiary is in Ireland. What follows from that fact alone?',options:['Its statutory basis must be IFRS.','Its basis must be the parent’s basis.','It has no statutory reporting obligations.','You still need to establish the applicable statutory reporting basis.'],correctIndex:3,explanation:'Location alone does not choose the framework. Scope the entity and reporting output before changing policies or formats.',reviewSection:'fin-basis'},
   {id:'fin-check-4',prompt:'Which control best detects an unexplained mapping difference?',options:['Reconcile the source ledger to the new presentation and review exceptions.','Rename the headings only.','Accept the new total if it is higher.','Delete the unexplained lines.'],correctIndex:0,explanation:'A reconciliation connects presentation to its source and makes exceptions reviewable. This is a control design example, not a full implementation plan.',reviewSection:'fin-presentation'},
   {id:'fin-check-5',prompt:'In the case, adjusted operating profit and profit before financing/tax are both 400. What is the best conclusion?',options:['They are therefore the same measure.','The litigation expense has ceased to exist.','Equal numbers do not establish equal definitions.','Financing expense must be zero.'],correctIndex:2,explanation:'One figure adds a management adjustment; the other adds investing income. Their equality in this fictional case is coincidental.',reviewSection:'fin-mpm'}
  ],
  sources:[source('ifrs-overview','IFRS Foundation · IFRS 18 overview','https://www.ifrs.org/issued-standards/list-of-standards/ifrs-18-presentation-and-disclosure-in-financial-statements/','Effective date, presentation focus and specified subtotals.'),source('ifrs-terms','IFRS Foundation · IFRS 18 key terms','https://www.ifrs.org/supporting-implementation/supporting-materials-by-ifrs-standards/ifrs-18/key-terms/','Subtotal definitions, business-activity assessment and MPM definition.'),source('frc-frameworks','FRC · UK and Irish accounting standards','https://www.frc.org.uk/library/standards-codes-policy/accounting-and-reporting/uk-accounting-standards/','Framework distinctions; not an entity-specific eligibility opinion.'),source('frc102','FRC · FRS 102 and subsequent amendments','https://www.frc.org.uk/library/standards-codes-policy/accounting-and-reporting/uk-accounting-standards/frs-102/','Scope and current amendment inventory, including adapted formats.')]
 },
 payroll:{
  track:'payroll',lessonId:'6ffda415-3b18-46ab-afaa-414f81a7eb31',title:'Gross-to-Net: RPN, PAYE, USC & PRSI',
  goal:'Check payroll inputs, reconcile an employee’s net pay and explain a change without inventing a tax rate or a reason.',
  scope:'Written operational foundation. Deductions below are supplied fictional amounts, not rates or tax calculations. Live-date PAYE/USC/PRSI calculations, emergency rates, benefits and auto-enrolment need separate case-specific work.',
  sections:[
   {id:'pay-inputs',title:'1. Start with validated payroll inputs',paragraphs:[
    'Revenue requires the latest Revenue Payroll Notification before payroll. The RPN supplies Income Tax/USC information and LPT where applicable. If it cannot be retrieved, emergency-basis rules apply; missing information is not permission to invent a tax credit.',
    'For an original control walkthrough, first confirm the employee and employment record, pay date, approved pay inputs and relevant deductions. Retrieve the RPN and establish the basis to use. Keep the source and reviewer attached to any changed input. An RPN does not replace approved hours, salary changes, the employee’s PRSI assessment or the employer’s responsibility for a correct run.',
    'When investigating a failure, distinguish “no notification can be retrieved” from “the integration did not complete”. Identify the issue, follow the applicable official treatment and document the resolution. Do not quietly reuse assumptions merely to make net pay match last month.'
   ],supportPt:'O cálculo começa pelos dados corretos: empregado, vínculo, data de pagamento, remuneração aprovada e RPN atualizado. Uma falha de consulta não autoriza escolher créditos ou repetir valores sem análise.',sourceIds:['revenue-rpn']},
   {id:'pay-net',title:'2. Reconcile employee cash separately from employer cost',paragraphs:[
    'In the fictional payslip, gross cash pay is 3,000. Supplied employee deductions are PAYE 350, USC 60, employee PRSI 120 and pension 90. The employee receives 2,380: subtract each deduction once. The separate assumed employer PRSI of 330 brings the employer’s illustrated cost to 3,330, before other employer costs; it is not another deduction from employee cash.',
    'This is a reconciliation of supplied numbers, not a payroll engine. The example assumes no non-cash benefits or other pay adjustments. In a real payroll, cash pay, taxable pay and each contribution base can differ. A payslip can contain taxable non-cash items that do not represent additional cash deposited in the employee’s bank.',
    'Use two checks: gross cash less employee cash deductions should reconcile to employee net cash; employer cost should have its own bridge. Then connect the approved payroll output, payment file and accounting entry. Those reconciliations are original control suggestions; they do not establish that the tax computation itself was correct.'
   ],supportPt:'Líquido do empregado e custo do empregador são contas diferentes. Neste exercício, 2.380 vai ao empregado; os 330 adicionais são custo patronal, não desconto extra no líquido.',sourceIds:[]},
   {id:'pay-bases',title:'3. Do not apply one deduction base to everything',paragraphs:[
    'Revenue guidance distinguishes pension treatment for Income Tax from USC and PRSI. Eligible employee pension contributions may qualify for Income Tax relief subject to conditions and limits, but should not simply be deducted from gross pay when calculating USC or PRSI.',
    'Original review scenario: someone suggests calculating all charges on gross cash pay less pension. Stop and ask which charge is being calculated, which pension arrangement applies and whether the inputs and relief conditions have been validated. Do not treat the supplied PAYE in this lesson as a rate that can be transferred to another employee.',
    'In the worked example the pension deduction of 90 reduces the employee’s cash, while the other deductions have already been supplied as validated inputs for arithmetic practice. We do not recalculate their tax bases here. This separation prevents a useful cash reconciliation from becoming an unsupported live tax calculation.'
   ],supportPt:'A contribuição previdenciária do empregado pode ter tratamento diferente para Income Tax, USC e PRSI. O exemplo fornece os descontos prontos: ele não calcula alíquotas nem bases tributáveis reais.',sourceIds:['revenue-pension']},
   {id:'pay-explain',title:'4. Investigate, report and explain in the right order',paragraphs:[
    'Employers report pay and deductions to Revenue on or before the pay date. The date is linked to payment to the employee; monthly reporting is not a substitute for the payroll submission requirement. Apply Revenue’s specific guidance to payment methods and non-bank working days.',
    'Original investigation sequence: compare the current and prior payslips line by line, isolate the changed item, inspect the relevant RPN/basis and approved inputs, reproduce the difference, then arrange a reviewed correction if one is needed. Keep “confirmed cause”, “working hypothesis” and “next check” separate.',
    'A useful employee response begins with the verified difference: “Your gross pay is unchanged; the PAYE deduction is 70 higher. I am checking the tax basis and payroll inputs before confirming why.” This is more accurate than promising a refund or blaming Revenue. Give a next update point you can actually meet, use approved secure channels and avoid disclosing another employee’s information.'
   ],supportPt:'Primeiro identifique o desconto que mudou; depois valide a causa. Explique o que já está confirmado e o próximo passo, sem prometer um reembolso ainda não apurado.',sourceIds:['revenue-paydate']}
  ],
  terms:[
   {term:'Gross cash pay',meaning:'Cash earnings before the employee deductions in this example.',pt:'Remuneração bruta em dinheiro',example:'Gross cash pay remains 3,000 in both illustrative periods.'},
   {term:'Net pay',meaning:'Cash payable after the employee deductions and applicable cash adjustments.',pt:'Remuneração líquida',example:'The listed employee deductions leave net pay of 2,380.'},
   {term:'RPN',meaning:'Revenue Payroll Notification used for the relevant tax instructions.',pt:'Notificação fiscal para a folha',example:'Check that payroll retrieved the latest RPN.'},
   {term:'Tax basis',meaning:'The applicable method/instructions for calculating the relevant tax deduction.',pt:'Base ou regime de cálculo fiscal',example:'We need to verify the tax basis before explaining the difference.'},
   {term:'Employer cost',meaning:'The employer’s own total cost, distinct from employee cash deductions.',pt:'Custo do empregador',example:'Employer PRSI is shown in a separate cost bridge.'},
   {term:'Reconcile',meaning:'Compare related records and explain their differences.',pt:'Conciliar',example:'Reconcile the payslip, payment file and payroll journal.'}
  ],
  visual:{title:'Separate the two payroll bridges',note:'Original fictional supplied amounts; no rate is implied. Assumes no non-cash benefits or other adjustments.',headers:['Item','Amount','Whose bridge?'],rows:[['Gross cash pay','3,000','Employee cash'],['PAYE','(350)','Employee deduction'],['USC','(60)','Employee deduction'],['Employee PRSI','(120)','Employee deduction'],['Employee pension','(90)','Employee cash deduction'],['Net cash pay','2,380','Employee receives this amount'],['Employer PRSI','330','Separate employer cost'],['Illustrated employer cost','3,330','Gross cash plus employer PRSI only']],question:'Someone proposes net pay of 2,050 by subtracting employer PRSI too. What is wrong?',answer:'They deducted the employer’s own 330 liability from the employee’s cash a second time. Under these assumptions, employee net pay remains 2,380; the separate employer cost is 3,330.'},
  caseStudy:{title:'Same gross pay, a different net amount',scenario:[
   'Two fictional monthly payslips each show gross cash pay of 3,200. Last period: PAYE 400, USC 64, employee PRSI 128 and pension 96. This period: PAYE 470; the other supplied deductions are unchanged.',
   'Assumed employer PRSI is 352 in each period. The reason for the PAYE change has not been established. The employee asks whether payroll made an error and whether a refund is guaranteed.'
  ],task:'Reconcile net pay for both periods and employer cost for this period. Draft a short employee reply and list the evidence needed before deciding on a correction.',hints:['Only the supplied PAYE changes; isolate that 70 difference before discussing causes.','A reconciled difference does not establish whether the RPN, setup or payroll calculation caused it.'],modelAnswer:'Prior net pay is 2,512 (3,200 − 400 − 64 − 128 − 96). Current net pay is 2,442 after PAYE rises by 70. Illustrated employer cost remains 3,552 (3,200 + 352), before other costs. “Your gross pay is unchanged, but this month’s PAYE deduction is 70 higher. I will compare the RPN/tax basis and approved payroll inputs, then confirm the cause and whether a correction is needed. I cannot promise a refund before that review.” Obtain the relevant payslips, RPN/basis information, input approvals and calculation audit trail; do not assume the employer PRSI belongs in net pay.',reviewChecks:['Prior net 2,512; current net 2,442; difference 70.','Employer cost 3,552 is kept separate.','The changed line is confirmed but its cause remains unproven.','Evidence is requested without promising a refund or disclosing private records.'],transfer:'Give the same explanation in simpler English to an employee who does not know the term PAYE.'},
  checkpoint:[
   {id:'pay-check-1',prompt:'In the worked example, what cash does the employee receive?',options:['2,050','2,380','2,710','3,330'],correctIndex:1,explanation:'3,000 − 350 − 60 − 120 − 90 = 2,380. The separate employer PRSI is not subtracted from employee pay.',reviewSection:'pay-net'},
   {id:'pay-check-2',prompt:'Before running payroll, which RPN should be used?',options:['Any RPN from the same tax year.','The one that gives the lowest deduction.','The latest RPN; use the applicable emergency basis if none can be retrieved.','A manually invented RPN matching last month.'],correctIndex:2,explanation:'Use the latest RPN and follow the official treatment when unavailable. Never invent tax credits to force a desired net figure.',reviewSection:'pay-inputs'},
   {id:'pay-check-3',prompt:'When must employee pay and deductions generally be reported to Revenue?',options:['On or before the pay date.','Only at the end of the quarter.','Only when an employee complains.','The next time the RPN changes.'],correctIndex:0,explanation:'The obligation follows the pay date. Check Revenue’s detailed pay-date guidance for the payment method and calendar.',reviewSection:'pay-explain'},
   {id:'pay-check-4',prompt:'An employee pension deduction reduces cash pay. What is unsafe to assume?',options:['That it is a cash deduction.','That pension relief has conditions.','That the relevant arrangement needs review.','That it reduces Income Tax, USC and PRSI bases identically.'],correctIndex:3,explanation:'Revenue distinguishes eligible Income Tax relief from USC/PRSI treatment. Cash deduction and tax-base treatment are different questions.',reviewSection:'pay-bases'},
   {id:'pay-check-5',prompt:'The case confirms PAYE rose by 70. What is the appropriate first explanation?',options:['Revenue definitely made an error.','The changed deduction is known; its cause and any correction still require checking.','A refund of 70 is guaranteed.','Employer PRSI caused the lower net amount.'],correctIndex:1,explanation:'Reconciliation identifies the difference, not the cause. Communicate the known fact and the verification plan.',reviewSection:'pay-explain'}
  ],
  sources:[source('revenue-rpn','Revenue · Revenue Payroll Notification','https://www.revenue.ie/en/employing-people/becoming-an-employer-and-ongoing-obligations/employer-obligations-from-01-01-2019/revenue-payroll-notification.aspx','Latest RPN, included tax information and unavailable-RPN treatment.'),source('revenue-paydate','Revenue · Pay date','https://www.revenue.ie/en/employing-people/becoming-an-employer-and-ongoing-obligations/information-on-payroll-submission/pay-date.aspx','Reporting timing and payment-method details.'),source('revenue-pension','Revenue · Employee pension contributions','https://www.revenue.ie/en/employing-people/what-constitutes-pay/employees-pension-payments/index.aspx','Different Income Tax versus USC/PRSI treatment; not a live calculation.')]
 },
 english:{
  track:'english',lessonId:'f455a740-f50f-4eb7-95a7-9e4129ca4a68',title:'Tell a story naturally: past forms, rhythm & follow-up questions',
  goal:'Tell a clear everyday story, distinguish its background from events and keep a conversation moving with one relevant follow-up.',
  scope:'Written storytelling and grammar practice. No pronunciation, listening or real-time fluency score is inferred from text; this does not certify a CEFR level. All stories and exercises are original.',
  sections:[
   {id:'eng-scene',title:'1. Give the listener a reason to follow',paragraphs:[
    'Choose a small event rather than a life history: a delayed journey, a surprising conversation or a first day somewhere new. A useful original structure is setting, change, response and result. The listener needs enough context to understand why the event matters, not every detail you remember.',
    'Try this original opening: “On Saturday I was walking home when I noticed a tiny bookshop.” It identifies a time, an ongoing situation and a new event. The past continuous can present an action in progress, while the past simple can move the account forward with an event. The choice depends on the intended meaning, not a mechanical rule attached to the word “when”.',
    'Before polishing vocabulary, check whether another person could follow who did what. A short, clear story is more useful for this exercise than a long answer filled with unfamiliar expressions. You may invent personal details; the task does not require disclosing private experiences.'
   ],supportPt:'Escolha um acontecimento pequeno. Dê contexto, conte o que mudou e explique o resultado. O objetivo é uma história compreensível, não uma lista de tempos verbais.',sourceIds:['bc-continuous']},
   {id:'eng-sequence',title:'2. Use time relationships deliberately',paragraphs:[
    'Past simple forms can present a sequence of events. Past continuous uses was/were plus an -ing form to place an activity in progress around a past moment. Past perfect uses had plus the past participle to look back from a past reference point to something earlier.',
    'Original continuation: “I went inside and found a novel I had been looking for.” Here the search precedes the discovery. You do not need a perfect tense in every sentence of a story. Ask which relationship helps the listener: a background situation, the next event, or an earlier fact that explains the situation.',
    'For this lesson’s simpler case, compare “I was waiting when my friend called” with “I waited, then my friend called”. Both can make sense, but they present time differently. An answer should be assessed against the meaning requested by the exercise, not rejected merely because it differs from a memorised sentence.'
   ],supportPt:'O passado simples pode conduzir a sequência, o contínuo mostra uma ação em andamento e o past perfect aponta para algo anterior a um ponto já passado. Não use uma forma só porque ela parece mais avançada.',sourceIds:['bc-continuous','bc-perfect']},
   {id:'eng-interaction',title:'3. Make room for a real response',paragraphs:[
    'A follow-up should connect to what the other person actually said. If someone says a delay ended unexpectedly well, “What happened?” invites the interesting part. Asking three unrelated questions at once makes a casual exchange feel like a test.',
    'Original practice: after telling the bookshop story, ask “Have you found any good places by chance?” Then imagine two possible replies and respond to each differently. If the listener has a similar story, invite it; if they did not understand the setting, explain that before introducing another tense or vocabulary item.',
    'A helpful correction can be short: “You went there and met a friend — what was it like?” It acknowledges the intended message while offering the past forms. This is one possible coaching response, not a mandatory script. Different natural wording is acceptable when it preserves meaning and supports the exchange.'
   ],supportPt:'A pergunta seguinte deve nascer da resposta anterior. Corrija o que importa sem transformar toda a conversa em interrupções. Uma resposta pode ser boa sem repetir exatamente o modelo.',sourceIds:[]},
   {id:'eng-transfer',title:'4. Retell for another listener without changing the facts',paragraphs:[
    'For a friend, you might include a feeling or an amusing detail. For a colleague, lead with what happened and why it matters now. This is an original register exercise: keep the facts but vary the emphasis, not the truth.',
    'Friend version: “I nearly missed my stop because I was enjoying the conversation.” Colleague version: “I arrived ten minutes late after taking the wrong bus. I have adjusted the route for tomorrow.” These are examples of different situations and audiences, not universal rules for formal and informal English.',
    'Practise an optional pause between idea groups, then try a shorter retelling. On this screen nobody hears the delivery, so written work cannot establish timing, listening skill or pronunciation. UK and US alternatives should be considered on their merits rather than treating one regional spelling as proof of an error. The eventual voice lesson will need separate evidence for spoken performance.'
   ],supportPt:'Adapte o foco ao interlocutor. Escrever uma boa resposta não prova fluência oral ou pronúncia; essas habilidades precisam de evidência própria na conversa.',sourceIds:[]}
  ],
  terms:[
   {term:'Set the scene',meaning:'Give the time, place or situation needed to understand a story.',pt:'Contextualizar',example:'I was waiting at the bus stop after work.'},
   {term:'By chance',meaning:'Without planning or expecting it.',pt:'Por acaso',example:'I found the bookshop by chance.'},
   {term:'It turned out that…',meaning:'Introduce what became clear later.',pt:'Acabou que…',example:'It turned out that we had taken the same course.'},
   {term:'Already',meaning:'Before the time being discussed.',pt:'Já',example:'The bus had already left when I arrived.'},
   {term:'Follow-up',meaning:'A response or question connected to what was just said.',pt:'Pergunta ou resposta de continuidade',example:'What happened after that?'},
   {term:'Retell',meaning:'Tell an account again, perhaps with different wording or emphasis.',pt:'Recontar',example:'Retell the event for a colleague in two sentences.'}
  ],
  visual:{title:'Map the story’s time relationships',note:'An original written timeline. These labels describe the intended meaning of the example, not the only grammatical way to tell a story.',headers:['Time relationship','Original sentence','Function'],rows:[['Earlier fact','I had left my phone at home.','Explains a later problem'],['Background','I was waiting for the bus.','Action in progress'],['Event','A neighbour offered me a lift.','Moves the story forward'],['Outcome','I arrived on time.','Closes the immediate event']],question:'Which line explains why the person could not use a travel app, without inventing an extra fact?',answer:'The earlier fact: the phone had been left at home. The example makes that fact available; it does not tell us why the phone was forgotten or whether the app would have solved the journey.'},
  caseStudy:{title:'An unexpected encounter on the way to class',scenario:[
   'Original fictional facts: you left your travel card at home; you were waiting near a bus stop; a neighbour recognised you and offered a lift; you arrived at class on time; you felt relieved.',
   'A friend asks how your morning went. They then ask why you could not simply take the bus. For this task, do not add a stolen wallet, a cancelled service or any other unsupported event.'
  ],task:'Write or say a short account using the supplied facts. Clarify the earlier event and finish with one relevant follow-up question. Then give a more concise retelling for a colleague.',hints:['Use the forgotten travel card as the earlier fact, the waiting as background and the offered lift as an event.','Answer the friend’s clarification before asking your own follow-up. Several natural wordings are acceptable.'],modelAnswer:'“I had left my travel card at home, so I was waiting near the bus stop, wondering what to do. A neighbour recognised me and offered me a lift. I arrived at class on time and felt relieved. Has someone ever helped you out like that?” A concise retelling could be: “I forgot my travel card, but a neighbour gave me a lift, so I still arrived on time.” These are illustrative answers, not exact-match scripts; the supplied facts do not establish every available travel-payment option.',reviewChecks:['The listener can follow the earlier fact, background, event and result.','The explanation preserves the supplied facts.','The follow-up connects naturally to the experience.','No written answer is treated as evidence of pronunciation or real-time fluency.'],transfer:'Use a true or invented everyday experience with a different outcome. Keep the structure, not the model sentences.'},
  checkpoint:[
   {id:'eng-check-1',prompt:'Choose the intended ongoing-background/event contrast: “I ___ for the bus when my friend ___.”',options:['wait / calls','was waiting / called','had wait / calling','waiting / was called'],correctIndex:1,explanation:'Was waiting establishes the intended background; called introduces the event. Another meaning would require a different exercise context.',reviewSection:'eng-sequence'},
   {id:'eng-check-2',prompt:'“When I reached the stop, the bus had already left.” Which happened first?',options:['Reaching the stop.','Both necessarily at the same time.','The bus leaving.','The sentence establishes no time relationship.'],correctIndex:2,explanation:'Had already left looks back from arrival at the stop to the earlier departure.',reviewSection:'eng-sequence'},
   {id:'eng-check-3',prompt:'Someone says, “The delay turned into a lovely surprise.” Which offered reply best follows that point?',options:['What happened?','List all your professional qualifications.','You must have pronounced that incorrectly.','Let us change the subject immediately.'],correctIndex:0,explanation:'The first option invites the surprising part. It is best among these options, not the only good follow-up in a real conversation.',reviewSection:'eng-interaction'},
   {id:'eng-check-4',prompt:'What can this written checkpoint establish on its own?',options:['A certified CEFR level.','Accurate pronunciation.','Perfect real-time listening.','How your selected answers compare with this written answer key.'],correctIndex:3,explanation:'Written choices provide limited evidence. Listening, pronunciation and conversational timing are not measured here.',reviewSection:'eng-transfer'},
   {id:'eng-check-5',prompt:'When retelling the supplied case for a colleague, what should remain stable?',options:['Every exact word of the model answer.','The underlying facts, even if the emphasis and wording change.','The use of past perfect in every sentence.','The claim that the bus service was cancelled.'],correctIndex:1,explanation:'A retelling changes presentation for its audience, not the evidence. No cancellation was supplied.',reviewSection:'eng-transfer'}
  ],
  sources:[source('bc-continuous','British Council · Past continuous','https://learnenglish.britishcouncil.org/grammar/english-grammar-reference/past-continuous','Background and actions in progress. Teaching examples here are original, not copied exercises.'),source('bc-perfect','British Council · Past perfect','https://learnenglish.britishcouncil.org/free-resources/grammar/b1-b2/past-perfect','Earlier events viewed from a later past reference point.')]
 }
};
export function lessonModuleFor(track:StudyTrack,lessonId:string):LessonModule|null {
 const module=LESSON_MODULES[track];
 return module&&module.lessonId===lessonId?module:null;
}
export function checkLocalChoice(question:CheckpointQuestion,selected:unknown):'correct'|'incorrect'|'unanswered'{
 if(typeof selected!=='number'||!Number.isInteger(selected)||selected<0||selected>=question.options.length)return 'unanswered';
 return selected===question.correctIndex?'correct':'incorrect';
}
