import type {LessonModule} from './lessonModules.ts';
import {ACCA_B5_MODEL_ID,ACCA_B5_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-21';
export const ACCA_B5_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'20–26',segments:['Contractual rights, obligations and the liability-versus-equity question.','Financial-asset classification through business model and cash flows.','A narrated effective-interest schedule.','Retrieval pauses on transaction costs and compound instruments.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_B5_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask what contractual right or obligation exists before naming a measurement category.',supportedPractice:'Classify first, then build one effective-interest row with opening balance, effective interest, cash flow and closing balance.',misconception:'Coupon cash is not automatically the finance income or cost, and a contractual cash obligation is not equity merely because management calls it capital.',transfer:'Change the business model, transaction costs or settlement terms and ask which conclusion changes.',close:'Recap classification, initial measurement, effective interest and liability/equity substance without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_B5_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_B5_MODEL_ID,title:'ACCA FR B5 · Financial instruments',
 goal:'Classify basic financial instruments, apply initial and subsequent measurement, calculate amortised cost and distinguish liabilities from equity.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level B5 mapping must be checked against the exact selected exam sitting before publication. It is original teaching material, not ACCA approval, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-b5-foundation',title:'1. Start from the contractual right or obligation',paragraphs:[
   'A financial instrument is a contract that gives one entity a financial asset and another entity a financial liability or equity instrument. Cash, a contractual right to receive cash, and a contractual right to exchange financial instruments on potentially favourable terms are common financial assets. A contractual obligation to deliver cash or another financial asset is normally a financial liability.',
   'Recognition begins when the entity becomes party to the contractual provisions. Do not recognise an instrument merely because negotiations are advanced, and do not delay recognition until cash moves when an enforceable contract already exists. Identify both sides of the contract, the issuer and holder perspectives, and the currency, timing and variability of settlement.',
   'For the issuer, classification as liability or equity follows substance. An equity instrument evidences a residual interest after deducting liabilities. If the issuer cannot avoid delivering cash, the instrument is generally a liability even if it is legally labelled a share. When settlement uses the issuer’s own shares, the fixed-for-fixed principle and any relevant exceptions must be considered.'
  ],supportPt:'Comece pelo contrato: direito de receber caixa é ativo financeiro; obrigação inevitável de entregar caixa normalmente é passivo. A classificação dívida/patrimônio segue a substância, não o nome jurídico.',sourceIds:['ifrs-9','ias-32','acca-fr-syllabus']},
  {id:'acca-b5-classification',title:'2. Classify and measure financial assets consistently',paragraphs:[
   'For a basic debt financial asset, classification considers the business model and whether contractual cash flows are solely payments of principal and interest on the principal outstanding. A hold-to-collect asset that passes that cash-flow test is measured at amortised cost. A qualifying collect-and-sell model leads to fair value through other comprehensive income, while assets outside the qualifying conditions are measured at fair value through profit or loss.',
   'At initial recognition, measure a financial asset or liability at fair value. Add directly attributable transaction costs for an item not measured at fair value through profit or loss; expense transaction costs immediately for an FVTPL item. This distinction affects the opening carrying amount and therefore later effective-interest income or expense.',
   'Equity investments are measured at fair value. Unless an applicable irrevocable presentation election is made for a non-trading equity investment, fair-value changes go through profit or loss. Keep equity investments separate from debt instruments: shares do not generate contractual principal-and-interest cash flows merely because dividends are expected.'
  ],supportPt:'Para dívida básica, combine modelo de negócios e teste dos fluxos contratuais. Custos de transação entram no valor inicial quando o instrumento não está em FVTPL; em FVTPL, vão ao resultado.',sourceIds:['ifrs-9']},
  {id:'acca-b5-amortised',title:'3. Build amortised cost using the effective interest rate',paragraphs:[
   'The effective interest rate discounts estimated contractual cash flows through the expected life of the instrument to the initial carrying amount. Each period, apply that rate to the opening amortised cost to calculate finance income for an asset or finance cost for a liability. Then adjust for the actual coupon or cash paid or received to derive the closing balance.',
   'A discount, premium, issue cost or qualifying transaction cost is therefore spread through the effective-interest calculation rather than expensed or recognised as income mechanically on day one. For a liability, opening carrying amount plus effective finance cost minus cash paid equals closing amortised cost. For an asset, opening carrying amount plus effective finance income minus cash received follows the same schedule logic.',
   'Use the rate supplied in an FR question unless the task explicitly asks you to derive it. Keep percentages and cash flows on the same time basis, distinguish a coupon rate applied to nominal value from an effective rate applied to carrying amount, and reconcile the final balance to redemption value subject to rounding.'
  ],supportPt:'No custo amortizado, aplique a taxa efetiva ao saldo de abertura e depois retire o caixa real. Cupom incide no valor nominal; juros efetivos incidem no valor contábil.',sourceIds:['ifrs-9']},
  {id:'acca-b5-presentation',title:'4. Separate compound instruments and present substance',paragraphs:[
   'A compound instrument contains both a liability and an equity component, such as a convertible bond where the issuer must pay interest and principal but the holder also has a qualifying conversion option. On initial recognition, measure the liability component first using the fair value of comparable debt without conversion. The residual between total proceeds and that liability is equity.',
   'The liability then grows using its effective interest rate, while coupon cash reduces the liability. The equity component is not remeasured merely because conversion becomes more or less likely. At each stage, distinguish the initial split from subsequent finance cost and avoid allocating the issue proceeds by an unsupported percentage.',
   'Offset a financial asset and financial liability only when there is a legally enforceable right to set off and an intention to settle net or simultaneously. Commercial convenience, the same counterparty or an expected future offset is not enough. A concise exam response states the contractual substance, classification, measurement working and presentation effect.'
  ],supportPt:'Instrumento composto é separado: primeiro mensure o passivo como dívida equivalente; o residual é patrimônio. Depois, apenas o passivo segue custo amortizado. Compensação exige direito legal e intenção adequada.',sourceIds:['ias-32','ifrs-9']}
 ],
 terms:[
  {term:'Financial asset',meaning:'Cash or a contractual right to receive cash or another financial asset.',pt:'Ativo financeiro',example:'A trade receivable is a contractual right to cash.'},
  {term:'Financial liability',meaning:'Contractual obligation to deliver cash or another financial asset.',pt:'Passivo financeiro',example:'A redeemable loan note normally creates a cash obligation.'},
  {term:'Equity instrument',meaning:'Contract evidencing a residual interest after liabilities.',pt:'Instrumento patrimonial',example:'Ordinary shares with no unavoidable cash redemption may be equity.'},
  {term:'Amortised cost',meaning:'Initial amount adjusted for principal cash flows and cumulative effective interest.',pt:'Custo amortizado',example:'The carrying amount accretes from issue proceeds toward redemption.'},
  {term:'Effective interest rate',meaning:'Rate that discounts estimated contractual cash flows to initial carrying amount.',pt:'Taxa efetiva de juros',example:'Eight per cent applies to opening carrying amount, not nominal value.'},
  {term:'Compound instrument',meaning:'Instrument containing both liability and equity components.',pt:'Instrumento financeiro composto',example:'A qualifying convertible bond is split on initial recognition.'}
 ],
 visual:{title:'One amortised-cost row',note:'Original schedule; fictional CU amounts for a liability issued at CU940, redeemable at CU1,000, with 8% EIR and CU50 annual coupon.',headers:['Element','Calculation','CU'],rows:[['Opening liability','Initial net proceeds','940.0'],['Effective finance cost','940 × 8%','75.2'],['Cash coupon','1,000 × 5%','(50.0)'],['Closing liability','940 + 75.2 − 50','965.2']],question:'Why is finance cost CU75.2 rather than the CU50 coupon?',answer:'The effective rate is applied to opening amortised cost. The difference accretes the liability toward its CU1,000 redemption amount.'},
 caseStudy:{title:'Convertible bond: initial split and year-one liability',scenario:['An entity issues convertible bonds for CU1,000. Annual coupon cash is CU50, payable in arrears.','The present value of the contractual cash flows discounted at the market rate for equivalent debt without conversion is CU920.','The market effective rate for the liability component is 8%. Ignore tax and issue costs.'],task:'Calculate the initial liability and equity components, the year-one finance cost and the closing liability. Explain why equity is not remeasured.',hints:['Measure the liability first and put the residual in equity.','Apply 8% to the opening liability, then deduct coupon cash.'],modelAnswer:'Initially recognise the liability at CU920, the fair value of equivalent debt without conversion. Recognise equity of CU80 as the residual from the CU1,000 proceeds. Year-one finance cost is CU73.6 (920 × 8%). After the CU50 coupon payment, the closing liability is CU943.6 (920 + 73.6 − 50). The equity conversion component remains CU80 because it is an equity component and is not subsequently remeasured for changes in conversion probability.',reviewChecks:['Liability is measured before the residual equity component.','Initial liability and equity total CU1,000.','Effective interest uses CU920, not nominal CU1,000.','Closing liability reconciles to CU943.6 and equity is not remeasured.'],transfer:'Assume CU20 directly attributable issue costs are allocated CU18 to liability and CU2 to equity. Explain how the liability opening amount and future effective-interest schedule would change.'},
 checkpoint:[
  {id:'acca-b5-q1',prompt:'What normally identifies a financial liability?',options:['A management intention to pay','An unavoidable contractual obligation to deliver cash','Any decline in share price','A future sales forecast'],correctIndex:1,explanation:'A contractual cash obligation is central to liability classification.',reviewSection:'acca-b5-foundation'},
  {id:'acca-b5-q2',prompt:'When can a debt asset be measured at amortised cost?',options:['Whenever management prefers stable profit','When held to collect and contractual cash flows are solely principal and interest','Only when listed','Whenever it has a coupon'],correctIndex:1,explanation:'Both the hold-to-collect business model and contractual cash-flow test are required.',reviewSection:'acca-b5-classification'},
  {id:'acca-b5-q3',prompt:'How are transaction costs treated for an FVTPL asset?',options:['Added to carrying amount','Expensed immediately','Recorded in equity','Ignored permanently'],correctIndex:1,explanation:'Direct transaction costs for an FVTPL item are recognised in profit or loss.',reviewSection:'acca-b5-classification'},
  {id:'acca-b5-q4',prompt:'Which amount receives the effective interest rate?',options:['Opening amortised cost','Nominal amount in every case','Cash coupon only','Closing fair value'],correctIndex:0,explanation:'Effective finance income or cost is calculated from opening amortised cost.',reviewSection:'acca-b5-amortised'},
  {id:'acca-b5-q5',prompt:'How is initial equity measured in a compound convertible instrument?',options:['Fair value of the coupon','Residual after measuring the liability component','Entire issue proceeds','Present value of principal only'],correctIndex:1,explanation:'Measure the liability first; the residual proceeds form the equity component.',reviewSection:'acca-b5-presentation'}
 ],
 practiceExercises:[
  {id:'acca-b5-p1',question:'A liability opens at CU940, has an 8% effective rate and pays CU50 cash. Calculate closing amortised cost.',hints:['Calculate effective finance cost first.','Add finance cost and subtract cash.'],answer:'Finance cost is CU75.2. Closing liability is CU965.2 (940 + 75.2 − 50).',explanation:'The CU25.2 difference accretes the issue discount.'},
  {id:'acca-b5-p2',question:'Repair: “Redeemable preference shares are equity because their legal name includes shares.”',hints:['Focus on the issuer’s contractual obligation.','Apply substance over label.'],answer:'If the issuer has an unavoidable contractual obligation to redeem the shares for cash, they are generally a financial liability despite the legal label.',explanation:'Liability versus equity depends on contractual substance.'},
  {id:'acca-b5-p3',question:'A hold-to-collect debt asset has only principal and interest cash flows. Fair value is CU100 and directly attributable transaction costs are CU3. What is initial amortised cost?',hints:['It is not FVTPL.','Include qualifying transaction costs.'],answer:'Initial amortised cost is CU103. The directly attributable CU3 is included because the asset is not measured at FVTPL.',explanation:'The opening balance feeds the effective-interest schedule.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ifrs-9',label:'IFRS Foundation · IFRS 9 Financial Instruments',url:'https://www.ifrs.org/issued-standards/list-of-standards/ifrs-9-financial-instruments/',supports:'Recognition, initial measurement, business-model classification and amortised cost.',reviewedOn},
  {id:'ias-32',label:'IFRS Foundation · IAS 32 Financial Instruments: Presentation',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-32-financial-instruments-presentation/',supports:'Liability/equity distinction, compound instruments and offsetting.',reviewedOn}
 ]
};
export function localModelB5For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='B5'?ACCA_B5_MODEL_MODULE:null;}
export {ACCA_B5_MODEL_ID,ACCA_B5_MODEL_SLUG};
