import type {LessonModule} from './lessonModules.ts';
import {ACCA_E_MODEL_ID,ACCA_E_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_E_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'18–24',segments:['Plan an efficient digital response workflow.','Build transparent spreadsheet workings.','Navigate and revise without losing the requirement.','Present conclusions that link evidence to judgement.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_E_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask the learner to identify the requirement, available information and intended output before discussing a tool.',supportedPractice:'Require an input–working–check–output trail and one concise conclusion tied to the result.',misconception:'Technology can accelerate a weak method; a formula or polished chart is not evidence that the source, logic or conclusion is correct.',transfer:'Change one input, requirement or audience and ask which working, control and presentation choice must change.',close:'Recap the workflow and one control without claiming workplace competence or exam readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_E_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_E_MODEL_ID,title:'ACCA FR E · Employability and technology skills',
 goal:'Use digital tools to access, manipulate, revise and present financial-reporting information efficiently while preserving an auditable reasoning trail.',
 scope:'Local ACCA Financial Reporting capstone lesson. It maps the four section E capabilities for the selected exam sitting through an original simulated workspace; it does not reproduce or certify the live ACCA exam environment. It is not ACCA approval, persisted assessment, workplace-performance evidence or exam-readiness evidence.',
 sections:[
  {id:'acca-e-access',title:'1. Access and manipulate relevant information efficiently',paragraphs:[
   'Begin with the requirement, not with the tool. Identify the entity, period, reporting boundary, command verb and output before opening the exhibits. Create a short evidence index that records where each relevant figure or fact came from. Search and filtering help locate information, but relevance still depends on accounting judgement. Preserve source labels, units and signs so a copied number does not lose its meaning when it moves into a working.',
   'Separate inputs, assumptions, calculations and outputs. Enter each supplied amount once and reference it thereafter; use consistent units and explicit dates. A transparent formula is preferable to a typed answer because it responds safely when an input changes. Use reasonableness checks, subtotals and cross-casts to expose errors. Do not invent a missing figure merely to complete a schedule: state the evidence gap and show any necessary assumption clearly.',
   'Efficiency means reducing avoidable rework while retaining control. Read the requirement first, inspect all exhibits, then choose the minimum useful working. Copying every exhibit into a spreadsheet wastes time and can obscure the decisive facts. A good digital trail lets another reviewer follow source, transformation and conclusion without reverse-engineering unexplained constants or formatting.'
  ],supportPt:'Comece pelo requisito. Separe fonte, input, premissa, cálculo, controle e output; tecnologia acelera o trabalho, mas não substitui julgamento nem autoriza inventar dados.',sourceIds:['acca-fr-syllabus','acca-practice-platform']},
  {id:'acca-e-response',title:'2. Work on response options with appropriate functions',paragraphs:[
   'Choose the response format that fits the task. A spreadsheet is useful for repeated calculations, sensitivities and reconciliations; a narrative response is better for explaining recognition, uncertainty and limitations. Use basic formulae, cell references and structured workings rather than opaque shortcuts. Label the accounting treatment beside the number so the working explains why the result belongs in profit, OCI, assets, liabilities, equity or cash flow.',
   'Build a response in layers: requirement, method, working, check and conclusion. For a ratio analysis, calculate consistently before interpreting; for consolidation, keep acquisition, goodwill, NCI and intragroup adjustments in separate linked workings; for a single entity, map each adjustment to every affected statement. The tool should make dependencies visible. A correct number with no audit trail is fragile, and an elegant narrative with no calculation may not answer a computational requirement.',
   'Use response options iteratively. If a fact changes, revise the input and inspect all dependent outputs rather than overwriting the final answer. Compare alternatives only where the requirement asks for them, and distinguish a scenario from the reported answer. Keep sensitive or irrelevant data out of the response. The objective is a controlled professional workflow, not maximum use of every available feature.'
  ],supportPt:'Escolha a ferramenta pelo requisito e construa em camadas: método, working, check e conclusão. Altere inputs, não o resultado final, para preservar dependências.',sourceIds:['acca-fr-syllabus','acca-practice-platform']},
  {id:'acca-e-navigation',title:'3. Navigate, create and amend without losing control',paragraphs:[
   'Plan the workspace before writing: reserve areas for requirements, calculations, narrative and review notes. Use descriptive labels so switching between exhibits and response windows does not break context. Mark completed requirements and unresolved evidence, but do not treat a navigation marker as proof of completion. Save or review at natural checkpoints where the environment permits, and leave enough time to reopen each requirement and verify that the answer remains attached to the correct task.',
   'Amend deliberately. When correcting a formula, trace its precedents and dependants and repeat the relevant reasonableness check. When revising narrative, make sure the conclusion still agrees with the numbers. Avoid broad find-and-replace changes that can alter unrelated labels or assumptions. If an exhibit conflicts with another, document the conflict and apply the hierarchy or assumption supported by the question rather than silently selecting a convenient value.',
   'Navigation is part of professional control because fragmented screens create omission risk. A final sweep should test completeness, consistency, units, signs and presentation. Confirm that every command verb has a response, every material number has a working, and every conclusion is supported. Keyboard efficiency and window management are useful only when they reduce mechanical effort without reducing the quality of review.'
  ],supportPt:'Organize a área de trabalho, marque requisitos e revise alterações por dependência. Na checagem final, confirme completude, consistência, unidades, sinais e vínculo entre cálculo e conclusão.',sourceIds:['acca-fr-syllabus','acca-practice-platform']},
  {id:'acca-e-presentation',title:'4. Present data and information effectively',paragraphs:[
   'Presentation begins with hierarchy. Lead with the answer to the requirement, then provide the calculation or evidence and a concise explanation. Use headings that mirror the required tasks, tables for comparable values and narrative for judgement. Round consistently and retain enough precision in underlying workings. A chart is useful only when it makes a trend or comparison clearer; it should not hide scale, omit relevant periods or substitute decoration for analysis.',
   'Explain what a result means for the stated entity and stakeholder. A falling margin, for example, is an observation; a useful response connects it to revenue, cost or classification evidence, considers limitations and reaches a proportionate conclusion. Distinguish fact, calculation, assumption and judgement. Where evidence is insufficient, state the limitation rather than presenting false certainty. Material contradictory indicators should be reconciled, not ignored.',
   'Perform a reader test: can a reviewer identify the source, reproduce the working and understand the conclusion without guessing? Remove duplicate prose, unexplained abbreviations and excessive decimals. Keep tables aligned and labels specific. Effective presentation is not cosmetic polish; it is the final control that communicates the accounting logic faithfully and allows errors, assumptions and limitations to be challenged.'
  ],supportPt:'Apresente primeiro a resposta ao requisito, depois evidência e explicação. Diferencie fato, cálculo, premissa e julgamento; clareza é um controle, não apenas estética.',sourceIds:['acca-fr-syllabus','acca-practice-platform']}
 ],
 terms:[
  {term:'Evidence index',meaning:'Short map linking each relevant fact or amount to its source.',pt:'Índice de evidências',example:'Revenue CU4m — Exhibit 1, statement of profit or loss.'},
  {term:'Audit trail',meaning:'Traceable path from source through calculation to output and conclusion.',pt:'Trilha de auditoria',example:'A ratio references labelled inputs rather than typed constants.'},
  {term:'Cell reference',meaning:'Formula link to another spreadsheet cell instead of a hard-coded value.',pt:'Referência de célula',example:'Gross profit equals revenue cell minus cost-of-sales cell.'},
  {term:'Reasonableness check',meaning:'Independent test of whether a result is plausible and internally consistent.',pt:'Teste de razoabilidade',example:'Margin multiplied by turnover should reconcile to ROCE on the same basis.'},
  {term:'Dependency',meaning:'Relationship in which changing one input should update linked workings or outputs.',pt:'Dependência',example:'Changing consideration updates goodwill and the consolidated position.'},
  {term:'Reader test',meaning:'Review of whether another person can reproduce and understand the response.',pt:'Teste do leitor',example:'A reviewer can identify source, method, check and conclusion.'}
 ],
 visual:{title:'Controlled digital response trail',note:'A tool assists each step; judgement and review remain with the learner.',headers:['Stage','Efficient action','Control'],rows:[['Requirement','Identify verb, entity, period and output','Checklist against every task'],['Evidence','Index only relevant exhibits and inputs','Source, unit and sign labels'],['Working','Use linked formulae and clear assumptions','Cross-cast and reasonableness check'],['Revision','Change the input, then trace dependants','Reperform affected controls'],['Presentation','Lead with conclusion and supporting evidence','Reader test and limitation review']],question:'Why is changing a labelled input safer than typing a replacement final answer?',answer:'Linked workings update consistently and preserve the source-to-output trail, while a typed override can leave dependent figures and explanations inconsistent.'},
 caseStudy:{title:'Build and communicate a controlled performance response',scenario:['An entity reports current-year revenue CU5.0m, gross profit CU1.75m, operating profit CU0.50m and capital employed CU2.5m. Prior-year revenue was CU4.0m, gross profit CU1.60m, operating profit CU0.48m and capital employed CU2.4m.','A late exhibit says CU0.20m of current-year revenue came from a bill-and-hold arrangement that fails the stated recognition criteria; its associated cost was CU0.12m. The draft working currently contains typed final percentages with no source labels.','Prepare an auditable adjustment, calculate current and prior gross margin, operating margin and ROCE, and present a short conclusion with one limitation.'],task:'Design the response trail, amend the current-year inputs and explain the result without overriding final cells.',hints:['Reverse both the unearned revenue and its associated cost before calculating ratios.','Label source, formula and conclusion separately.'],modelAnswer:'Index the original statements and late exhibit, then adjust current revenue to CU4.80m and gross profit to CU1.67m (CU1.75m − CU0.20m + CU0.12m). Assuming no other operating effect, adjusted operating profit is CU0.42m. Current gross margin is 34.79%, operating margin is 8.75% and ROCE is 16.80%. Prior gross margin is 40.00%, operating margin is 12.00% and ROCE is 20.00%. Present the formulas through labelled cell references, cross-check gross profit, and conclude that adjusted profitability deteriorated across all three measures. One limitation is that the supplied data do not explain whether price, volume or other cost changes caused the remaining movement.',reviewChecks:['Adjusted revenue CU4.80m and gross profit CU1.67m.','Adjusted operating profit CU0.42m.','Current ratios 34.79%, 8.75% and 16.80%.','Prior ratios 40.00%, 12.00% and 20.00%, with a stated limitation.'],transfer:'Assume instead that the arrangement qualifies for revenue recognition. Restore the two inputs and explain which formulas, comparisons and conclusion update automatically.'},
 checkpoint:[
  {id:'acca-e-q1',prompt:'What should happen before selecting a spreadsheet or narrative tool?',options:['Format the final answer','Identify the requirement, information and intended output','Copy every exhibit','Choose the most advanced feature'],correctIndex:1,explanation:'The requirement determines the useful tool and response structure.',reviewSection:'acca-e-access'},
  {id:'acca-e-q2',prompt:'Which practice best preserves an audit trail?',options:['Type the final percentage','Hide assumptions','Reference labelled inputs in the formula','Round every input first'],correctIndex:2,explanation:'Labelled references connect source, transformation and result.',reviewSection:'acca-e-response'},
  {id:'acca-e-q3',prompt:'After changing a source input, what is the strongest next action?',options:['Trust the displayed result','Trace dependent outputs and repeat relevant checks','Rewrite only the conclusion','Delete prior labels'],correctIndex:1,explanation:'Dependencies and controls must be rechecked after an amendment.',reviewSection:'acca-e-navigation'},
  {id:'acca-e-q4',prompt:'What is the adjusted current operating margin in the case?',options:['8.40%','8.75%','10.00%','12.00%'],correctIndex:1,explanation:'CU0.42m divided by CU4.80m equals 8.75%.',reviewSection:'acca-e-presentation'},
  {id:'acca-e-q5',prompt:'Which conclusion is best supported?',options:['Technology proves the answer is correct','Profitability deteriorated, but the supplied data do not fully explain the causes','Revenue growth guarantees stronger performance','Formatting removes the need for limitations'],correctIndex:1,explanation:'All three adjusted ratios fall, while causal evidence remains incomplete.',reviewSection:'acca-e-presentation'}
 ],
 practiceExercises:[
  {id:'acca-e-p1',question:'A formula shows =1250/4000 with no labels. Rewrite the working so a reviewer can trace it.',hints:['Create named or labelled input cells.','State the ratio and period.'],answer:'Label CU1,250 as current-year gross profit and CU4,000 as current-year revenue, then reference those cells in a “current-year gross margin” formula. The result is 31.25%.',explanation:'The same arithmetic becomes auditable when source, unit, period and meaning are visible.'},
  {id:'acca-e-p2',question:'A corrected receivables input changes a ratio. List the minimum review steps before submitting.',hints:['Think dependencies, narrative and units.','Include an independent check.'],answer:'Trace every dependent formula, recompute or independently check the ratio, confirm units and period, update the interpretation, and verify the conclusion still answers the requirement.',explanation:'A revised number can make an unchanged narrative internally inconsistent.'},
  {id:'acca-e-p3',question:'Repair: “The chart looks professional, so no calculation table or limitation is needed.”',hints:['A chart is a presentation choice.','Consider reproducibility and uncertainty.'],answer:'Retain labelled calculations or an auditable working, use the chart only if it clarifies the comparison, and disclose material assumptions or limitations. Appearance does not validate the source or method.',explanation:'Effective presentation exposes rather than conceals the reasoning trail.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'The four section E employability and technology capabilities.',reviewedOn},
  {id:'acca-practice-platform',label:'ACCA · Practice Platform and CBE support',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/professional-exams-study-resources/cbe-platform-support.html',supports:'Official practice environment context for constructed responses and computer-based exam tools.',reviewedOn}
 ]
};
export function localModelEFor(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='E'?ACCA_E_MODEL_MODULE:null;}
export {ACCA_E_MODEL_ID,ACCA_E_MODEL_SLUG};
