import type {LessonModule,LessonSource} from './lessonModules.ts';
import {
 ENGLISH_E6_MODEL_ID,ENGLISH_E6_MODEL_SLUG,
 ENGLISH_E7_MODEL_ID,ENGLISH_E7_MODEL_SLUG,
 ENGLISH_E8_MODEL_ID,ENGLISH_E8_MODEL_SLUG,
 ENGLISH_E9_MODEL_ID,ENGLISH_E9_MODEL_SLUG,
 ENGLISH_E10_MODEL_ID,ENGLISH_E10_MODEL_SLUG,
 localEnglishCodeFor,
} from './localEnglishLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';

const reviewedOn='2026-09-23';
const source=(id:string,label:string,url:string,supports:string):LessonSource=>({id,label,url,supports,reviewedOn});
const speaking=source('bc-speaking','British Council · Speaking','https://learnenglish.britishcouncil.org/skills/speaking','Interaction strategies and speaking practice; all dialogues and tasks here are original.');
const shopping=source('bc-shopping','British Council · A1 listening','https://learnenglish.britishcouncil.org/free-resources/listening/a1','Everyday shopping and service encounters; the lesson uses new B1–B2 scenarios.');
const restaurant=source('bc-restaurant','British Council · Starting Out','https://learnenglish.britishcouncil.org/free-resources/general/video-series/starting-out','Restaurant and social situations; no exercise or dialogue is copied.');
const agreeing=source('bc-agreeing','British Council · Agreeing and disagreeing','https://learnenglish.britishcouncil.org/free-resources/speaking/b1/agreeing-disagreeing','Useful interaction choices for expressing and responding to opinions.');
const stative=source('bc-stative','British Council · Stative verbs','https://learnenglish.britishcouncil.org/grammar/b1-b2-grammar/stative-verbs','Verbs commonly used for preferences, opinions, senses and possession.');

export const ENGLISH_E6_MODEL_MODULE:LessonModule={
 track:'english',lessonId:ENGLISH_E6_MODEL_ID,title:'Shopping and returns: compare options and resolve a problem',
 goal:'Compare products, describe a purchase problem with evidence and ask for an available remedy without inventing a store policy or becoming unnecessarily confrontational.',
 scope:'Original written everyday-English practice with fictional shops and purchases. It does not make a purchase, submit a complaint, determine consumer rights, promise a refund, assess spoken performance or certify a CEFR level.',
 sections:[
  {id:'eng-shop-compare',title:'1. Compare the feature that actually matters',paragraphs:['Start with purpose and constraint: “I need headphones for calls, and battery life matters more than bass.” This gives the assistant a useful basis for comparison.','Use comparatives precisely: lighter than, more durable than and less expensive than. “Better” needs a criterion; ask “Better for what?” when the comparison is vague.','Check whether a feature is included or merely available: “Does this model come with a cable?” is different from “Can I buy a cable for it?”'],supportPt:'Diga a finalidade e o critério principal. Comparações como “melhor” precisam indicar em qual aspecto.',sourceIds:['bc-shopping','bc-stative']},
  {id:'eng-shop-problem',title:'2. Describe the problem in a short sequence',paragraphs:['Give the product, purchase timing and observed symptom: “I bought these two days ago, and the left side no longer charges.”','Separate observation from diagnosis. “It does not charge with the supplied cable” is evidence; “the battery is defective” may still require inspection.','Bring only evidence you actually have: receipt, order number, packaging or a short record of the troubleshooting already attempted.'],supportPt:'Informe produto, data e sintoma observado. Não transforme uma suspeita técnica em diagnóstico confirmado.',sourceIds:['bc-speaking']},
  {id:'eng-shop-remedy',title:'3. Ask what remedy is available',paragraphs:['A practical request leaves room for the applicable process: “Could you tell me whether an exchange or another solution is available?”','Refund, exchange, repair and store credit are different outcomes. Do not treat the option you prefer as an entitlement established by this language lesson.','If the first answer is unclear, narrow the question: “Are you saying it needs to be inspected before you can confirm the next step?”'],supportPt:'Peça a solução disponível e diferencie troca, reembolso, reparo e crédito. A aula não determina seus direitos reais.',sourceIds:['bc-speaking','bc-shopping']},
  {id:'eng-shop-close',title:'4. Confirm the next step and what you keep',paragraphs:['Read back the action, timing and evidence retained: “You will inspect it today, and I will keep this receipt with the reference number.”','If the item stays with the shop, ask for a written record that identifies it. Do not say an outcome is approved when only an assessment was opened.','Close calmly even when the answer is not final: “Thanks. I understand the review is pending; when should I expect an update?”'],supportPt:'Confirme ação, prazo e comprovante. Uma análise aberta ainda não é uma troca ou reembolso aprovado.',sourceIds:['bc-speaking']},
 ],
 terms:[
  {term:'come with',meaning:'Be included with a product.',pt:'vir com / estar incluído',example:'Does the charger come with the device?'},
  {term:'receipt',meaning:'Proof showing details of a purchase.',pt:'recibo / comprovante',example:'I have the receipt from Monday.'},
  {term:'faulty',meaning:'Not working as it should.',pt:'com defeito',example:'The item may be faulty, but it still needs inspection.'},
  {term:'exchange',meaning:'Replace a purchased item with another.',pt:'troca',example:'Is an exchange available after inspection?'},
  {term:'refund',meaning:'Money returned after a purchase is reversed.',pt:'reembolso',example:'The assistant has not yet confirmed a refund.'},
  {term:'store credit',meaning:'Value that can be spent with the same retailer.',pt:'crédito na loja',example:'Store credit is different from a cash refund.'},
 ],
 visual:{title:'A clear return conversation',note:'Preference, evidence, request and approved outcome are different layers.',headers:['Layer','Useful wording','Boundary'],rows:[['Need','For calls; battery matters','Selection criterion'],['Evidence','Left side does not charge','Observed symptom'],['Request','Is an exchange available?','Not yet approved'],['Next step','Inspection; update Friday','Current agreement']],question:'What can you safely say before inspection?',answer:'Describe what the product does or does not do; avoid claiming a confirmed technical cause.'},
 caseStudy:{title:'Headphones that stopped charging',scenario:['A fictional pair of headphones was purchased two days ago.','The left side does not charge using the supplied cable; no cause has been confirmed.','You have the receipt and prefer an exchange, but do not know the shop’s policy.'],task:'Explain the issue, state the evidence, ask about available remedies and confirm the next step.',hints:['Keep the preferred exchange separate from the outcome.','Ask when the shop will update you if inspection is required.'],modelAnswer:'“Hi, I bought these headphones two days ago. The left side no longer charges with the supplied cable, although the right side does. I have the receipt. Could you tell me whether an exchange or another solution is available? Understood — you’ll inspect them today and update me by Friday. Could I have a reference for the item I’m leaving with you?”',reviewChecks:['Purchase and symptom are clear.','No unsupported diagnosis is stated.','The remedy is requested rather than assumed.','Inspection, update and reference are read back.'],transfer:'Use the same structure for clothing that is the wrong size rather than faulty.'},
 checkpoint:[
  {id:'eng-shop-q1',prompt:'Which comparison is most useful?',options:['This one is better.','This one has eight hours more battery life and is lighter.','They are different.','I like products.'],correctIndex:1,explanation:'It names the criteria rather than relying on an undefined “better”.',reviewSection:'eng-shop-compare'},
  {id:'eng-shop-q2',prompt:'Which sentence is observable evidence?',options:['The battery was manufactured badly.','The company always sells defective items.','The left side does not charge with the supplied cable.','A refund is legally guaranteed.'],correctIndex:2,explanation:'It describes the behaviour without inventing a cause, pattern or legal conclusion.',reviewSection:'eng-shop-problem'},
  {id:'eng-shop-q3',prompt:'What does “Could you tell me whether an exchange is available?” do?',options:['Confirms the exchange.','Asks about a possible remedy.','Cancels the purchase automatically.','Proves the cause.'],correctIndex:1,explanation:'It opens a request; the answer and applicable process are still pending.',reviewSection:'eng-shop-remedy'},
  {id:'eng-shop-q4',prompt:'The shop keeps the item for inspection. What should you request?',options:['A record identifying the item.','A guarantee that no inspection is needed.','A new diagnosis you invented.','Silence.'],correctIndex:0,explanation:'A reference or receipt records the current handover without promising the outcome.',reviewSection:'eng-shop-close'},
  {id:'eng-shop-q5',prompt:'Which closing is accurate?',options:['Thanks — my refund is complete.','Thanks — the review is pending; when should I expect an update?','Thanks — the product is definitely defective.','Thanks — no reference is needed.'],correctIndex:1,explanation:'It keeps the unresolved status visible and asks for timing.',reviewSection:'eng-shop-close'},
 ],
 practiceExercises:[
  {id:'eng-shop-p1',question:'Compare two fictional jackets: A is lighter; B is warmer and €20 cheaper.',hints:['Use two comparatives.','Tie the choice to a purpose.'],answer:'Jacket A is lighter, but jacket B is warmer and €20 cheaper, so B may be better for cold weather.',explanation:'The comparison names the criteria and makes the conclusion conditional.'},
  {id:'eng-shop-p2',question:'Replace “The battery is broken” with an evidence-based description.',hints:['Say what happens.','Name the cable tested.'],answer:'The left side does not charge when I use the supplied cable.',explanation:'The sentence reports the symptom without pretending the cause is known.'},
  {id:'eng-shop-p3',question:'Ask for an exchange without assuming the policy.',hints:['Use “whether”.','Allow another remedy.'],answer:'Could you tell me whether an exchange or another remedy is available?',explanation:'The question states the preference while leaving the real process open.'},
 ],sources:[shopping,speaking,stative],
};

export const ENGLISH_E7_MODEL_MODULE:LessonModule={
 track:'english',lessonId:ENGLISH_E7_MODEL_ID,title:'Restaurants: express preferences and handle the order naturally',
 goal:'Discuss preferences, order clearly, check an important ingredient and resolve a small order problem without blaming someone or claiming safety that has not been confirmed.',
 scope:'Original written everyday-English practice with a fictional restaurant. It does not place an order, assess food safety, diagnose an allergy, guarantee ingredient separation, assess pronunciation or certify a CEFR level.',
 sections:[
  {id:'eng-food-preference',title:'1. Turn taste into a useful preference',paragraphs:['“I like Italian food” is a start; “I prefer lighter dishes and I enjoy vegetables, but I do not like very spicy sauces” helps another person recommend something.','Stative verbs often describe preferences and senses: like, prefer, want, taste and seem. Use them naturally rather than forcing a continuous form: “I prefer fish,” not usually “I am preferring fish.”','A recommendation should reflect the listener’s taste: “If you like smoky flavours, you might enjoy this” is more useful than “This is objectively the best dish.”'],supportPt:'Explique sua preferência com detalhes úteis. Recomendações dependem do gosto da outra pessoa, não de uma ideia absoluta de “melhor”.',sourceIds:['bc-stative','bc-restaurant']},
  {id:'eng-food-order',title:'2. Order in manageable parts',paragraphs:['A natural sequence is drink, main choice, adjustments and confirmation: “I’ll have the grilled fish, with the sauce on the side, please.”','Use “Could I have…?” or “I’ll have…” for a clear request. “I want…” is grammatical but can sound abrupt in some service situations.','When several people order, pause between items and let the server confirm. Speed is not the same as fluency.'],supportPt:'Organize o pedido em partes e dê espaço para confirmação. Clareza é mais importante do que falar rápido.',sourceIds:['bc-restaurant','bc-speaking']},
  {id:'eng-food-ingredient',title:'3. Ask about an ingredient precisely',paragraphs:['State the practical question: “Does the sauce contain peanuts?” If a real allergy or dietary requirement is involved, say so accurately and follow the restaurant’s real safety process.','“Peanut-free” can describe an ingredient claim, but it does not automatically establish how a kitchen prevents cross-contact. Ask the specific question you need answered.','If the server is unsure, accept escalation: “Could you check with the kitchen, please?” Do not convert uncertainty into reassurance.'],supportPt:'Faça uma pergunta específica sobre o ingrediente. Em situação real de alergia, informe isso claramente e não confunda ingrediente com garantia de ausência de contato cruzado.',sourceIds:['bc-speaking']},
  {id:'eng-food-problem',title:'4. Resolve a mismatch without escalating the tone',paragraphs:['Lead with the mismatch: “Sorry, I ordered the sauce on the side, but it is on the dish.” This is easier to act on than a judgement about the staff.','Ask for a workable correction: “Could this be replaced, please?” If time matters, say so: “We need to leave in twenty minutes; what is possible?”','When the bill arrives, distinguish a question from an accusation: “Could we check this item? I think we were charged for two drinks, but we ordered one.”'],supportPt:'Descreva a diferença entre pedido e entrega. Peça correção concreta antes de atribuir culpa.',sourceIds:['bc-speaking','bc-restaurant']},
 ],
 terms:[
  {term:'I’ll have…',meaning:'A common way to state your order.',pt:'eu vou querer…',example:'I’ll have the grilled fish, please.'},
  {term:'on the side',meaning:'Served separately rather than on the food.',pt:'à parte',example:'Could I have the sauce on the side?'},
  {term:'contain',meaning:'Have a particular ingredient as part of something.',pt:'conter',example:'Does this dressing contain nuts?'},
  {term:'cross-contact',meaning:'Unintended transfer of an ingredient between foods or surfaces.',pt:'contato cruzado',example:'The ingredient list alone does not answer a cross-contact question.'},
  {term:'replace',meaning:'Provide another item instead of the incorrect one.',pt:'substituir',example:'Could the dish be replaced?'},
  {term:'split the bill',meaning:'Divide the amount among people.',pt:'dividir a conta',example:'Could we split the bill evenly?'},
 ],
 visual:{title:'From preference to confirmed order',note:'Taste, ingredient information and kitchen assurance are separate.',headers:['Moment','Useful wording','What it establishes'],rows:[['Preference','I prefer lighter dishes','Personal taste'],['Order','Sauce on the side, please','Requested preparation'],['Ingredient','Does it contain peanuts?','Question requiring answer'],['Problem','The sauce is on the dish','Observed mismatch']],question:'What should you do if the server is unsure about an important ingredient?',answer:'Ask them to check with the kitchen; do not treat uncertainty as confirmation.'},
 caseStudy:{title:'A dinner order with one important check',scenario:['At a fictional restaurant, you prefer a mild fish dish.','You need to ask whether the sauce contains peanuts; the server is initially unsure.','You order sauce on the side, but the dish arrives with sauce on it.'],task:'Ask for a recommendation, check the ingredient, place the order and resolve the mismatch politely.',hints:['Do not turn “unsure” into “safe”.','Describe what arrived before requesting a replacement.'],modelAnswer:'“I prefer mild dishes and I’m thinking about the fish. What would you recommend? Does the sauce contain peanuts? Could you check with the kitchen, please? Thanks. I’ll have the grilled fish with the sauce on the side. Sorry, I ordered the sauce on the side, but it is on the dish. Could this be replaced, please?”',reviewChecks:['Preferences guide the recommendation.','The ingredient question is escalated when uncertain.','The order is clear.','The mismatch and requested correction are specific.'],transfer:'Change the case to a vegetarian preference that is not an allergy.'},
 checkpoint:[
  {id:'eng-food-q1',prompt:'Which sentence gives the most useful preference?',options:['Food is good.','I prefer mild dishes and lighter sauces.','Choose for me without asking.','Everything tastes the same.'],correctIndex:1,explanation:'It supplies criteria that can guide a recommendation.',reviewSection:'eng-food-preference'},
  {id:'eng-food-q2',prompt:'Which request means the sauce should be separate?',options:['No sauce ever.','Sauce on the side, please.','Extra side.','The sauce is a side.'],correctIndex:1,explanation:'“On the side” asks for separate serving.',reviewSection:'eng-food-order'},
  {id:'eng-food-q3',prompt:'The server is unsure about peanuts. What is the best next step?',options:['Assume there are none.','Ask them to check with the kitchen.','Say uncertainty is a guarantee.','Order without mentioning it.'],correctIndex:1,explanation:'The uncertainty needs a real check rather than invented reassurance.',reviewSection:'eng-food-ingredient'},
  {id:'eng-food-q4',prompt:'Which opening best addresses the wrong preparation?',options:['You never listen.','Sorry, I ordered the sauce on the side, but it is on the dish.','This restaurant is terrible.','Someone is guilty.'],correctIndex:1,explanation:'It states the actionable mismatch without unsupported blame.',reviewSection:'eng-food-problem'},
  {id:'eng-food-q5',prompt:'Which bill question avoids an unsupported accusation?',options:['You stole from us.','Could we check this item? We ordered one drink, not two.','The bill is criminal.','I will not explain.'],correctIndex:1,explanation:'It identifies the disputed line and the expected quantity.',reviewSection:'eng-food-problem'},
 ],
 practiceExercises:[
  {id:'eng-food-p1',question:'State a preference for vegetables, mild food and small portions.',hints:['Use prefer or like.','Give three useful criteria.'],answer:'I prefer vegetable dishes that are mild, and I would like a smaller portion.',explanation:'The sentence turns taste into an actionable preference.'},
  {id:'eng-food-p2',question:'Order pasta and ask for cheese separately.',hints:['Use “I’ll have”.','Use “on the side”.'],answer:'I’ll have the pasta, with the cheese on the side, please.',explanation:'The order and adjustment are compact and clear.'},
  {id:'eng-food-p3',question:'Politely question a bill showing three coffees when you ordered two.',hints:['Ask to check the item.','Contrast the quantities.'],answer:'Could we check the coffee line, please? The bill shows three, but we ordered two.',explanation:'The wording identifies the discrepancy without assuming intent.'},
 ],sources:[restaurant,speaking,stative],
};

export const ENGLISH_E8_MODEL_MODULE:LessonModule={
 track:'english',lessonId:ENGLISH_E8_MODEL_ID,title:'Family plans: arrange playdates, routines and weekends',
 goal:'Invite another family, coordinate timing and responsibilities, communicate a change and confirm the final plan without pressuring the other person or leaving key details implicit.',
 scope:'Original written everyday-English practice with fictional families and plans. It does not contact another parent, make childcare or safety decisions, assess a child’s needs, assess spoken performance or certify a CEFR level.',
 sections:[
  {id:'eng-family-invite',title:'1. Make an invitation easy to answer',paragraphs:['Include the activity, approximate duration and whether the timing is flexible: “Would you like to meet at the park on Saturday morning for about an hour?”','Leave genuine room for “no”: “No problem if this weekend is busy.” An invitation is not a test of friendship.','For a child-related plan, address the responsible adult and confirm arrangements directly rather than relying on a message passed through children.'],supportPt:'Inclua atividade, duração e flexibilidade. Um convite deve permitir uma recusa sem pressão.',sourceIds:['bc-speaking']},
  {id:'eng-family-logistics',title:'2. Name the practical details',paragraphs:['Clarify who will be present, meeting point, pickup or drop-off and anything that needs to be brought. Do not assume that “the usual place” is shared knowledge.','Use specific time language: “between ten and eleven” is a window; “at ten” is a point. “Around ten” allows some variation and may need a tighter confirmation.','If a routine matters, ask rather than prescribe: “Is there a snack time we should plan around?”'],supportPt:'Confirme pessoas, local, horário e responsabilidades. Diferencie horário exato, janela e aproximação.',sourceIds:['bc-speaking']},
  {id:'eng-family-change',title:'3. Communicate a change early and offer an alternative',paragraphs:['Lead with the change: “We are running about twenty minutes late.” Then say what remains possible.','A useful alternative has one or two options: “We can arrive at 10:30, or we can take a rain check for next weekend.” Too many options shift the planning burden.','Apologise for the impact without inventing a dramatic excuse: “Sorry for the late change” may be enough.'],supportPt:'Avise a mudança diretamente, diga o que ainda é possível e ofereça poucas alternativas claras.',sourceIds:['bc-speaking']},
  {id:'eng-family-confirm',title:'4. Close the loop without overloading the message',paragraphs:['A final summary can be one sentence: “Great — Saturday at 10:30 by the playground entrance; we will both stay for about an hour.”','If something is still open, label it: “The time is confirmed; we still need to decide about lunch.”','After the event, a short, specific response keeps the relationship natural: “Thanks for today — the children really enjoyed the treasure hunt.”'],supportPt:'Resuma apenas o essencial e indique o que ainda está em aberto. Depois, agradeça com um detalhe real.',sourceIds:['bc-speaking']},
 ],
 terms:[
  {term:'playdate',meaning:'An arranged time for children to play together.',pt:'encontro para as crianças brincarem',example:'Would you like to arrange a playdate on Saturday?'},
  {term:'works for me',meaning:'The proposed arrangement is suitable.',pt:'funciona para mim',example:'Ten thirty works for me.'},
  {term:'drop off',meaning:'Take someone to a place and leave them there.',pt:'deixar alguém',example:'Are parents staying, or is it drop-off?'},
  {term:'pick up',meaning:'Collect someone from a place.',pt:'buscar alguém',example:'What time should I pick her up?'},
  {term:'running late',meaning:'Likely to arrive after the agreed time.',pt:'atrasado / atrasando',example:'We are running about twenty minutes late.'},
  {term:'take a rain check',meaning:'Decline now while suggesting doing it another time.',pt:'deixar para outra ocasião',example:'Could we take a rain check for next weekend?'},
 ],
 visual:{title:'A family plan with no hidden assumptions',note:'An invitation becomes a plan only after the practical details are accepted.',headers:['Stage','Question','Example'],rows:[['Invite','What and when?','Park, Saturday morning'],['Logistics','Who, where, responsibility?','Parents stay; playground gate'],['Change','What changed?','Arrival moves to 10:30'],['Confirm','What is agreed?','10:30; one hour']],question:'What remains unknown if someone only says “Saturday works”?',answer:'The exact time, place, duration and responsibility may still need confirmation.'},
 caseStudy:{title:'A weekend plan that needs one adjustment',scenario:['Two fictional families are considering a park playdate on Saturday.','Both parents will stay. The original time is 10:00 by the playground entrance for one hour.','On Saturday morning, one family learns it will be twenty minutes late.'],task:'Write the invitation, initial confirmation, change message and final read-back.',hints:['Give the other family an easy way to decline.','Do not treat the new time as accepted until they reply.'],modelAnswer:'“Would you like to meet at the park on Saturday at ten for about an hour? We can meet by the playground entrance, and we will both stay. No problem if this weekend is busy.” Later: “We are running about twenty minutes late. Would 10:30 still work, or should we take a rain check?” After acceptance: “Great — Saturday at 10:30 by the playground entrance, and both parents will stay.”',reviewChecks:['The invitation is specific and low-pressure.','Responsibility and meeting point are explicit.','The delay includes workable alternatives.','The new time is read back only after acceptance.'],transfer:'Adapt the exchange for a family lunch where the venue is still undecided.'},
 checkpoint:[
  {id:'eng-family-q1',prompt:'Which invitation is easiest to answer?',options:['We should meet sometime.','Would you like to meet at the park on Saturday at ten for about an hour?','You must come.','Let us organise everything later.'],correctIndex:1,explanation:'It supplies activity, day, time and duration.',reviewSection:'eng-family-invite'},
  {id:'eng-family-q2',prompt:'“Between ten and eleven” is:',options:['One exact minute.','A time window.','A cancellation.','A place.'],correctIndex:1,explanation:'It allows arrival or availability within a range.',reviewSection:'eng-family-logistics'},
  {id:'eng-family-q3',prompt:'Which message handles a delay well?',options:['Late.','We are twenty minutes late. Would 10:30 still work?','Assume they will wait.','Say nothing.'],correctIndex:1,explanation:'It states the change and requests confirmation of the alternative.',reviewSection:'eng-family-change'},
  {id:'eng-family-q4',prompt:'What does “take a rain check” suggest?',options:['Cancel forever.','Move the plan to another occasion.','Check the weather only.','Arrive earlier.'],correctIndex:1,explanation:'It keeps open the possibility of doing the activity another time.',reviewSection:'eng-family-change'},
  {id:'eng-family-q5',prompt:'Which final read-back is complete?',options:['See you then.','Saturday at 10:30 by the playground entrance; both parents will stay.','Somewhere tomorrow.','The plan is obvious.'],correctIndex:1,explanation:'It confirms the key agreed details.',reviewSection:'eng-family-confirm'},
 ],
 practiceExercises:[
  {id:'eng-family-p1',question:'Invite a family to lunch on Sunday at 12:30 and make refusal easy.',hints:['Name the activity and time.','Add a low-pressure close.'],answer:'Would you like to join us for lunch on Sunday at 12:30? No problem at all if this weekend is busy.',explanation:'The invitation is concrete without creating pressure.'},
  {id:'eng-family-p2',question:'Ask whether adults stay during a playdate.',hints:['Do not assume the arrangement.','Contrast the two options.'],answer:'Just to check, are parents staying, or is this a drop-off playdate?',explanation:'The question makes the responsibility arrangement explicit.'},
  {id:'eng-family-p3',question:'Offer two alternatives after a one-hour delay.',hints:['Give a new time.','Offer another day.'],answer:'We are running an hour late. Would noon still work, or would next Saturday be better?',explanation:'Two bounded options help the other person respond.'},
 ],sources:[speaking],
};

export const ENGLISH_E9_MODEL_MODULE:LessonModule={
 track:'english',lessonId:ENGLISH_E9_MODEL_ID,title:'News and politics: express a view without ending the conversation',
 goal:'Discuss a news or political topic by distinguishing source, fact, interpretation and opinion, then disagree respectfully and ask a genuine follow-up.',
 scope:'Original written everyday-English practice with fictional public-policy examples. It does not verify current news, advocate a party or candidate, provide civic or legal advice, assess political beliefs, assess spoken performance or certify a CEFR level.',
 sections:[
  {id:'eng-news-source',title:'1. Say what you know and where it came from',paragraphs:['Separate the report from your own conclusion: “According to the article, the proposal would start next year. I have not read the full text.”','A headline is not the whole evidence. Use “It reports that…” for the source’s claim and reserve “It proves…” for evidence that actually establishes the conclusion.','When recency matters, name the date or admit that you need to check: “I saw that yesterday, but I do not know whether it has changed.”'],supportPt:'Separe o que a fonte diz da sua interpretação. Se a atualidade for importante, informe a data ou reconheça que precisa verificar.',sourceIds:['bc-speaking']},
  {id:'eng-news-view',title:'2. Build an opinion with a reason and a limit',paragraphs:['A useful opinion has position, reason and boundary: “I support the goal because public transport matters, but I am unsure about the proposed funding.”','Hedging is not weakness when evidence is incomplete: “It seems”, “I may be missing something” and “As far as I understand” show the appropriate level of certainty.','Avoid treating a group as if every member holds one view. Discuss the argument or policy rather than assigning motives to millions of people.'],supportPt:'Dê posição, razão e limite. Linguagem de incerteza torna a opinião mais precisa quando a evidência é incompleta.',sourceIds:['bc-agreeing']},
  {id:'eng-news-disagree',title:'3. Disagree with the point, not the person',paragraphs:['Acknowledge before contrasting: “I see why cost is your concern. I look at the trade-off differently because…”','Use questions to understand, not to trap: “Which part of the proposal worries you most?” is more open than “How can anyone believe that?”','Agreement can be partial: “I agree about the problem, but not about the proposed solution.” This identifies common ground and the actual disagreement.'],supportPt:'Reconheça o ponto antes de contrastar. Discorde do argumento e use perguntas para compreender, não para encurralar.',sourceIds:['bc-agreeing','bc-speaking']},
  {id:'eng-news-repair',title:'4. Slow down or leave the topic well',paragraphs:['If the exchange becomes tense, name the process: “I think we are talking past each other. Can we separate the goal from the method?”','Correct yourself openly: “I stated that too strongly. What I mean is…” This improves accuracy without pretending the first wording never happened.','It is acceptable to close a topic: “We may not agree, but I appreciate hearing your reasoning.” A conversation does not require a forced consensus.'],supportPt:'Se a conversa ficar tensa, separe os pontos, reformule o que exagerou e encerre com respeito quando necessário.',sourceIds:['bc-agreeing']},
 ],
 terms:[
  {term:'according to',meaning:'Identifies the source of reported information.',pt:'de acordo com',example:'According to the article, the vote is next week.'},
  {term:'as far as I understand',meaning:'Marks a current but limited understanding.',pt:'pelo que entendo',example:'As far as I understand, the details are not final.'},
  {term:'trade-off',meaning:'A balance where gaining one benefit involves a cost elsewhere.',pt:'contrapartida / escolha entre vantagens',example:'The debate involves a cost and access trade-off.'},
  {term:'common ground',meaning:'A point or principle both sides share.',pt:'ponto em comum',example:'We found common ground on the goal.'},
  {term:'I see it differently',meaning:'Signals disagreement without attacking the other person.',pt:'eu vejo de outra forma',example:'I see it differently because the evidence is incomplete.'},
  {term:'talk past each other',meaning:'Respond without addressing what the other person actually means.',pt:'falar sem realmente se entender',example:'We may be talking past each other about the word “fair”.'},
 ],
 visual:{title:'Keep four layers separate',note:'A sourced claim can still require verification and interpretation.',headers:['Layer','Example','Question'],rows:[['Source','The article reports a proposal','Which article/date?'],['Fact claimed','Start date would be January','Is the text final?'],['Interpretation','Funding may be difficult','What evidence supports this?'],['Opinion','I support the goal','Why, and with what limit?']],question:'Why say “the article reports” instead of “this proves” at the start?',answer:'It accurately attributes the claim without overstating what the source establishes.'},
 caseStudy:{title:'A respectful disagreement about a fictional transport proposal',scenario:['A fictional article says a city may reduce bus fares next year; the funding plan is not final.','One person supports lower fares for access. Another worries about service quality and cost.','Both agree that reliable public transport matters.'],task:'State one position with a limit, acknowledge the other concern, identify common ground and ask one genuine follow-up.',hints:['Do not invent a final funding decision.','Make the follow-up answerable rather than rhetorical.'],modelAnswer:'“According to the article, the city may reduce fares next year, but the funding plan is not final. I support the goal because lower fares could improve access, although I am unsure how the service would be funded. I see why you are concerned about quality; we agree that reliability matters. Which part worries you more: the funding risk or the possibility of overcrowding?”',reviewChecks:['The source claim and unresolved status are clear.','The opinion includes a reason and uncertainty.','The other concern is acknowledged.','The question seeks information rather than victory.'],transfer:'Use the same structure for a discussion about remote work or school screen time.'},
 checkpoint:[
  {id:'eng-news-q1',prompt:'Which sentence attributes information most accurately?',options:['This headline proves everything.','According to the article, the proposal may start next year.','Everyone knows it is final.','My memory is the official text.'],correctIndex:1,explanation:'It names the source and preserves the reported uncertainty.',reviewSection:'eng-news-source'},
  {id:'eng-news-q2',prompt:'Which opinion includes a useful limit?',options:['I am completely right.','I support the goal, but I am unsure about the funding.','Only bad people disagree.','There is no trade-off.'],correctIndex:1,explanation:'It states a position while keeping an unresolved issue visible.',reviewSection:'eng-news-view'},
  {id:'eng-news-q3',prompt:'Which line shows partial agreement?',options:['You understand nothing.','I agree about the problem, but not the proposed solution.','There is no common ground.','I refuse to listen.'],correctIndex:1,explanation:'It separates the shared diagnosis from the disputed remedy.',reviewSection:'eng-news-disagree'},
  {id:'eng-news-q4',prompt:'Which is a genuine follow-up question?',options:['How can anyone think that?','Which part of the proposal concerns you most?','Do you admit I am right?','Why are people like you impossible?'],correctIndex:1,explanation:'It invites the person to explain the substance of the concern.',reviewSection:'eng-news-disagree'},
  {id:'eng-news-q5',prompt:'You overstated a claim. What is a useful repair?',options:['Repeat it louder.','I stated that too strongly. What I mean is…','Change the source secretly.','Attack the listener.'],correctIndex:1,explanation:'Open self-correction improves accuracy and trust.',reviewSection:'eng-news-repair'},
 ],
 practiceExercises:[
  {id:'eng-news-p1',question:'Turn “The policy will definitely fail” into a bounded opinion.',hints:['Use “I think” or “may”.','Name the uncertainty.'],answer:'I think the policy may struggle unless the funding details are clearer.',explanation:'The version states a concern without pretending the outcome is known.'},
  {id:'eng-news-p2',question:'Disagree with a friend about remote work while acknowledging one benefit.',hints:['Name the benefit first.','Contrast your concern.'],answer:'I agree that remote work saves commuting time, but I see the collaboration trade-off differently.',explanation:'The response recognises a real point before stating the disagreement.'},
  {id:'eng-news-p3',question:'Ask a genuine question about a friend’s concern over cost.',hints:['Avoid a rhetorical question.','Ask for the most important part.'],answer:'Which cost do you think would have the biggest impact, and why?',explanation:'The question invites explanation rather than demanding surrender.'},
 ],sources:[agreeing,speaking],
};

export const ENGLISH_E10_MODEL_MODULE:LessonModule={
 track:'english',lessonId:ENGLISH_E10_MODEL_ID,title:'TV, films and hobbies: recommend, react and keep talking',
 goal:'Describe entertainment and hobbies vividly, recommend something for another person’s taste, avoid unwanted spoilers and sustain a natural exchange with relevant follow-ups.',
 scope:'Original written everyday-English practice. Fictional titles are used where detail matters. It does not reproduce copyrighted dialogue or plots, assess listening or pronunciation, access a streaming service or certify a CEFR level.',
 sections:[
  {id:'eng-culture-describe',title:'1. Describe the experience, not the entire plot',paragraphs:['Give genre, premise and tone: “It is a slow mystery about a family rebuilding trust after a disappearance.” That helps without narrating every event.','Distinguish “funny” from “fun”: funny makes you laugh; fun is enjoyable. “Moving”, “tense”, “light-hearted” and “thought-provoking” add useful precision.','Ask about spoiler preference before revealing a turning point: “How far have you watched?” or “Do you want the spoiler-free version?”'],supportPt:'Dê gênero, premissa e tom sem contar toda a trama. Confirme antes de revelar pontos importantes.',sourceIds:['bc-speaking','bc-stative']},
  {id:'eng-culture-recommend',title:'2. Recommend for a person, not for everyone',paragraphs:['Connect the recommendation to known taste: “Since you liked character-driven dramas, you might enjoy this.”','Use calibrated language: “I think you would like it” is a recommendation; “You will love it” is stronger and may sound overconfident.','Include a possible drawback: “The first episode is slow, but the relationships become more interesting.” This makes the recommendation more credible.'],supportPt:'Relacione a recomendação ao gosto da pessoa e inclua uma ressalva útil quando houver.',sourceIds:['bc-speaking']},
  {id:'eng-culture-react',title:'3. React with more than “good” or “bad”',paragraphs:['Choose one aspect and explain it: acting, pacing, dialogue, visuals, theme or ending. “The pacing felt uneven because the middle episodes repeated the same conflict.”','A different taste is not an error: “It was not for me, but I can see why people like the atmosphere.”','Follow the other person’s detail: if they mention a character, ask about that character rather than switching immediately to your own list.'],supportPt:'Escolha um aspecto e explique sua reação. Gosto diferente não é erro; dê continuidade ao detalhe trazido pela outra pessoa.',sourceIds:['bc-speaking','bc-stative']},
  {id:'eng-culture-hobby',title:'4. Turn a hobby answer into a conversation',paragraphs:['Move from label to routine: “I cook on weekends, mainly simple fish and vegetable dishes.”','Add motivation or recent change: “I started because I wanted calmer evenings, and now I enjoy experimenting with sauces.”','End with one connected invitation or question: “What do you like cooking when you have more time?”'],supportPt:'Vá além do nome do hobby: diga rotina, motivação ou mudança recente e faça uma pergunta conectada.',sourceIds:['bc-speaking']},
 ],
 terms:[
  {term:'premise',meaning:'The basic situation or idea a story begins with.',pt:'premissa',example:'The premise is simple, but the characters are complex.'},
  {term:'spoiler',meaning:'Information that reveals an important story development.',pt:'spoiler / revelação da trama',example:'I can explain it without spoilers.'},
  {term:'pacing',meaning:'The speed and rhythm at which a story develops.',pt:'ritmo narrativo',example:'The pacing becomes faster after episode two.'},
  {term:'thought-provoking',meaning:'Making you consider an idea deeply.',pt:'instigante / que faz pensar',example:'It is a thought-provoking documentary.'},
  {term:'be into',meaning:'Be interested in or enjoy something.',pt:'gostar / curtir',example:'Are you into historical dramas?'},
  {term:'give it a try',meaning:'Try something to see whether you like it.',pt:'dar uma chance / experimentar',example:'Give the first episode a try.'},
 ],
 visual:{title:'A recommendation that fits the listener',note:'A useful recommendation includes fit and a boundary.',headers:['Part','Example','Purpose'],rows:[['Taste','You like character dramas','Listener fit'],['Premise','Family mystery','Basic content'],['Tone','Slow and tense','Expectation'],['Caveat','First episode is gradual','Honest boundary']],question:'What should come before revealing a major event?',answer:'Check how far the person has watched and whether they want spoilers.'},
 caseStudy:{title:'Recommend a fictional series without spoiling it',scenario:['A friend likes character-driven mysteries but dislikes graphic violence.','The fictional series North Window is slow, tense and focused on family secrets; violence is discussed but not shown graphically.','The first episode is gradual. A major episode-three reveal must not be described.'],task:'Give a spoiler-free recommendation, include one caveat and ask a follow-up about the friend’s taste.',hints:['Connect the series to the supplied preferences.','Do not reveal the episode-three event.'],modelAnswer:'“Since you like character-driven mysteries, you might enjoy North Window. It is a slow, tense story about a family dealing with old secrets, and the violence is discussed rather than shown graphically. The first episode is quite gradual, but the relationships become more compelling. Are you usually patient with a slow opening if the characters are strong?”',reviewChecks:['The recommendation uses the friend’s preferences.','Genre, premise and tone are clear.','The caveat is honest.','No major reveal is disclosed.'],transfer:'Recommend a hobby to someone who wants a calm activity with little equipment.'},
 checkpoint:[
  {id:'eng-culture-q1',prompt:'Which description is useful and spoiler-light?',options:['Everything happens and I will tell you the ending.','It is a tense family mystery with a slow opening.','It is good.','Watch it because I said so.'],correctIndex:1,explanation:'It gives genre, tone and pacing without exposing the plot.',reviewSection:'eng-culture-describe'},
  {id:'eng-culture-q2',prompt:'Which word means enjoyable rather than causing laughter?',options:['Funny','Fun','Spoiled','Tense'],correctIndex:1,explanation:'“Fun” means enjoyable; “funny” normally means amusing or strange.',reviewSection:'eng-culture-describe'},
  {id:'eng-culture-q3',prompt:'Which recommendation is best calibrated?',options:['Every human will love it.','Since you like character dramas, you might enjoy it.','You are wrong if you dislike it.','It has no weakness.'],correctIndex:1,explanation:'It links the suggestion to the listener’s known taste without guaranteeing a reaction.',reviewSection:'eng-culture-recommend'},
  {id:'eng-culture-q4',prompt:'A friend dislikes the series you love. What is a natural response?',options:['Your taste is incorrect.','It was not for you — what felt too slow?','Stop talking.','You must rewatch it.'],correctIndex:1,explanation:'It accepts different taste and invites a specific explanation.',reviewSection:'eng-culture-react'},
  {id:'eng-culture-q5',prompt:'Which hobby answer best sustains conversation?',options:['Cooking.','I cook simple meals on weekends. What do you enjoy making?','None of your business.','All hobbies are identical.'],correctIndex:1,explanation:'It adds routine and a connected follow-up.',reviewSection:'eng-culture-hobby'},
 ],
 practiceExercises:[
  {id:'eng-culture-p1',question:'Describe a fictional comedy-drama using genre, premise and tone.',hints:['Do not narrate the ending.','Use one precise tone word.'],answer:'It is a warm comedy-drama about two neighbours starting a community garden after retirement.',explanation:'The sentence gives enough shape for conversation without a plot summary.'},
  {id:'eng-culture-p2',question:'Recommend a slow documentary to someone who enjoys history.',hints:['Connect it to their taste.','Include the pacing caveat.'],answer:'Since you enjoy history, you might like this documentary; it is very detailed, although the pacing is slow.',explanation:'The recommendation includes both fit and a useful limitation.'},
  {id:'eng-culture-p3',question:'Expand “I like running” into a conversational answer.',hints:['Add routine or motivation.','Ask one related question.'],answer:'I run twice a week because it helps me clear my head. Do you prefer exercising alone or with someone?',explanation:'The answer adds personal meaning and opens a related path.'},
 ],sources:[speaking,stative],
};

export const ENGLISH_EVERYDAY_MONTH_MODULES=[
 ENGLISH_E6_MODEL_MODULE,
 ENGLISH_E7_MODEL_MODULE,
 ENGLISH_E8_MODEL_MODULE,
 ENGLISH_E9_MODEL_MODULE,
 ENGLISH_E10_MODEL_MODULE,
] as const;

export function localEnglishEverydayMonthExpansionFor(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{
 const code=localEnglishCodeFor(track,lesson);
 if(code==='E6'&&lesson.slug===ENGLISH_E6_MODEL_SLUG)return ENGLISH_E6_MODEL_MODULE;
 if(code==='E7'&&lesson.slug===ENGLISH_E7_MODEL_SLUG)return ENGLISH_E7_MODEL_MODULE;
 if(code==='E8'&&lesson.slug===ENGLISH_E8_MODEL_SLUG)return ENGLISH_E8_MODEL_MODULE;
 if(code==='E9'&&lesson.slug===ENGLISH_E9_MODEL_SLUG)return ENGLISH_E9_MODEL_MODULE;
 if(code==='E10'&&lesson.slug===ENGLISH_E10_MODEL_SLUG)return ENGLISH_E10_MODEL_MODULE;
 return null;
}
