import type {LessonModule} from './lessonModules.ts';
import {ACCA_C1_MODEL_ID,ACCA_C1_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_C1_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'20–26',segments:['Historical information and future prediction limits.','Manipulation, bias and window-dressing warning signs.','Seasonality and major year-end transactions.','Why consolidated totals can hide different group economics.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_C1_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask what comparison the learner is trying to make and whether the reported figure represents the whole period or only the reporting date.',supportedPractice:'Name the limitation, show its likely direction of distortion and request the additional information needed before reaching a conclusion.',misconception:'Audited historical statements are useful evidence, but they do not guarantee future performance or make a year-end balance representative of the period.',transfer:'Change the seasonality, acquisition date, accounting choice or group composition and ask which conclusion becomes weaker.',close:'Recap evidence limits, manipulation risk, point-in-time balances and group aggregation without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_C1_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_C1_MODEL_ID,title:'ACCA FR C1 · Limitations of financial statements',
 goal:'Explain why historical, year-end and consolidated figures can mislead prediction or comparison, identify manipulation risk, and request better evidence before concluding.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level C1 mapping must be checked against the exact selected exam sitting before publication. It teaches analytical limitations rather than an audit or fraud investigation. It is original teaching material, not ACCA approval, assurance, legal advice, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-c1-history',title:'1. Use historical information without treating it as a forecast',paragraphs:[
   'Financial statements describe transactions and conditions from a completed reporting period using applicable recognition and measurement requirements. They are essential evidence for trends, stewardship and financial position, but future demand, prices, financing conditions, regulation and management decisions can differ. A historical growth rate is therefore a starting point for questions, not an automatic forecast of the next period.',
   'Comparability also depends on a stable basis. Inflation, exchange-rate movements, acquisitions, disposals, accounting-policy changes and one-off events can make nominal figures from two periods economically different. Separate recurring drivers from structural changes and avoid projecting a percentage merely because it appears consistently in a short series. The more the business model or environment changes, the weaker a mechanical extrapolation becomes.',
   'The Conceptual Framework seeks useful information for investors, lenders and other creditors, not certainty about future cash flows. An analyst should combine the statements with budgets that have been challenged, order data, market conditions, capacity, customer concentration and other relevant information. Those additions do not erase uncertainty; they make the assumptions behind a forward-looking conclusion visible.'
  ],supportPt:'Demonstrações históricas ajudam a identificar tendências e stewardship, mas não são previsão automática. Separe fatores recorrentes de inflação, aquisições, câmbio, itens isolados e mudanças no ambiente.',sourceIds:['acca-fr-syllabus','conceptual-framework']},
  {id:'acca-c1-manipulation',title:'2. Challenge desired presentation effects and unsupported estimates',paragraphs:[
   'Management may have incentives to present stronger profit, liquidity or gearing. Risk can arise from biased estimates, selective classification, premature revenue, delayed expenses, omitted liabilities or transactions timed around year end. Some choices may be permitted policies requiring transparent and consistent application; others may be errors or non-compliance. An analyst identifies warning signs and seeks evidence rather than assuming intent from one unusual number.',
   'Window dressing describes short-term action or presentation designed to make the reporting-date position appear stronger without a corresponding sustained improvement. Compare year-end balances with monthly or quarterly averages, cash movements after year end, supplier and customer ageing, policy disclosures and prior estimates. A ratio can be arithmetically correct while the underlying snapshot is unrepresentative.',
   'Do not “normalise” a suspicious amount by silently replacing it with a preferred number. State the issue, quantify a transparent sensitivity where facts permit, and explain what would confirm the treatment. If evidence shows a transaction was recognised before its IFRS criteria were met, the statements require correction; analytical commentary is not a substitute for proper accounting, governance or audit procedures.'
  ],supportPt:'Procure sinais de bias, timing e window dressing, mas não conclua intenção sem evidência. Compare médias, ageing, caixa posterior e políticas; se o reconhecimento estiver incorreto, a contabilidade deve ser corrigida.',sourceIds:['acca-fr-syllabus','acca-interpretation']},
  {id:'acca-c1-snapshot',title:'3. Test whether closing balances represent the period',paragraphs:[
   'A statement of financial position is measured at one date. Seasonal trading can make closing inventory, receivables, cash and short-term borrowing much higher or lower than normal operating levels. Ratios combining a full-year income-statement flow with one closing balance can therefore distort efficiency. When available, use a representative average and explain the approximation rather than assuming the reporting date is typical.',
   'A major asset acquisition near year end creates a different comparability problem. Closing capital employed includes the new asset and related financing, while current-year revenue or profit may include little of its productive effect. Return measures can fall even if the investment is performing as planned. Review the acquisition date, funding, expected capacity, post-year-end activity and like-for-like results before describing performance as worse.',
   'The same discipline applies to disposals, restructurings and large settlements. Ask which statement contains a period flow and which contains a point-in-time balance, then align numerator and denominator as far as reliable data allow. An adjusted measure should be labelled, reconciled and accompanied by its limitation; it is not automatically more faithful than the reported figure.'
  ],supportPt:'O statement of financial position é uma fotografia. Sazonalidade e aquisições próximas ao fechamento podem distorcer ratios que combinam saldo final com fluxo anual; use média representativa quando houver e explique a limitação.',sourceIds:['acca-fr-syllabus','acca-interpretation']},
  {id:'acca-c1-group',title:'4. Recognise what consolidated totals can conceal',paragraphs:[
   'Consolidated financial statements present the parent and subsidiaries as a single economic entity, eliminating intragroup balances and transactions. This is useful for assessing the group as a whole, but aggregation can combine entities operating in different industries, countries, currencies, margins, growth stages and risk profiles. A group average may describe none of its significant components particularly well.',
   'Changes in group composition weaken trend comparisons. A subsidiary acquired part-way through the year contributes results only after acquisition but its closing assets and liabilities enter the consolidated statement of financial position. A disposal has the opposite effect. Goodwill, non-controlling interests, fair-value adjustments and intragroup eliminations can also make a simple comparison with a standalone competitor inappropriate.',
   'Use segment information and acquisition or disposal disclosures where available, distinguish organic from acquired movement and avoid adding parent and subsidiary ratios. Ratios must be calculated from a consistent consolidated data set. Even then, segment mix, different year ends or limited disaggregation may prevent a precise explanation, so identify what is known and what remains uncertain.'
  ],supportPt:'Consolidação mostra o grupo como uma entidade econômica, mas pode esconder diferenças entre segmentos e países. Mudanças no perímetro, goodwill e eliminações limitam tendências e comparações com empresas isoladas.',sourceIds:['ifrs-10','acca-fr-syllabus','acca-interpretation']}
 ],
 terms:[
  {term:'Historical information',meaning:'Information about completed transactions and conditions rather than a guaranteed forecast.',pt:'Informação histórica',example:'Past revenue growth needs current market evidence before projection.'},
  {term:'Window dressing',meaning:'Short-term action or presentation that makes a reporting-date position appear stronger without sustained change.',pt:'Maquiagem de balanço',example:'An unusually low closing working-capital balance may require average data.'},
  {term:'Seasonality',meaning:'Predictable variation in activity or balances across a year.',pt:'Sazonalidade',example:'A retailer may hold far less inventory just after its peak season.'},
  {term:'Representative average',meaning:'Average intended to reflect normal balances across the period more fairly than one closing amount.',pt:'Média representativa',example:'Monthly inventory can support a more informative days calculation.'},
  {term:'Group composition',meaning:'Entities and activities included in consolidated financial statements during the period.',pt:'Composição do grupo',example:'A mid-year acquisition changes both trend and ratio interpretation.'},
  {term:'Sensitivity',meaning:'Transparent recalculation showing how a conclusion changes under a stated alternative assumption.',pt:'Análise de sensibilidade',example:'Compare inventory days using closing and monthly-average inventory.'}
 ],
 visual:{title:'From apparent signal to responsible conclusion',note:'Analytical map; a warning sign is not proof of manipulation or future performance.',headers:['Observed signal','Possible limitation','Next evidence'],rows:[['Revenue grew 20%','Historical trend may not persist','Orders, market and capacity'],['Closing inventory fell sharply','Seasonal snapshot may be atypical','Monthly average and ageing'],['ROCE fell after 30 December purchase','Capital included before its profit contribution','Acquisition date and like-for-like return'],['Group margin is stable','Different segment movements may offset','Segment and perimeter analysis'],['Year-end liquidity improved suddenly','Timing or window dressing may affect snapshot','Post-year-end cash and ageing']],question:'Why is a monthly average useful but not automatically the “correct” reported balance?',answer:'It can better represent normal activity for analysis, while the statement of financial position must still report the balance at its specified date under IFRS.'},
 caseStudy:{title:'Seasonal inventory and a late acquisition',scenario:['A retailer reports annual cost of sales of CU720,000 and closing inventory of CU100,000. Its reliable monthly-average inventory for the year is CU220,000. The prior year’s inventory days, calculated from a representative average, were 105 days.','On 30 December, the group acquired a distribution hub for CU600,000 financed by a five-year loan. The hub made no significant contribution to current-year revenue or operating profit. Management highlights lower closing inventory days and describes any fall in return on capital as operating deterioration.','Internal review also identifies a CU50,000 sale recorded in December even though control transfers in January. The amount must be assessed and corrected under the applicable revenue requirements rather than treated only as an analytical adjustment.'],task:'Calculate inventory days using closing and average inventory, then explain why the inventory trend, return conclusion and recorded sale require different responses.',hints:['Use inventory divided by cost of sales multiplied by 365 under each stated basis.','Separate an unrepresentative but valid closing snapshot, a denominator timing effect and a potentially incorrect recognition entry.'],modelAnswer:'Closing inventory days are 50.7 days: CU100,000 / CU720,000 × 365. Using the reliable monthly average gives 111.5 days: CU220,000 / CU720,000 × 365. Compared with the prior representative 105 days, average inventory days worsened by 6.5 days, so the closing calculation alone does not support an efficiency improvement; seasonality explains why the snapshot may be atypical. A current-year return measure can also fall because the CU600,000 hub and loan enter closing capital while the hub contributes almost no current-year profit, so like-for-like or future-period evidence is needed before calling this operating deterioration. The CU50,000 sale is different: if control transfers only in January, December recognition is not repaired by commentary and the accounting must be corrected under the applicable revenue requirements.',reviewChecks:['Closing inventory days are 50.7.','Average inventory days are 111.5, versus 105 previously.','The late acquisition creates a denominator and comparability issue, not automatic deterioration.','Potential premature revenue requires accounting correction, not silent analytical normalisation.'],transfer:'Assume the monthly average inventory was CU180,000 and the hub was acquired on 1 July with six months of profit contribution. Reassess which limitations remain strongest.'},
 checkpoint:[
  {id:'acca-c1-q1',prompt:'Why should historical revenue growth not be projected mechanically?',options:['Historical statements contain no useful information','Future conditions and business decisions may differ','Revenue can never be compared across years','Only cash flow may be analysed'],correctIndex:1,explanation:'Historical evidence is useful, but changed conditions can break the observed trend.',reviewSection:'acca-c1-history'},
  {id:'acca-c1-q2',prompt:'What best describes window dressing?',options:['Every permitted accounting policy','Short-term action or presentation making a reporting-date position appear stronger','Any fall in profit','A required consolidation elimination'],correctIndex:1,explanation:'Window dressing concerns an apparent snapshot improvement without corresponding sustained change.',reviewSection:'acca-c1-manipulation'},
  {id:'acca-c1-q3',prompt:'Why can a major asset purchase near year end reduce ROCE?',options:['The asset is always impaired immediately','Closing capital can include the asset before a full period of related profit','Revenue must be removed from the ratio','Long-term debt is never capital employed'],correctIndex:1,explanation:'Numerator and denominator can reflect different periods of contribution.',reviewSection:'acca-c1-snapshot'},
  {id:'acca-c1-q4',prompt:'What is a key limitation of a consolidated group margin?',options:['It cannot be calculated','It may hide offsetting performance across different segments','Intragroup items are never eliminated','It contains only parent-company activity'],correctIndex:1,explanation:'Aggregation can conceal economically different component trends.',reviewSection:'acca-c1-group'},
  {id:'acca-c1-q5',prompt:'In the worked case, what do average inventory days indicate?',options:['50.7 days and clear improvement','105 days and no change','111.5 days and a 6.5-day worsening','220 days and a 115-day worsening'],correctIndex:2,explanation:'CU220,000 / CU720,000 × 365 = 111.5 days, compared with 105 previously.',reviewSection:'acca-c1-snapshot'}
 ],
 practiceExercises:[
  {id:'acca-c1-p1',question:'A seasonal company has closing inventory CU90,000, reliable average inventory CU180,000 and cost of sales CU900,000. Calculate both inventory-days figures.',hints:['Apply each inventory basis separately.','Multiply inventory divided by cost of sales by 365.'],answer:'Closing inventory days are 36.5; average inventory days are 73.0. The difference shows why the reporting-date snapshot may not represent the year.',explanation:'A full-year flow paired with an atypical closing balance can distort efficiency analysis.'},
  {id:'acca-c1-p2',question:'Repair: “The financial statements are audited, so last year’s 15% growth will definitely repeat.”',hints:['Separate reliability of historical reporting from forecasting certainty.','Name one item of forward-looking evidence.'],answer:'Audit status does not guarantee future growth. Use the historical 15% as evidence, then test it against orders, market conditions, capacity and changes in the business before forecasting.',explanation:'Historical reporting and future prediction answer different questions.'},
  {id:'acca-c1-p3',question:'A group margin is unchanged, but one segment rose from 8% to 14% while another fell from 18% to 10%. What should the analyst say?',hints:['Do not stop at the group average.','Consider segment size and mix.'],answer:'The stable group margin hides offsetting segment movements. Quantify each segment’s contribution and any change in mix before assessing performance.',explanation:'Consolidated aggregation can conceal important component economics.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Current C1 outcomes for history, manipulation, reporting-date balances and consolidated limitations.',reviewedOn},
  {id:'acca-interpretation',label:'ACCA · How to improve your answer to FR interpretation exam questions',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/technical-articles/interpretation-questions.html',supports:'Evidence-linked interpretation, ratio relationships and scenario-based explanation.',reviewedOn},
  {id:'conceptual-framework',label:'IFRS Foundation · Conceptual Framework for Financial Reporting',url:'https://www.ifrs.org/issued-standards/list-of-standards/conceptual-framework/',supports:'Objective, users and concepts supporting useful financial information.',reviewedOn},
  {id:'ifrs-10',label:'IFRS Foundation · IFRS 10 Consolidated Financial Statements',url:'https://www.ifrs.org/issued-standards/list-of-standards/ifrs-10-consolidated-financial-statements/',supports:'Single-economic-entity basis for consolidated financial statements.',reviewedOn}
 ]
};
export function localModelC1For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='C1'?ACCA_C1_MODEL_MODULE:null;}
export {ACCA_C1_MODEL_ID,ACCA_C1_MODEL_SLUG};
