import type {LessonModule,LessonSource} from './lessonModules.ts';
import {
 ENGLISH_P6_MODEL_ID,ENGLISH_P6_MODEL_SLUG,
 ENGLISH_P7_MODEL_ID,ENGLISH_P7_MODEL_SLUG,
 ENGLISH_P8_MODEL_ID,ENGLISH_P8_MODEL_SLUG,
 ENGLISH_P9_MODEL_ID,ENGLISH_P9_MODEL_SLUG,
 ENGLISH_P10_MODEL_ID,ENGLISH_P10_MODEL_SLUG,
 localEnglishCodeFor,
} from './localEnglishLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';

const reviewedOn='2026-09-23';
const source=(id:string,label:string,url:string,supports:string):LessonSource=>({id,label,url,supports,reviewedOn});
const ias8=source('ifrs-ias8','IFRS Foundation · IAS 8 Basis of Preparation of Financial Statements','https://www.ifrs.org/issued-standards/list-of-standards/ias-8-basis-of-preparation-of-financial-statements/','High-level distinction involving accounting estimates and prior-period errors; the lesson is not a complete accounting treatment.');
const controls=source('acca-controls','ACCA · Internal controls','https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f1/technical-articles/internal-controls.html','Control objectives, control activities and evidence vocabulary.');
const oecdTax=source('oecd-tax','OECD · Taxation','https://www.oecd.org/en/topics/policy-areas/taxation.html','International tax context and the need to identify the relevant jurisdiction and rule set.');
const revenueRpn=source('revenue-rpn','Revenue · Revenue Payroll Notification','https://www.revenue.ie/en/employing-people/becoming-an-employer-and-ongoing-obligations/employer-obligations-from-01-01-2019/revenue-payroll-notification.aspx','Current Irish RPN terminology and the need for the latest applicable notification.');
const revenuePay=source('revenue-pay','Revenue · Gross and taxable pay','https://www.revenue.ie/en/employing-people/what-constitutes-pay/what-are-gross-and-taxable-pay/index.aspx','Current distinction between gross and taxable pay; lesson amounts remain fictional supplied inputs.');
const ias7=source('ifrs-ias7','IFRS Foundation · IAS 7 Statement of Cash Flows','https://www.ifrs.org/issued-standards/list-of-standards/ias-7-statement-of-cash-flows/','Cash and cash-equivalent concepts and operating, investing and financing cash-flow categories.');
const fm=source('acca-fm','ACCA · Financial Management essentials','https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f9/session-cbe-introduction/financial-management-fm--essentials-on-one-page.html','Cash-flow planning, working capital and financial-risk vocabulary.');
const law=source('acca-law','ACCA · Corporate and Business Law technical articles','https://www.accaglobal.com/uk/en/student/exam-support-resources/fundamentals-exams-study-resources/f4/technical-articles.html','Contract-law learning context; the lesson does not determine a real contract’s legal effect.');
const compliance=source('acca-compliance','ACCA · Laws and regulations','https://www.accaglobal.com/uk/en/student/exam-support-resources/fundamentals-exams-study-resources/f8/technical-articles/laws-and-regulations.html','Language for identifying possible non-compliance, evidence and escalation.');

export const ENGLISH_P6_MODEL_MODULE:LessonModule={
 track:'english',lessonId:ENGLISH_P6_MODEL_ID,title:'Month-end: explain reconciliations, errors and estimates',
 goal:'Explain a month-end reconciliation by stating the control total, identified items, unresolved difference, accounting judgement and next action without forcing the balance or overstating the conclusion.',
 scope:'Original technical-English practice using fictional ledgers and supplied amounts. It is not an accounting opinion, a complete IAS 8 analysis, an audit procedure, a live close instruction or evidence that the underlying entries are correct.',
 sections:[
  {id:'eng-close-status',title:'1. Lead with status, amount and consequence',paragraphs:['A useful close update begins with the conclusion available now: “The receivables reconciliation has a 20,000 difference and is not ready for sign-off.”','Name the records and date: general ledger, subledger, bank statement, schedule or consolidation pack. “It does not reconcile” is incomplete without the two populations compared.','State the consequence proportionately: open investigation, proposed adjustment or missed deadline. Do not call every difference a misstatement before understanding it.'],supportPt:'Comece com status, valor, registros comparados e consequência. Diferença ainda não investigada não é automaticamente erro contábil.',sourceIds:['acca-controls']},
  {id:'eng-close-reconcile',title:'2. Build a bridge that accounts for the whole difference',paragraphs:['Move from one control total to the other and list signed reconciling items. A bridge must explain the entire gap or show the residual explicitly.','An identified item is not automatically cleared. “We found a duplicate journal of 12,000” describes evidence; reversal, approval and posting still need their own status.','Use “agrees to” only when the adjusted totals genuinely match. If 8,000 remains open, say “12,000 is explained; 8,000 remains unresolved.”'],supportPt:'Construa uma ponte com sinais corretos e mostre o residual. Item identificado ainda pode depender de aprovação e lançamento.',sourceIds:['acca-controls']},
  {id:'eng-close-judgement',title:'3. Distinguish error, estimate and missing evidence',paragraphs:['An error involves incorrect or omitted information; an estimate uses judgement under measurement uncertainty. The exact accounting treatment depends on the facts and applicable requirements.','A new invoice can be evidence relevant to an accrual without proving that the prior amount was an error. Ask what information was available when the estimate was made.','Use conditional language while the analysis is incomplete: “This may require an adjustment” or “We need to determine whether this is a current-period correction or a prior-period matter.”'],supportPt:'Diferencie informação incorreta de estimativa sob incerteza. A existência de informação nova não resolve sozinha o tratamento contábil.',sourceIds:['ifrs-ias8']},
  {id:'eng-close-action',title:'4. Close with entry, evidence, owner and deadline',paragraphs:['A complete action line says what is needed and by whom: “Maria will obtain the invoice support by 14:00; I will update the bridge and route any journal for approval.”','Separate proposed from posted: “We propose a 12,000 reversal” is not “We posted a 12,000 reversal.”','For escalation, include the decision required: “Please confirm whether we can hold sign-off until the residual is resolved.”'],supportPt:'Indique evidência, responsável, prazo e decisão necessária. Separe lançamento proposto, aprovado e contabilizado.',sourceIds:['acca-controls']},
 ],
 terms:[
  {term:'control total',meaning:'A total used as the reference point for a reconciliation.',pt:'total de controle',example:'The subledger control total is 1,230,000.'},
  {term:'reconciling item',meaning:'An identified item explaining part of a difference between records.',pt:'item de conciliação',example:'The duplicate journal is a reconciling item.'},
  {term:'residual difference',meaning:'The portion still unexplained after known items.',pt:'diferença residual',example:'A residual difference of 8,000 remains.'},
  {term:'accrual',meaning:'Recognition related to income or expense before cash settlement under the applicable accounting basis.',pt:'provisão por competência / accrual',example:'The team is reviewing the supporting basis for the accrual.'},
  {term:'estimate',meaning:'A monetary amount subject to measurement uncertainty.',pt:'estimativa',example:'The expected credit loss is an accounting estimate.'},
  {term:'sign-off',meaning:'Formal confirmation that a review or process is complete.',pt:'aprovação formal',example:'The reconciliation is not ready for sign-off.'},
 ],
 visual:{title:'Receivables reconciliation bridge',note:'Fictional amounts; identification does not equal posting approval.',headers:['Step','Amount','Status'],rows:[['General ledger','1,250,000','Control total'],['Less duplicate journal','(12,000)','Identified; reversal proposed'],['Residual difference','(8,000)','Unresolved'],['Subledger','1,230,000','Comparison total']],question:'Can the reconciliation be signed off after finding only the 12,000 item?',answer:'No. The bridge still has an unexplained residual of 8,000, and the proposed reversal has not necessarily been approved or posted.'},
 caseStudy:{title:'A close bridge that is only partly explained',scenario:['Fictional receivables GL balance: 1,250,000; subledger: 1,230,000.','A duplicate GL journal of 12,000 has been identified. A reversal is proposed but not approved or posted.','The remaining 8,000 has no confirmed cause. Supporting records are due from the process owner at 14:00.'],task:'Give a concise controller update with the bridge, accounting uncertainty, owner, deadline and sign-off decision.',hints:['Do not say the full 20,000 is resolved.','Keep proposed, approved and posted statuses separate.'],modelAnswer:'“The receivables reconciliation has a 20,000 difference: the GL is 1,250,000 and the subledger is 1,230,000. We identified a duplicate GL journal of 12,000 and have proposed a reversal, but it is not yet approved or posted. The remaining 8,000 is unresolved. The process owner will provide supporting records by 14:00; I will update the bridge and route any supported journal for approval. I recommend holding sign-off until the residual is resolved.”',reviewChecks:['Both control totals and the full difference are stated.','Only 12,000 is identified.','Journal status is accurate.','Owner, deadline and sign-off decision are explicit.'],transfer:'Adapt the update to a bank reconciliation with an outstanding deposit and one unknown withdrawal.'},
 checkpoint:[
  {id:'eng-close-q1',prompt:'Which opening gives the most useful status?',options:['There is an issue.','The receivables reconciliation has a 20,000 difference and is not ready for sign-off.','Close is difficult.','Everything may be wrong.'],correctIndex:1,explanation:'It states process, amount and current consequence.',reviewSection:'eng-close-status'},
  {id:'eng-close-q2',prompt:'A 20,000 difference includes one known 12,000 item. What remains?',options:['Nothing','8,000','12,000','32,000'],correctIndex:1,explanation:'20,000 less the identified 12,000 leaves an unresolved 8,000 residual.',reviewSection:'eng-close-reconcile'},
  {id:'eng-close-q3',prompt:'Which status is accurate before approval?',options:['The reversal was posted.','A 12,000 reversal is proposed.','The close is complete.','The full difference is cleared.'],correctIndex:1,explanation:'“Proposed” preserves the actual workflow state.',reviewSection:'eng-close-action'},
  {id:'eng-close-q4',prompt:'What should you ask before calling a changed estimate an error?',options:['Whether the number looks large.','What information was available when the estimate was made.','Whether the deadline is close.','Whether a manager dislikes it.'],correctIndex:1,explanation:'The distinction depends on facts, including information available at the relevant time.',reviewSection:'eng-close-judgement'},
  {id:'eng-close-q5',prompt:'When is “agrees to” appropriate?',options:['Whenever an item is proposed.','When the adjusted totals genuinely match.','When evidence is missing.','Before the bridge is calculated.'],correctIndex:1,explanation:'The phrase should reflect a completed numerical reconciliation.',reviewSection:'eng-close-reconcile'},
 ],
 practiceExercises:[
  {id:'eng-close-p1',question:'Write a status line for a bank-to-GL difference of 5,400 that remains open.',hints:['Name both records.','State sign-off status.'],answer:'The bank-to-GL reconciliation has an open difference of 5,400 and is not ready for sign-off.',explanation:'The sentence gives the comparison, amount and consequence.'},
  {id:'eng-close-p2',question:'Correct “We posted the entry” when it has only been drafted.',hints:['Use the true workflow status.','Do not imply approval.'],answer:'We drafted the entry and will submit it for approval.',explanation:'Drafting and approval are kept separate from posting.'},
  {id:'eng-close-p3',question:'Escalate an 8,000 residual and ask for a decision.',hints:['State what is unresolved.','Name the requested decision.'],answer:'An 8,000 residual remains unresolved. Please confirm whether sign-off should remain on hold while we obtain the support.',explanation:'The escalation links the fact to a specific decision.'},
 ],sources:[ias8,controls],
};

export const ENGLISH_P7_MODEL_MODULE:LessonModule={
 track:'english',lessonId:ENGLISH_P7_MODEL_ID,title:'Tax: explain facts, positions, exposure and evidence',
 goal:'Communicate a tax issue by fixing the jurisdiction, period, transaction and evidence, then separate the filing position, accounting impact and unresolved legal interpretation.',
 scope:'Original technical-English practice with a fictional cross-border service invoice. It does not provide tax or legal advice, select a withholding rate, determine residence, calculate a live liability or replace jurisdiction-specific review.',
 sections:[
  {id:'eng-tax-facts',title:'1. Anchor the issue in jurisdiction, period and transaction',paragraphs:['“This is a tax issue” is too broad. State the entity, jurisdiction, tax type, period and transaction being reviewed.','Distinguish invoice date, service period, payment date and filing period. Different rules may attach to different events, so do not collapse them into “the date”.','Describe the arrangement from documents before applying a label: parties, service, location, contract, invoice and payment flow.'],supportPt:'Fixe entidade, jurisdição, tributo, período e transação. Datas de contrato, serviço, fatura, pagamento e declaração não são intercambiáveis.',sourceIds:['oecd-tax']},
  {id:'eng-tax-position',title:'2. Separate fact, assumption and position',paragraphs:['A fact can be evidenced: “The supplier invoice is 100,000.” An assumption is provisional: “We currently assume the service was performed outside the customer jurisdiction.”','A filing position is the treatment the entity plans to apply; it should not be presented as settled law merely because it appeared in a prior return.','Use precise attribution: “The external adviser’s draft says…” rather than “The law says…” when the analysis is not final.'],supportPt:'Separe fato documentado, premissa, posição da empresa e conclusão jurídica. Atribua corretamente análises preliminares.',sourceIds:['oecd-tax']},
  {id:'eng-tax-exposure',title:'3. Quantify a scenario without manufacturing certainty',paragraphs:['State the base and rate only if both are supplied and applicable. Otherwise communicate the exposure qualitatively or as a scenario: “If withholding applies, the cash payment and filing need reassessment.”','Accounting provision, tax payable, cash payment, penalty and interest are different amounts. Do not combine them under the word “exposure” without a bridge.','Use ranges only when their basis is known. A wide range with unexplained endpoints is not stronger than an honest unknown.'],supportPt:'Só quantifique com base e regra sustentadas. Separe imposto, caixa, provisão, multa e juros.',sourceIds:['oecd-tax']},
  {id:'eng-tax-action',title:'4. Request evidence and protect the deadline',paragraphs:['List the evidence that resolves the actual question: executed contract, invoice, proof of service location, residence document, prior advice or filing record.','Name the owner and decision date: “Legal will confirm the contract wording by Wednesday; Tax will document the position before payment release.”','If timing is at risk, escalate the dependency rather than inventing a conclusion: “Payment is scheduled for Friday, but the withholding analysis remains open.”'],supportPt:'Peça evidência ligada à questão, defina responsável e prazo e escale a dependência antes do pagamento ou obrigação.',sourceIds:['oecd-tax','acca-controls']},
 ],
 terms:[
  {term:'jurisdiction',meaning:'The country or legal system whose rules may apply.',pt:'jurisdição',example:'We need to confirm the relevant jurisdiction.'},
  {term:'taxable event',meaning:'An event that may trigger a tax consequence under applicable rules.',pt:'fato gerador',example:'The payment date may be relevant to the taxable event.'},
  {term:'withholding',meaning:'Tax deducted from a payment and remitted under applicable rules.',pt:'retenção na fonte',example:'The withholding analysis is still open.'},
  {term:'filing position',meaning:'The tax treatment an entity adopts or proposes in a return.',pt:'posição adotada na declaração',example:'Document the filing position and its support.'},
  {term:'exposure',meaning:'Potential financial or compliance effect of an unresolved tax matter.',pt:'exposição',example:'The team has not yet quantified the exposure.'},
  {term:'subject to review',meaning:'Not final until a specified review is completed.',pt:'sujeito a revisão',example:'The conclusion is subject to local tax review.'},
 ],
 visual:{title:'Tax communication ladder',note:'Do not jump from an invoice to a legal conclusion.',headers:['Layer','Example','Status'],rows:[['Fact','Service invoice: 100,000','Documented'],['Assumption','Service performed abroad','Needs evidence'],['Position','No withholding proposed','Draft only'],['Decision','Release payment','Pending review']],question:'Which layer must remain open if service-location evidence is missing?',answer:'The assumption and therefore the proposed tax position and payment decision remain open.'},
 caseStudy:{title:'A cross-border service invoice before payment',scenario:['Fictional entity A received a 100,000 service invoice from supplier B in another jurisdiction.','The draft contract describes advisory services, but the executed copy and evidence of service location are missing.','Payment is scheduled for Friday. An adviser’s draft mentions possible withholding but gives no final conclusion or rate.'],task:'Prepare a tax status update that separates known facts, assumptions, exposure and the evidence/action required before payment.',hints:['Do not select a rate or claim that withholding applies.','Identify the payment deadline as a dependency.'],modelAnswer:'“Entity A has a 100,000 cross-border advisory-services invoice from supplier B, with payment scheduled for Friday. We have the draft contract and invoice, but not the executed agreement or evidence of where the services were performed. The adviser’s draft flags possible withholding but does not conclude whether it applies or identify a supported rate. The filing and cash positions therefore remain open. Legal will obtain the executed contract, Procurement will confirm service evidence and Tax will document the jurisdiction-specific conclusion before payment release.”',reviewChecks:['Entity, amount, transaction and deadline are clear.','Missing evidence is explicit.','No law or rate is invented.','Owners and release dependency are stated.'],transfer:'Adapt the update to an indirect-tax question on a digital-service invoice without assuming place-of-supply rules.'},
 checkpoint:[
  {id:'eng-tax-q1',prompt:'Which opening is sufficiently anchored?',options:['Tax is complicated.','Entity A is reviewing withholding on a 100,000 cross-border service invoice due Friday.','There may be a law.','The invoice exists.'],correctIndex:1,explanation:'It identifies entity, issue, transaction amount and timing.',reviewSection:'eng-tax-facts'},
  {id:'eng-tax-q2',prompt:'Which is an assumption rather than a documented fact?',options:['The invoice states 100,000.','The signed contract is attached.','We currently assume the service was performed abroad.','Payment is scheduled for Friday.'],correctIndex:2,explanation:'The wording explicitly marks a provisional understanding that needs evidence.',reviewSection:'eng-tax-position'},
  {id:'eng-tax-q3',prompt:'The adviser’s draft flags possible withholding but no rate. What may you safely say?',options:['Withholding definitely applies at 20%.','The withholding analysis remains open.','No tax can apply.','The payment is approved.'],correctIndex:1,explanation:'It reflects the evidence without inventing a conclusion or rate.',reviewSection:'eng-tax-exposure'},
  {id:'eng-tax-q4',prompt:'Which evidence is most directly relevant to the described service-location question?',options:['An unrelated payroll file.','Evidence showing where the contracted services were performed.','A marketing brochure.','A guessed percentage.'],correctIndex:1,explanation:'The requested evidence addresses the open factual assumption.',reviewSection:'eng-tax-action'},
  {id:'eng-tax-q5',prompt:'Which sentence protects the deadline honestly?',options:['Release payment and decide later.','Payment is scheduled for Friday, but the withholding analysis remains open.','The deadline proves no tax applies.','Silence confirms approval.'],correctIndex:1,explanation:'It exposes the dependency without manufacturing a decision.',reviewSection:'eng-tax-action'},
 ],
 practiceExercises:[
  {id:'eng-tax-p1',question:'Turn “The tax rate is 15%” into an open issue when no supported rate is available.',hints:['Do not keep the number.','Name the required review.'],answer:'The applicable withholding treatment and any rate remain subject to jurisdiction-specific review.',explanation:'The rewrite removes unsupported precision and states the unresolved work.'},
  {id:'eng-tax-p2',question:'Request three pieces of evidence for the fictional service invoice.',hints:['Include the executed contract.','Include evidence about the service.'],answer:'Please provide the executed contract, the final invoice and evidence showing where the services were performed.',explanation:'Each document connects to the described transaction and open assumption.'},
  {id:'eng-tax-p3',question:'Write a one-sentence payment escalation.',hints:['Name Friday.','State what is unresolved.'],answer:'Payment is scheduled for Friday, but Tax cannot clear release until the withholding analysis and supporting evidence are complete.',explanation:'The sentence makes the dependency and consequence visible.'},
 ],sources:[oecdTax,controls],
};

export const ENGLISH_P8_MODEL_MODULE:LessonModule={
 track:'english',lessonId:ENGLISH_P8_MODEL_ID,title:'Payroll: explain inputs, deductions, queries and controls',
 goal:'Reconcile supplied gross-to-net data, distinguish employee deductions from employer cost, investigate a pay query and communicate only the minimum necessary personal information.',
 scope:'Original technical-English practice with fictional supplied payroll amounts. It is not a payroll calculator, a live Irish tax computation, employee-specific advice or permission to disclose payroll data; current rates and treatment require validated inputs and applicable rules.',
 sections:[
  {id:'eng-pay-inputs',title:'1. Validate inputs before explaining the result',paragraphs:['Start with employee record, pay period, pay date, approved gross-pay inputs and the applicable tax instruction or payroll notification.','Gross pay, taxable pay and cash pay can differ. Do not use the terms interchangeably merely because they happen to match in a simple example.','When an input is missing, say what cannot yet be concluded: “We cannot explain the PAYE movement until we compare the applicable notification and approved inputs.”'],supportPt:'Valide vínculo, período, data, remuneração aprovada e instrução fiscal aplicável. Bruto, tributável e caixa podem diferir.',sourceIds:['revenue-rpn','revenue-pay']},
  {id:'eng-pay-bridge',title:'2. Keep employee net pay separate from employer cost',paragraphs:['A gross-to-net bridge subtracts employee cash deductions once. Employer payroll taxes or contributions belong in a separate employer-cost bridge.','Use supplied amounts rather than reverse-engineering rates from one payslip. A valid-looking percentage may be wrong for another employee, period or pay element.','State the boundary: “This reconciles the listed cash amounts; it does not validate the underlying tax calculation.”'],supportPt:'Concilie descontos do empregado uma vez e mantenha custo patronal separado. A aritmética não valida automaticamente o cálculo fiscal.',sourceIds:['revenue-pay']},
  {id:'eng-pay-query',title:'3. Answer the employee with known facts and a check plan',paragraphs:['Lead with the visible change: “Your gross pay is unchanged; the PAYE deduction is 60 higher.”','Do not guess the cause or promise a refund. Explain which records payroll will compare and when the employee will receive an update.','Use privacy-aware language. A manager may need status, not the employee’s full tax record or detailed personal deductions.'],supportPt:'Explique a mudança visível, o plano de verificação e o prazo. Não adivinhe causa, prometa reembolso ou exponha dados desnecessários.',sourceIds:['revenue-rpn','acca-controls']},
  {id:'eng-pay-control',title:'4. Correct with approval and an audit trail',paragraphs:['A correction should identify the approved input, affected run or submission, reviewer and employee communication.','“We found the cause” is not the same as “the correction is processed.” Keep investigation, approval, recalculation, submission and payment statuses distinct.','After resolution, record the control improvement if one is supported: better master-data review, exception report or independent approval.'],supportPt:'Separe causa identificada, ajuste aprovado, recálculo, envio e pagamento. Preserve trilha de auditoria e comunicação apropriada.',sourceIds:['acca-controls']},
 ],
 terms:[
  {term:'gross pay',meaning:'Total pay before employee deductions, subject to the applicable definition.',pt:'remuneração bruta',example:'The fictional gross cash pay is 4,000.'},
  {term:'taxable pay',meaning:'Pay amount subject to a particular tax calculation under applicable rules.',pt:'remuneração tributável',example:'Taxable pay may differ from cash gross pay.'},
  {term:'net pay',meaning:'Cash payable after the relevant employee deductions and adjustments.',pt:'remuneração líquida',example:'The listed deductions leave net pay of 3,140.'},
  {term:'deduction',meaning:'Amount subtracted from employee pay.',pt:'desconto',example:'PAYE is shown as an employee deduction in the example.'},
  {term:'payroll notification',meaning:'Applicable tax instruction retrieved for payroll processing in the relevant system.',pt:'notificação fiscal da folha',example:'Check the latest applicable payroll notification.'},
  {term:'audit trail',meaning:'Record showing inputs, changes, approvals and processing history.',pt:'trilha de auditoria',example:'The correction must retain an audit trail.'},
 ],
 visual:{title:'Two payroll bridges',note:'Fictional supplied amounts; no live tax rate is implied.',headers:['Item','Amount','Bridge'],rows:[['Gross cash pay','4,000','Employee cash'],['Employee deductions','(860)','Employee cash'],['Net cash pay','3,140','Employee receives'],['Employer contribution','440','Separate employer cost']],question:'What is the illustrated employer cost before other costs?',answer:'4,440. The employer contribution is added to employer cost, not deducted again from employee net pay.'},
 caseStudy:{title:'Same gross pay, lower net pay',scenario:['Fictional current gross cash pay: 4,000. Supplied deductions: PAYE 500, USC 80, employee PRSI 160 and pension 120.','Net pay is therefore 3,140. A separate employer contribution of 440 gives illustrated employer cost of 4,440 before other costs.','Last period PAYE was 440 and all other listed amounts were unchanged. The cause of the 60 increase has not been established.'],task:'Reconcile net pay and employer cost, then draft a concise employee response and investigation plan.',hints:['Do not subtract the employer contribution from employee cash.','Identify the 60 movement without promising its correction.'],modelAnswer:'“The listed employee deductions total 860, so net cash pay is 3,140. The separate employer contribution of 440 produces an illustrated employer cost of 4,440 before other costs. Your gross pay is unchanged, but PAYE is 60 higher than last period. Payroll will compare the applicable notification, approved inputs and calculation audit trail, then update you by tomorrow. We cannot confirm the cause or any correction before that review.”',reviewChecks:['Net pay is 3,140.','Employer cost is 4,440 and remains separate.','The known movement is 60.','Cause, correction and refund remain unconfirmed.'],transfer:'Explain the same issue to a manager without revealing the employee’s detailed deductions.'},
 checkpoint:[
  {id:'eng-pay-q1',prompt:'What is net pay from the supplied amounts?',options:['2,700','3,140','3,560','4,440'],correctIndex:1,explanation:'4,000 − 500 − 80 − 160 − 120 = 3,140.',reviewSection:'eng-pay-bridge'},
  {id:'eng-pay-q2',prompt:'Where does the separate 440 employer contribution belong?',options:['As another employee deduction.','In the employer-cost bridge.','As employee net pay.','Nowhere.'],correctIndex:1,explanation:'It is part of employer cost, not a second deduction from employee cash.',reviewSection:'eng-pay-bridge'},
  {id:'eng-pay-q3',prompt:'What fact is established about the period change?',options:['The notification is wrong.','A refund is due.','PAYE is 60 higher while the listed gross and other deductions are unchanged.','Employer cost caused the net movement.'],correctIndex:2,explanation:'The arithmetic identifies the changed line but not its cause.',reviewSection:'eng-pay-query'},
  {id:'eng-pay-q4',prompt:'Which reply protects accuracy?',options:['A refund is guaranteed.','We will compare the applicable notification, inputs and audit trail before confirming the cause.','Your tax record is definitely wrong.','No review is needed.'],correctIndex:1,explanation:'It promises a check, not an unsupported outcome.',reviewSection:'eng-pay-query'},
  {id:'eng-pay-q5',prompt:'Which status must remain distinct from “cause identified”?',options:['Correction processed.','Question received.','Payslip viewed.','Employee name known.'],correctIndex:0,explanation:'Finding the cause does not prove the correction was approved, calculated, submitted or paid.',reviewSection:'eng-pay-control'},
 ],
 practiceExercises:[
  {id:'eng-pay-p1',question:'Reconcile net pay from gross 3,500 and supplied employee deductions of 420, 70, 140 and 105.',hints:['Subtract each once.','Do not add employer cost.'],answer:'Net pay is 2,765: 3,500 − 420 − 70 − 140 − 105.',explanation:'The bridge uses only the listed employee cash deductions.'},
  {id:'eng-pay-p2',question:'Write a manager update without listing private deductions.',hints:['State status and timing.','Avoid personal detail.'],answer:'Payroll is reviewing an employee pay variance against the approved inputs and applicable notification and will provide a status update tomorrow.',explanation:'The manager receives operational status without unnecessary payroll details.'},
  {id:'eng-pay-p3',question:'Correct “The employee refund is complete” when only recalculation is approved.',hints:['Use the true status.','Leave payment open.'],answer:'The recalculation has been approved; processing and any resulting payment are still pending.',explanation:'Approval is kept separate from completed processing and cash settlement.'},
 ],sources:[revenueRpn,revenuePay,controls],
};

export const ENGLISH_P9_MODEL_MODULE:LessonModule={
 track:'english',lessonId:ENGLISH_P9_MODEL_ID,title:'Treasury: communicate cash, forecasts and liquidity risk',
 goal:'Explain current cash, availability, forecast movements, liquidity risk and payment controls without treating forecast receipts as cash or confusing accounting profit with liquidity.',
 scope:'Original technical-English practice with fictional supplied amounts. It is not an investment recommendation, banking instruction, hedge decision, cash-flow-statement preparation or live liquidity assessment.',
 sections:[
  {id:'eng-treasury-position',title:'1. Separate bank balance, available cash and cash equivalents',paragraphs:['A bank balance may include restricted or unavailable amounts. State gross balance, restrictions and the resulting amount available for operations.','Cash equivalents have specific characteristics under the applicable reporting basis; do not call every short-term investment “cash” for convenience.','Quote the as-of time and currency: “Available EUR cash at 09:00 is 2.0 million.” Treasury positions can change during the day.'],supportPt:'Separe saldo bancário, valores restritos e caixa disponível. Informe moeda e horário da posição.',sourceIds:['ifrs-ias7']},
  {id:'eng-treasury-forecast',title:'2. Label forecast inflows and outflows honestly',paragraphs:['A forecast is a time-bound view based on assumptions. Distinguish confirmed payments, expected receipts and scenarios.','Do not add an expected receipt to current cash when answering “What is available now?” Present current position and projected closing separately.','Show sensitivity to the uncertain driver: “Closing cash is 1.3 million if the 0.6 million receipt arrives; otherwise it is 0.7 million.”'],supportPt:'Previsão não é saldo atual. Separe pagamentos confirmados, recebimentos esperados e cenários.',sourceIds:['acca-fm']},
  {id:'eng-treasury-risk',title:'3. Explain liquidity and market exposure precisely',paragraphs:['Liquidity risk concerns the ability to meet obligations when due; profitability does not itself guarantee available cash.','An FX exposure needs currency, amount, timing and transaction basis. “We have currency risk” is not enough for a decision.','A hedge proposal must remain a proposal until the authorised decision and execution are evidenced. Do not imply that a forecast or conversation completed a trade.'],supportPt:'Descreva risco de liquidez e exposição cambial com valor, moeda e prazo. Proposta de hedge não é operação executada.',sourceIds:['ifrs-ias7','acca-fm']},
  {id:'eng-treasury-control',title:'4. Communicate payment control and escalation',paragraphs:['For a payment, name beneficiary validation, invoice or instruction support, approval status, value date and release status.','Urgency does not remove segregation of duties. Escalate the business consequence and the control dependency together.','Close with the decision needed: prioritise, fund, delay, validate or approve — and identify who has authority.'],supportPt:'Inclua validação, suporte, aprovação, data-valor e status de liberação. Urgência não elimina segregação de funções.',sourceIds:['acca-controls','acca-fm']},
 ],
 terms:[
  {term:'available cash',meaning:'Cash that can currently be used, after relevant restrictions.',pt:'caixa disponível',example:'Available cash is 2.0 million after the restriction.'},
  {term:'restricted cash',meaning:'Cash whose use is limited by an arrangement or requirement.',pt:'caixa restrito',example:'The 0.4 million deposit is restricted in the example.'},
  {term:'cash forecast',meaning:'Projection of cash inflows, outflows and balances over a period.',pt:'previsão de caixa',example:'The forecast includes an expected customer receipt.'},
  {term:'liquidity risk',meaning:'Risk of difficulty meeting obligations when they fall due.',pt:'risco de liquidez',example:'The delayed receipt increases short-term liquidity risk.'},
  {term:'value date',meaning:'Date on which a payment or receipt takes financial effect.',pt:'data-valor',example:'Confirm the value date before release.'},
  {term:'release',meaning:'Authorised execution step for a payment.',pt:'liberação',example:'Approval exists, but payment release is still pending.'},
 ],
 visual:{title:'Current cash versus projected closing',note:'Fictional EUR millions; expected receipt is not current cash.',headers:['Layer','Amount','Status'],rows:[['Bank balance','2.4','Current'],['Less restricted amount','(0.4)','Unavailable'],['Available cash','2.0','Current at 09:00'],['Projected closing','1.3','If 0.6 receipt arrives']],question:'What is projected closing cash if the expected 0.6 receipt does not arrive and 1.3 of payments are made?',answer:'0.7 million: 2.0 available cash less 1.3 confirmed payments.'},
 caseStudy:{title:'A cash position with one uncertain receipt',scenario:['Fictional bank balance at 09:00: EUR 2.4 million, including EUR 0.4 million restricted.','Confirmed same-day payments: EUR 1.3 million. Expected customer receipt: EUR 0.6 million, not yet credited.','One urgent payment is approved but beneficiary validation and release remain pending.'],task:'Give a treasury update with current available cash, two closing scenarios, liquidity implication and the control dependency.',hints:['Do not add the expected receipt to available cash.','Approval is not the same as validated release.'],modelAnswer:'“At 09:00, the bank balance is EUR 2.4 million, of which EUR 0.4 million is restricted, leaving EUR 2.0 million available. After confirmed payments of EUR 1.3 million, closing cash would be EUR 0.7 million without the expected receipt or EUR 1.3 million if the EUR 0.6 million receipt arrives. The urgent payment is approved, but beneficiary validation and release are pending. We need confirmation of the receipt timing and completion of the control before deciding whether to reprioritise payments.”',reviewChecks:['Available cash is 2.0 million.','Both 0.7 and 1.3 scenarios are correct.','The expected receipt is not treated as current cash.','Approval, validation and release remain distinct.'],transfer:'Add a USD supplier payment and describe the FX exposure without proposing a hedge amount.'},
 checkpoint:[
  {id:'eng-treasury-q1',prompt:'What is current available cash in the case?',options:['0.7m','1.3m','2.0m','2.4m plus 0.6m'],correctIndex:2,explanation:'2.4m bank balance less 0.4m restricted equals 2.0m available.',reviewSection:'eng-treasury-position'},
  {id:'eng-treasury-q2',prompt:'Can the expected 0.6m receipt be described as current available cash?',options:['Yes, because it is forecast.','No, it has not been credited.','Yes, if management wants it.','Always.'],correctIndex:1,explanation:'Forecast inflow and current cash are different facts.',reviewSection:'eng-treasury-forecast'},
  {id:'eng-treasury-q3',prompt:'What is closing cash without the receipt?',options:['0.7m','1.3m','2.0m','2.6m'],correctIndex:0,explanation:'2.0m available less 1.3m payments equals 0.7m.',reviewSection:'eng-treasury-forecast'},
  {id:'eng-treasury-q4',prompt:'Which details make an FX exposure actionable?',options:['Only “currency risk”.','Currency, amount, timing and transaction basis.','The employee’s opinion.','A generic headline.'],correctIndex:1,explanation:'Those details define the exposure that needs assessment.',reviewSection:'eng-treasury-risk'},
  {id:'eng-treasury-q5',prompt:'The urgent payment is approved. What can still remain pending?',options:['Beneficiary validation and release.','The existence of currency.','Every control is automatically complete.','Nothing by definition.'],correctIndex:0,explanation:'Approval is one status in the controlled payment flow.',reviewSection:'eng-treasury-control'},
 ],
 practiceExercises:[
  {id:'eng-treasury-p1',question:'Calculate available cash from 5.0m bank balance and 0.8m restricted.',hints:['Subtract the restriction.','Label the result as current.'],answer:'Current available cash is 4.2 million.',explanation:'The restricted amount is excluded from operational availability.'},
  {id:'eng-treasury-p2',question:'Write two closing scenarios from 4.2m available, 3.0m payments and 1.1m expected receipt.',hints:['One scenario includes the receipt.','One excludes it.'],answer:'Closing cash is 1.2 million without the receipt or 2.3 million if the 1.1 million receipt arrives.',explanation:'The scenarios expose the uncertain inflow rather than hiding it in one figure.'},
  {id:'eng-treasury-p3',question:'Correct “The payment is done” when it is approved but not released.',hints:['Name both statuses.','Do not imply execution.'],answer:'The payment is approved, but release is still pending.',explanation:'The statement preserves the real control status.'},
 ],sources:[ias7,fm,controls],
};

export const ENGLISH_P10_MODEL_MODULE:LessonModule={
 track:'english',lessonId:ENGLISH_P10_MODEL_ID,title:'Contracts and compliance: identify obligations and escalate risk',
 goal:'Read a clause for actor, obligation, condition and timing; describe a possible compliance issue without giving unsupported legal advice; and escalate the evidence and decision required.',
 scope:'Original technical-English practice with fictional contract wording. It is not legal advice, contract interpretation for a real agreement, a conclusion that a breach occurred or a substitute for qualified counsel and applicable law.',
 sections:[
  {id:'eng-contract-parse',title:'1. Parse the clause before paraphrasing it',paragraphs:['Identify who must or may act, what action is required, any condition, timing and defined term. Small words such as “may”, “must”, “within” and “unless” can change the meaning.','Preserve the unit: “within five business days after month-end” is not automatically “by calendar day five”.','Quote only the necessary phrase, then paraphrase it and mark uncertainty. Do not rewrite the clause as a stronger promise.'],supportPt:'Identifique sujeito, obrigação, condição, prazo e termo definido. Preserve palavras e unidades que mudam o sentido.',sourceIds:['acca-law']},
  {id:'eng-contract-status',title:'2. Separate contractual wording from operational status',paragraphs:['The contract may require a report; operations must still establish whether the triggering condition occurred and whether delivery was completed.','A missing internal tracker entry does not prove non-delivery, and a sent email does not necessarily prove contractually compliant delivery. Gather the agreed evidence.','Use “possible missed obligation” while facts remain open, not “breach” as a settled legal conclusion.'],supportPt:'Cláusula, ocorrência do gatilho e evidência de cumprimento são camadas diferentes. Não declare violação antes da análise adequada.',sourceIds:['acca-law','acca-compliance']},
  {id:'eng-contract-risk',title:'3. Describe risk without performing the lawyer’s job',paragraphs:['State the commercial or control consequence that management needs to understand: delayed service, disputed fee, reporting failure or need for notice.','Attribute interpretation: “Legal’s preliminary view is…” and name whether it is draft or final. Avoid “The contract definitely means…” when counsel has not concluded.','Materiality can have contractual, financial, regulatory or operational meanings. Name the meaning intended rather than assuming one universal threshold.'],supportPt:'Descreva consequência comercial e de controle, atribua a interpretação e especifique o sentido de materialidade.',sourceIds:['acca-compliance','acca-law']},
  {id:'eng-contract-action',title:'4. Escalate with evidence, owner and decision',paragraphs:['A useful escalation attaches the executed agreement, relevant clause, timeline, delivery evidence and open question.','Name who owns factual verification and who provides legal interpretation. Finance can quantify an effect without issuing a legal conclusion.','Ask for a decision by a real deadline: “Please confirm by 15:00 whether notice is required and who is authorised to send it.”'],supportPt:'Escale com contrato, cláusula, cronologia, evidência e pergunta aberta. Separe dono do fato, análise jurídica e quantificação financeira.',sourceIds:['acca-compliance','acca-controls']},
 ],
 terms:[
  {term:'clause',meaning:'A distinct provision within a contract or legal document.',pt:'cláusula',example:'Clause 4 sets the reporting deadline.'},
  {term:'obligation',meaning:'An action a party is required to perform under the applicable arrangement.',pt:'obrigação',example:'The team is verifying whether the obligation was triggered.'},
  {term:'condition',meaning:'An event or requirement on which another right or duty depends.',pt:'condição',example:'Access to the data is a stated condition.'},
  {term:'business day',meaning:'A working day as defined or interpreted for the agreement.',pt:'dia útil',example:'The clause says five business days, not five calendar days.'},
  {term:'breach',meaning:'Failure to comply with a legal or contractual duty, subject to the applicable analysis.',pt:'violação / inadimplemento',example:'Do not conclude that a breach occurred before review.'},
  {term:'escalate',meaning:'Raise an issue to the person with authority or expertise to decide it.',pt:'escalar',example:'Escalate the open interpretation to Legal.'},
 ],
 visual:{title:'From clause to decision',note:'Text, facts, interpretation and action must not collapse into one sentence.',headers:['Layer','Question','Owner example'],rows:[['Clause','What does the executed text say?','Contract owner'],['Facts','Did the trigger and delivery occur?','Operations'],['Interpretation','What is the legal effect?','Legal counsel'],['Impact/action','What decision is needed?','Management']],question:'Who should determine the legal effect in this fictional workflow?',answer:'The appropriate Legal reviewer; Operations and Finance supply facts and quantified impacts without replacing legal interpretation.'},
 caseStudy:{title:'A reporting deadline with incomplete evidence',scenario:['A fictional executed contract says: “Supplier shall deliver the monthly service report within five business days after month-end, provided Customer has supplied the required data.”','The team assumed the deadline was calendar day five. The customer-data handover date is not documented, and the delivery tracker is blank.','An email draft exists, but sent-message evidence and Legal’s interpretation are missing.'],task:'Prepare an escalation that quotes the key wording, separates open facts from interpretation and requests a decision.',hints:['Do not conclude that the supplier breached the contract.','Identify the customer-data condition and business-day wording.'],modelAnswer:'“Clause 4 requires the supplier to deliver the monthly service report within five business days after month-end, provided the customer has supplied the required data. The team planned around calendar day five, but we have not documented when the customer data was supplied. The delivery tracker is blank, and we have found a draft email but no sent-message evidence. We therefore have a possible missed obligation, not a confirmed breach. Operations will establish the data and delivery timeline; Legal should confirm the deadline interpretation and whether any notice is required.”',reviewChecks:['The key wording is preserved accurately.','Business days and calendar days are not confused.','Missing evidence and the condition are visible.','No unsupported breach conclusion is made.'],transfer:'Apply the same four-layer analysis to an approval clause containing “may” rather than “must”.'},
 checkpoint:[
  {id:'eng-contract-q1',prompt:'What is the correct paraphrase of “within five business days”?',options:['Always by calendar day five.','No later than the end of the five-business-day period, subject to the clause and definitions.','Whenever convenient.','Exactly five hours later.'],correctIndex:1,explanation:'It preserves the unit and avoids inventing a calendar date.',reviewSection:'eng-contract-parse'},
  {id:'eng-contract-q2',prompt:'What fact is open in the case?',options:['The clause exists.','When the customer supplied the required data.','Month-end occurs.','The word supplier is present.'],correctIndex:1,explanation:'That timing may affect whether the stated condition and deadline were triggered.',reviewSection:'eng-contract-status'},
  {id:'eng-contract-q3',prompt:'A delivery tracker is blank. What does that prove?',options:['A breach definitely occurred.','Only that the tracker contains no entry; delivery needs other evidence.','The contract is void.','Legal approved the conclusion.'],correctIndex:1,explanation:'Absence from one internal record is not by itself the full contractual fact pattern.',reviewSection:'eng-contract-status'},
  {id:'eng-contract-q4',prompt:'Which phrase preserves the current uncertainty?',options:['Confirmed breach.','Possible missed obligation pending factual and legal review.','No risk exists.','Finance has issued legal advice.'],correctIndex:1,explanation:'It communicates the concern without claiming a legal conclusion.',reviewSection:'eng-contract-risk'},
  {id:'eng-contract-q5',prompt:'What belongs in the escalation?',options:['Only an angry summary.','Executed agreement, clause, timeline, delivery evidence and open question.','A rewritten clause that is easier for Finance.','An invented notice.'],correctIndex:1,explanation:'Those materials allow the appropriate reviewer to assess the issue.',reviewSection:'eng-contract-action'},
 ],
 practiceExercises:[
  {id:'eng-contract-p1',question:'Extract actor, action and timing from: “Buyer must approve the invoice within three business days.”',hints:['Name the actor.','Preserve “must” and “business days”.'],answer:'Actor: Buyer. Required action: approve the invoice. Timing: within three business days.',explanation:'The extraction keeps the operative words intact.'},
  {id:'eng-contract-p2',question:'Replace “The supplier breached the contract” when delivery evidence is incomplete.',hints:['Use “possible”.','Name the missing review.'],answer:'There is a possible missed delivery obligation, subject to factual verification and legal review.',explanation:'The rewrite raises the risk without issuing an unsupported legal conclusion.'},
  {id:'eng-contract-p3',question:'Request a legal decision by 15:00 on whether notice is required.',hints:['Name the decision.','Name the authority question.'],answer:'Please confirm by 15:00 whether contractual notice is required and who is authorised to send it.',explanation:'The request gives the reviewer a bounded decision and deadline.'},
 ],sources:[law,compliance,controls],
};

export const ENGLISH_TECHNICAL_MONTH_MODULES=[
 ENGLISH_P6_MODEL_MODULE,
 ENGLISH_P7_MODEL_MODULE,
 ENGLISH_P8_MODEL_MODULE,
 ENGLISH_P9_MODEL_MODULE,
 ENGLISH_P10_MODEL_MODULE,
] as const;

export function localEnglishTechnicalMonthExpansionFor(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{
 const code=localEnglishCodeFor(track,lesson);
 if(code==='P6'&&lesson.slug===ENGLISH_P6_MODEL_SLUG)return ENGLISH_P6_MODEL_MODULE;
 if(code==='P7'&&lesson.slug===ENGLISH_P7_MODEL_SLUG)return ENGLISH_P7_MODEL_MODULE;
 if(code==='P8'&&lesson.slug===ENGLISH_P8_MODEL_SLUG)return ENGLISH_P8_MODEL_MODULE;
 if(code==='P9'&&lesson.slug===ENGLISH_P9_MODEL_SLUG)return ENGLISH_P9_MODEL_MODULE;
 if(code==='P10'&&lesson.slug===ENGLISH_P10_MODEL_SLUG)return ENGLISH_P10_MODEL_MODULE;
 return null;
}
