import type {LessonModule} from './lessonModules.ts';
import {ACCA_B9_MODEL_ID,ACCA_B9_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_B9_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'22–28',segments:['Held-for-sale and discontinued-operation boundaries.','Policy, estimate and prior-period error timing.','A narrated basic and diluted EPS bridge.','IFRS S1 objective and four core content areas.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_B9_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask whether the issue changes measurement, presentation, comparative information or non-financial disclosure before calculating.',supportedPractice:'Classify the reporting issue first, then apply its timing and measurement rule; for EPS, reconcile numerator and denominator separately.',misconception:'A management intention to sell does not by itself satisfy IFRS 5, and a new estimate is not a prior-period error merely because an earlier estimate changed.',transfer:'Change the disposal facts, share date or potential ordinary shares and ask the learner to reassess one conclusion.',close:'Recap IFRS 5, IAS 8, EPS and IFRS S1 without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_B9_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_B9_MODEL_ID,title:'ACCA FR B9 · Reporting financial and non-financial performance',
 goal:'Account for held-for-sale assets and discontinued operations, distinguish IAS 8 changes and errors, calculate basic and diluted EPS, and explain the IFRS S1 reporting core.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level B9 mapping must be checked against the exact selected exam sitting before publication. It is original teaching material, not ACCA approval, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-b9-disposals',title:'1. Apply the held-for-sale and discontinued-operation boundaries',paragraphs:[
   'Classify a non-current asset or disposal group as held for sale when its carrying amount will be recovered principally through sale rather than continuing use. The asset must be available for immediate sale in its present condition, subject only to usual terms, and the sale must be highly probable. This normally requires an appropriate management commitment, an active programme to locate a buyer, reasonable pricing and an expectation of completion within one year, subject to limited exceptions.',
   'Immediately before classification, update measurement under the normally applicable Standards. Then measure the held-for-sale asset or disposal group at the lower of carrying amount and fair value less costs to sell, recognise any resulting loss, stop depreciation and present qualifying assets and related disposal-group liabilities separately. A plan alone is insufficient, and the held-for-sale label is not a way to postpone an impairment that already exists.',
   'A discontinued operation is a disposed component, or one classified as held for sale, that represents a separate major line of business or geographical area, is part of a single coordinated plan to dispose of one, or is a subsidiary acquired exclusively for resale. Present its post-tax result separately so users can distinguish continuing performance. Not every asset sale or closed location meets that strategic component threshold.'
  ],supportPt:'Held for sale exige recuperação principalmente pela venda, disponibilidade imediata e venda altamente provável. Mensure pelo menor entre carrying amount e fair value less costs to sell, pare a depreciação e separe discontinued operations apenas quando houver componente estratégico qualificável.',sourceIds:['ifrs-5','acca-fr-syllabus']},
  {id:'acca-b9-changes',title:'2. Separate material items, policies, estimates and errors',paragraphs:[
   'Material information must not be obscured by aggregation. When an item of income or expense is material, disclose its nature and amount in the financial statements in a way that helps users understand performance. Separate disclosure does not create an extraordinary category. The judgement considers size, nature and context, so a smaller restructuring or litigation item may warrant explanation even when it is not the largest movement in the period.',
   'An accounting policy is a principle, basis, convention, rule or practice used to prepare financial statements. Apply a voluntary policy change only when it provides reliable and more relevant information, and normally apply the change retrospectively by adjusting opening equity and comparatives as if the new policy had always applied, unless impracticable. Follow specific transitional provisions when a new or amended Standard supplies them.',
   'An accounting estimate changes because new information or developments alter measurement uncertainty; recognise its effect prospectively in the current and, when relevant, future periods. A material prior-period error arises from failing to use, or misusing, reliable information available when earlier statements were authorised and is normally corrected retrospectively by restating comparatives. Do not use hindsight to relabel a good-faith estimate as an error.'
  ],supportPt:'Item material requer apresentação ou divulgação útil, não uma categoria extraordinária. Mudança de policy e erro material normalmente são retrospectivos; mudança de estimate por informação nova é prospectiva.',sourceIds:['ifrs-18','ias-8']},
  {id:'acca-b9-eps',title:'3. Build basic and diluted earnings per share carefully',paragraphs:[
   'Basic EPS divides profit attributable to ordinary equity holders by the weighted-average ordinary shares outstanding. Time-weight a full-market-value issue from its issue date. A bonus issue changes resources per share without adding resources, so restate the share count retrospectively for all periods presented. A rights issue commonly contains both a full-price and bonus element, requiring the supplied theoretical ex-rights relationship before time weighting.',
   'Diluted EPS shows the potential reduction in EPS if dilutive potential ordinary shares become ordinary shares. For convertible debt, increase the numerator by the after-tax finance cost saved and increase the denominator by shares issued on assumed conversion. For options or warrants, use the treasury-share logic: only the incremental shares beyond those assumed purchasable at average market price dilute. Exclude instruments that are antidilutive.',
   'Present basic and diluted EPS with equal prominence for profit or loss attributable to ordinary equity holders, and give continuing-operation measures when applicable. A discontinued operation also requires per-share information in the statement or notes. Keep earnings and share adjustments consistent: do not add potential shares without the corresponding numerator adjustment where one exists, and do not include a conversion that increases rather than reduces EPS.'
  ],supportPt:'Basic EPS usa lucro atribuível e média ponderada de ações. Bonus issue é retrospectivo; emissão a valor de mercado é ponderada pelo tempo. Diluted EPS ajusta numerator e denominator apenas para instrumentos dilutivos.',sourceIds:['ias-33']},
  {id:'acca-b9-sustainability',title:'4. Explain the IFRS S1 objective and core content',paragraphs:[
   'IFRS S1 requires disclosure of sustainability-related risks and opportunities that could reasonably be expected to affect an entity’s prospects: its cash flows, access to finance or cost of capital over the short, medium or long term. The objective is decision-useful information for users of general purpose financial reports who provide resources to the entity. It is not a catalogue of every environmental or social fact regardless of financial relevance.',
   'The core content has four connected areas. Governance explains oversight, controls and procedures. Strategy explains how risks and opportunities affect the business model, decision-making and prospects. Risk management explains processes to identify, assess, prioritise and monitor them. Metrics and targets explain performance, including progress against targets set by the entity or required by law or regulation.',
   'Useful sustainability-related financial information is connected with the financial statements and uses consistent assumptions where relevant. Reporting should let users see relationships rather than treating sustainability disclosure as a detached promotional story. At FR level, focus on IFRS S1’s objective, scope and core content: identify a prospect-relevant risk or opportunity, then explain the governance, strategic, risk-process and performance information users need.'
  ],supportPt:'IFRS S1 foca riscos e oportunidades de sustentabilidade que afetam perspectivas financeiras. O core content conecta governance, strategy, risk management e metrics and targets para usuários dos relatórios financeiros de propósito geral.',sourceIds:['ifrs-s1']}
 ],
 terms:[
  {term:'Held for sale',meaning:'Classification when recovery is expected principally through a highly probable sale rather than continuing use.',pt:'Mantido para venda',example:'A committed and actively marketed disposal group may qualify.'},
  {term:'Discontinued operation',meaning:'Qualifying disposed or held-for-sale component representing a major line, geography or specified disposal plan.',pt:'Operação descontinuada',example:'Its post-tax result is presented separately from continuing operations.'},
  {term:'Retrospective application',meaning:'Applying a policy or correction as if it had always been applied, subject to requirements.',pt:'Aplicação retrospectiva',example:'Comparatives may be restated for a material prior-period error.'},
  {term:'Weighted-average shares',meaning:'Ordinary shares outstanding weighted for the portion of the reporting period.',pt:'Média ponderada de ações',example:'A full-market issue late in the year receives only a partial weighting.'},
  {term:'Diluted EPS',meaning:'EPS reflecting dilutive potential ordinary shares on an assumed-conversion basis.',pt:'Lucro diluído por ação',example:'Convertible debt can adjust both earnings and the share denominator.'},
  {term:'Sustainability-related risk or opportunity',meaning:'Matter that could reasonably affect cash flows, access to finance or cost of capital over time.',pt:'Risco ou oportunidade de sustentabilidade',example:'A supply constraint may affect strategy and future cash flows.'}
 ],
 visual:{title:'Basic and diluted EPS bridge',note:'Original calculation; fictional CU000 amounts and share counts. Tax rate is 25%.',headers:['Measure','Numerator CU000','Shares 000 / EPS'],rows:[['Basic continuing operations','900','2,150 / 41.86c'],['Convertible adjustment','+45','+400'],['Diluted continuing operations','945','2,550 / 37.06c'],['Discontinued loss per basic share','(120)','2,150 / (5.58c)']],question:'Why is CU45, not CU60, added back for the convertible debt?',answer:'The assumed conversion removes CU60 finance cost but also removes its 25% tax effect, so the numerator rises by CU45.'},
 caseStudy:{title:'Sale classification, discontinued result and EPS',scenario:['On 31 December, a board-committed division is available for immediate sale, actively marketed at a reasonable price and expected to sell within six months. Its carrying amount after normal IFRS measurement is CU500,000 and fair value less costs to sell is CU460,000. The division is a separate major line of business and made a post-tax loss of CU120,000.','Continuing profit attributable to ordinary shareholders is CU900,000. Two million ordinary shares were outstanding from 1 January, and 600,000 shares were issued at full market value on 1 October.','Convertible debt has annual finance cost CU60,000, tax rate 25% and would create 400,000 ordinary shares on conversion. Assume the conversion is dilutive.'],task:'Determine the IFRS 5 measurement and presentation, then calculate basic and diluted continuing EPS and basic EPS for the discontinued loss.',hints:['Use the lower IFRS 5 measurement and stop depreciation.','Time-weight the October full-market issue for three months.'],modelAnswer:'The division meets the held-for-sale conditions and is measured at CU460,000, producing a CU40,000 loss from its CU500,000 carrying amount. Depreciation stops and the qualifying assets and liabilities are presented separately. Because it is a separate major line, its CU120,000 post-tax loss is presented as a discontinued operation. Weighted-average shares are 2,150,000: 2,000,000 + 600,000 × 3/12. Basic continuing EPS is 41.86 cents (CU900,000 / 2,150,000). The convertible adds CU45,000 after-tax earnings and 400,000 shares, so diluted continuing EPS is 37.06 cents (CU945,000 / 2,550,000). Basic discontinued loss per share is 5.58 cents loss (CU120,000 / 2,150,000).',reviewChecks:['Held-for-sale measurement is CU460,000 and loss is CU40,000.','The major-line result is separately presented as discontinued.','Weighted-average shares are 2,150,000.','Continuing basic EPS 41.86c and diluted EPS 37.06c reconcile.'],transfer:'Assume the division is not available for immediate sale because major refurbishment is required before marketing. Reassess classification and the timing of IFRS 5 measurement.'},
 checkpoint:[
  {id:'acca-b9-q1',prompt:'How is a qualifying held-for-sale asset measured after classification?',options:['Higher of carrying amount and value in use','Lower of carrying amount and fair value less costs to sell','Historical cost only','Fair value through OCI only'],correctIndex:1,explanation:'IFRS 5 uses the lower of carrying amount and fair value less costs to sell.',reviewSection:'acca-b9-disposals'},
  {id:'acca-b9-q2',prompt:'How is a change in an accounting estimate from new information normally applied?',options:['Retrospectively','Prospectively','Directly to share capital','Never recognised'],correctIndex:1,explanation:'New-information estimate changes affect the current and, when relevant, future periods.',reviewSection:'acca-b9-changes'},
  {id:'acca-b9-q3',prompt:'Two million shares exist all year and 600,000 are issued at full market value on 1 October. What is the weighted average?',options:['2,000,000','2,150,000','2,450,000','2,600,000'],correctIndex:1,explanation:'The issue is weighted for three months: 2,000,000 + 600,000 × 3/12.',reviewSection:'acca-b9-eps'},
  {id:'acca-b9-q4',prompt:'Which convertible-debt adjustment is used for diluted EPS?',options:['Add finance cost before tax only','Add after-tax finance cost and assumed conversion shares','Add shares only','Subtract finance cost and shares'],correctIndex:1,explanation:'Assumed conversion removes the after-tax interest and adds conversion shares.',reviewSection:'acca-b9-eps'},
  {id:'acca-b9-q5',prompt:'Which list is IFRS S1 core content?',options:['Tax, audit, dividends, capital','Governance, strategy, risk management, metrics and targets','Assets, liabilities, equity, cash','Policy, estimate, error, event'],correctIndex:1,explanation:'Those four connected areas organise IFRS S1 disclosures.',reviewSection:'acca-b9-sustainability'}
 ],
 practiceExercises:[
  {id:'acca-b9-p1',question:'A qualifying asset has carrying amount CU720 and fair value less costs to sell CU680. What happens on held-for-sale classification?',hints:['Select the lower amount.','Remember depreciation after classification.'],answer:'Measure it at CU680, recognise a CU40 loss and cease depreciation while it remains classified as held for sale.',explanation:'IFRS 5 applies lower-of measurement and stops depreciation.'},
  {id:'acca-b9-p2',question:'Repair: “A revised useful life based on new wear data is a prior-period error and always restates comparatives.”',hints:['Ask whether reliable information was misused earlier.','New measurement evidence often changes an estimate.'],answer:'If the earlier estimate properly used information then available, the new wear data changes an accounting estimate and is applied prospectively, not as a retrospective error correction.',explanation:'New information differs from failure to use previously available reliable information.'},
  {id:'acca-b9-p3',question:'Profit is CU500,000 and weighted-average shares are 2,000,000. Convertible debt adds CU30,000 after-tax earnings and 200,000 shares. Calculate basic and diluted EPS.',hints:['Calculate each numerator-denominator pair separately.','Check that the assumed conversion reduces EPS.'],answer:'Basic EPS is 25.00 cents. Diluted EPS is 24.09 cents: CU530,000 / 2,200,000. The potential shares are dilutive because EPS falls.',explanation:'Convertible debt adjusts both numerator and denominator on assumed conversion.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ifrs-5',label:'IFRS Foundation · IFRS 5 Non-current Assets Held for Sale and Discontinued Operations',url:'https://www.ifrs.org/issued-standards/list-of-standards/ifrs-5-non-current-assets-held-for-sale-and-discontinued-operations/',supports:'Held-for-sale measurement, depreciation and separate presentation.',reviewedOn},
  {id:'ifrs-18',label:'IFRS Foundation · IFRS 18 Presentation and Disclosure in Financial Statements',url:'https://www.ifrs.org/issued-standards/list-of-standards/ifrs-18-presentation-and-disclosure-in-financial-statements/',supports:'Presentation, disclosure, aggregation and disaggregation context.',reviewedOn},
  {id:'ias-8',label:'IFRS Foundation · IAS 8 Basis of Preparation of Financial Statements',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-8-basis-of-preparation-of-financial-statements/',supports:'Policies, estimates and correction of prior-period errors.',reviewedOn},
  {id:'ias-33',label:'IFRS Foundation · IAS 33 Earnings per Share',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-33-earnings-per-share/',supports:'Basic and diluted EPS principles and presentation.',reviewedOn},
  {id:'ifrs-s1',label:'IFRS Foundation · IFRS S1 General Requirements',url:'https://www.ifrs.org/issued-standards/ifrs-sustainability-standards-navigator/ifrs-s1-general-requirements/',supports:'Objective, scope and four core content areas.',reviewedOn}
 ]
};
export function localModelB9For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='B9'?ACCA_B9_MODEL_MODULE:null;}
export {ACCA_B9_MODEL_ID,ACCA_B9_MODEL_SLUG};
