import type {LessonModule} from './lessonModules.ts';
import {ACCA_D1_MODEL_ID,ACCA_D1_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_D1_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'27–34',segments:['Build the primary statements from adjusted balances.','Separate profit, OCI and owner movements in equity.','Construct operating cash flow by the indirect method.','Use an adjustment matrix to prevent double counting.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_D1_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask which statement, period and adjustment the learner is preparing before discussing presentation.',supportedPractice:'Trace each adjustment once through profit or loss, OCI, assets, liabilities, equity and cash-flow reconciliation.',misconception:'A balancing statement is not necessarily correct: classification, recognition, OCI, non-cash adjustments and owner transactions must still be justified.',transfer:'Change one adjustment, tax effect or cash-flow classification and ask which statements and subtotals move.',close:'Recap statement linkage, equity reconciliation and indirect cash-flow logic without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_D1_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_D1_MODEL_ID,title:'ACCA FR D1 · Single entity financial statements',
 goal:'Prepare and explain a single entity’s primary financial statements, statement of changes in equity and indirect-method cash-flow extracts using consistent IFRS adjustments.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level D1 mapping must be checked against the exact selected exam sitting before publication. It uses original simplified statements and does not replace a complete IFRS disclosure checklist or jurisdictional filing advice. It is not ACCA approval, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-d1-primary',title:'1. Build a linked set of primary financial statements',paragraphs:[
   'Start from adjusted balances, not from the desired shape of the final answer. For each item decide recognition, measurement, statement and category before aggregating it. The statement of financial position must distinguish assets, liabilities and equity and normally current from non-current items. The statement of profit or loss and other comprehensive income reports income and expenses for the period; comparative information and material disaggregation remain part of faithful presentation.',
   'For the 2026/27 FR sitting, IFRS 18 is examinable and replaces IAS 1 for annual periods beginning on or after 1 January 2027. It introduces defined profit-or-loss subtotals including operating profit and profit before financing and income taxes, while preserving the need to apply the underlying standards. A ledger label does not determine a category: classification follows the nature of the item and, where relevant, the entity’s main business activities.',
   'Use a preparation schedule that maps every trial-balance line and adjustment to one destination and then cross-checks linked totals. Closing inventory affects both cost of sales and current assets; depreciation affects expense and accumulated depreciation; current tax affects tax expense and a payable after payments. A statement that balances can still contain an omitted adjustment twice offset by another error, so arithmetic and accounting review are separate controls.'
  ],supportPt:'Prepare a partir dos saldos ajustados. Mapeie cada item para reconhecimento, mensuração, demonstração e categoria; o simples fato de o balanço fechar não prova que a apresentação está correta.',sourceIds:['acca-fr-syllabus','ifrs-18']},
  {id:'acca-d1-equity',title:'2. Reconcile profit, OCI and transactions with owners',paragraphs:[
   'The statement of changes in equity explains each equity component from opening to closing balance. Profit for the period normally increases retained earnings; other comprehensive income moves the relevant reserve or accumulated OCI component; issues of shares and dividends are transactions with owners and are not income or expenses. Prior-period adjustments and retrospective policy changes, when applicable, adjust opening equity rather than being disguised as current performance.',
   'Share capital and share premium must follow the terms of the issue. A revaluation gain recognised in OCI increases a revaluation surplus after its related tax effect when required. A transfer within equity, such as a realised revaluation transfer permitted by the applicable treatment, changes the composition of equity but not total equity. Show the transfer in both affected columns so it is not mistaken for new income.',
   'Use a column for every material equity component and reconcile opening balance, restatement, total comprehensive income, owner contributions, distributions and transfers. Profit plus OCI equals total comprehensive income, but not every movement in equity is comprehensive income. A dividend reduces retained earnings when recognised and appears as a financing cash flow when paid under the lesson’s stated policy; an unpaid dividend does not create the same-period cash outflow.'
  ],supportPt:'Separe resultado, OCI e transações com proprietários. Emissão de ações e dividendos alteram equity, mas não são receitas ou despesas; transferências internas não mudam o total do patrimônio.',sourceIds:['acca-fr-syllabus','ifrs-18']},
  {id:'acca-d1-cashflow',title:'3. Prepare indirect-method cash-flow extracts without counting cash twice',paragraphs:[
   'The indirect method begins with the specified profit measure and reconciles it to operating cash. Add back non-cash expenses such as depreciation and impairment; remove income or expenses whose cash effects belong to investing or financing activities; then adjust for operating working-capital movements. An increase in receivables or inventory normally absorbs operating cash, while an increase in operating payables normally releases it.',
   'The reconciliation is not a second record of each cash transaction. Adding back depreciation removes a non-cash expense from profit; the purchase of property, plant and equipment is shown separately as investing cash when paid. Adding back a finance cost removes it from the operating reconciliation when the stated classification places the interest paid in financing; the actual interest payment is then presented once in that category. State the classification assumptions used.',
   'Tax expense and tax paid are different measures. Begin with the statement of financial position and tax-expense information to derive or verify cash paid, considering opening and closing tax balances and non-cash tax effects where supplied. Non-cash acquisitions, share issues for assets and revaluations are excluded from cash flows but may require separate disclosure. Finally reconcile the net movement to opening and closing cash and cash equivalents.'
  ],supportPt:'No método indireto, remova do lucro itens não caixa e efeitos classificados fora da operação, ajuste capital de giro e apresente o caixa real apenas uma vez na categoria apropriada.',sourceIds:['acca-fr-syllabus','ias-7']},
  {id:'acca-d1-integrated',title:'4. Control adjustments across profit, position, equity and cash',paragraphs:[
   'An adjustment matrix prevents isolated entries. For each fact record the profit-or-loss effect, OCI effect, asset or liability effect, equity effect and cash-flow treatment. Accruals and prepayments align expenses with the period; impairment and depreciation reduce carrying amounts without immediate cash; provisions recognise qualifying obligations; deferred tax can arise from temporary differences; held-for-sale classification and discontinued operations require their own criteria rather than management intention alone.',
   'Tax effects and presentation may follow the underlying item. A revaluation gain recognised in OCI generally has its related tax consequence recognised consistently in OCI, while tax on profit-or-loss items normally belongs in profit or loss. The lesson’s examples state their assumptions, but a real preparer must use the applicable standard and facts. Do not force every debit or credit through retained earnings simply to balance the statement.',
   'Finish with four independent checks: the statement of financial position balances; profit and OCI reconcile to equity movements; cash-flow movement reconciles opening to closing cash; and all adjustments have exactly one complete path through the statements. Explain estimates and missing evidence rather than inventing them. This produces an auditable answer and makes a later error easier to isolate than a single compressed calculation.'
  ],supportPt:'Use uma matriz de ajustes e quatro conciliações independentes: posição financeira, resultado/OCI com equity, movimento de caixa e trilha completa de cada ajuste.',sourceIds:['acca-fr-syllabus','ifrs-18','ias-7']}
 ],
 terms:[
  {term:'Primary financial statements',meaning:'Core statements presenting financial position, performance, changes in equity and cash flows.',pt:'Demonstrações financeiras primárias',example:'The profit figure links profit or loss to retained earnings.'},
  {term:'Other comprehensive income',meaning:'Income and expenses recognised outside profit or loss when required or permitted by IFRS Standards.',pt:'Outros resultados abrangentes',example:'A CU80 revaluation gain with CU16 related tax gives CU64 net OCI.'},
  {term:'Statement of changes in equity',meaning:'Reconciliation of each equity component from opening to closing balance.',pt:'Demonstração das mutações do patrimônio líquido',example:'Profit, OCI, a share issue and dividends are shown separately.'},
  {term:'Indirect method',meaning:'Operating cash-flow presentation that reconciles profit for non-cash, non-operating and working-capital effects.',pt:'Método indireto',example:'An increase in receivables is deducted in the operating reconciliation.'},
  {term:'Cash equivalent',meaning:'Short-term, highly liquid investment readily convertible to known cash with insignificant value-change risk.',pt:'Equivalente de caixa',example:'Not every short-term investment automatically qualifies.'},
  {term:'Adjustment matrix',meaning:'Control showing every statement and cash-flow effect of an accounting adjustment.',pt:'Matriz de ajustes',example:'Depreciation affects expense, accumulated depreciation and the operating reconciliation.'}
 ],
 visual:{title:'One adjustment, linked statement effects',note:'Original control map; “none” means no direct effect in the stated example, not that disclosure is unnecessary.',headers:['Adjustment','Performance/equity effect','Position/cash-flow effect'],rows:[['Depreciation CU90','Operating expense; retained earnings','Accumulated depreciation; add back in CFO'],['Revaluation CU80, tax CU16','OCI and revaluation surplus +CU64','PPE and deferred tax; no cash'],['Receivables increase CU50','No second expense','Receivables +CU50; deduct in CFO'],['Share issue CU120','Owner contribution, not income','Equity +CU120; financing inflow'],['Dividend CU70 paid','Retained earnings −CU70','Cash −CU70; financing outflow']],question:'Why is depreciation added back in operating cash flow while the PPE purchase remains investing cash?',answer:'Depreciation reduced profit without using current-period cash; the purchase is the separate cash transaction and must be presented once as investing cash.'},
 caseStudy:{title:'Prepare a linked single-entity statement pack',scenario:['A non-financial entity reports revenue CU2,000, cost of sales CU1,180, other operating expenses CU430, depreciation CU90, finance cost CU30 and income-tax expense CU60. A CU80 property revaluation gain is recognised in OCI with CU16 related tax. There are no investing-category income or discontinued operations.','Opening equity was share capital CU500, share premium CU100, revaluation surplus CU40 and retained earnings CU620. A cash share issue added CU100 share capital and CU20 premium; CU70 dividends were recognised and paid.','For cash-flow purposes, receivables increased CU50, inventory increased CU30 and operating payables increased CU20. PPE purchases paid were CU260, income tax paid was CU55 and a CU100 bank loan was received. Interest paid CU30 is classified as financing under the stated policy. Opening cash was CU85.'],task:'Prepare the key profit/OCI/equity totals and an indirect-method cash-flow summary, then reconcile closing cash.',hints:['Calculate operating profit before finance and tax, then separate profit from OCI.','In the operating reconciliation add back depreciation and finance cost before working-capital changes.'],modelAnswer:'Operating profit is CU300 (CU2,000 − CU1,180 − CU430 − CU90). With no investing-category income, profit before financing and income taxes is also CU300. After CU30 finance cost, profit before tax is CU270 and profit for the period is CU210. Net OCI is CU64 (CU80 − CU16), so total comprehensive income is CU274. Closing share capital is CU600, share premium CU120, revaluation surplus CU104 and retained earnings CU760 (CU620 + CU210 − CU70), giving total equity CU1,584. The indirect operating reconciliation is CU270 + CU90 + CU30 − CU50 − CU30 + CU20 = CU330 cash generated from operations; after CU55 tax paid, operating cash is CU275. Investing cash is CU260 outflow. Financing cash is CU120 share proceeds + CU100 loan − CU30 interest − CU70 dividend = CU120 inflow. Net cash increases CU135, reconciling opening CU85 to closing cash CU220. The CU64 net revaluation is non-cash and does not enter the cash-flow total.',reviewChecks:['Operating profit CU300; profit for the period CU210.','Net OCI CU64; total comprehensive income CU274.','Closing equity CU1,584 with retained earnings CU760.','Operating cash CU275 and closing cash CU220.'],transfer:'Assume receivables instead fell CU20 and only CU40 of the dividend was paid. Recalculate operating cash, financing cash and closing cash while keeping equity recognition unchanged.'},
 checkpoint:[
  {id:'acca-d1-q1',prompt:'Which movement belongs in OCI rather than profit under the stated case facts?',options:['Revenue CU2,000','Finance cost CU30','Property revaluation gain CU80','Dividend CU70'],correctIndex:2,explanation:'The stated revaluation gain is recognised in OCI; the dividend is an owner distribution.',reviewSection:'acca-d1-equity'},
  {id:'acca-d1-q2',prompt:'Why is depreciation added back in an indirect operating cash-flow reconciliation?',options:['It is financing income','It reduced profit without a current cash outflow','It is an owner contribution','It increases receivables'],correctIndex:1,explanation:'The add-back removes a non-cash expense from the profit starting point.',reviewSection:'acca-d1-cashflow'},
  {id:'acca-d1-q3',prompt:'What is closing retained earnings in the worked case?',options:['CU690','CU760','CU830','CU1,584'],correctIndex:1,explanation:'CU620 opening + CU210 profit − CU70 dividend = CU760.',reviewSection:'acca-d1-equity'},
  {id:'acca-d1-q4',prompt:'Which check best detects a duplicated or omitted adjustment?',options:['Accept that the statement balances','Trace each fact through an adjustment matrix and reconcile all linked statements','Present every item in operating profit','Put the difference in retained earnings'],correctIndex:1,explanation:'Independent linked reconciliations test more than arithmetic balance.',reviewSection:'acca-d1-integrated'},
  {id:'acca-d1-q5',prompt:'What is the closing cash balance in the worked case?',options:['CU135','CU170','CU220','CU305'],correctIndex:2,explanation:'CU85 opening + CU275 operating − CU260 investing + CU120 financing = CU220.',reviewSection:'acca-d1-cashflow'}
 ],
 practiceExercises:[
  {id:'acca-d1-p1',question:'Opening retained earnings are CU400, profit is CU95, dividends recognised are CU25 and a CU10 transfer is made from revaluation surplus to retained earnings. Calculate closing retained earnings and explain the total-equity effect of the transfer.',hints:['Add profit and the incoming transfer; deduct dividends.','A transfer moves amounts between equity columns.'],answer:'Closing retained earnings are CU480. The CU10 transfer changes equity composition but has no effect on total equity.',explanation:'Owner distributions reduce total equity; an internal reserve transfer does not.'},
  {id:'acca-d1-p2',question:'Profit before tax is CU180, including depreciation CU35 and a gain on disposal CU12. Inventory rises CU20 and payables fall CU8. Calculate cash generated from operations before tax.',hints:['Add back depreciation and remove the investing gain.','Inventory growth and a payable decrease both absorb cash.'],answer:'Cash generated from operations is CU175: CU180 + CU35 − CU12 − CU20 − CU8.',explanation:'The reconciliation removes non-cash/non-operating effects and applies working-capital directions.'},
  {id:'acca-d1-p3',question:'Repair: “The statement of financial position balances, so the financial statements must be correct.”',hints:['Balancing tests double-entry arithmetic only.','Name two linked reconciliations.'],answer:'A balanced position statement can still contain compensating errors, omissions or misclassifications. Reconcile profit and OCI to equity, cash movement to opening/closing cash, and trace each adjustment across all affected statements.',explanation:'Arithmetic equality is necessary but not sufficient for correct reporting.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Current D1 outcomes for single-entity statements, changes in equity and indirect cash-flow extracts.',reviewedOn},
  {id:'ifrs-18',label:'IFRS Foundation · IFRS 18 Presentation and Disclosure in Financial Statements',url:'https://www.ifrs.org/issued-standards/list-of-standards/ifrs-18-presentation-and-disclosure-in-financial-statements/',supports:'Primary-statement presentation, defined profit-or-loss subtotals, aggregation and disaggregation.',reviewedOn},
  {id:'ias-7',label:'IFRS Foundation · IAS 7 Statement of Cash Flows',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-7-statement-of-cash-flows/',supports:'Operating, investing and financing cash flows and the indirect method.',reviewedOn}
 ]
};
export function localModelD1For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='D1'?ACCA_D1_MODEL_MODULE:null;}
export {ACCA_D1_MODEL_ID,ACCA_D1_MODEL_SLUG};
