import type {LessonModule} from './lessonModules.ts';
import {ACCA_B12_MODEL_ID,ACCA_B12_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_B12_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'20–26',segments:['Functional currency versus presentation currency.','Initial recognition at the transaction-date spot rate.','A reporting-date monetary and non-monetary item walk-through.','Settlement exchange differences and a compact rate-selection drill.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_B12_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask for the entity’s functional currency, the foreign-currency amount, the relevant date and whether the item is monetary before choosing a rate.',supportedPractice:'Classify the item before translating it, then reconcile transaction-date, reporting-date and settlement carrying amounts separately.',misconception:'A foreign-currency purchase does not mean every related balance is retranslated at the closing rate; the payable and historical-cost inventory have different characteristics.',transfer:'Change the transaction date, closing rate, settlement rate or monetary classification and ask for one revised amount and exchange difference.',close:'Recap functional currency, initial recognition, closing translation and settlement without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_B12_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_B12_MODEL_ID,title:'ACCA FR B12 · Foreign currency transactions',
 goal:'Distinguish functional and presentation currency, record foreign-currency transactions initially, and translate monetary and non-monetary items at reporting and settlement dates.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level B12 mapping must be checked against the exact selected exam sitting before publication. It focuses on individual foreign-currency transactions rather than full foreign-operation consolidation. It is original teaching material, not ACCA approval, treasury advice, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-b12-currencies',title:'1. Distinguish functional currency from presentation currency',paragraphs:[
   'Functional currency is the currency of the primary economic environment in which the entity operates: normally the environment in which it primarily generates and expends cash. Primary indicators include the currency that mainly influences sales prices and the currency that mainly influences labour, material and other costs. Financing and the currency in which operating receipts are retained can provide supporting evidence. Determine the functional currency from facts; it is not a free presentation choice.',
   'Presentation currency is the currency in which the financial statements are presented. IAS 21 permits an entity to present financial statements in a currency different from its functional currency, but that choice does not change the currency used to measure the entity’s underlying transactions. This lesson distinguishes the concepts without teaching the full translation of a foreign operation or group.',
   'Adjustments are necessary because a foreign-currency amount can represent a different functional-currency amount as exchange rates change. Without translation, adding amounts denominated in different currencies would not produce meaningful financial statements. The accounting therefore identifies the transaction date, the reporting date and settlement date, then applies the appropriate rate to the particular asset, liability, income or expense.'
  ],supportPt:'Functional currency vem do ambiente econômico principal; presentation currency é a moeda escolhida para apresentar as demonstrações. A mensuração das transações parte da functional currency, ainda que a apresentação final use outra moeda.',sourceIds:['ias-21','acca-fr-syllabus']},
  {id:'acca-b12-initial',title:'2. Record initial recognition at the transaction-date rate',paragraphs:[
   'On initial recognition, translate a foreign-currency transaction into the functional currency using the spot exchange rate at the transaction date. The transaction date is when the transaction first qualifies for recognition under IFRS Accounting Standards. Apply the stated quotation consistently: if the rate is CU0.80 for one foreign-currency unit, multiply FC100,000 by CU0.80 to record CU80,000.',
   'A rate that approximates the actual rate, such as an average for a week or month, may be practical for a volume of transactions when exchange rates do not fluctuate significantly. It is not appropriate when volatility makes the approximation unreliable. In an exam calculation, use the rate and convention supplied and label whether it is functional currency per foreign unit or the inverse.',
   'Initial recognition commonly creates two items with the same translated amount but different later treatment. A purchase of inventory on credit records inventory and a payable at the transaction-date rate. Inventory measured at historical cost is non-monetary; the payable is monetary because it is an obligation to deliver a fixed or determinable number of currency units. Classify each item before the reporting-date calculation.'
  ],supportPt:'Na data da transação, use a spot rate e respeite a cotação fornecida. Uma compra a prazo pode criar inventory não monetário e payable monetário com o mesmo valor inicial, mas tratamentos posteriores diferentes.',sourceIds:['ias-21']},
  {id:'acca-b12-reporting',title:'3. Choose the reporting-date rate from the item’s measurement basis',paragraphs:[
   'At each reporting date, translate foreign-currency monetary items using the closing rate. Cash, trade receivables, trade payables and many loans are monetary because they are currency held or rights and obligations to receive or pay a fixed or determinable number of currency units. The difference between the translated closing amount and the existing carrying amount creates an exchange difference.',
   'Translate non-monetary items measured at historical cost using the exchange rate at the transaction date. Therefore, inventory or equipment at historical cost is not mechanically retranslated simply because its related payable uses the closing rate. Its normal measurement Standard still applies: for example, inventory must still be tested against net realisable value, but that is a separate measurement question.',
   'Translate a non-monetary item measured at fair value using the rate at the date when fair value was measured. When a gain or loss on that item is recognised in profit or loss, its exchange component follows that treatment; when the gain or loss is recognised in other comprehensive income, the exchange component is also recognised there. Start with the item’s measurement basis, not just its currency label.'
  ],supportPt:'Monetary items usam closing rate. Non-monetary items a historical cost mantêm transaction-date rate; os medidos a fair value usam a taxa da data da mensuração. Classifique antes de calcular.',sourceIds:['ias-21']},
  {id:'acca-b12-differences',title:'4. Reconcile exchange differences through reporting and settlement',paragraphs:[
   'Exchange differences arising on settlement of monetary items, or on translating them at rates different from those used when they were initially recognised or previously reported, are generally recognised in profit or loss in the period in which they arise. If a payable increases in functional-currency terms by the reporting date, the entity recognises an exchange loss; if it later settles for less than that closing carrying amount, it recognises a subsequent exchange gain.',
   'Keep each reporting period separate. A year-end loss updates the liability to the closing rate and belongs to that reporting period. Settlement after year end compares the cash paid with the retranslated opening liability and produces the next period’s difference. Do not recompute the settlement result only from the original transaction amount and place the whole movement in one period.',
   'A reliable working has four columns: foreign-currency amount, relevant date, selected rate and functional-currency amount. State the reason for the rate—transaction date, closing date or fair-value measurement date—and then calculate the difference against the current carrying amount. This makes inverted rates, duplicated movements and incorrect retranslations of historical-cost items easier to detect.'
  ],supportPt:'Exchange differences de monetary items normalmente vão ao profit or loss do período correspondente. Feche o saldo na reporting date e calcule a liquidação posterior contra esse carrying amount, sem misturar períodos.',sourceIds:['ias-21']}
 ],
 terms:[
  {term:'Functional currency',meaning:'Currency of the primary economic environment in which the entity operates.',pt:'Moeda funcional',example:'It is determined from the entity’s economic facts, not selected for appearance.'},
  {term:'Presentation currency',meaning:'Currency in which financial statements are presented.',pt:'Moeda de apresentação',example:'It can differ from the functional currency.'},
  {term:'Spot exchange rate',meaning:'Exchange rate for immediate delivery at a specified date.',pt:'Taxa de câmbio à vista',example:'Initial recognition uses the spot rate at the transaction date.'},
  {term:'Closing rate',meaning:'Spot exchange rate at the end of the reporting period.',pt:'Taxa de fechamento',example:'A foreign-currency trade payable is translated at the closing rate.'},
  {term:'Monetary item',meaning:'Currency held or an asset or liability to receive or pay a fixed or determinable number of currency units.',pt:'Item monetário',example:'A trade payable for FC100,000 is monetary.'},
  {term:'Exchange difference',meaning:'Difference resulting from translating the same number of foreign-currency units at different rates.',pt:'Diferença cambial',example:'A payable rising from CU80,000 to CU86,000 creates a CU6,000 loss.'}
 ],
 visual:{title:'One purchase, different reporting-date treatments',note:'Original schedule; fictional amounts. Rates are CU per FC1. The purchase is FC100,000.',headers:['Item or event','Rate used','Functional-currency amount'],rows:[['Initial inventory and payable','Transaction: 0.80','CU80,000 each'],['Closing trade payable','Reporting date: 0.86','CU86,000'],['Closing historical-cost inventory','Transaction: 0.80','CU80,000'],['Year-end exchange difference','0.86 less 0.80','CU6,000 loss'],['Settlement next period','Settlement: 0.84','CU84,000 cash / CU2,000 gain']],question:'Why is the inventory CU80,000 while the payable becomes CU86,000 at year end?',answer:'The historical-cost inventory is non-monetary and retains the transaction-date rate; the payable is monetary and uses the closing rate.'},
 caseStudy:{title:'Credit purchase across a reporting date',scenario:['An entity whose functional currency is CU buys inventory for FC100,000 on 1 November, when the spot rate is CU0.80 per FC1. The purchase is unpaid at the 31 December reporting date, when the closing rate is CU0.86 per FC1.','The inventory remains on hand at historical cost and no separate write-down is required. The payable is settled on 31 January for FC100,000 when the spot rate is CU0.84 per FC1. Ignore tax and transaction costs.'],task:'Record the initial purchase, determine the inventory and payable carrying amounts at year end, and calculate exchange differences at reporting and settlement dates.',hints:['At year end, classify the inventory and payable separately before selecting rates.','At settlement, compare the CU84,000 cash payment with the CU86,000 opening payable.'],modelAnswer:'On 1 November, recognise inventory and the trade payable at CU80,000: FC100,000 × CU0.80. At 31 December, the historical-cost inventory remains CU80,000 because it is non-monetary, while the monetary payable is retranslated at the CU0.86 closing rate to CU86,000. Recognise a CU6,000 exchange loss in profit or loss for that reporting period. On 31 January, settlement costs CU84,000: FC100,000 × CU0.84. Derecognising the CU86,000 payable for CU84,000 cash creates a CU2,000 exchange gain in the next reporting period. Across both periods, the net CU4,000 loss equals the difference between the original CU80,000 liability and CU84,000 cash paid.',reviewChecks:['Initial inventory and payable are CU80,000 each.','Closing inventory remains CU80,000 under historical cost.','Closing payable is CU86,000 and year-end exchange loss is CU6,000.','Settlement cash CU84,000 produces a subsequent CU2,000 gain.'],transfer:'Assume instead that the closing rate is CU0.76 and the settlement rate is CU0.78. Recalculate the two period-specific exchange differences.'},
 checkpoint:[
  {id:'acca-b12-q1',prompt:'What determines an entity’s functional currency?',options:['The currency management prefers for the annual report','The primary economic environment in which the entity operates','The currency with the strongest exchange rate','The legal name of the parent company'],correctIndex:1,explanation:'Functional currency follows the primary economic environment and relevant indicators.',reviewSection:'acca-b12-currencies'},
  {id:'acca-b12-q2',prompt:'Which rate is normally used for initial recognition of a foreign-currency transaction?',options:['The prior year closing rate','The transaction-date spot rate','The eventual settlement rate','Any rate chosen consistently'],correctIndex:1,explanation:'Initial recognition uses the spot exchange rate at the transaction date.',reviewSection:'acca-b12-initial'},
  {id:'acca-b12-q3',prompt:'How is a foreign-currency trade payable translated at the reporting date?',options:['At its original transaction rate forever','At the closing rate because it is monetary','At an average rate because it is non-monetary','It is never translated'],correctIndex:1,explanation:'The obligation to pay a fixed foreign-currency amount is monetary and uses the closing rate.',reviewSection:'acca-b12-reporting'},
  {id:'acca-b12-q4',prompt:'Which rate applies at year end to inventory carried at historical cost?',options:['The transaction-date rate','The closing rate in every case','The next settlement rate','The presentation-currency rate chosen by management'],correctIndex:0,explanation:'Historical-cost non-monetary items retain the transaction-date rate.',reviewSection:'acca-b12-reporting'},
  {id:'acca-b12-q5',prompt:'In the worked case, what exchange difference arises when the payable is settled?',options:['CU2,000 gain','CU2,000 loss','CU6,000 gain','CU4,000 loss entirely in the settlement period'],correctIndex:0,explanation:'The CU86,000 payable is settled for CU84,000, producing a CU2,000 gain in the next period.',reviewSection:'acca-b12-differences'}
 ],
 practiceExercises:[
  {id:'acca-b12-p1',question:'A foreign receivable of FC40,000 was initially recorded at CU0.75 per FC1 and the closing rate is CU0.78. Calculate the closing receivable and exchange difference.',hints:['A receivable for fixed currency units is monetary.','Compare the closing amount with the CU30,000 initial carrying amount.'],answer:'The closing receivable is CU31,200 (FC40,000 × CU0.78), producing a CU1,200 exchange gain.',explanation:'The monetary receivable is retranslated at the closing rate.'},
  {id:'acca-b12-p2',question:'Repair: “The payable used the closing rate, so the related historical-cost equipment must use it too.”',hints:['Classify the two balances separately.','Identify the equipment’s measurement basis.'],answer:'The payable is monetary and uses the closing rate. Equipment carried at historical cost is non-monetary and retains the transaction-date rate, subject to its other applicable measurement requirements.',explanation:'A shared transaction does not make both resulting balances monetary.'},
  {id:'acca-b12-p3',question:'A monetary liability is CU52,000 at year end and is settled next period for CU49,000. What settlement exchange difference arises?',hints:['Compare cash paid with the opening carrying amount.','A lower settlement amount benefits the debtor.'],answer:'Recognise a CU3,000 exchange gain in the settlement period.',explanation:'Settlement removes a CU52,000 liability using CU49,000 cash.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ias-21',label:'IFRS Foundation · IAS 21 The Effects of Changes in Foreign Exchange Rates',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-21-the-effects-of-changes-in-foreign-exchange-rates/',supports:'Functional and presentation currency, rate selection and exchange-difference principles.',reviewedOn}
 ]
};
export function localModelB12For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='B12'?ACCA_B12_MODEL_MODULE:null;}
export {ACCA_B12_MODEL_ID,ACCA_B12_MODEL_SLUG};
