import type {LessonModule} from './lessonModules.ts';
import {ACCA_B6_MODEL_ID,ACCA_B6_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-21';
export const ACCA_B6_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'18–24',segments:['Does the contract contain an identified asset and controlled use?','Initial lease liability and right-of-use asset.','A narrated liability roll-forward.','Retrieval pauses on depreciation, exemptions and presentation.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_B6_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask who controls use of the identified asset and obtains its economic benefits.',supportedPractice:'Build the lease in two linked schedules: liability roll-forward and right-of-use depreciation.',misconception:'The cash payment is not the period’s whole lease expense under the normal lessee model.',transfer:'Change payment timing, ownership transfer or lease term and ask which measurement changes.',close:'Recap lease identification, initial measurement and subsequent entries without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_B6_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_B6_MODEL_ID,title:'ACCA FR B6 · Leasing',
 goal:'Identify a lease and account for a lessee’s lease liability and right-of-use asset from commencement through subsequent measurement.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level B6 mapping must be checked against the exact selected exam sitting before publication. It is original teaching material, not ACCA approval, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-b6-identify',title:'1. Decide whether the contract contains a lease',paragraphs:[
   'A contract contains a lease when it conveys the right to control the use of an identified asset for a period of time in exchange for consideration. The asset may be explicitly or implicitly specified, but a supplier’s substantive substitution right can mean there is no identified asset. A physically distinct portion of a larger asset can qualify when it is identified.',
   'The customer controls use when it obtains substantially all economic benefits from use and directs how and for what purpose the asset is used throughout the period. Protective rights held by the supplier do not by themselves remove customer control. If the relevant decisions are predetermined, consider who designed the asset or has the right to operate it without the supplier changing instructions.',
   'Separate a lease component from non-lease services when the question provides the necessary information and applicable method. Do not conclude that every contract mentioning equipment is a lease: dedicated capacity, substitution rights, decision-making and the period of use all matter. State the identified asset and both control tests before performing any lease calculation.'
  ],supportPt:'Há lease quando o cliente controla o uso de ativo identificado por um período em troca de contraprestação. Verifique benefícios econômicos e quem dirige como e para qual finalidade o ativo será usado.',sourceIds:['ifrs-16','acca-fr-syllabus']},
  {id:'acca-b6-initial',title:'2. Measure the lease liability and right-of-use asset at commencement',paragraphs:[
   'At commencement, measure the lease liability at the present value of lease payments not yet paid. Discount using the interest rate implicit in the lease when readily determinable; otherwise use the lessee’s incremental borrowing rate. Depending on the facts, payments can include fixed payments less incentives receivable, in-substance fixed payments, relevant index- or rate-based amounts and certain residual value or option amounts.',
   'The right-of-use asset starts with the initial lease liability and is adjusted for lease payments made at or before commencement, less incentives received, plus qualifying initial direct costs and an estimate of restoration or dismantling obligations. Avoid adding general overhead or future operating costs that do not form part of the asset measurement.',
   'The liability and right-of-use asset often begin at different amounts. A prepayment increases the asset but is not an unpaid lease liability; an incentive reduces the appropriate measurement; a restoration provision can increase the asset without entering the lease liability. Show a separate reconciliation for each balance instead of forcing them to remain equal.'
  ],supportPt:'O passivo é o valor presente dos pagamentos não pagos. O ativo de direito de uso parte desse passivo e ajusta pré-pagamentos, incentivos, custos diretos e restauração. Os dois saldos não precisam ser iguais.',sourceIds:['ifrs-16']},
  {id:'acca-b6-subsequent',title:'3. Roll the liability forward and depreciate the right of use',paragraphs:[
   'After commencement, increase the lease liability by finance cost using the effective interest method and reduce it by lease payments. With payments in arrears, apply interest before deducting the cash payment; with payments in advance, follow the timing supplied. A complete working labels opening liability, interest, cash and closing liability.',
   'Depreciate the right-of-use asset over the useful life of the underlying asset when ownership transfers by the end of the lease or purchase is reasonably certain under the relevant condition. Otherwise depreciate over the shorter of useful life and lease term. Apply impairment requirements when relevant and adjust future depreciation after a change in carrying amount.',
   'The normal lessee model therefore reports depreciation and finance cost rather than one straight-line rental expense. The cash payment is split between liability reduction and interest in the schedule; it is not automatically the expense recognised for the period. Keep the statement of financial position roll-forward consistent with the profit-or-loss charges.'
  ],supportPt:'Depois do início, passivo aumenta pelos juros e diminui pelo pagamento. O ativo é depreciado; normalmente o resultado mostra depreciação mais juros, não o pagamento inteiro como aluguel.',sourceIds:['ifrs-16']},
  {id:'acca-b6-scope',title:'4. Apply exemptions and changes without losing the core model',paragraphs:[
   'In a sale-and-leaseback, first assess whether the transfer qualifies as a sale under the revenue requirements. If it does and proceeds equal fair value, the seller-lessee recognises only the gain relating to rights transferred to the buyer-lessor, measures the retained right-of-use asset as the proportion of the previous carrying amount relating to the right retained, and recognises the lease liability. If the transfer is not a sale, the seller-lessee continues the asset and recognises a financial liability for the proceeds.',
   'A lessee may elect recognition exemptions for qualifying short-term leases and leases of low-value underlying assets. The short-term assessment is based on a lease term of 12 months or less and excludes a purchase option. Low value refers to the underlying asset when new rather than the size or profitability of the lessee. Qualifying payments are generally recognised as expense systematically over the lease term.',
   'Changes in lease term, option assessment or index- and rate-based payments can require remeasurement using the applicable IFRS 16 mechanics. A separate lease arises from some modifications that add a right of use at a commensurate stand-alone price; other modifications adjust the existing balances. At FR level, follow the data and instruction supplied rather than inventing a modification.',
   'Present and disclose enough information for users to understand assets, liabilities, finance cost, depreciation and cash effects. In an exam answer, finish by reconciling closing liability and right-of-use asset, naming exemptions only when the facts qualify, and separating accounting measurement from a broader commercial judgement about whether leasing is economical.'
  ],supportPt:'Isenções podem existir para leases de curto prazo e ativos de baixo valor. Mudanças podem exigir remensuração, mas a resposta deve seguir os dados fornecidos e reconciliar passivo e ativo separadamente.',sourceIds:['ifrs-16']}
 ],
 terms:[
  {term:'Identified asset',meaning:'Asset explicitly or implicitly specified without a substantive supplier substitution right.',pt:'Ativo identificado',example:'A specified machine can be identified when substitution is not substantive.'},
  {term:'Right to control use',meaning:'Right to obtain economic benefits and direct use of the identified asset.',pt:'Direito de controlar o uso',example:'The customer decides how and for what purpose equipment is used.'},
  {term:'Lease liability',meaning:'Present value of lease payments not paid at commencement, subsequently rolled forward.',pt:'Passivo de arrendamento',example:'Interest increases and cash payments reduce the balance.'},
  {term:'Right-of-use asset',meaning:'Asset representing the lessee’s right to use an underlying asset.',pt:'Ativo de direito de uso',example:'It is initially linked to, but may differ from, the liability.'},
  {term:'Incremental borrowing rate',meaning:'Rate the lessee would pay to borrow for a similar term and security to obtain a similar-value asset.',pt:'Taxa incremental de empréstimo',example:'It is used when the implicit lease rate is not readily determinable.'},
  {term:'Lease term',meaning:'Non-cancellable period plus option periods included under the applicable certainty assessment.',pt:'Prazo do arrendamento',example:'A reasonably certain extension can affect measurement and depreciation.'}
 ],
 visual:{title:'Linked year-one lease schedules',note:'Original schedule; fictional CU amounts with CU90 opening liability, 10% interest, CU30 payment and CU98 right-of-use asset over four years.',headers:['Balance or expense','Calculation','CU'],rows:[['Finance cost','90 × 10%','9.0'],['Closing liability','90 + 9 − 30','69.0'],['ROU depreciation','98 ÷ 4 years','24.5'],['Year-one P/L charges','9 + 24.5','33.5']],question:'Why is the CU30 cash payment not the total year-one expense?',answer:'The normal lessee model separates CU9 finance cost and CU24.5 depreciation. Cash also repays part of the lease liability.'},
 caseStudy:{title:'Initial measurement and first-year lease accounting',scenario:['At commencement, the present value of four annual CU30,000 payments in arrears is CU90,000. The lease term is four years and ownership does not transfer.','The lessee pays CU4,000 qualifying initial direct costs, receives a CU2,000 lease incentive and recognises a CU6,000 restoration obligation.','The effective interest rate is 10%. The underlying asset’s useful life is six years.'],task:'Calculate the initial lease liability and right-of-use asset, year-one finance cost, cash reduction, closing liability and depreciation.',hints:['Start the right-of-use asset with the liability, then apply the three adjustments.','Because ownership does not transfer, compare lease term with useful life.'],modelAnswer:'Initial lease liability is CU90,000. Initial right-of-use asset is CU98,000 (90,000 + 4,000 − 2,000 + 6,000). Year-one finance cost is CU9,000 (90,000 × 10%). After the CU30,000 payment, closing liability is CU69,000. Depreciate the right-of-use asset over the four-year lease term, the shorter period because ownership does not transfer, giving CU24,500 per year. Before any impairment or remeasurement, its closing carrying amount is CU73,500.',reviewChecks:['Initial liability uses the supplied present value of unpaid payments.','Right-of-use adjustments reconcile to CU98,000.','Liability roll-forward gives CU69,000.','Four-year depreciation gives CU24,500 and closing ROU CU73,500.'],transfer:'Assume the payment is made at the start of each year instead. Explain why the timing of cash and interest in the first roll-forward must change.'},
 checkpoint:[
  {id:'acca-b6-q1',prompt:'What two control elements must the customer have?',options:['Legal title and insurance','Economic benefits and the right to direct use','A purchase option and residual guarantee','Maintenance and storage'],correctIndex:1,explanation:'Control requires substantially all economic benefits and the right to direct use.',reviewSection:'acca-b6-identify'},
  {id:'acca-b6-q2',prompt:'How is the initial lease liability measured?',options:['Total undiscounted payments in every case','Present value of lease payments not yet paid','Fair value of the underlying asset','One year of rental expense'],correctIndex:1,explanation:'The commencement liability is the present value of unpaid lease payments included in measurement.',reviewSection:'acca-b6-initial'},
  {id:'acca-b6-q3',prompt:'Which item can increase the right-of-use asset without increasing lease liability?',options:['Qualifying initial direct costs','Cash repayment of principal','Annual depreciation','Supplier substitution right'],correctIndex:0,explanation:'Initial direct costs are added to the right-of-use asset but are not unpaid lease payments.',reviewSection:'acca-b6-initial'},
  {id:'acca-b6-q4',prompt:'How does a payment in arrears affect the normal liability schedule?',options:['Deduct cash before all interest regardless of timing','Add effective interest, then deduct cash','Expense the entire payment only','Increase both liability and cash'],correctIndex:1,explanation:'For an in-arrears payment, interest accrues before the payment reduces the liability.',reviewSection:'acca-b6-subsequent'},
  {id:'acca-b6-q5',prompt:'When ownership does not transfer, which depreciation period is normally used?',options:['Always the useful life','Shorter of useful life and lease term','Always twelve months','Remaining liability duration plus one year'],correctIndex:1,explanation:'Without ownership transfer or the relevant purchase certainty, use the shorter of useful life and lease term.',reviewSection:'acca-b6-subsequent'}
 ],
 practiceExercises:[
  {id:'acca-b6-p1',question:'A lease liability opens at CU90, interest is 10% and CU30 is paid in arrears. Calculate closing liability.',hints:['Apply interest first.','Then deduct cash.'],answer:'Finance cost is CU9 and closing liability is CU69 (90 + 9 − 30).',explanation:'Payment timing controls the order of the roll-forward.'},
  {id:'acca-b6-p2',question:'Repair: “The right-of-use asset must always equal the lease liability.”',hints:['List commencement adjustments.','Keep the schedules separate.'],answer:'The right-of-use asset starts with the liability but is adjusted for prepayments, incentives, qualifying initial direct costs and restoration obligations, so the balances can differ.',explanation:'Related initial measurements are not necessarily identical.'},
  {id:'acca-b6-p3',question:'A seller-lessee transfers an asset at fair value and the transfer qualifies as a sale, then leases it back. Should it recognise the whole disposal gain?',hints:['Separate the right transferred from the right retained.','Use the sale-and-leaseback model.'],answer:'No. The seller-lessee recognises only the gain relating to the rights transferred to the buyer-lessor, recognises a right-of-use asset for the retained right and records the lease liability.',explanation:'A qualifying sale does not make the retained use disappear from the accounting.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ifrs-16',label:'IFRS Foundation · IFRS 16 Leases',url:'https://www.ifrs.org/issued-standards/list-of-standards/ifrs-16-leases/',supports:'Lease definition, single lessee model, right-of-use assets, lease liabilities and exemptions.',reviewedOn}
 ]
};
export function localModelB6For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='B6'?ACCA_B6_MODEL_MODULE:null;}
export {ACCA_B6_MODEL_ID,ACCA_B6_MODEL_SLUG};
