import type {LessonModule} from './lessonModules.ts';
import {ACCA_C4_MODEL_ID,ACCA_C4_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_C4_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'20–26',segments:['From profit objective to service mission and public accountability.','Funding restrictions, budgets and financial sustainability.','Economy, efficiency, effectiveness and outcome measures.','A stakeholder interpretation of a community-health case.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_C4_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask what mission the entity serves, who provides resources and who receives services before choosing a performance measure.',supportedPractice:'Connect financial sustainability with service volume, quality, outcomes, funding restrictions and accountability to the relevant stakeholder.',misconception:'A surplus is not the primary objective of every not-for-profit or public sector entity, but financial resources and liquidity still constrain delivery of the mission.',transfer:'Change the stakeholder, funding restriction, service volume, outcome rate or reporting framework and ask which conclusion changes.',close:'Recap mission, accountability, funding, sustainability and outcomes without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_C4_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_C4_MODEL_ID,title:'ACCA FR C4 · Not-for-profit and public sector entities',
 goal:'Explain how mission, users, funding and reporting requirements change interpretation for not-for-profit and public sector entities, while retaining disciplined analysis of sustainability and service outcomes.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level C4 mapping must be checked against the exact selected exam sitting before publication. Requirements vary by jurisdiction and entity; this lesson does not prescribe IFRS Accounting Standards, IPSAS Standards or charity law to every organisation. It is original teaching material, not ACCA approval, public-policy advice, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-c4-objectives',title:'1. Start with mission, service potential and accountability',paragraphs:[
   'A profit-oriented entity normally seeks sustainable returns for capital providers, although it also has wider stakeholders. A not-for-profit entity exists primarily to advance a mission rather than distribute profit to owners. A public sector entity commonly delivers services, redistributes resources or implements public policy. A surplus can protect future services, but maximising it is not automatically the primary performance objective.',
   'The user map therefore changes. Donors, grantors, members, service recipients, taxpayers, voters, legislatures, oversight bodies, lenders, employees and suppliers may need different information. In public sector general purpose reporting, the IPSASB framework focuses particularly on service recipients and resource providers and on information useful for accountability and decision-making.',
   'Interpretation should ask whether resources were obtained and used as authorised, whether the entity can continue delivering services and whether outputs or outcomes support its stated purpose. Financial statements remain important, but profit margin and shareholder return cannot answer those questions alone. Mission clarity is the starting point for selecting relevant measures.'
  ],supportPt:'O objetivo principal pode ser serviço ou missão, não maximização do lucro. Identifique provedores de recursos, beneficiários e órgãos de accountability antes de escolher métricas.',sourceIds:['acca-fr-syllabus','ipsasb-framework']},
  {id:'acca-c4-funding',title:'2. Interpret funding restrictions, budgets and sustainability',paragraphs:[
   'Funding may come from taxes, appropriations, grants, donations, membership fees, contracts or service charges rather than ordinary commercial sales. Some resources are restricted to a specified programme, capital project or period. A large restricted cash balance may therefore be unavailable for payroll or other general obligations. Inspect the nature, timing and enforceability of restrictions rather than treating all income and cash as interchangeable.',
   'Budget compliance can be central to accountability in public sector and grant-funded settings. Compare approved and actual amounts, explain material variances and distinguish authority to spend from accounting recognition. A favourable underspend may mean economy, delayed delivery, capacity constraints or failure to provide planned services. The applicable reporting framework and law determine the formal statements and budget disclosures; do not assume one universal model.',
   'Financial sustainability still matters. Review liquidity, debt, commitments, unrestricted reserves, asset condition, cash flows and dependence on a small number of funders. A deficit may be planned use of reserves for mission delivery, while repeated deficits without credible funding can threaten service continuity. A surplus can strengthen resilience or indicate that resources were not deployed as promised; context decides.'
  ],supportPt:'Funding restrito não é automaticamente disponível para custos gerais. Analise orçamento, variações, caixa, reservas livres, compromissos e concentração de funding sem confundir underspend com sucesso.',sourceIds:['acca-fr-syllabus','ipsasb-framework','ipsasb-handbook']},
  {id:'acca-c4-performance',title:'3. Combine economy, efficiency and effectiveness',paragraphs:[
   'Economy concerns acquiring suitable inputs at an appropriate cost and quality. Efficiency relates outputs to inputs—for example, service users supported per staff hour or programme cost per completed case. Effectiveness asks whether intended objectives and outcomes were achieved. A lower cost per user can indicate efficiency, but not if service quality, reach or outcomes deteriorate materially.',
   'Distinguish outputs from outcomes. Vaccinations delivered, training places provided or applications processed are outputs; improved health, employment or safe housing are outcomes. Outcomes can take time and depend on external factors, so attribution may be uncertain. Use baselines, targets, definitions and data-quality information, and avoid claiming that one entity caused every observed change.',
   'Relevant non-financial measures can include service volume, waiting time, completion, quality, beneficiary satisfaction, geographic or demographic coverage, safety and environmental impact. Ratios such as administration cost percentage can be useful but simplistic: necessary governance, safeguarding and systems may support durable mission delivery. Compare a balanced set rather than rewarding the lowest visible overhead.'
  ],supportPt:'Economy avalia inputs; efficiency relaciona inputs e outputs; effectiveness considera objetivos e outcomes. Menor custo não basta se qualidade, alcance ou resultado caem.',sourceIds:['acca-fr-syllabus','ipsasb-framework']},
  {id:'acca-c4-integrated',title:'4. Tailor conclusions to the entity and stakeholder',paragraphs:[
   'Begin with the entity’s objectives and reporting environment, then connect financial capacity to service evidence. A donor may focus on restrictions, programme delivery and stewardship; a service recipient on access and quality; a legislature or taxpayer on authority, sustainability and outcomes; a lender on liquidity and debt service. State whose decision the analysis supports.',
   'Comparisons require care. Entities may serve populations with different needs, count outputs differently, receive donated assets or volunteer labour, and operate under different legal and accounting frameworks. Targets can also create incentives to favour easy cases or redefine measures. Reconcile definitions and explain missing data instead of forcing a league table.',
   'A balanced conclusion acknowledges trade-offs. Higher service volume can coexist with lower outcome rates; stronger restricted funding can coexist with weaker unrestricted liquidity; a smaller surplus can reflect intentional programme investment or deteriorating control. Quantify each signal, explain plausible scenario-based causes and request evidence that would distinguish them.'
  ],supportPt:'Adapte a conclusão ao stakeholder e ao framework aplicável. Conecte capacidade financeira com volume, qualidade e outcomes, reconhecendo restrições, definições diferentes e trade-offs.',sourceIds:['acca-fr-syllabus','ipsasb-framework','ipsasb-handbook']}
 ],
 terms:[
  {term:'Service potential',meaning:'Capacity of a resource to support delivery of services rather than only generate cash.',pt:'Potencial de serviço',example:'A clinic building provides service potential to the community.'},
  {term:'Accountability',meaning:'Obligation to explain and justify use of entrusted resources and achievement of authorised purposes.',pt:'Prestação de contas',example:'A grantor compares restricted spending with the approved programme.'},
  {term:'Economy',meaning:'Obtaining suitable inputs at an appropriate cost and quality.',pt:'Economicidade',example:'Medicine purchasing must consider quality as well as price.'},
  {term:'Efficiency',meaning:'Relationship between resources used and outputs delivered.',pt:'Eficiência',example:'Total cost per service user falls from CU200 to CU190.'},
  {term:'Effectiveness',meaning:'Extent to which intended objectives or outcomes are achieved.',pt:'Efetividade',example:'The successful-outcome rate falls despite serving more people.'},
  {term:'Restricted funding',meaning:'Resources limited by enforceable or specified conditions to a particular purpose, period or activity.',pt:'Recursos restritos',example:'A programme grant may not be available for general payroll.'}
 ],
 visual:{title:'A balanced mission-performance dashboard',note:'Original framework; measures and reporting requirements must be adapted to the entity and jurisdiction.',headers:['Lens','Illustrative measure','Interpretation caution'],rows:[['Mission reach','Service users and coverage','Volume is not outcome quality'],['Efficiency','Cost per service user','Lower cost may reduce service quality'],['Effectiveness','Successful-outcome rate','External factors affect attribution'],['Stewardship','Restricted spend versus purpose','Restrictions limit resource flexibility'],['Sustainability','Unrestricted reserves and cash cover','One reporting date may be seasonal']],question:'Why can service-user growth and a falling outcome rate both be true?',answer:'The entity can serve more people while the mix, capacity, quality or external conditions reduce the percentage achieving the intended outcome; both volume and effectiveness must be reported.'},
 caseStudy:{title:'Community-health growth with tighter unrestricted resources',scenario:['A community-health not-for-profit reports 2026 total income CU2.40m, total expenditure CU2.28m and programme expenditure CU1.80m. In 2025 the amounts were CU2.00m, CU1.80m and CU1.35m. It supported 12,000 service users in 2026 and 9,000 in 2025.','Cash fell from CU0.40m to CU0.30m while current liabilities rose from CU0.30m to CU0.42m. Unrestricted reserves fell from CU0.45m to CU0.24m. Of 2026 income, CU0.90m is restricted to a two-year outreach programme and cannot be assumed available for general obligations; restricted income was CU0.50m in 2025.','The successful-outcome rate fell from 72% to 68% and beneficiary satisfaction from 88% to 82%. Definitions were applied consistently, but management has not yet provided waiting-time, staff-capacity or demographic-mix evidence.'],task:'Calculate financial and service indicators, then give a balanced conclusion for the governing board and a grantor.',hints:['Calculate surplus margin, total and programme cost per user, programme-spend proportion and cash coverage of current liabilities.','Separate volume from outcome rate and restricted resources from unrestricted resilience.'],modelAnswer:'The surplus fell from CU0.20m to CU0.12m, so surplus margin decreased from 10.0% to 5.0%. Service users increased 33.3%. Total cost per user improved from CU200 (CU1.80m / 9,000) to CU190 (CU2.28m / 12,000), while programme cost per user stayed CU150. Programme expenditure rose from 75.0% to 78.9% of total expenditure. Cash divided by current liabilities fell from 1.33 to 0.71, and unrestricted reserves fell by CU0.21m to CU0.24m, so general financial resilience weakened even though restricted funding increased. Successful outcomes increased in absolute terms from 6,480 to 8,160, but the outcome rate fell from 72% to 68% and satisfaction from 88% to 82%. The board should recognise greater reach and stable programme cost per user while investigating liquidity, capacity and quality. The grantor should test whether restricted resources were used for the authorised outreach outcomes. Obtain waiting times, staffing, beneficiary mix, restriction compliance and a cash forecast before concluding that efficiency gains are sustainable.',reviewChecks:['Surplus margin falls from 10.0% to 5.0%.','Total cost per user falls to CU190; programme cost per user remains CU150.','Cash coverage falls from 1.33 to 0.71 and unrestricted reserves decline.','Absolute successful outcomes rise to 8,160 while the rate and satisfaction fall.'],transfer:'Assume 2026 satisfaction stayed at 88%, unrestricted reserves were CU0.50m and 75% of the restricted grant remained unspent. Reassess the board and grantor conclusions.'},
 checkpoint:[
  {id:'acca-c4-q1',prompt:'What is normally the primary starting point for interpreting a not-for-profit entity?',options:['Maximising dividend per share','Its mission, service objectives and accountability','Its stock-market capitalisation','Its share-buyback policy'],correctIndex:1,explanation:'Measures should follow the entity’s purpose and the decisions of its resource providers and service users.',reviewSection:'acca-c4-objectives'},
  {id:'acca-c4-q2',prompt:'Why can a large cash balance fail to solve general liquidity pressure?',options:['Cash never belongs in financial statements','It may be restricted to a specified programme','Public entities cannot hold cash','Every grant is a liability'],correctIndex:1,explanation:'Restrictions can make resources unavailable for general obligations.',reviewSection:'acca-c4-funding'},
  {id:'acca-c4-q3',prompt:'Which measure most directly addresses effectiveness?',options:['Price paid per input','Number of staff hours','Percentage of beneficiaries achieving the intended outcome','Cash at year end'],correctIndex:2,explanation:'Effectiveness concerns achievement of objectives or outcomes.',reviewSection:'acca-c4-performance'},
  {id:'acca-c4-q4',prompt:'Why is a favourable budget underspend not automatically good performance?',options:['Budgets have no accountability role','It may reflect delayed or undelivered services','Expenditure is always better than outcomes','Only restricted funds can be budgeted'],correctIndex:1,explanation:'Lower spending can represent economy or failure to deliver, so service evidence is needed.',reviewSection:'acca-c4-funding'},
  {id:'acca-c4-q5',prompt:'What is the strongest conclusion from the worked case?',options:['Higher user volume proves every outcome improved','The smaller surplus proves failure','Reach and cost efficiency improved, but liquidity, unrestricted reserves, outcome rate and satisfaction require investigation','Restricted funding can pay any liability'],correctIndex:2,explanation:'A balanced conclusion connects financial sustainability with volume, efficiency, quality and restrictions.',reviewSection:'acca-c4-integrated'}
 ],
 practiceExercises:[
  {id:'acca-c4-p1',question:'A programme costs CU900,000 and delivers 6,000 completed services, of which 4,500 meet the intended outcome. Calculate cost per service and outcome rate.',hints:['Divide cost by completed services.','Divide successful outcomes by completed services.'],answer:'Cost per completed service is CU150 and the outcome rate is 75.0%. Both efficiency and effectiveness are needed for interpretation.',explanation:'One measure relates inputs to outputs; the other tests achievement.'},
  {id:'acca-c4-p2',question:'Repair: “The charity made a surplus, so it achieved its mission.”',hints:['Separate financial resilience from mission performance.','Name one service or outcome measure.'],answer:'A surplus may support resilience, but mission achievement requires evidence such as reach, quality, completion and beneficiary outcomes, together with compliance with funding restrictions.',explanation:'Financial capacity enables service but does not prove effectiveness.'},
  {id:'acca-c4-p3',question:'A public service spends 8% below budget but treats 15% fewer users than planned. What should the analyst investigate?',hints:['An underspend can have more than one cause.','Ask about capacity, demand, timing and outcomes.'],answer:'Investigate whether the underspend reflects genuine economy, lower demand, delayed delivery, staff or supply constraints, or exclusion of harder cases; compare quality and outcomes before judging performance.',explanation:'Budget variance must be interpreted beside authorised service delivery.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Current C4 outcome for interpreting not-for-profit and public sector entities.',reviewedOn},
  {id:'ipsasb-framework',label:'IPSASB · Conceptual Framework for General Purpose Financial Reporting by Public Sector Entities',url:'https://www.ipsasb.org/publications/conceptual-framework-general-purpose-financial-reporting-public-sector-entities-2023',supports:'Public sector users, accountability, decision-making and service-potential concepts.',reviewedOn},
  {id:'ipsasb-handbook',label:'IPSASB · 2026 Handbook of International Public Sector Accounting Standards Board Pronouncements',url:'https://www.ipsasb.org/standards-pronouncements',supports:'Current public sector standards and Conceptual Framework collection; jurisdictional application remains separate.',reviewedOn}
 ]
};
export function localModelC4For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='C4'?ACCA_C4_MODEL_MODULE:null;}
export {ACCA_C4_MODEL_ID,ACCA_C4_MODEL_SLUG};
