import type {LessonModule} from './lessonModules.ts';
import {ACCA_B3_MODEL_ID,ACCA_B3_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-21';
export const ACCA_B3_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'18–24',segments:['From impairment indicator to recoverable amount.','Fair value less costs of disposal versus value in use.','A narrated cash-generating unit allocation.','Retrieval pauses on reversals and goodwill.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_B3_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask what evidence suggests that carrying amount may no longer be recoverable.',supportedPractice:'Build the calculation in four steps: carrying amount, two recovery measures, higher amount, loss.',misconception:'Recoverable amount is the higher—not lower—of value in use and fair value less costs of disposal.',transfer:'Change one cash flow, disposal cost or CGU fact and ask the learner to recompute before explaining.',close:'Recap recognition, CGU allocation and reversal limits without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_B3_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_B3_MODEL_ID,title:'ACCA FR B3 · Impairment of assets',
 goal:'Identify impairment, calculate recoverable amount, allocate a cash-generating-unit loss and apply reversal limits using IAS 36 principles.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level B3 mapping must be checked against the exact selected exam sitting before publication. It is original teaching material, not ACCA approval, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-b3-identify',title:'1. Identify when an impairment review is required',paragraphs:[
   'An asset is impaired when its carrying amount exceeds the amount expected to be recovered through use or sale. At each reporting date, look for external indicators such as an unexpected fall in market value, adverse technological or economic change, or higher market interest rates, and internal indicators such as damage, obsolescence or performance below forecast. An indicator triggers an estimate; it does not itself determine the loss.',
   'Goodwill acquired in a business combination, an intangible asset with an indefinite useful life and an intangible asset not yet available for use require an annual impairment test. Other assets in the IAS 36 scope are tested when an indicator exists. Inventory, many financial assets and biological assets measured under IAS 41 follow their own Standards rather than being forced through IAS 36.',
   'Begin an exam response by establishing the reporting date, the asset or cash-generating unit, its carrying amount and why testing is required. Keep later events separate: evidence about conditions existing at the reporting date may affect the estimate, while a genuinely new event may require disclosure instead of changing the year-end number.'
  ],supportPt:'Impairment ocorre quando o valor contábil supera o valor recuperável. Indicadores externos ou internos normalmente acionam o teste; goodwill e certos intangíveis têm teste anual. Primeiro defina data, unidade contábil e evidência.',sourceIds:['ias-36','acca-fr-syllabus']},
  {id:'acca-b3-recoverable',title:'2. Calculate recoverable amount in the correct direction',paragraphs:[
   'Recoverable amount is the higher of fair value less costs of disposal and value in use. Fair value less costs of disposal reflects an orderly market-based exit amount after direct disposal costs. Value in use is entity-specific: estimate future cash flows from the asset in its current condition and discount them using an appropriate pre-tax rate that reflects time value and relevant risks without double counting.',
   'Compare recoverable amount with carrying amount only after selecting the higher recovery measure. If carrying amount is greater, recognise the difference as an impairment loss and reduce the asset. If recoverable amount equals or exceeds carrying amount, there is no impairment loss even when one of the two recovery measures is below carrying amount.',
   'Avoid mixing measurement bases. Do not subtract disposal costs from value in use, choose the lower measure for prudence, include unsupported future restructurings in current-condition cash flows, or discount a value that the question already presents as a present value. Label every number and show the comparison so the direction of the conclusion can be reviewed.'
  ],supportPt:'Valor recuperável é o maior entre valor justo menos custos de alienação e valor em uso. Compare esse maior valor ao valor contábil; só há perda quando o valor contábil é superior.',sourceIds:['ias-36']},
  {id:'acca-b3-cgu',title:'3. Test a cash-generating unit and allocate the loss safely',paragraphs:[
   'When an individual asset does not generate largely independent cash inflows, test the smallest identifiable cash-generating unit that does. Goodwill cannot normally be tested alone, so allocate it to the unit or group of units expected to benefit from the business combination. The unit must be defined consistently unless a justified change produces a better representation.',
   'For an impaired cash-generating unit, allocate the loss first to goodwill and then pro rata to the other assets. An individual asset must not be reduced below the highest of its own fair value less costs of disposal, its own value in use when determinable, and zero. Any amount blocked by that floor is reallocated across the remaining eligible assets.',
   'The allocation sequence matters because it protects identifiable assets from arbitrary write-downs and makes goodwill absorb the first loss. After recognition, calculate future depreciation or amortisation using the revised carrying amount and remaining useful life. In a structured answer, reconcile the unit before and after allocation and explicitly check every asset floor.'
  ],supportPt:'Se o ativo não gera entradas independentes, teste a menor UGC adequada. A perda reduz primeiro o goodwill e depois os demais ativos proporcionalmente, respeitando o piso individual aplicável.',sourceIds:['ias-36']},
  {id:'acca-b3-reversal',title:'4. Reassess reversals without recreating past depreciation',paragraphs:[
   'At later reporting dates, consider whether a recognised impairment loss has decreased. For assets other than goodwill, a reversal is recognised when the estimates used to determine recoverable amount have changed. The revised carrying amount cannot exceed the amount that would have existed, net of normal depreciation or amortisation, if no impairment had ever been recognised.',
   'An impairment loss recognised for goodwill is never reversed. For a cash-generating unit, a permitted reversal is allocated to assets other than goodwill, subject to each asset’s ceiling. After a reversal, prospective depreciation or amortisation is adjusted again over the remaining useful life.',
   'Do not reverse merely because management feels more optimistic. Identify a supportable change in recovery evidence, recompute recoverable amount and apply the no-impairment counterfactual ceiling. The answer should distinguish a new estimate from correction of an earlier error and should state whether profit or loss or a revaluation route is relevant to the asset supplied.'
  ],supportPt:'A reversão exige mudança sustentada nas estimativas e não pode elevar o ativo acima do valor líquido que existiria sem a perda anterior. Perda de goodwill nunca é revertida.',sourceIds:['ias-36']}
 ],
 terms:[
  {term:'Impairment loss',meaning:'Excess of carrying amount over recoverable amount.',pt:'Perda por impairment',example:'Carrying amount 900 minus recoverable amount 760 gives a loss of 140.'},
  {term:'Recoverable amount',meaning:'Higher of fair value less costs of disposal and value in use.',pt:'Valor recuperável',example:'The higher recovery measure is compared with carrying amount.'},
  {term:'Value in use',meaning:'Present value of cash flows expected from use and ultimate disposal in the asset’s current condition.',pt:'Valor em uso',example:'Current-condition cash flows are discounted consistently.'},
  {term:'Fair value less costs of disposal',meaning:'Fair value reduced by direct incremental disposal costs.',pt:'Valor justo menos custos de alienação',example:'Market value 820 less disposal costs 20 equals 800.'},
  {term:'Cash-generating unit',meaning:'Smallest group producing cash inflows largely independent from other assets.',pt:'Unidade geradora de caixa',example:'A store may be a CGU when it has independent inflows.'},
  {term:'Reversal ceiling',meaning:'Carrying amount that would exist net of depreciation if the prior loss had not occurred.',pt:'Limite de reversão',example:'Recovery cannot recreate depreciation that would already have been charged.'}
 ],
 visual:{title:'IAS 36 decision and calculation path',note:'Original calculation map; values are fictional and shown in CU.',headers:['Step','Evidence or calculation','Result'],rows:[['Trigger','Adverse demand and damaged equipment','Test required'],['Recovery measure 1','FVLCD: 780 − 20','760'],['Recovery measure 2','Value in use','810'],['Comparison','Carrying amount 900 vs recoverable amount 810','Impairment loss 90']],question:'Why is the recoverable amount 810 rather than 760?',answer:'IAS 36 uses the higher of value in use and fair value less costs of disposal because the entity can recover through the better of use or sale.'},
 caseStudy:{title:'Allocate a CGU impairment with an asset floor',scenario:['A CGU has goodwill of CU40, equipment A of CU120 and equipment B of CU240. Its carrying amount is CU400 and recoverable amount is CU310.','Equipment A has an individual fair value less costs of disposal of CU110; its value in use cannot be determined separately.','Assume no revaluation accounting is involved.'],task:'Calculate the impairment loss, allocate it within the CGU and explain the protection provided by the individual asset floor.',hints:['Reduce goodwill first.','The remaining loss is allocated pro rata, but A cannot fall below CU110.'],modelAnswer:'The CGU impairment is CU90 (400 − 310). Allocate CU40 first to goodwill, reducing it to zero. The remaining CU50 would initially be allocated between A and B in their 120:240 ratio: CU16.67 to A and CU33.33 to B. A may fall only from CU120 to its CU110 floor, so only CU10 is allocated to A. Reallocate the blocked CU6.67 to B. Final carrying amounts are goodwill nil, A CU110 and B CU200, totalling the CU310 recoverable amount.',reviewChecks:['Recoverable amount is compared with the total CGU carrying amount.','Goodwill absorbs the first CU40.','A’s individual floor is applied.','The final carrying amounts reconcile to CU310.'],transfer:'Assume the CGU later recovers to CU350. Explain why the goodwill loss remains and what ceiling must be checked before reversing losses on A and B.'},
 checkpoint:[
  {id:'acca-b3-q1',prompt:'Which amount is recoverable amount?',options:['The lower of value in use and FVLCD','The higher of value in use and FVLCD','Carrying amount before depreciation','Historical cost'],correctIndex:1,explanation:'Recoverable amount is the higher amount recoverable through use or sale.',reviewSection:'acca-b3-recoverable'},
  {id:'acca-b3-q2',prompt:'When is a typical IAS 36 asset tested?',options:['Only when sold','When an impairment indicator exists','Every month regardless of evidence','Only after cash is received'],correctIndex:1,explanation:'Most assets are tested when indicators exist; goodwill and specified intangibles have annual testing requirements.',reviewSection:'acca-b3-identify'},
  {id:'acca-b3-q3',prompt:'Which CGU item absorbs an impairment loss first?',options:['Inventory','Goodwill','Cash','The newest asset'],correctIndex:1,explanation:'Goodwill is reduced first, then other eligible assets pro rata subject to floors.',reviewSection:'acca-b3-cgu'},
  {id:'acca-b3-q4',prompt:'Can an impairment loss on goodwill be reversed?',options:['Yes, whenever profit improves','Yes, after one year','No','Only through revenue'],correctIndex:2,explanation:'IAS 36 prohibits reversal of an impairment loss recognised for goodwill.',reviewSection:'acca-b3-reversal'},
  {id:'acca-b3-q5',prompt:'What limits a reversal for another asset?',options:['Original cash price only','The amount management requests','The carrying amount that would exist without the prior impairment','Zero in every case'],correctIndex:2,explanation:'The reversal cannot exceed the no-impairment carrying amount after normal depreciation or amortisation.',reviewSection:'acca-b3-reversal'}
 ],
 practiceExercises:[
  {id:'acca-b3-p1',question:'An asset has carrying amount CU620, value in use CU570 and fair value less costs of disposal CU590. Calculate impairment.',hints:['Choose the higher recovery measure.','Compare it with carrying amount.'],answer:'Recoverable amount is CU590, the higher of CU570 and CU590. The impairment loss is CU30 (CU620 − CU590).',explanation:'Do not choose the lower amount in the name of prudence.'},
  {id:'acca-b3-p2',question:'Repair: “A CGU loss is allocated proportionately to every asset, including goodwill.”',hints:['State the sequence.','Mention individual floors.'],answer:'Allocate the CGU impairment first to goodwill, then pro rata to other eligible assets, without reducing an asset below its applicable individual floor.',explanation:'Goodwill-first allocation and asset floors are separate controls.'},
  {id:'acca-b3-p3',question:'A non-goodwill asset recovers. Its recoverable amount is CU480, but without the old impairment its net carrying amount would be CU450. To what amount may it be reversed?',hints:['Apply the reversal ceiling.','Use the lower permitted closing amount.'],answer:'The asset may be increased only to CU450. The reversal ceiling prevents the carrying amount exceeding the amount that would exist after normal depreciation without the original impairment.',explanation:'A reversal restores lost carrying amount; it does not erase depreciation.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ias-36',label:'IFRS Foundation · IAS 36 Impairment of Assets',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-36-impairment-of-assets/',supports:'Indicators, recoverable amount, CGUs, allocation, recognition and reversals.',reviewedOn}
 ]
};
export function localModelB3For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='B3'?ACCA_B3_MODEL_MODULE:null;}
export {ACCA_B3_MODEL_ID,ACCA_B3_MODEL_SLUG};
