import type {LessonModule} from './lessonModules.ts';
import {ACCA_C3_MODEL_ID,ACCA_C3_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_C3_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'21–27',segments:['Why a precise ratio can still support a weak conclusion.','Accounting-policy and measurement comparability traps.','Cash-flow evidence beside accrual performance.','Profit growth versus EPS growth and denominator effects.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_C3_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask which conclusion is being drawn, which comparator supports it and what limitation could change it.',supportedPractice:'Separate calculation accuracy from interpretation reliability, connect profit to cash and identify policy, denominator or data-quality effects.',misconception:'Ratios and EPS are useful indicators, not self-explanatory facts; a movement can arise from accounting choices, transaction timing or a changed share base.',transfer:'Change the accounting policy, cash-flow pattern, comparator or number of shares and ask which conclusion survives.',close:'Recap ratio limits, comparability, cash-flow corroboration and EPS limitations without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_C3_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_C3_MODEL_ID,title:'ACCA FR C3 · Limitations of interpretation techniques',
 goal:'Explain why ratio and EPS trends can mislead, assess accounting-policy comparability, and use cash-flow information to confirm or challenge accrual performance.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level C3 mapping must be checked against the exact selected exam sitting before publication. It teaches critical interpretation, not valuation, audit assurance or a mechanical list of “good” ratios. It is original teaching material, not ACCA approval, investment advice, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-c3-ratio-limits',title:'1. Treat ratio analysis as a question generator, not a verdict',paragraphs:[
   'A ratio compresses accounting information into a relationship, making trends and comparisons easier to see. That usefulness also removes detail. The same current ratio can combine collectible receivables with obsolete inventory or the reverse; the same margin can arise from different product mixes, markets and risks. Calculation accuracy therefore does not guarantee a reliable conclusion.',
   'Ratios depend on the quality, timing and classification of their inputs. Year-end figures may be seasonal or deliberately managed, averages may be unavailable, inflation can make amounts from different years economically unlike, and one-off transactions can dominate a period. Different definitions—such as debt divided by equity rather than debt divided by debt plus equity—also produce different numbers. State the formula and use a consistent basis before comparing.',
   'A benchmark must be genuinely relevant. Industry averages may hide size, geography, business-model and life-cycle differences; a competitor can have different year ends or segment mix; one prior period may be exceptional. Ratios rarely identify causation. Use them to locate an issue, quantify its direction and ask for disaggregated, non-financial and forward-looking evidence rather than attaching a generic cause.'
  ],supportPt:'Um ratio resume informação e aponta onde investigar, mas não prova a causa. Verifique qualidade dos dados, timing, fórmula, sazonalidade e relevância do benchmark antes de concluir.',sourceIds:['acca-fr-syllabus','acca-interpretation']},
  {id:'acca-c3-policies',title:'2. Restore comparability when policies or estimates differ',paragraphs:[
   'A change in accounting policy can create a break in a time series. IAS 8 generally requires voluntary policy changes to be applied retrospectively when practicable, which can restore comparable amounts, but an analyst must still read the nature, reason and quantified effect of the change. A change in estimate reflects new information and is normally prospective, so it may alter current and future results without restating the past.',
   'Two entities may apply different permitted policies or measurement bases. Cost versus revaluation for property, different inventory cost formulas for interchangeable items where permitted, or different presentation and classification choices can affect assets, expenses and ratios. Estimates—useful lives, residual values, impairment assumptions and expected credit losses—also differ even when the headline policy is the same.',
   'Do not “correct” a comparator with invented adjustments. Identify the difference, use disclosed reconciliations or a transparent sensitivity where reliable facts permit, and explain any remaining uncertainty. A consistent calculation based on inconsistent accounting inputs can create false precision. Notes, policy disclosures and segment information are part of the evidence, not an optional appendix.'
  ],supportPt:'Políticas, bases de mensuração e estimativas podem romper a comparabilidade. Use restatements e disclosures disponíveis; não invente ajustes apenas para produzir números aparentemente comparáveis.',sourceIds:['acca-fr-syllabus','acca-interpretation']},
  {id:'acca-c3-cashflow',title:'3. Compare cash generation with accrual performance',paragraphs:[
   'Profit or loss measures performance using accrual accounting: income and expenses are recognised when the applicable criteria are met, not simply when cash moves. The statement of cash flows explains operating, investing and financing cash movements. It can reveal whether reported profit is converting into operating cash, how assets are being renewed and whether dividends or expansion are funded internally, by debt or by equity.',
   'Cash flow is not automatically superior to profit. A healthy entity can report weak operating cash in a growth period because receivables or inventory rise, while delaying suppliers can temporarily strengthen cash. Investing outflows may represent productive capacity rather than deterioration; financing inflows increase cash but not operating success. Conversely, asset sales can support liquidity while weakening future capacity.',
   'Reconcile related signals. Compare operating cash with operating profit over more than one period, inspect working-capital movements, separate maintenance from expansion investment where evidence permits, and connect financing flows to gearing and interest cover. Cash data is less affected by some estimates but still depends on classification, timing and the completeness of the period analysed.'
  ],supportPt:'Profit usa accrual accounting; cash flow explica movimentos operacionais, de investimento e financiamento. Nenhum é “melhor” isoladamente: reconcilie lucro, capital de giro, investimento e funding ao longo do tempo.',sourceIds:['acca-fr-syllabus','acca-cashflows','acca-interpretation']},
  {id:'acca-c3-eps',title:'4. Distinguish company profit growth from return per ordinary share',paragraphs:[
   'Profit is an entity-level amount; earnings per share relates earnings attributable to ordinary equity holders to the weighted-average ordinary shares outstanding. Profit can rise while basic EPS falls if the share base grows faster. EPS can therefore be a more relevant trend for an ordinary shareholder and is widely used with market price in indicators such as the price/earnings ratio.',
   'EPS improves denominator discipline but does not remove accounting limitations. Earnings retain policy, estimate, acquisition and one-off effects. Share buy-backs can increase EPS without improving operations, while a new issue can reduce EPS before the capital contributes a full period of profit. Basic EPS also excludes the possible denominator effect of dilutive instruments that diluted EPS is designed to reflect.',
   'Market relevance is not the same as a complete performance measure. EPS says nothing directly about cash generation, risk, capital required, distribution capacity, service quality or sustainability. Compare basic and diluted EPS, reconcile the earnings and share movements, inspect continuing and discontinued operations where relevant, and interpret market price as an external expectation rather than accounting evidence.'
  ],supportPt:'EPS relaciona earnings atribuíveis com a média ponderada de ações e pode contar uma história diferente do lucro total. Ainda depende da qualidade dos earnings, do denominador e de contexto sobre caixa, risco e capital.',sourceIds:['acca-fr-syllabus','ias-33','acca-interpretation']}
 ],
 terms:[
  {term:'Ratio limitation',meaning:'Feature of data, definition or context that weakens the conclusion supported by a ratio.',pt:'Limitação do índice',example:'A seasonal closing balance can distort a days ratio.'},
  {term:'Comparability',meaning:'Ability to identify similarities and differences using sufficiently consistent information.',pt:'Comparabilidade',example:'Different measurement bases can weaken a peer comparison.'},
  {term:'Accounting policy',meaning:'Specific principles, bases and practices applied in preparing financial statements.',pt:'Política contábil',example:'A disclosed policy change can break an unadjusted trend.'},
  {term:'Cash conversion',meaning:'Relationship between reported performance and cash generated from operations.',pt:'Conversão em caixa',example:'Operating cash of CU62m is only 43.1% of operating profit of CU144m.'},
  {term:'EPS trend',meaning:'Movement in earnings attributable to each weighted-average ordinary share.',pt:'Tendência do lucro por ação',example:'Profit rises but EPS falls after a large share issue.'},
  {term:'False precision',meaning:'Appearance of exactness that exceeds the reliability or comparability of underlying data.',pt:'Falsa precisão',example:'A ratio to two decimals may still compare inconsistent policies.'}
 ],
 visual:{title:'Four signals, four interpretation limits',note:'Original analytical map; a limitation weakens certainty but does not make the information useless.',headers:['Reported signal','What it adds','What may still mislead'],rows:[['Operating margin 12% in both years','Shows stable profit per revenue unit','Mix, policy and one-off changes'],['Operating cash / operating profit 43.1%','Challenges accrual-to-cash conversion','Growth working capital or classification'],['Profit after tax +12.5%','Shows entity-level earnings growth','Changed share base and one-offs'],['Basic EPS −25.0%','Shows lower earnings per weighted share','Issue timing and future use of new capital'],['Peer ROCE is higher','Provides external benchmark','Different age, valuation and policy of assets']],question:'Why can the EPS trend be more shareholder-relevant than the profit trend without being a complete performance measure?',answer:'EPS includes the weighted share base, but it still inherits earnings limitations and excludes cash, risk, capital needs and many non-financial outcomes.'},
 caseStudy:{title:'Profit growth, weak cash conversion and a larger share base',scenario:['A listed entity reports 2026 revenue CU1,200m, operating profit CU144m, profit attributable to ordinary shareholders CU90m and cash generated from operations CU62m. In 2025 the amounts were CU1,000m, CU120m, CU80m and CU115m.','Trade receivables rose from CU140m to CU240m and inventory from CU160m to CU210m. During 2026 the entity spent CU180m on property, plant and equipment, raised a CU150m loan and paid CU40m dividends. Further evidence is needed to distinguish maintenance from expansion investment.','Weighted-average ordinary shares were 120m in 2026 and 80m in 2025 following an equity issue. A peer reports a higher ROCE but revalues property while this entity uses cost.'],task:'Calculate key growth, margin, cash-conversion and EPS movements, then explain the limitations of a simple “performance improved” conclusion.',hints:['Compare revenue and profit growth with stable operating margin and operating cash conversion.','Calculate EPS from attributable profit and weighted-average shares, then inspect the peer’s measurement basis.'],modelAnswer:'Revenue grew 20.0% and operating profit also grew 20.0%, leaving operating margin unchanged at 12.0%. Profit attributable to ordinary shareholders rose 12.5%. However, operating cash divided by operating profit fell from 95.8% (CU115m / CU120m) to 43.1% (CU62m / CU144m), consistent with—but not proved solely by—the increases in receivables and inventory. The CU180m investing outflow may support future capacity, while the CU150m loan shows significant external funding and the CU40m dividend uses cash. Basic EPS fell from CU1.00 (CU80m / 80m shares) to CU0.75 (CU90m / 120m shares), a 25.0% decline, because the weighted share base rose faster than earnings. For an ordinary shareholder, that contradicts a conclusion based only on total profit growth. The peer ROCE comparison is also weakened by different property measurement bases. Review receivables ageing, inventory quality, investment purpose, policy disclosures, diluted EPS and future returns from the new equity before concluding.',reviewChecks:['Revenue and operating profit grow 20.0%; operating margin remains 12.0%.','Operating-cash conversion falls from 95.8% to 43.1%.','Basic EPS falls from CU1.00 to CU0.75, a 25.0% decline.','Different property measurement bases weaken the peer ROCE comparison.'],transfer:'Assume 2026 weighted-average shares were 90m and operating cash was CU130m. Recalculate EPS and cash conversion, then identify which limitations remain.'},
 checkpoint:[
  {id:'acca-c3-q1',prompt:'Why does a correctly calculated ratio not guarantee a reliable conclusion?',options:['Ratios may compress weak, incomparable or unrepresentative inputs','Every ratio must be audited separately','Ratios cannot compare periods','Only cash amounts are useful'],correctIndex:0,explanation:'Arithmetic can be correct while definitions, data quality, timing or comparators remain weak.',reviewSection:'acca-c3-ratio-limits'},
  {id:'acca-c3-q2',prompt:'What is the responsible response to different permitted accounting policies?',options:['Invent an adjustment until ratios match','Ignore the notes','Use reliable disclosures or sensitivities and explain residual uncertainty','Conclude the entity with higher assets performs better'],correctIndex:2,explanation:'Transparent, evidence-based adjustments preserve rather than manufacture comparability.',reviewSection:'acca-c3-policies'},
  {id:'acca-c3-q3',prompt:'Why might operating cash fall during genuine growth?',options:['Profit must be wrong','Receivables or inventory may absorb cash','Financing inflows are operating cash','Depreciation is a cash payment'],correctIndex:1,explanation:'Growth in working capital can reduce operating cash even when accrual performance grows.',reviewSection:'acca-c3-cashflow'},
  {id:'acca-c3-q4',prompt:'How can profit rise while basic EPS falls?',options:['The weighted-average share base rises faster than attributable earnings','EPS excludes ordinary shareholders','Cash must always be negative','Revenue is omitted from profit'],correctIndex:0,explanation:'EPS introduces a per-share denominator that total profit does not contain.',reviewSection:'acca-c3-eps'},
  {id:'acca-c3-q5',prompt:'What is the strongest conclusion from the worked case?',options:['The 20% revenue growth proves performance improved','The EPS fall proves the equity issue destroyed value','Growth is visible, but weak cash conversion, lower EPS and policy differences require more evidence','The loan is operating income'],correctIndex:2,explanation:'The integrated conclusion recognises useful signals and their limitations without claiming an unsupported cause.',reviewSection:'acca-c3-eps'}
 ],
 practiceExercises:[
  {id:'acca-c3-p1',question:'Profit attributable rises from CU60m to CU72m while weighted-average shares rise from 50m to 80m. Calculate both EPS figures and their movement.',hints:['Divide attributable profit by weighted-average shares.','Compare CU0.90 with the prior result.'],answer:'EPS falls from CU1.20 to CU0.90, a 25.0% decline, even though total attributable profit rises 20.0%.',explanation:'The larger denominator changes the ordinary shareholder trend.'},
  {id:'acca-c3-p2',question:'Repair: “Operating cash is lower than profit, so the profit is fraudulent.”',hints:['A difference is a signal, not proof of intent.','Identify working-capital and non-cash evidence to inspect.'],answer:'Lower operating cash may reflect receivable or inventory growth, non-cash expenses, timing or classification. Reconcile those movements over several periods before assessing earnings quality or intent.',explanation:'Cash-flow analysis challenges and explains accrual performance but does not prove fraud by itself.'},
  {id:'acca-c3-p3',question:'Two peers report ROCE of 14% and 18%, but one revalues property and the other holds old assets at cost. What should the analyst say?',hints:['Consider the capital-employed denominator.','Do not rank the entities without policy evidence.'],answer:'The ratios are not directly comparable because the property measurement bases can materially change capital employed. Use disclosed values or a transparent sensitivity if reliable, and retain the limitation.',explanation:'Consistent formulas cannot repair inconsistent measurement inputs on their own.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Current C3 outcomes for ratio limitations, policies, cash flow and EPS.',reviewedOn},
  {id:'acca-interpretation',label:'ACCA · How to improve your answer to FR interpretation exam questions',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/technical-articles/interpretation-questions.html',supports:'Evidence-linked comparison, ratio relationships and scenario-specific interpretation.',reviewedOn},
  {id:'acca-cashflows',label:'ACCA · Analysing a statement of cash flows',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/technical-articles/analysing-cashflows.html',supports:'Operating, investing and financing cash-flow analysis in the FR context.',reviewedOn},
  {id:'ias-33',label:'IFRS Foundation · IAS 33 Earnings per Share',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-33-earnings-per-share/',supports:'Purpose, scope, basic and diluted EPS, numerator and weighted-average denominator principles.',reviewedOn}
 ]
};
export function localModelC3For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='C3'?ACCA_C3_MODEL_MODULE:null;}
export {ACCA_C3_MODEL_ID,ACCA_C3_MODEL_SLUG};
