import type {LessonModule} from './lessonModules.ts';
import {ACCA_B2_MODEL_ID,ACCA_B2_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_B2_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'22–28',segments:['Identifiability, control and recognition.','Separate acquisition, research and development.','Six development criteria and the recognition cut-off.','Finite versus indefinite lives and a narrated amortisation schedule.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_B2_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask whether the intangible is separately acquired or internally generated and when every development criterion became demonstrable.',supportedPractice:'Build a dated expenditure timeline before calculating capitalisation and amortisation; offer one criterion-focused hint before revealing the cut-off.',misconception:'Later project success does not reinstate research or development expenditure that was correctly expensed before all criteria were met.',transfer:'Change the feasibility date, funding evidence, available-for-use date, useful life or renewal facts and ask for the revised treatment.',close:'Recap identifiability, research expense, development cut-off and subsequent measurement without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_B2_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_B2_MODEL_ID,title:'ACCA FR B2 · Intangible assets and development expenditure',
 goal:'Classify intangible expenditure, apply all development criteria at the correct date and calculate amortisation and carrying amount.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level B2 mapping must be checked against the exact selected exam sitting before publication. It focuses on core IAS 38 treatment and does not replace a complete impairment, business-combination or disclosure analysis. It is original teaching material, not ACCA approval, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-b2-definition',title:'1. Identify and recognise an intangible asset',paragraphs:[
   'An intangible asset is an identifiable non-monetary asset without physical substance. It is identifiable when it is separable or arises from contractual or other legal rights. The entity must control the resource and expect future economic benefits; physical form is unnecessary, but an idea or skilled workforce does not automatically create a controlled asset.',
   'Recognise an intangible asset when future benefits are probable and cost can be measured reliably. A separately acquired intangible normally meets those probability and measurement conditions through its purchase price. Initial cost can include directly attributable preparation costs, but advertising, training, start-up and general overhead do not become intangible assets merely because future benefits are hoped for.',
   'Goodwill acquired in a business combination follows IFRS 3. Internally generated goodwill is not recognised because its cost cannot be distinguished reliably from developing the business as a whole. Internally generated brands, mastheads, publishing titles, customer lists and similar items are also prohibited when the applicable IAS 38 restriction applies.'
  ],supportPt:'O intangível deve ser identificável, controlado, não monetário e sem substância física. Compra separada difere de goodwill interno, marcas e listas geradas internamente, que enfrentam proibições específicas.',sourceIds:['ias-38','acca-fr-syllabus']},
  {id:'acca-b2-research',title:'2. Separate research from development',paragraphs:[
   'Research is original and planned investigation undertaken to gain new knowledge and understanding. Research expenditure is recognised as an expense when incurred because the entity cannot yet demonstrate an intangible asset that will generate probable future benefits. If research and development phases cannot be distinguished, treat the expenditure as research.',
   'Development applies research findings or knowledge to a plan or design for new or substantially improved products, processes, systems or services before commercial production or use. The label in a project budget does not decide the phase: use the activities and evidence at each date.',
   'Once an amount is expensed, later success does not retrospectively turn it into an asset. Build a timeline of expenditure and evidence so the capitalisation cut-off is explicit and auditable.'
  ],supportPt:'Pesquisa é despesa. Desenvolvimento só começa quando as atividades e evidências mudam; se as fases não forem separáveis, trate como pesquisa. Custos já lançados não são reativados depois.',sourceIds:['ias-38']},
  {id:'acca-b2-development',title:'3. Capitalise development only after every criterion is demonstrated',paragraphs:[
   'Capitalise development expenditure only when the entity demonstrates technical feasibility; intention to complete; ability to use or sell; probable future benefits, including a market or internal usefulness; adequate technical, financial and other resources; and ability to measure attributable expenditure reliably. The six conditions operate as a complete set.',
   'The recognition date is when all criteria first become demonstrable, not when management first hopes for success or when the final product launches. Capitalised cost includes directly attributable expenditure from that date. Earlier research and pre-criteria development remain expenses, and later abnormal waste or selling costs are excluded.',
   'Evidence can include approved technical milestones, market or internal-use analysis, funding and staffing plans, and reliable project-cost records. Avoid repeating management assertions without support. When a criterion is missing, state what evidence is needed rather than inventing a capitalisation date.'
  ],supportPt:'Os seis critérios funcionam juntos. Capitalize somente a partir da data em que todos são demonstráveis; custos anteriores continuam como despesa, mesmo se o projeto tiver sucesso depois.',sourceIds:['ias-38']},
  {id:'acca-b2-subsequent',title:'4. Amortise finite lives and test indefinite lives appropriately',paragraphs:[
   'A finite-life intangible is amortised systematically over useful life from the date it is available for use. Residual value is normally zero unless a third party has committed to purchase the asset or an active market is expected to exist. Review useful life and method at least annually and treat changes prospectively as estimates.',
   'An indefinite useful life means no foreseeable limit to the period of net cash inflows; it does not mean infinite. Do not amortise while the life is indefinite, but test annually for impairment and reconsider the life each period. An intangible not yet available for use is also tested annually for impairment.',
   'Under the cost model, carry the asset at cost less accumulated amortisation and impairment. The revaluation model is available only when fair value can be measured by reference to an active market, which is uncommon for many unique intangibles. Derecognise on disposal or when no benefits are expected.'
  ],supportPt:'Intangível de vida finita é amortizado quando disponível para uso. Vida indefinida não é “eterna”: não há amortização, mas há teste anual de impairment e revisão da vida útil.',sourceIds:['ias-38','ias-36']}
 ],
 terms:[
  {term:'Identifiable',meaning:'Separable or arising from contractual or other legal rights.',pt:'Identificável',example:'A patent arising from legal rights can be identifiable.'},
  {term:'Research phase',meaning:'Investigation seeking new knowledge before a development asset can be demonstrated.',pt:'Fase de pesquisa',example:'Alternative materials are explored before feasibility is established.'},
  {term:'Development phase',meaning:'Application of knowledge to a plan or design before commercial use.',pt:'Fase de desenvolvimento',example:'A technically feasible prototype is refined for production.'},
  {term:'Capitalisation cut-off',meaning:'Date from which all development recognition criteria are demonstrable.',pt:'Data de corte da capitalização',example:'Only eligible expenditure after 1 July is capitalised.'},
  {term:'Finite useful life',meaning:'Limited period over which benefits are expected.',pt:'Vida útil definida',example:'A five-year product right is amortised over its useful life.'},
  {term:'Indefinite useful life',meaning:'No foreseeable limit to the benefit period based on current evidence.',pt:'Vida útil indefinida',example:'The asset is not amortised but is tested annually for impairment.'}
 ],
 visual:{title:'Development expenditure timeline',note:'Original fictional amounts in CU; all six criteria are first demonstrated on 1 July.',headers:['Period','Evidence status','Accounting'],rows:[['January–March','Research','Expense CU90'],['April–June','Development but criteria incomplete','Expense CU60'],['July–September','All criteria demonstrated','Capitalise CU240'],['1 October','Available for use','Begin amortisation'],['October–December','Five-year finite life','Amortisation CU12']],question:'Why is the CU60 from April–June not added to the asset after the project succeeds?',answer:'The recognition criteria were not all demonstrated when that expenditure was incurred. IAS 38 does not reinstate amounts previously recognised as expenses.'},
 caseStudy:{title:'A dated software-development decision',scenario:['Research from January to March costs CU90. Development begins in April. Costs are CU20 per month.','Technical feasibility and intention are supported on 1 May, but funding and reliable project-cost measurement are demonstrated only on 1 July. A market, ability to complete and adequate staff are also supported on 1 July.','The software is available for use on 1 October, has a five-year finite life and zero residual value. Costs continue through September; year-end is 31 December.'],task:'Calculate expense, capitalised development, amortisation and closing carrying amount, and explain the cut-off.',hints:['All six criteria are first demonstrated on 1 July.','Capitalise July–September, then amortise for three months from availability.'],modelAnswer:'Expense CU90 research plus CU60 development incurred from April through June, for total pre-capitalisation expense of CU150. Capitalise CU60 incurred from July through September because all six criteria are first demonstrated on 1 July. The software is available for use on 1 October, so annual amortisation is CU12 (60 / 5) and three months is CU3. Closing carrying amount is CU57. Later success does not reinstate the CU150 expense, and amortisation does not begin on the capitalisation date while development is still in progress.',reviewChecks:['All criteria—not only feasibility—determine the 1 July cut-off.','CU150 remains expensed.','Capitalised cost is CU60.','Three-month amortisation is CU3 and closing amount CU57.'],transfer:'Assume the software is not available for use until 1 January 2027. Explain amortisation and year-end impairment requirements.'},
 checkpoint:[
  {id:'acca-b2-q1',prompt:'Which feature makes an intangible identifiable?',options:['It has no invoice','It is separable or arises from contractual/legal rights','It is profitable','It has physical form'],correctIndex:1,explanation:'Identifiability comes from separability or contractual or legal rights.',reviewSection:'acca-b2-definition'},
  {id:'acca-b2-q2',prompt:'How is research expenditure treated?',options:['Capitalised automatically','Expensed when incurred','Recorded in equity','Deferred until launch'],correctIndex:1,explanation:'Research expenditure is expensed because a qualifying intangible asset cannot yet be demonstrated.',reviewSection:'acca-b2-research'},
  {id:'acca-b2-q3',prompt:'When does development capitalisation begin?',options:['When the idea arises','When every criterion is demonstrable','When cash is paid','At commercial launch only'],correctIndex:1,explanation:'All six IAS 38 development criteria must be demonstrated.',reviewSection:'acca-b2-development'},
  {id:'acca-b2-q4',prompt:'Can later success reinstate earlier research expenditure?',options:['Yes, always','No','Only through OCI','Only if unpaid'],correctIndex:1,explanation:'Amounts correctly expensed before recognition cannot later be restored as an intangible asset.',reviewSection:'acca-b2-research'},
  {id:'acca-b2-q5',prompt:'What happens to an indefinite-life intangible?',options:['Amortise over ten years','No amortisation; annual impairment testing and life review','Expense immediately','Never test impairment'],correctIndex:1,explanation:'Indefinite does not mean infinite; annual impairment testing and reconsideration are required.',reviewSection:'acca-b2-subsequent'}
 ],
 practiceExercises:[
  {id:'acca-b2-p1',question:'Research CU40; pre-criteria development CU30; eligible post-criteria development CU120. How much is capitalised?',hints:['Research is expensed.','Use the date all criteria are met.'],answer:'Capitalise CU120. Expense CU70 of research and pre-criteria development.',explanation:'The cut-off is prospective from demonstrated criteria.'},
  {id:'acca-b2-p2',question:'A capitalised asset of CU240 is available for use on 1 October with a five-year life. Calculate year-end amortisation.',hints:['Annual amount first.','Use three months.'],answer:'Annual amortisation is CU48; three months is CU12.',explanation:'Amortisation begins when available for use, not when capitalisation begins.'},
  {id:'acca-b2-p3',question:'Repair: “Indefinite life means the asset lasts forever and requires no annual accounting.”',hints:['No foreseeable limit is not infinity.','Name the annual test.'],answer:'Indefinite life means no foreseeable limit based on current evidence. The asset is not amortised, but it is tested annually for impairment and its useful-life assessment is reconsidered.',explanation:'Indefinite-life assets require continuing evidence and impairment work.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ias-38',label:'IFRS Foundation · IAS 38 Intangible Assets',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-38-intangible-assets/',supports:'Definition, recognition, research, development, useful life, amortisation and derecognition.',reviewedOn},
  {id:'ias-36',label:'IFRS Foundation · IAS 36 Impairment of Assets',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-36-impairment-of-assets/',supports:'Annual testing for specified intangibles and impairment interaction.',reviewedOn}
 ]
};
export function localModelB2For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='B2'?ACCA_B2_MODEL_MODULE:null;}
export {ACCA_B2_MODEL_ID,ACCA_B2_MODEL_SLUG};
