import type {LessonModule} from './lessonModules.ts';
import {ACCA_B11_MODEL_ID,ACCA_B11_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_B11_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'20–26',segments:['Recognition only when both reasonable-assurance conditions are met.','Income-related grants and systematic matching.','A narrated comparison of the two asset-grant presentations.','Repayment, non-monetary grants and disclosures.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_B11_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask which cost or asset the grant is intended to compensate and whether both reasonable-assurance conditions are supported.',supportedPractice:'Separate recognition, timing and presentation; reconcile the deferred-income and net-asset methods without treating cash receipt as grant income.',misconception:'Receiving cash does not by itself prove that grant conditions will be met, and an asset grant is not normally immediate profit merely because it has been received.',transfer:'Change the grant condition, useful life, presentation policy or repayment facts and ask the learner to revise one conclusion.',close:'Recap recognition, systematic profit-or-loss timing, presentation and repayment without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_B11_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_B11_MODEL_ID,title:'ACCA FR B11 · Government grants',
 goal:'Apply IAS 20 recognition and timing, account for income- and asset-related grants, compare permitted presentations, and deal with repayment and disclosure.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level B11 mapping must be checked against the exact selected exam sitting before publication. It is original teaching material, not ACCA approval, legal advice on grant conditions, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-b11-recognition',title:'1. Recognise a grant only when both conditions have reasonable assurance',paragraphs:[
   'A government grant transfers resources to an entity in return for past or future compliance with conditions linked to its operating activities. Recognise it only when there is reasonable assurance both that the entity will comply with the attached conditions and that the grant will be received. The test is not absolute certainty, but it requires support for both limbs. A signed offer or a cash receipt may be relevant evidence, yet neither replaces analysis of the conditions.',
   'Do not recognise a grant merely when an application is filed or management expects approval. Conversely, receipt does not automatically create immediate income: the entity might initially have a liability if recognition conditions or related performance remain unresolved. Read the agreement carefully, identify the qualifying expenditure or conduct, and document why compliance and collection are reasonably assured at the reporting date.',
   'Distinguish a grant from general government assistance whose value cannot reasonably be placed on it or from transactions with government that cannot be distinguished from normal trading. IAS 20 disclosures can still make significant assistance understandable. The accounting label follows the substance of the support and its conditions, not the name used in a funding letter.'
  ],supportPt:'Reconheça o grant apenas com reasonable assurance de cumprimento das condições e recebimento. Aprovação, expectativa ou caixa isoladamente não resolvem a análise; leia a finalidade e as condições do acordo.',sourceIds:['ias-20','acca-fr-syllabus']},
  {id:'acca-b11-income',title:'2. Match income-related grants to the related costs systematically',paragraphs:[
   'Recognise government grants in profit or loss on a systematic basis over the periods in which the entity recognises the related costs that the grants are intended to compensate. This is not a cash-basis rule. A two-year grant supporting qualifying training normally follows the relevant training expense across those periods when the recognition conditions are met, rather than becoming all income on the receipt date.',
   'A grant receivable as compensation for expenses or losses already incurred, or as immediate support with no future related costs, is recognised in profit or loss in the period it becomes receivable. That conclusion depends on the substance of the arrangement. Do not use the immediate-support treatment simply to accelerate income when future qualifying expenditure or continuing conditions remain.',
   'For a grant related to income, IAS 20 permits presentation separately or under a general heading such as other income, or deduction from the related expense. Apply the selected accounting policy consistently and disclose it. Gross and net presentation can change displayed lines, but they should not change the resulting profit when the same grant and expense are recognised in the same period.'
  ],supportPt:'Grants relacionados a income acompanham sistematicamente os custos compensados. A apresentação pode ser separada ou deduzida da despesa relacionada, com política consistente; o recebimento não determina sozinho o timing.',sourceIds:['ias-20']},
  {id:'acca-b11-assets',title:'3. Compare the two presentations for an asset-related grant',paragraphs:[
   'For a grant related to a depreciable asset, one permitted presentation records deferred income and recognises it in profit or loss systematically over the asset’s useful life. The asset remains recorded at its full amount under its applicable Standard, so depreciation is based on that amount. Grant income then offsets part of the related depreciation in the performance for each period.',
   'The alternative deducts the grant in arriving at the asset’s carrying amount. Depreciation is calculated on that reduced amount, so there is no separate recurring grant-income line for the same support. The two presentations produce different statement-of-financial-position amounts and gross profit-or-loss lines but, with consistent assumptions, the same net expense over the asset’s useful life.',
   'A grant related to a non-depreciable asset may still require fulfilment of obligations, so recognise it in profit or loss over the periods that bear the cost of meeting those obligations. A non-monetary grant, such as land, may be accounted for at fair value; IAS 20 also permits a nominal amount approach. State the policy and do not assume a free asset means immediate income.'
  ],supportPt:'Asset grant pode aparecer como deferred income ou como redução do carrying amount do ativo. Os valores brutos diferem, mas o efeito líquido ao longo da vida útil deve reconciliar sob premissas consistentes.',sourceIds:['ias-20']},
  {id:'acca-b11-repayment',title:'4. Treat repayment as a change in estimate and disclose the policy',paragraphs:[
   'When a government grant becomes repayable, account for the effect as a change in accounting estimate. For an income-related grant, apply repayment first against any unamortised deferred credit for that grant; recognise any excess immediately in profit or loss. This treatment does not reopen prior periods as though the original recognition had automatically been an error.',
   'For an asset-related grant, increase the asset’s carrying amount or reduce the deferred-income balance by the amount repayable, according to the presentation used. Recognise immediately in profit or loss any cumulative additional depreciation that would have been recognised to date without the grant. Also consider whether the circumstances indicate that the asset itself may be impaired under the applicable Standard.',
   'Disclose the accounting policy adopted, including the presentation methods, the nature and extent of grants recognised, and unfulfilled conditions or other contingencies attaching to recognised assistance. Clear disclosure helps users distinguish recurring operational performance from government support. It does not remove the need to apply the recognition, measurement and repayment requirements to the underlying facts.'
  ],supportPt:'Repayment é change in estimate. Use primeiro eventual deferred credit, reconheça o excesso e, em asset grants, ajuste ativo ou deferred income e registre depreciação acumulada adicional quando aplicável. Divulgue política, natureza e condições pendentes.',sourceIds:['ias-20']}
 ],
 terms:[
  {term:'Government grant',meaning:'Transfer of resources by government in return for past or future compliance with operating conditions.',pt:'Subvenção governamental',example:'A grant may support the purchase of qualifying equipment.'},
  {term:'Reasonable assurance',meaning:'Supported expectation that the entity will comply with conditions and receive the grant.',pt:'Segurança razoável',example:'Both compliance and receipt require evidence before recognition.'},
  {term:'Income-related grant',meaning:'A grant other than one whose primary condition concerns qualifying long-term assets.',pt:'Subvenção relacionada a receita',example:'Support for two years of staff training follows the related costs.'},
  {term:'Asset-related grant',meaning:'A grant whose primary condition requires purchase, construction or acquisition of long-term assets.',pt:'Subvenção relacionada a ativo',example:'Funding for a machine can be deferred or deducted from the asset.'},
  {term:'Deferred income',meaning:'Grant balance recognised in profit or loss systematically as related costs arise.',pt:'Receita diferida',example:'One fifth of a five-year machine grant may be released each year under stated assumptions.'},
  {term:'Change in accounting estimate',meaning:'Prospective accounting for effects arising from new information or developments.',pt:'Mudança de estimativa contábil',example:'A newly repayable grant is accounted for as a change in estimate.'}
 ],
 visual:{title:'Asset grant: two permitted presentation routes',note:'Original schedule; fictional CU000 amounts. Machine cost CU500, grant CU100, five-year straight-line life, nil residual value.',headers:['Year-one measure','Deferred-income method','Net-asset method'],rows:[['Initial depreciable amount','500','400'],['Depreciation expense','100','80'],['Grant income','20','—'],['Net year-one expense','80','80'],['Closing PPE','400','320'],['Closing deferred income','80','—']],question:'Why is year-one net expense CU80 under both methods?',answer:'The deferred-income method reports CU100 depreciation less CU20 grant income; the net-asset method depreciates CU400 over five years, giving CU80.'},
 caseStudy:{title:'Machine grant and first-year presentation',scenario:['On 1 January, an entity buys a machine for CU500,000 and receives a CU100,000 government grant toward that asset. There is reasonable assurance that the entity will comply with the attached conditions and retain the grant.','The machine has a five-year useful life, nil residual value and straight-line depreciation. The entity has not yet selected between IAS 20’s deferred-income and net-asset presentation methods. Ignore tax and impairment.'],task:'Prepare the year-one amounts under both permitted presentations and explain why their net profit-or-loss effect agrees.',hints:['Under deferred income, depreciate CU500,000 and release CU100,000 over five years.','Under the net method, reduce the depreciable amount by the grant before calculating depreciation.'],modelAnswer:'Under the deferred-income method, record the machine at CU500,000, charge CU100,000 depreciation and recognise CU20,000 grant income in year one. Closing PPE is CU400,000 and closing deferred income is CU80,000, so the net year-one expense is CU80,000. Under the net-asset method, deduct the CU100,000 grant from the asset, giving a CU400,000 depreciable amount; year-one depreciation is CU80,000 and closing PPE is CU320,000. There is no separate grant-income release under that method. Both methods therefore give the same CU80,000 net year-one expense, while their gross lines and statement-of-financial-position amounts differ.',reviewChecks:['Recognition is supported by both reasonable-assurance conditions.','Deferred method: depreciation CU100,000 and grant income CU20,000.','Deferred closing balances: PPE CU400,000 and deferred income CU80,000.','Net method: depreciation CU80,000 and closing PPE CU320,000.'],transfer:'Assume the useful life is four years instead. Recalculate year-one depreciation, grant income and closing balances under both methods.'},
 checkpoint:[
  {id:'acca-b11-q1',prompt:'When is a government grant recognised under IAS 20?',options:['Whenever an application is submitted','When there is reasonable assurance of both compliance and receipt','Only when every condition is legally discharged','Whenever cash enters the bank'],correctIndex:1,explanation:'Recognition requires reasonable assurance of compliance with conditions and receipt.',reviewSection:'acca-b11-recognition'},
  {id:'acca-b11-q2',prompt:'How is a grant compensating future related costs normally recognised?',options:['Immediately on receipt','Systematically over the periods of the related costs','Directly in share capital','Only when the asset is sold'],correctIndex:1,explanation:'Profit-or-loss recognition follows the periods in which the compensated costs are expensed.',reviewSection:'acca-b11-income'},
  {id:'acca-b11-q3',prompt:'Which pair describes the permitted statement-of-financial-position presentations for an asset grant?',options:['Deferred income or deduction from the asset','Revenue or share premium','Provision or contingent liability','Inventory or receivable'],correctIndex:0,explanation:'IAS 20 permits deferred income or deduction in arriving at the asset carrying amount.',reviewSection:'acca-b11-assets'},
  {id:'acca-b11-q4',prompt:'How is a newly repayable government grant accounted for?',options:['Always as a prior-period error','As a change in accounting estimate','Always against share capital','By ignoring the repayment until cash is paid'],correctIndex:1,explanation:'IAS 20 treats the effect of repayment as a change in estimate.',reviewSection:'acca-b11-repayment'},
  {id:'acca-b11-q5',prompt:'In the worked case, what is closing deferred income after year one?',options:['CU20,000','CU80,000','CU100,000','CU400,000'],correctIndex:1,explanation:'CU100,000 initial deferred income less the CU20,000 year-one release leaves CU80,000.',reviewSection:'acca-b11-assets'}
 ],
 practiceExercises:[
  {id:'acca-b11-p1',question:'A CU60,000 grant compensates qualifying training expense incurred evenly over two years. Recognition conditions are met. How much grant income is recognised each year?',hints:['Follow the related expense periods.','Do not use the cash date as the sole timing rule.'],answer:'Recognise CU30,000 in each year, assuming the qualifying training expense is incurred evenly as stated.',explanation:'Income-related grants are recognised systematically with the related costs.'},
  {id:'acca-b11-p2',question:'Repair: “The entity received the cash, so the entire asset grant is immediate profit.”',hints:['Test both reasonable-assurance conditions.','Then connect profit or loss to the related asset cost.'],answer:'Cash receipt alone does not determine recognition or timing. Once both recognition conditions are supported, account for the asset grant using a permitted presentation and recognise its effect systematically with the related depreciation or obligations.',explanation:'Receipt is evidence, not a substitute for the recognition and matching analysis.'},
  {id:'acca-b11-p3',question:'An income grant becomes repayable by CU50,000. Its unamortised deferred credit is CU30,000. What is the immediate profit-or-loss charge?',hints:['Apply repayment against the deferred credit first.','Charge the excess immediately.'],answer:'Reduce deferred income by CU30,000 and recognise the CU20,000 excess immediately in profit or loss.',explanation:'Repayment first uses the unamortised deferred credit; the excess is recognised immediately.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ias-20',label:'IFRS Foundation · IAS 20 Accounting for Government Grants and Disclosure of Government Assistance',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-20-accounting-for-government-grants-and-disclosure-of-government-assistance/',supports:'Recognition, systematic profit-or-loss timing, presentation and repayment principles.',reviewedOn}
 ]
};
export function localModelB11For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='B11'?ACCA_B11_MODEL_MODULE:null;}
export {ACCA_B11_MODEL_ID,ACCA_B11_MODEL_SLUG};
