import type {LessonModule} from './lessonModules.ts';
import {ACCA_A3_MODEL_ID,ACCA_A3_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_A3_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'18–24',segments:['Elements before recognition.','Recognition under relevance and faithful representation.','Historical-cost and current-value measurement families.','Derecognition, unit of account and uncertainty.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_A3_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask the learner to identify the right or obligation and the past event before discussing an accounting label.',supportedPractice:'Separate definition, recognition, measurement and presentation in that order; give one targeted hint before revealing a conclusion.',misconception:'A cash payment does not automatically create an asset, and uncertainty does not automatically prohibit recognition.',transfer:'Change control, the obligation, measurement uncertainty or the unit of account and ask which stage of the analysis changes.',close:'Recap the four-stage reasoning path and one unresolved fact without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_A3_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_A3_MODEL_ID,title:'ACCA FR A3 · Recognition, derecognition and measurement',
 goal:'Apply the Conceptual Framework definitions, separate recognition from measurement and explain a supported derecognition conclusion.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level A3 mapping must be checked against the exact selected exam sitting before publication. It teaches Conceptual Framework reasoning and does not replace the requirements of a specific IFRS Accounting Standard. It is original teaching material, not ACCA approval, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-a3-elements',title:'1. Identify the element before choosing an account',paragraphs:[
   'An asset is a present economic resource controlled by the entity as a result of past events; an economic resource is a right with the potential to produce economic benefits. A liability is a present obligation to transfer an economic resource as a result of past events. Equity is the residual interest after liabilities are deducted from assets. Income increases assets or decreases liabilities in a way that increases equity, other than owner contributions; expenses work in the opposite direction, excluding distributions to owners.',
   'Start with rights and obligations rather than physical form or ledger labels. A licence can be an economic resource without being tangible. Paying cash proves that cash changed, not that the recipient now controls a qualifying resource. Likewise, management intention by itself does not create a present obligation when the entity retains the practical ability to avoid a transfer.',
   'Use four questions: what is the right or duty, which past event created it, who controls the right or cannot avoid the duty, and how could benefits flow or resources be transferred? Only then map the conclusion to an element and the relevant Standard.'
  ],supportPt:'Comece pelo direito ou obrigação, pelo evento passado e por controle ou impossibilidade prática de evitar a transferência. Pagamento, forma física e nome da conta não resolvem sozinhos a definição.',sourceIds:['conceptual-framework','acca-fr-syllabus']},
  {id:'acca-a3-recognition',title:'2. Decide whether recognition provides useful information',paragraphs:[
   'Recognition depicts an element in the statement of financial position or performance in words and a monetary amount. Under the Conceptual Framework, recognition is appropriate when it provides relevant information, a faithful representation and benefits that justify the costs. The analysis is not a mechanical probability gate applied identically to every topic; the applicable Standard supplies the operational recognition requirements.',
   'Existence uncertainty, outcome uncertainty and measurement uncertainty are different. High measurement uncertainty can make one estimate less informative, but an estimate may still faithfully represent the item when the method, inputs and uncertainty are clearly described. Omitting a material obligation can be less faithful than recognising a supportable range-based estimate.',
   'Keep definition and recognition separate. An item may meet an element definition yet remain unrecognised because the resulting information would not be useful under the applicable requirements. Conversely, recognising an amount does not eliminate the need for disclosures about assumptions, estimation uncertainty or unrecognised rights and obligations.'
  ],supportPt:'Definição e reconhecimento são etapas diferentes. Incerteza não significa automaticamente ausência de reconhecimento: avalie relevância, representação fiel, custo-benefício e a norma aplicável.',sourceIds:['conceptual-framework']},
  {id:'acca-a3-measurement',title:'3. Match the measurement basis to the information needed',paragraphs:[
   'Historical-cost measures begin from the transaction or event that created the item and are updated for matters such as consumption, impairment, payments and interest. Current-value measures use conditions at the measurement date and include fair value, value in use or fulfilment value, and current cost. These are families of information, not interchangeable labels.',
   'Historical cost can be verifiable and useful for margins and resource consumption, but it may become less relevant when prices change significantly. Fair value reflects a market-participant perspective; value in use and fulfilment value are entity-specific present values. Current cost reflects the cost of an equivalent asset or consideration for an equivalent liability at the measurement date.',
   'The selection considers relevance, faithful representation, the characteristics of the item, how it contributes to cash flows and cost constraints. In an exam answer, state the basis required or supplied, keep market and entity-specific assumptions distinct, and avoid inventing a measurement choice when a specific Standard governs it.'
  ],supportPt:'Custo histórico parte da transação; valores atuais refletem condições da data de mensuração. Diferencie perspectiva de mercado e perspectiva específica da entidade e siga a norma aplicável.',sourceIds:['conceptual-framework']},
  {id:'acca-a3-derecognition',title:'4. Analyse derecognition and the unit of account',paragraphs:[
   'Derecognition removes all or part of a recognised asset or liability, normally when control of a resource is lost or a present obligation no longer exists. The goal is to represent faithfully both the resources or obligations retained after the transaction and the change produced by it. Sometimes separate presentation or continued recognition is necessary to avoid hiding retained exposure.',
   'The unit of account is the right, group of rights, obligation or group to which recognition and measurement concepts are applied. Aggregating items can reduce cost and improve understandability, but excessive aggregation can conceal different risks. Splitting a single economic exposure into artificial pieces can be equally misleading.',
   'For a transfer, identify what left, what remained, any continuing involvement and the relevant measurement. Do not treat legal title, invoice cancellation or cash settlement as conclusive without checking the economic rights and obligations and the governing Standard.'
  ],supportPt:'Na baixa, identifique o que saiu, o que permaneceu e qualquer envolvimento continuado. A unidade de conta deve representar a substância sem esconder riscos por agregação ou divisão inadequada.',sourceIds:['conceptual-framework']}
 ],
 terms:[
  {term:'Economic resource',meaning:'A right that has the potential to produce economic benefits.',pt:'Recurso econômico',example:'A contractual licence can be a right even without physical form.'},
  {term:'Present obligation',meaning:'A duty or responsibility the entity has no practical ability to avoid.',pt:'Obrigação presente',example:'Past contamination may create an obligation when the facts establish the duty.'},
  {term:'Recognition',meaning:'Capturing an element in a financial statement in words and a monetary amount.',pt:'Reconhecimento',example:'A recognised liability affects both position and performance as applicable.'},
  {term:'Measurement basis',meaning:'An identified feature used to determine a monetary amount.',pt:'Base de mensuração',example:'Historical cost and fair value provide different information.'},
  {term:'Derecognition',meaning:'Removal of all or part of a recognised asset or liability.',pt:'Baixa',example:'A liability is removed when the obligation is extinguished.'},
  {term:'Unit of account',meaning:'The right, obligation or group to which recognition and measurement are applied.',pt:'Unidade de conta',example:'Related rights may be assessed together when that faithfully represents the exposure.'}
 ],
 visual:{title:'Four-stage accounting judgement',note:'The stages are linked but must not be collapsed into one yes/no question.',headers:['Stage','Question','Control against error'],rows:[['Definition','Is there a qualifying right or present obligation?','Identify past event and control/avoidability'],['Recognition','Would recognition provide useful information?','Separate uncertainty types'],['Measurement','Which required basis represents the item?','Do not mix market and entity assumptions'],['Derecognition','What left and what remains?','Check retained exposure and unit of account']],question:'Why is “cash was paid” insufficient to recognise an asset?',answer:'Payment establishes a transaction, but recognition also requires a controlled present economic resource and the applicable recognition and measurement requirements.'},
 caseStudy:{title:'A purchased right and an environmental duty',scenario:['On 1 December an entity pays CU120 for a non-refundable three-year right to access specialised data. Access begins immediately; the entity can restrict employee access but cannot resell the right.','Past production contaminated land before year-end. Legislation and the entity’s actions establish a present clean-up duty. Engineers estimate CU180–CU240, with CU210 the probability-weighted estimate under the supplied assumptions.','Assume the relevant Standards permit recognition using the supplied measurement facts; ignore discounting and tax.'],task:'Analyse the asset and liability through definition, recognition and measurement, then state what further evidence would be needed before derecognition.',hints:['Identify the controlled right separately from its lack of resale rights.','For the clean-up, separate existence of the duty from uncertainty in its amount.'],modelAnswer:'The data access is a present right created by payment and contract. The ability to obtain the service and restrict internal access can support control even though resale is prohibited. Under the supplied recognition assumptions, initially recognise CU120 and then apply the relevant consumption or impairment requirements. The contamination creates a present obligation from past production; uncertainty over the amount does not erase the obligation. Under the supplied measurement assumption, CU210 is the estimate, with the range and method explained as required. The data asset is not derecognised merely because one month passes, and the liability is not derecognised until the duty is extinguished or the applicable requirements support another conclusion. Obtain contract termination rights, service-consumption evidence, remediation timing and settlement evidence before any later derecognition.',reviewChecks:['The right and obligation are identified before labels.','Definition, recognition and measurement are separate.','Measurement uncertainty is not treated as non-existence.','Derecognition depends on what rights or duties remain.'],transfer:'Assume the supplier can terminate access without refund on 31 December. Reassess control, impairment evidence and the carrying amount without assuming automatic derecognition.'},
 checkpoint:[
  {id:'acca-a3-q1',prompt:'What is an economic resource?',options:['Any cash payment','A right with potential to produce economic benefits','Every physical object','Management intention'],correctIndex:1,explanation:'The Conceptual Framework defines an economic resource as a right with potential to produce economic benefits.',reviewSection:'acca-a3-elements'},
  {id:'acca-a3-q2',prompt:'Does measurement uncertainty automatically prevent recognition?',options:['Yes, in every case','No; usefulness and the applicable requirements must be assessed','Only for liabilities','Only when no cash was paid'],correctIndex:1,explanation:'A supportable estimate can faithfully represent an item when the method and uncertainty are appropriately described.',reviewSection:'acca-a3-recognition'},
  {id:'acca-a3-q3',prompt:'Which basis is entity-specific?',options:['Value in use','Quoted fair value','Transaction price in every case','Share capital'],correctIndex:0,explanation:'Value in use reflects entity-specific cash flows; fair value uses a market-participant perspective.',reviewSection:'acca-a3-measurement'},
  {id:'acca-a3-q4',prompt:'What is the main derecognition question?',options:['Whether an invoice was deleted','What rights or obligations left and what remain','Whether profit increases','Whether cash was forecast'],correctIndex:1,explanation:'Derecognition should represent the transferred and retained rights or obligations faithfully.',reviewSection:'acca-a3-derecognition'},
  {id:'acca-a3-q5',prompt:'Why does unit of account matter?',options:['It chooses the reporting currency','It determines which right, obligation or group is analysed','It removes all uncertainty','It replaces the applicable Standard'],correctIndex:1,explanation:'Aggregation or separation changes what is recognised and measured and must faithfully represent the exposure.',reviewSection:'acca-a3-derecognition'}
 ],
 practiceExercises:[
  {id:'acca-a3-p1',question:'Repair: “The entity paid CU50, so it must have an asset.”',hints:['Identify a right.','Ask whether the entity controls it.'],answer:'Payment alone is insufficient. Identify a present right with potential benefits, assess control and apply the relevant recognition and measurement requirements.',explanation:'Transaction evidence is not the same as an element conclusion.'},
  {id:'acca-a3-p2',question:'Contrast fair value with value in use in one sentence.',hints:['Name the perspective.','Keep both at the measurement date.'],answer:'Fair value uses a market-participant perspective, while value in use is an entity-specific present value of cash flows expected from use and disposal.',explanation:'Do not mix market and entity-specific assumptions.'},
  {id:'acca-a3-p3',question:'A transfer leaves the entity guaranteeing 30% of losses. What must a derecognition analysis address?',hints:['Identify continuing involvement.','Consider retained exposure.'],answer:'It must identify the rights transferred and the guarantee retained, then apply the relevant Standard so the retained exposure is not hidden by full derecognition.',explanation:'Legal transfer alone may not depict continuing involvement.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'conceptual-framework',label:'IFRS Foundation · Conceptual Framework for Financial Reporting',url:'https://www.ifrs.org/issued-standards/list-of-standards/conceptual-framework/',supports:'Elements, recognition, measurement, presentation, derecognition and unit of account.',reviewedOn}
 ]
};
export function localModelA3For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='A3'?ACCA_A3_MODEL_MODULE:null;}
export {ACCA_A3_MODEL_ID,ACCA_A3_MODEL_SLUG};
