import type {LessonModule} from './lessonModules.ts';
import {ENGLISH_E3_MODEL_ID,ENGLISH_E3_MODEL_SLUG,ENGLISH_E4_MODEL_ID,ENGLISH_E4_MODEL_SLUG,localEnglishCodeFor} from './localEnglishLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';

const reviewedOn='2026-09-22';
const speakingSource={id:'bc-speaking',label:'British Council · Speaking',url:'https://learnenglish.britishcouncil.org/skills/speaking',supports:'General interaction, clarification and speaking practice; all scenarios and dialogues here are original.',reviewedOn};
const requestsSource={id:'bc-requests',label:'British Council · Requests, offers and invitations',url:'https://learnenglish.britishcouncil.org/grammar/english-grammar-reference/requests-offers-invitations',supports:'Language choices for polite requests and offers.',reviewedOn};

export const ENGLISH_E3_MODEL_MODULE:LessonModule={
 track:'english',lessonId:ENGLISH_E3_MODEL_ID,title:'Appointments: confirm, reschedule and clarify by phone',goal:'Confirm an appointment, repair a misunderstood detail and propose a workable new time without pretending that the change is already accepted.',scope:'Original written everyday-English practice for appointment calls. It does not place a real call, make or change an appointment, assess listening or pronunciation, give medical advice or certify a CEFR level.',
 sections:[
  {id:'eng-appointment-open',title:'1. Open with purpose and useful identity',paragraphs:['Start with the reason for the call and only the details needed to locate the appointment: “Hi, I’m calling about my appointment on Thursday at half past two.” This is easier to process than a long personal history before the request.','If the organisation asks for an identifier, repeat it in manageable groups. Do not volunteer unrelated private details. In practice here, every name, number and appointment is fictional.','On the phone, a short signpost helps: “I’d like to confirm the time” or “I need to ask whether a later slot is available.” The listener knows what action you need.'],supportPt:'Comece com o motivo da ligação e apenas os dados necessários. Use uma frase-guia curta: confirmar horário, esclarecer um detalhe ou pedir outra opção.',sourceIds:['bc-speaking']},
  {id:'eng-appointment-time',title:'2. Make time expressions unambiguous',paragraphs:['“Half two” can be interpreted differently across languages. In Ireland and the UK, “half two” commonly means 2:30, but a precise confirmation is safer: “Just to confirm, that’s two thirty in the afternoon, correct?”','Use on with days and dates, at with clock times and in with broader periods: on Thursday, at 14:30, in the afternoon. For important arrangements, repeat both the day and time rather than relying on “then”.','If you mishear a detail, repair it directly: “Sorry, did you say Tuesday the thirteenth or Thursday the fifteenth?” A specific contrast is more useful than pretending you understood.'],supportPt:'Confirme dia e horário de forma explícita. Quando houver dúvida, contraste as duas opções que você ouviu em vez de fingir entendimento.',sourceIds:['bc-speaking']},
  {id:'eng-appointment-request',title:'3. Ask for a change without assuming acceptance',paragraphs:['A clear rescheduling request contains the existing arrangement, the problem and a question: “I’m booked for Thursday at 14:30, but I can’t attend then. Would Friday morning be possible?”','“Could I move it?” asks for permission or availability; it does not mean the appointment has changed. Wait for confirmation and keep the original time unless the other person explicitly accepts the new arrangement.','Offer a useful range instead of an impossible promise: “I’m available after ten on Friday.” If no suitable time exists, ask what options are available rather than inventing a slot.'],supportPt:'Inclua compromisso atual, problema e pedido. Um pedido não altera o horário sozinho; espere confirmação explícita.',sourceIds:['bc-requests']},
  {id:'eng-appointment-close',title:'4. Close with a read-back',paragraphs:['End by reading back the final arrangement: “Thanks. That’s Friday the sixteenth at ten fifteen, at the same address.” This catches errors while both people still have the conversation in mind.','If the change was not accepted, say what remains true: “Understood — I’ll keep Thursday at two thirty and call again if anything changes.” Do not close with wording that creates a false confirmation.','For a spelling repair, use chunks and a comparison when helpful: “That’s M-A-R-A, not M-A-R-Y.” The goal is accurate information, not a judgement about accent.'],supportPt:'Finalize repetindo data, horário e local confirmados. Se a mudança não foi aceita, diga claramente qual compromisso continua válido.',sourceIds:['bc-speaking']}
 ],
 terms:[
  {term:'I’m calling about…',meaning:'A direct way to state the subject of a call.',pt:'estou ligando sobre…',example:'I’m calling about my appointment on Thursday.'},
  {term:'Just to confirm…',meaning:'Introduces a check of an important detail.',pt:'só para confirmar…',example:'Just to confirm, that is two thirty.'},
  {term:'Would … be possible?',meaning:'Polite question about availability.',pt:'seria possível…?',example:'Would Friday morning be possible?'},
  {term:'available',meaning:'Free and able to attend.',pt:'disponível',example:'I am available after ten.'},
  {term:'keep the appointment',meaning:'Leave the existing booking unchanged.',pt:'manter o compromisso',example:'I will keep the Thursday appointment.'},
  {term:'read back',meaning:'Repeat details to verify them.',pt:'repetir para confirmar',example:'Let me read that back.'}
 ],
 visual:{title:'Appointment call: status before and after the request',note:'A request is not a confirmed change.',headers:['Moment','What is known','Useful wording'],rows:[['Opening','Thursday at 14:30 is booked','I’m calling about my Thursday appointment.'],['Clarification','Time may have been misheard','Did you say two thirty?'],['Request','Friday is preferred, not confirmed','Would Friday morning be possible?'],['Close','Friday at 10:15 is accepted','Just to confirm: Friday at ten fifteen.']],question:'When should you treat the new time as active?',answer:'Only after the other person explicitly confirms it; then read the final arrangement back.'},
 caseStudy:{title:'A change that still needs confirmation',scenario:['You have a fictional appointment on Thursday 15 October at 14:30.','You cannot attend then and are available after 10:00 on Friday 16 October.','The person first says “ten fifteen”; you are unsure whether you heard “ten fifty”.'],task:'Open the call, ask to reschedule, clarify the uncertain time and close with a precise read-back.',hints:['Keep the Thursday appointment as the current fact until the change is accepted.','Contrast ten fifteen with ten fifty directly.'],modelAnswer:'“Hi, I’m calling about my appointment on Thursday the fifteenth at two thirty. I can’t attend then. Would Friday morning after ten be possible? Sorry, did you say ten fifteen or ten fifty? Great, thank you. Just to confirm, the new appointment is Friday the sixteenth at ten fifteen.”',reviewChecks:['Purpose and current appointment are clear.','The preferred range is phrased as a request.','The uncertain time is clarified directly.','The final day and time are read back only after acceptance.'],transfer:'Change the situation to a school meeting and keep the same confirmation discipline.'},
 checkpoint:[
  {id:'eng-appointment-q1',prompt:'Which opening is clearest?',options:['I have many things to explain.','I’m calling about my appointment on Thursday at two thirty.','You know who I am.','Change it.'],correctIndex:1,explanation:'It states the purpose and the relevant existing arrangement without unnecessary detail.',reviewSection:'eng-appointment-open'},
  {id:'eng-appointment-q2',prompt:'What is the safest confirmation of “half two”?',options:['Later.','Half.','Two thirty in the afternoon.','Whenever.'],correctIndex:2,explanation:'The full hour and minutes remove the most likely ambiguity.',reviewSection:'eng-appointment-time'},
  {id:'eng-appointment-q3',prompt:'What does “Would Friday morning be possible?” establish?',options:['Friday is already booked.','A request for availability has been made.','Thursday is automatically cancelled.','The call is complete.'],correctIndex:1,explanation:'A polite request does not itself confirm or cancel an appointment.',reviewSection:'eng-appointment-request'},
  {id:'eng-appointment-q4',prompt:'You are unsure between 10:15 and 10:50. What should you say?',options:['Yes, that is fine.','Repeat the first number only.','Did you say ten fifteen or ten fifty?','Guess from context.'],correctIndex:2,explanation:'A direct contrast exposes the precise point that needs repair.',reviewSection:'eng-appointment-time'},
  {id:'eng-appointment-q5',prompt:'What belongs in the closing read-back?',options:['Only a thank-you.','Every personal detail.','The confirmed day, date, time and relevant place.','An unaccepted preferred time.'],correctIndex:2,explanation:'A concise read-back verifies the details that now govern the arrangement.',reviewSection:'eng-appointment-close'}
 ],
 practiceExercises:[
  {id:'eng-appointment-p1',question:'Rewrite “Move my appointment to Friday” as a clear request.',hints:['Name the existing appointment.','Ask whether your preferred range is available.'],answer:'I’m booked for Thursday at two thirty. Would any time after ten on Friday be possible?',explanation:'The request preserves the current fact and gives a useful alternative range.'},
  {id:'eng-appointment-p2',question:'Repair this uncertain detail: you heard either the 13th or the 30th.',hints:['Say that you need clarification.','Contrast both dates.'],answer:'Sorry, could I check the date? Did you say the thirteenth or the thirtieth?',explanation:'The listener can resolve the exact ambiguity immediately.'},
  {id:'eng-appointment-p3',question:'Write a one-sentence read-back for Friday 16 October at 10:15.',hints:['Use “just to confirm”.','Include day, date and time.'],answer:'Just to confirm, the new appointment is Friday the sixteenth of October at ten fifteen.',explanation:'The final sentence verifies the complete accepted arrangement.'}
 ],sources:[speakingSource,requestsSource]
};

export const ENGLISH_E4_MODEL_MODULE:LessonModule={
 track:'english',lessonId:ENGLISH_E4_MODEL_ID,title:'Housing: report a repair and arrange access',goal:'Describe a household problem using observable evidence, request a next step and confirm access without inventing a cause or a completed repair.',scope:'Original written everyday-English practice with a fictional housing scenario. It is not legal, tenancy, safety or emergency advice; it does not contact a landlord or service, assess listening or pronunciation or certify a CEFR level.',
 sections:[
  {id:'eng-repair-observe',title:'1. Report what you can observe',paragraphs:['Begin with the location, symptom and timing: “There is water on the kitchen floor below the sink. I first noticed it this morning.” These facts help the reader act without requiring you to diagnose the cause.','Separate observation from inference. “The pipe is leaking” may be a reasonable hypothesis, but “water appears below the sink when the tap runs” is stronger evidence if you have not inspected the pipe.','If the situation may be urgent or unsafe, use the appropriate real service rather than relying on this language lesson. The fictional examples here teach communication only.'],supportPt:'Descreva local, sinal observado e momento. Não transforme hipótese sobre a causa em fato confirmado.',sourceIds:['bc-speaking']},
  {id:'eng-repair-evidence',title:'2. Add bounded evidence',paragraphs:['Useful evidence can include frequency, change and a photo you actually have: “It happened twice today” or “The patch is larger than yesterday.” Do not claim a photo, measurement or previous report that does not exist.','A short sequence is easier to follow: what happened, what you did and what happened next. “I dried the floor, did not use the tap for an hour and then saw water again after running it.”','Avoid dramatic certainty when the cause is unknown. “It may be coming from the connection under the sink” keeps the inference appropriately limited.'],supportPt:'Acrescente frequência, mudança e sequência real. Não invente foto, medida, causa ou contato anterior.',sourceIds:['bc-speaking']},
  {id:'eng-repair-request',title:'3. Ask for action and offer access',paragraphs:['Make the requested next step visible: “Could someone inspect it tomorrow?” If timing matters, give a real availability window: “I can provide access between nine and noon.”','Offering access is not the same as confirming a visit. “Tomorrow morning works for me” states availability; “The technician is coming tomorrow” requires confirmation from the service.','If you cannot provide access, propose an alternative rather than leaving the message open: “I’m not available before five, but Saturday morning would work.”'],supportPt:'Peça uma ação concreta e ofereça uma janela real. Disponibilidade não é visita confirmada.',sourceIds:['bc-requests']},
  {id:'eng-repair-follow',title:'4. Confirm ownership and follow-up',paragraphs:['Close with who will do what next: “Please confirm whether someone can attend tomorrow morning. I’ll keep the area clear and check the message at six.”','After a conversation, summarise the agreement without adding certainty: “Thanks — you’ll check availability and update me this afternoon.” This is different from saying that a visit is booked.','A useful follow-up references the earlier report and the new fact: “Following up on yesterday’s message: the water appeared again this morning.” Repeating the whole history can hide the change.'],supportPt:'Feche com próximo passo e responsável. Ao acompanhar, mencione o contato anterior e apenas a informação nova.',sourceIds:['bc-speaking','bc-requests']}
 ],
 terms:[
  {term:'I noticed…',meaning:'Introduces an observed fact.',pt:'eu percebi…',example:'I noticed water below the sink this morning.'},
  {term:'appears to',meaning:'Signals an inference rather than certainty.',pt:'parece',example:'It appears to happen when the tap runs.'},
  {term:'inspect',meaning:'Examine to identify condition or cause.',pt:'inspecionar',example:'Could someone inspect it tomorrow?'},
  {term:'access window',meaning:'Period when entry can be provided.',pt:'janela de acesso',example:'My access window is nine to noon.'},
  {term:'follow up',meaning:'Contact again about an earlier matter.',pt:'acompanhar / retomar',example:'I’m following up on yesterday’s report.'},
  {term:'keep me updated',meaning:'Ask for new information as it becomes available.',pt:'mantenha-me informado',example:'Please keep me updated on availability.'}
 ],
 visual:{title:'From observation to confirmed next step',note:'Keep evidence, request and confirmation separate.',headers:['Layer','Example','Boundary'],rows:[['Observation','Water below the sink','Directly seen'],['Possible cause','May be from a connection','Not confirmed'],['Request','Could someone inspect it?','Action requested'],['Agreement','Service will check availability','Visit not yet booked']],question:'Which statement can you make without diagnosing the cause?',answer:'“Water appears below the sink when the tap runs.” It reports the observable pattern.'},
 caseStudy:{title:'A repair report with an unknown cause',scenario:['In a fictional rented flat, you saw water below the kitchen sink twice today.','You dried the floor. The water appeared again after the tap ran, but you have not identified the cause.','You can provide access tomorrow between 09:00 and 12:00. No visit has been confirmed.'],task:'Write a concise report with evidence, a request for inspection, your access window and a confirmation question.',hints:['Describe the pattern without claiming which part failed.','Make clear that tomorrow morning is availability, not a confirmed visit.'],modelAnswer:'“Hi, I’m reporting water below the kitchen sink. I noticed it twice today, and it appeared again after I dried the floor and ran the tap. I haven’t identified the cause. Could someone inspect it? I can provide access tomorrow between nine and noon. Please confirm whether a visit can be arranged.”',reviewChecks:['Location, symptom and timing are clear.','The possible cause is not presented as certain.','The inspection request and access window are explicit.','The message asks for confirmation instead of inventing a booking.'],transfer:'Change the problem to a window that does not close and preserve the same evidence/request structure.'},
 checkpoint:[
  {id:'eng-repair-q1',prompt:'Which sentence reports the strongest observable evidence?',options:['The plumbing system has failed.','Water appears below the sink when the tap runs.','The landlord ignored the problem.','It will flood the building.'],correctIndex:1,explanation:'It describes a visible pattern without inventing cause, responsibility or future outcome.',reviewSection:'eng-repair-observe'},
  {id:'eng-repair-q2',prompt:'Which detail should be included only if it is true?',options:['A photo was attached.','The location of the water.','When it was noticed.','Your real availability.'],correctIndex:0,explanation:'Never claim that evidence was attached when no such evidence exists.',reviewSection:'eng-repair-evidence'},
  {id:'eng-repair-q3',prompt:'“I can provide access tomorrow morning” means:',options:['A visit is confirmed.','The repair is complete.','That time is available to you.','The cause is known.'],correctIndex:2,explanation:'It offers an access window; the service still needs to confirm attendance.',reviewSection:'eng-repair-request'},
  {id:'eng-repair-q4',prompt:'Which request is most actionable?',options:['Please deal with it.','Could someone inspect the sink, and confirm the visit time?','This is unacceptable.','You know the problem.'],correctIndex:1,explanation:'It identifies the action and the confirmation still required.',reviewSection:'eng-repair-request'},
  {id:'eng-repair-q5',prompt:'What belongs in a useful follow-up?',options:['Only the complete original message.','A new invented diagnosis.','The earlier reference and the new observed fact.','A claim that silence means confirmation.'],correctIndex:2,explanation:'A concise follow-up links the existing report to material new evidence.',reviewSection:'eng-repair-follow'}
 ],
 practiceExercises:[
  {id:'eng-repair-p1',question:'Replace this unsupported diagnosis: “The pipe is broken.”',hints:['State what you can see.','Describe when it occurs.'],answer:'Water appears below the sink after the tap runs, but I have not identified the cause.',explanation:'The rewrite separates observation from the unknown cause.'},
  {id:'eng-repair-p2',question:'Ask for inspection and offer access from 17:00 to 19:00.',hints:['Use a polite request.','Keep availability separate from confirmation.'],answer:'Could someone inspect it? I can provide access between five and seven this evening; please confirm whether that time is available.',explanation:'The message requests action and asks the service to confirm the proposed window.'},
  {id:'eng-repair-p3',question:'Write a one-sentence follow-up after the water appears again.',hints:['Refer to the earlier report.','Add only the new observation.'],answer:'Following up on this morning’s report: water appeared below the sink again after the tap ran at six.',explanation:'The follow-up connects the report with specific new evidence.'}
 ],sources:[speakingSource,requestsSource]
};

export function localEnglishEverydayExpansionFor(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{
 const code=localEnglishCodeFor(track,lesson);
 if(code==='E3'&&lesson.slug===ENGLISH_E3_MODEL_SLUG)return ENGLISH_E3_MODEL_MODULE;
 if(code==='E4'&&lesson.slug===ENGLISH_E4_MODEL_SLUG)return ENGLISH_E4_MODEL_MODULE;
 return null;
}
