import type {LessonModule} from './lessonModules.ts';
import {ACCA_A4_MODEL_ID,ACCA_A4_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_A4_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'18–24',segments:['Why general-purpose reporting is regulated.','IFRS Foundation, IASB and due process.','Standard setting versus adoption and enforcement.','Ethical judgement under reporting pressure.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_A4_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask who is making the reporting decision, which requirement applies and what pressure or conflict may affect the judgement.',supportedPractice:'Separate standard setting, jurisdictional adoption, entity compliance and regulatory enforcement before analysing the ethical response.',misconception:'The IASB issues IFRS Accounting Standards but does not adopt them for every jurisdiction or enforce every entity’s financial statements.',transfer:'Change the stakeholder pressure, evidence, governance route or jurisdictional status and ask what part of the response changes.',close:'Recap requirement, evidence, bias risk, documentation and escalation without claiming saved mastery.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_A4_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_A4_MODEL_ID,title:'ACCA FR A4 · Regulation, standard setting and ethical reporting judgement',
 goal:'Explain the reporting architecture and respond to pressure using evidence, transparent judgement and proportionate governance.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level A4 mapping must be checked against the exact selected exam sitting before publication. It is a high-level reporting and ethics lesson, not jurisdiction-specific legal advice or an investigation protocol. It is original teaching material, not ACCA approval, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-a4-regulation',title:'1. Explain why general-purpose reporting is regulated',paragraphs:[
   'Investors, lenders and other creditors often cannot demand information tailored to them and may face an information disadvantage relative to management. Standards create a common reporting language, constrain opportunistic choices and support comparability, transparency and accountability. Regulation cannot eliminate judgement, estimation or every reporting failure.',
   'A standards-based system also has costs: preparation, systems, assurance, enforcement and the risk that detailed rules obscure the economic question. The response is not to abandon requirements but to use principles, materiality, due process and clear disclosure so the information remains decision-useful.',
   'In an exam answer, connect regulation to users and market confidence rather than merely stating that it is compulsory. Then acknowledge limits: different business models, enforcement quality, estimates and incentives mean identical standards do not guarantee identical outcomes.'
  ],supportPt:'A regulação reduz assimetria de informação, limita escolhas oportunistas e melhora comparabilidade, mas não elimina julgamento, estimativas, custos nem diferenças de enforcement.',sourceIds:['acca-fr-syllabus','ifrs-foundation']},
  {id:'acca-a4-architecture',title:'2. Distinguish the institutions and their roles',paragraphs:[
   'The IFRS Foundation provides the governance structure. The International Accounting Standards Board develops and issues IFRS Accounting Standards; the International Sustainability Standards Board develops IFRS Sustainability Disclosure Standards. Trustees oversee governance and strategy, while monitoring and advisory arrangements support public accountability and technical input.',
   'The IASB does not approve each entity’s accounts. Jurisdictions decide whether and how standards are adopted or endorsed, and local regulators, exchanges, courts, auditors and governance bodies have distinct compliance and enforcement roles. An entity must establish the framework applicable to the particular financial statements.',
   'Keep “issued by the IASB”, “adopted in a jurisdiction”, “applicable to this entity” and “enforced or assured” as separate statements. Collapsing them can lead to a technically correct IFRS description but the wrong legal conclusion for the reporting entity.'
  ],supportPt:'Separe emissão pelo IASB, adoção na jurisdição, aplicabilidade à entidade, auditoria e enforcement. Uma dessas etapas não prova automaticamente as demais.',sourceIds:['ifrs-foundation','due-process']},
  {id:'acca-a4-due-process',title:'3. Use due-process logic without treating consultation as a vote',paragraphs:[
   'The IASB’s due process includes research, public consultation, exposure drafts, consideration of feedback, public meetings and explanation of final decisions. Effects analysis, fieldwork and post-implementation review can support the evidence base. Mandatory and non-mandatory steps are governed by the Due Process Handbook.',
   'Consultation improves transparency and allows preparers, users, auditors, regulators and others to identify consequences and alternatives. It does not mean every comment is accepted or that the most popular answer becomes a Standard. The board must weigh evidence against its objectives and explain its reasoning.',
   'For a short answer, describe the proposal, stakeholder input, public deliberation and final rationale. Avoid claiming that due process removes lobbying, judgement or implementation cost; its purpose is accountable standard setting, not automatic unanimity.'
  ],supportPt:'Due process combina pesquisa, consulta pública, deliberação e explicação. Feedback informa a decisão, mas não funciona como votação nem elimina julgamento ou custo de implementação.',sourceIds:['due-process']},
  {id:'acca-a4-ethics',title:'4. Protect reporting judgement from bias and pressure',paragraphs:[
   'Reporting pressure can arise from financing targets, bonuses, covenants, forecasts or fear of criticism. First preserve the evidence and identify the applicable requirement and reporting date. Then distinguish legitimate estimation choices from bias, omission, manipulation or delay designed to achieve a preferred result.',
   'A proportionate response records the facts, assumptions, alternatives, decision and reviewer; seeks technically competent advice; and uses the entity’s governance and escalation channels when pressure threatens faithful reporting. Confidentiality does not require silence within authorised reporting or whistleblowing arrangements, while external disclosure depends on professional and legal obligations.',
   'Do not manufacture certainty or accuse people without evidence. State the threat, the accounting effect and the safeguard. If a conflict cannot be resolved, document the position and follow applicable professional, governance and legal requirements rather than signing off a conclusion you cannot support.'
  ],supportPt:'Preserve evidência, aplique a exigência da data-base, documente alternativas e use revisão e escalonamento proporcionais. Não invente certeza nem aceite omissão para atingir meta.',sourceIds:['acca-ethics','conceptual-framework']}
 ],
 terms:[
  {term:'General-purpose financial reporting',meaning:'Reporting designed for users who cannot require tailored information.',pt:'Relatório financeiro para propósito geral',example:'Investors use common statements rather than private management reports.'},
  {term:'Standard setting',meaning:'Process of developing and issuing authoritative reporting requirements.',pt:'Emissão de normas',example:'The IASB develops IFRS Accounting Standards through due process.'},
  {term:'Adoption',meaning:'A jurisdictional decision to make standards applicable in a defined setting.',pt:'Adoção',example:'Local law or regulation determines the endorsed framework.'},
  {term:'Enforcement',meaning:'Actions that monitor and respond to non-compliance.',pt:'Fiscalização e enforcement',example:'A securities regulator may review listed-company reporting.'},
  {term:'Due process',meaning:'Transparent procedures for research, consultation, deliberation and decisions.',pt:'Devido processo normativo',example:'An exposure draft invites public comment before final requirements.'},
  {term:'Bias threat',meaning:'Pressure or incentive that may distort a neutral judgement.',pt:'Ameaça de viés',example:'A covenant target may encourage delayed recognition of adverse information.'}
 ],
 visual:{title:'From global standard setting to an entity conclusion',note:'The same organisation does not perform every role.',headers:['Layer','Core question','Example output'],rows:[['IFRS Foundation / IASB','What global requirement should be issued?','IFRS Accounting Standard'],['Jurisdiction','Has it been adopted or endorsed?','Applicable local framework'],['Entity and governance','How does it apply to these facts?','Documented accounting judgement'],['Regulator / assurance','Was reporting compliant and supportable?','Review, audit or enforcement response']],question:'Why can an IASB-issued Standard still require a jurisdictional applicability check?',answer:'The IASB issues the global Standard, while jurisdictions determine adoption or endorsement and the entities and periods to which it legally applies.'},
 caseStudy:{title:'Financing pressure before an impairment review',scenario:['A reporting manager asks the team to postpone a required year-end impairment review until after a bank financing meeting because the preliminary evidence may reduce profit.','The adverse operating evidence existed at the reporting date. The estimate needs engineering and finance input, and a board audit committee is available under the entity’s governance process.','Assume the applicable reporting requirement calls for the review; do not give jurisdiction-specific legal advice.'],task:'Explain the reporting, ethical and governance response and distinguish standard setting from entity compliance.',hints:['Start with the reporting-date evidence and requirement.','Name the bias threat and a proportionate review or escalation route.'],modelAnswer:'The IASB’s standard-setting role does not decide this entity’s estimate; the entity must apply the applicable adopted framework to its reporting-date facts. The financing meeting creates a self-interest and bias threat but does not change the reporting date or permit the review to be deferred. Preserve the adverse evidence, complete the assessment with competent engineering and finance input, document assumptions and alternatives, obtain independent review and escalate unresolved pressure to the audit committee. Do not promise an impairment amount before completing the evidence-based estimate, but do not omit or delay the assessment to protect profit. Follow applicable professional and legal channels if governance does not resolve the conflict.',reviewChecks:['Reporting-date evidence is applied.','IASB, adoption, entity judgement and governance roles are separated.','The financing incentive is identified as a bias threat.','Documentation, competence, review and escalation are proportionate.'],transfer:'Assume the evidence arose only after year-end from a new event. Reassess the accounting-date analysis while keeping the ethical safeguards.'},
 checkpoint:[
  {id:'acca-a4-q1',prompt:'Which body issues IFRS Accounting Standards?',options:['Every national regulator','The IASB','Each audit committee','The stock exchange alone'],correctIndex:1,explanation:'The IASB develops and issues IFRS Accounting Standards within the IFRS Foundation governance structure.',reviewSection:'acca-a4-architecture'},
  {id:'acca-a4-q2',prompt:'Does IASB issuance prove a Standard is legally applicable to every entity?',options:['Yes','No; adoption, scope and effective date must be established','Only when profit falls','Only for private companies'],correctIndex:1,explanation:'Jurisdictional adoption or endorsement and entity scope remain separate questions.',reviewSection:'acca-a4-architecture'},
  {id:'acca-a4-q3',prompt:'What is public consultation in due process?',options:['A binding popularity vote','Evidence and feedback considered in public deliberation','An audit opinion','A replacement for board judgement'],correctIndex:1,explanation:'Consultation informs accountable decisions but does not make every comment binding.',reviewSection:'acca-a4-due-process'},
  {id:'acca-a4-q4',prompt:'What should happen first when asked to omit adverse reporting-date evidence?',options:['Delete the evidence','Preserve and assess it under the applicable requirement','Wait until financing closes','Change the reporting date'],correctIndex:1,explanation:'The evidence and requirement anchor the accounting judgement before safeguards and escalation are applied.',reviewSection:'acca-a4-ethics'},
  {id:'acca-a4-q5',prompt:'Which statement best explains regulation?',options:['It eliminates judgement','It supports common, decision-useful reporting while retaining costs and limitations','It guarantees no fraud','It lets management choose any outcome'],correctIndex:1,explanation:'Standards improve comparability and accountability but cannot eliminate incentives, estimates or enforcement differences.',reviewSection:'acca-a4-regulation'}
 ],
 practiceExercises:[
  {id:'acca-a4-p1',question:'Repair: “The IASB enforces every company’s financial statements.”',hints:['Separate issuance from enforcement.','Name the jurisdictional layer.'],answer:'The IASB issues IFRS Accounting Standards. Jurisdictions determine adoption, while regulators, governance bodies, auditors and legal systems have distinct compliance and enforcement roles.',explanation:'Do not collapse the reporting architecture.'},
  {id:'acca-a4-p2',question:'Why is an exposure draft useful if the IASB does not accept every comment?',hints:['Think evidence and transparency.','Keep board accountability.'],answer:'It exposes proposals to diverse evidence and consequences, allows public scrutiny and requires the IASB to consider feedback and explain its final reasoning.',explanation:'Consultation informs rather than replaces judgement.'},
  {id:'acca-a4-p3',question:'A bonus target creates pressure to defer an expense. State one accounting action and one safeguard.',hints:['Anchor the reporting date.','Choose review or escalation.'],answer:'Apply the relevant requirement to the reporting-date evidence and document the conclusion; obtain independent review or escalate unresolved pressure through governance.',explanation:'A complete response links technical treatment and ethical safeguards.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ifrs-foundation',label:'IFRS Foundation · About us and governance',url:'https://www.ifrs.org/about-us/who-we-are/',supports:'Institutional roles and governance structure.',reviewedOn},
  {id:'due-process',label:'IFRS Foundation · Due Process Handbook',url:'https://www.ifrs.org/about-us/how-we-set-ifrs-standards/',supports:'Research, consultation, deliberation and standard-setting process.',reviewedOn},
  {id:'conceptual-framework',label:'IFRS Foundation · Conceptual Framework',url:'https://www.ifrs.org/issued-standards/list-of-standards/conceptual-framework/',supports:'Purpose and qualitative characteristics of useful reporting.',reviewedOn},
  {id:'acca-ethics',label:'ACCA · Ethics and professional skills',url:'https://www.accaglobal.com/gb/en/student/ethics.html',supports:'Professional ethics context and development resources.',reviewedOn}
 ]
};
export function localModelA4For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='A4'?ACCA_A4_MODEL_MODULE:null;}
export {ACCA_A4_MODEL_ID,ACCA_A4_MODEL_SLUG};
