import type {LessonModule} from './lessonModules.ts';
import {ACCA_B4_MODEL_ID,ACCA_B4_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-21';
export const ACCA_B4_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'18–24',segments:['What belongs in inventory cost.','Lower of cost and net realisable value item by item.','A narrated cost-formula example.','Biological assets, agricultural produce and the harvest boundary.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_B4_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask the learner to separate purchase, conversion and avoidable abnormal costs.',supportedPractice:'Use one inventory schedule, then cross the harvest boundary into IAS 2.',misconception:'Net realisable value is entity-specific; it is not automatically fair value and is not reduced by selling costs already omitted from the estimate.',transfer:'Change selling price, completion cost or harvest timing and request a revised measurement.',close:'Recap IAS 2 measurement, cost formula and IAS 41 boundary without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_B4_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_B4_MODEL_ID,title:'ACCA FR B4 · Inventories and biological assets',
 goal:'Measure inventories under IAS 2, recognise write-downs and reversals, and distinguish biological assets from agricultural produce under IAS 41.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level B4 mapping must be checked against the exact selected exam sitting before publication. It is original teaching material, not ACCA approval, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-b4-cost',title:'1. Build inventory cost from permitted components',paragraphs:[
   'Inventories are measured initially at cost. Cost includes purchase price after trade discounts, import duties and non-refundable taxes, transport and handling, conversion costs, and other costs incurred to bring inventory to its present location and condition. For production, allocate fixed overhead using normal capacity and variable overhead using actual production consistently with the units produced.',
   'Exclude abnormal waste, storage that is not necessary in the production process, administrative overhead that does not bring inventory to its present location and condition, and selling costs. Financing is not added merely because payment is deferred; identify any financing element under the applicable guidance rather than hiding it in inventory.',
   'Use specific identification for items that are not ordinarily interchangeable or are produced for specific projects. For ordinarily interchangeable items, IAS 2 permits FIFO or weighted average applied consistently to inventories with similar nature and use. LIFO is not an IAS 2 cost formula. A clear working separates quantity, unit cost and excluded period expense.'
  ],supportPt:'O custo inclui compra, conversão e gastos para levar o estoque à condição e local atuais. Exclua perdas anormais, armazenagem desnecessária, administração sem relação e despesas de venda. IAS 2 aceita FIFO ou média ponderada, não LIFO.',sourceIds:['ias-2','acca-fr-syllabus']},
  {id:'acca-b4-nrv',title:'2. Apply lower of cost and net realisable value',paragraphs:[
   'At each reporting date, carry inventory at the lower of cost and net realisable value. Net realisable value is the estimated selling price in the ordinary course of business less estimated costs of completion and costs necessary to make the sale. It is entity-specific and therefore is not simply another label for fair value.',
   'Normally compare cost and net realisable value item by item. Grouping similar or related items can be appropriate in limited circumstances, but a profitable product should not conceal a loss on an unrelated item. Evidence after the reporting date can refine the estimate when it confirms conditions existing at that date.',
   'Recognise a write-down as an expense. If net realisable value later increases because circumstances change, reverse the previous write-down only up to its original amount, so the new carrying amount remains the lower of revised cost and revised net realisable value. When inventory is sold, recognise its carrying amount as an expense in the period of related revenue.'
  ],supportPt:'No fechamento, estoque fica pelo menor entre custo e valor realizável líquido: preço estimado de venda menos custos de conclusão e venda. A reversão posterior é limitada à baixa anteriormente reconhecida.',sourceIds:['ias-2']},
  {id:'acca-b4-biological',title:'3. Separate biological assets from agricultural produce',paragraphs:[
   'A biological asset is a living animal or plant. Agricultural produce is the harvested product of the entity’s biological assets. IAS 41 generally measures a biological asset on initial recognition and at each reporting date at fair value less costs to sell, with changes recognised in profit or loss, unless fair value is not reliably measurable in the narrow circumstances permitted by the Standard.',
   'Agricultural produce harvested from a biological asset is measured at fair value less costs to sell at the point of harvest. That amount becomes its cost when IAS 2 applies after harvest. This boundary prevents the same produce from remaining indefinitely under IAS 41: grapes on a vine and harvested grapes are different accounting subjects at the harvest point.',
   'Bearer plants used in the production or supply of agricultural produce are accounted for under IAS 16 rather than measured as biological assets under IAS 41, while the produce growing on them remains within IAS 41. Always classify the asset before calculating, because an apparently small wording change can move measurement between Standards.'
  ],supportPt:'Ativo biológico é animal ou planta viva; produto agrícola é o produto colhido. Na colheita, valor justo menos custos de venda vira o custo inicial para IAS 2. Plantas portadoras seguem IAS 16, mas o produto nelas segue IAS 41.',sourceIds:['ias-41','ias-2']},
  {id:'acca-b4-judgement',title:'4. Integrate classification, estimates and disclosure',paragraphs:[
   'A reliable solution follows the asset through time. Before harvest, identify the biological asset and measure under IAS 41. At harvest, measure agricultural produce and establish the deemed cost. After harvest, accumulate only valid IAS 2 costs and compare the resulting inventory balance with net realisable value at the reporting date.',
   'Estimates require evidence. Selling price should reflect ordinary-course conditions; completion and selling costs should be supportable; fair value and costs to sell should not be confused with net realisable value. When the scenario gives a sales contract, damaged goods or changing market price, explain how that fact relates to the reporting-date condition rather than mechanically selecting the latest number.',
   'Present the answer as a short reconciliation: classification and Standard, initial or harvest measurement, subsequent costs, closing measurement and profit-or-loss effect. State assumptions where data are missing. Do not claim that a lower number is automatically prudent; the required measurement basis and neutral evidence determine the result.'
  ],supportPt:'Siga o item no tempo: IAS 41 antes e no ponto da colheita; IAS 2 depois. Separe valor justo menos custos de venda de VRL e mostre classificação, cálculo, saldo final e efeito no resultado.',sourceIds:['ias-2','ias-41']}
 ],
 terms:[
  {term:'Inventory cost',meaning:'Purchase, conversion and other costs bringing inventory to present location and condition.',pt:'Custo do estoque',example:'Freight-in may qualify; selling commission does not.'},
  {term:'Net realisable value',meaning:'Estimated ordinary-course selling price less completion and sale costs.',pt:'Valor realizável líquido',example:'CU120 selling price less CU15 completion and CU5 selling cost gives CU100.'},
  {term:'FIFO',meaning:'Cost formula assuming earliest purchased or produced items are sold first.',pt:'PEPS',example:'Closing inventory reflects more recent eligible unit costs.'},
  {term:'Weighted average',meaning:'Cost formula based on the weighted average cost of similar items.',pt:'Média ponderada',example:'Total eligible cost is divided by total eligible units.'},
  {term:'Biological asset',meaning:'A living animal or plant within the relevant IAS 41 scope.',pt:'Ativo biológico',example:'A dairy cow is a biological asset.'},
  {term:'Agricultural produce',meaning:'Harvested product of a biological asset.',pt:'Produto agrícola',example:'Milk collected from the cow is agricultural produce.'}
 ],
 visual:{title:'From growing produce to closing inventory',note:'Original boundary map; amounts are fictional and shown in CU.',headers:['Stage','Measurement basis','Illustrative amount'],rows:[['Produce growing on bearer plants','IAS 41 fair value less costs to sell','92'],['At harvest','IAS 41 amount becomes IAS 2 cost','92'],['Valid post-harvest processing','Added under IAS 2','+18'],['Reporting date','Lower of cost 110 and NRV 104','104']],question:'What expense arises at the reporting date if the harvested inventory cost is CU110?',answer:'Recognise a CU6 inventory write-down because IAS 2 requires the lower of CU110 cost and CU104 net realisable value.'},
 caseStudy:{title:'Coffee harvest, processing and closing write-down',scenario:['Harvested coffee beans are measured at fair value of CU150,000 with costs to sell of CU6,000 at harvest.','After harvest, valid processing costs are CU20,000. Abnormal spoilage of CU4,000 and selling commission of CU3,000 are also incurred.','At year end, the beans can sell for CU170,000 after further completion costs of CU8,000 and necessary selling costs of CU5,000.'],task:'Calculate the IAS 2 cost after harvest, the year-end net realisable value and the amount recognised as inventory. Explain every exclusion.',hints:['The harvest measurement becomes IAS 2 cost.','Abnormal waste and selling commission are period expenses, not inventory cost.'],modelAnswer:'At harvest, the agricultural produce is measured at CU144,000 (150,000 − 6,000), which becomes its IAS 2 cost. Add CU20,000 valid post-harvest processing, giving inventory cost of CU164,000. Expense the CU4,000 abnormal spoilage and CU3,000 selling commission. Net realisable value is CU157,000 (170,000 − 8,000 − 5,000). Inventory is therefore CU157,000, the lower of cost and NRV, and the IAS 2 write-down is CU7,000.',reviewChecks:['Harvest fair value less costs to sell becomes IAS 2 cost.','Only valid CU20,000 processing is added.','Abnormal spoilage and commission are excluded.','The CU157,000 closing amount and CU7,000 write-down reconcile.'],transfer:'Assume revised evidence next year raises NRV to CU166,000 before sale. Explain the maximum reversal and resulting carrying amount.'},
 checkpoint:[
  {id:'acca-b4-q1',prompt:'How is inventory measured at the reporting date?',options:['Higher of cost and NRV','Lower of cost and NRV','Fair value in every case','Selling price before costs'],correctIndex:1,explanation:'IAS 2 requires the lower of cost and net realisable value.',reviewSection:'acca-b4-nrv'},
  {id:'acca-b4-q2',prompt:'Which cost is normally excluded from inventory?',options:['Import duty','Direct conversion labour','Abnormal waste','Freight-in'],correctIndex:2,explanation:'Abnormal waste is recognised as an expense rather than included in inventory cost.',reviewSection:'acca-b4-cost'},
  {id:'acca-b4-q3',prompt:'Which IAS 2 formula is prohibited?',options:['FIFO','Weighted average','Specific identification when appropriate','LIFO'],correctIndex:3,explanation:'IAS 2 does not permit LIFO.',reviewSection:'acca-b4-cost'},
  {id:'acca-b4-q4',prompt:'What happens to agricultural produce at harvest?',options:['It stays under IAS 41 forever','It is measured at FVLCTS and that amount becomes IAS 2 cost','It is measured only at historical cash cost','It becomes revenue immediately'],correctIndex:1,explanation:'Fair value less costs to sell at harvest becomes cost for subsequent IAS 2 accounting.',reviewSection:'acca-b4-biological'},
  {id:'acca-b4-q5',prompt:'How far may an IAS 2 write-down be reversed?',options:['Without limit','Only up to the original write-down','Never','Up to gross selling price'],correctIndex:1,explanation:'The reversal is limited to the amount of the original write-down.',reviewSection:'acca-b4-nrv'}
 ],
 practiceExercises:[
  {id:'acca-b4-p1',question:'Inventory cost is CU80. Selling price is CU92, completion cost CU8 and selling cost CU7. Calculate the carrying amount.',hints:['Calculate NRV first.','Select the lower amount.'],answer:'NRV is CU77 (92 − 8 − 7). Inventory is carried at CU77 and a CU3 write-down is recognised.',explanation:'NRV includes both completion and necessary selling costs.'},
  {id:'acca-b4-p2',question:'Repair: “Fair value less costs to sell and net realisable value are always the same.”',hints:['Distinguish market and entity-specific measures.','Name the relevant Standards.'],answer:'They are different measures. IAS 41 fair value less costs to sell is market-based, while IAS 2 net realisable value is the entity-specific ordinary-course selling price less completion and sale costs.',explanation:'Similar deductions do not make the measurement objectives identical.'},
  {id:'acca-b4-p3',question:'Classify an apple tree used repeatedly to grow fruit, apples growing on it and harvested apples.',hints:['Use IAS 16, then IAS 41, then IAS 2.','Identify the harvest boundary.'],answer:'The bearer apple tree is accounted for under IAS 16. Apples growing on it are agricultural produce within IAS 41. At harvest, the apples are measured at fair value less costs to sell, which becomes their cost under IAS 2.',explanation:'Classification changes at the harvest boundary.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ias-2',label:'IFRS Foundation · IAS 2 Inventories',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-2-inventories/',supports:'Inventory cost, cost formulas, lower of cost and NRV, expense and reversal principles.',reviewedOn},
  {id:'ias-41',label:'IFRS Foundation · IAS 41 Agriculture',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-41-agriculture/',supports:'Biological assets, agricultural produce, fair value less costs to sell and harvest boundary.',reviewedOn}
 ]
};
export function localModelB4For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='B4'?ACCA_B4_MODEL_MODULE:null;}
export {ACCA_B4_MODEL_ID,ACCA_B4_MODEL_SLUG};
