import type {LessonModule} from './lessonModules.ts';
import {ACCA_B8_MODEL_ID,ACCA_B8_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-21';
export const ACCA_B8_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'20–26',segments:['Current tax versus deferred tax.','Tax bases for assets and liabilities.','A narrated temporary-difference schedule.','Retrieval pauses on recognition, rates and presentation.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_B8_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask whether the calculation concerns tax payable now or future tax consequences of recovery or settlement.',supportedPractice:'Build a three-column schedule: carrying amount, tax base and taxable or deductible temporary difference.',misconception:'Deferred tax is not calculated by applying the tax rate to every accounting balance or every permanent difference.',transfer:'Change the tax base, recovery pattern or enacted rate and ask the learner to recompute the closing balance.',close:'Recap current tax, tax base, deferred tax direction and movement without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_B8_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_B8_MODEL_ID,title:'ACCA FR B8 · Taxation',
 goal:'Account for current tax and calculate basic deferred tax balances and movements from temporary differences under IAS 12.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level B8 mapping must be checked against the exact selected exam sitting before publication. It is original teaching material, not ACCA approval, jurisdiction-specific tax advice, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-b8-current',title:'1. Separate current tax from deferred tax',paragraphs:[
   'Current tax is the amount of income tax payable or recoverable for taxable profit or loss for the current and prior periods. Recognise unpaid current tax as a liability and an overpayment as an asset. Measure using tax rates and laws enacted or substantively enacted by the reporting date, based on the entity’s supportable taxable-profit computation.',
   'Payments on account reduce the current tax payable; they do not by themselves change the current tax expense. If current tax for the year is CU120 and CU90 has already been paid, current tax expense is CU120 and the closing current tax liability is CU30. Prior-year under- or over-provisions are reflected when identified under the applicable accounting treatment.',
   'Deferred tax addresses future tax consequences of recovering assets and settling liabilities at their carrying amounts. It does not replace the current tax computation and is not simply tax delayed for cash-flow reasons. Keep current and deferred components separate before presenting the total tax effect.'
  ],supportPt:'Current tax é o imposto do lucro tributável atual ou anterior; pagamentos antecipados reduzem o passivo, não a despesa. Deferred tax trata consequências fiscais futuras de recuperar ativos ou liquidar passivos.',sourceIds:['ias-12','acca-fr-syllabus']},
  {id:'acca-b8-taxbase',title:'2. Determine tax bases and temporary differences',paragraphs:[
   'The tax base of an asset is the amount deductible for tax purposes against future taxable economic benefits when the carrying amount is recovered. If those future benefits will not be taxable, the tax base equals the carrying amount. Comparing an asset’s carrying amount with its tax base identifies the future taxable or deductible consequence.',
   'The tax base of a liability is generally its carrying amount less amounts deductible for tax purposes in future periods when the liability is settled. A warranty provision of CU80 that becomes tax-deductible only when paid therefore has a tax base of zero and creates an CU80 deductible temporary difference, subject to recognition requirements.',
   'For an asset, carrying amount above tax base commonly creates a taxable temporary difference and deferred tax liability; carrying amount below tax base commonly creates a deductible difference. For a liability, carrying amount above tax base commonly creates a deductible difference. Use the recovery or settlement logic rather than memorising one sign for every situation.'
  ],supportPt:'Tax base mede o valor atribuído fiscalmente. Ativo com carrying amount maior que tax base normalmente gera diferença tributável; passivo cuja liquidação futura será dedutível normalmente gera diferença dedutível.',sourceIds:['ias-12']},
  {id:'acca-b8-deferred',title:'3. Recognise and measure deferred tax balances',paragraphs:[
   'IAS 12 generally recognises a deferred tax liability for taxable temporary differences and, subject to specified exceptions, a deferred tax asset for deductible temporary differences, unused tax losses and credits. Recognise a deferred tax asset only to the extent that sufficient future taxable profit is probable for utilisation.',
   'Measure deferred tax using enacted or substantively enacted rates expected to apply when the asset is realised or liability settled, reflecting the expected manner of recovery or settlement where relevant. Deferred tax balances are not discounted. Reassess deferred tax assets at each reporting date as evidence about future taxable profit changes.',
   'Permanent differences affect the relationship between accounting profit and taxable profit but do not reverse in future periods, so they do not create deferred tax under the temporary-difference approach. Likewise, avoid double counting an item already embedded in the carrying amount and tax base. State any relevant recognition exception supplied by the question.'
  ],supportPt:'DTL normalmente nasce de diferença temporária tributável; DTA depende de diferença dedutível e lucro tributável futuro provável. Use taxa enacted/substantively enacted, não desconte e não crie deferred tax para diferença permanente.',sourceIds:['ias-12']},
  {id:'acca-b8-movement',title:'4. Reconcile the closing balance and tax expense',paragraphs:[
   'Build a closing deferred tax schedule by item: carrying amount, tax base, temporary-difference direction, applicable rate and resulting asset or liability. Offset deferred tax assets and liabilities only when the IAS 12 conditions are met, including the appropriate legally enforceable right and taxation-authority relationship; otherwise present them separately.',
   'The movement from opening to closing deferred tax is normally recognised in profit or loss to the extent that the underlying transaction or event was recognised there. Tax relating to an item recognised outside profit or loss follows that item, such as relevant other comprehensive income or equity treatment. Do not send every deferred tax movement automatically to tax expense.',
   'For a simple profit-or-loss case, closing net deferred tax liability minus opening net liability gives deferred tax expense; a decrease gives deferred tax income. Add current tax expense and the profit-or-loss deferred tax movement to reconcile total income-tax expense, while separately reconciling current tax cash payments to the current tax liability.'
  ],supportPt:'Monte schedule por item e calcule o movimento do saldo inicial ao final. O imposto segue onde o item subjacente foi reconhecido. Em caso simples no resultado, aumento do DTL líquido gera deferred tax expense.',sourceIds:['ias-12']}
 ],
 terms:[
  {term:'Current tax',meaning:'Income tax payable or recoverable for taxable profit or loss of current and prior periods.',pt:'Imposto corrente',example:'Current tax expense can differ from the cash still payable.'},
  {term:'Tax base',meaning:'Amount attributed to an asset or liability for tax purposes.',pt:'Base fiscal',example:'A provision deductible only when paid can have a nil tax base.'},
  {term:'Temporary difference',meaning:'Difference between carrying amount and tax base with future tax consequences.',pt:'Diferença temporária',example:'Different accounting and tax depreciation can reverse later.'},
  {term:'Deferred tax liability',meaning:'Future tax consequence generally arising from taxable temporary differences.',pt:'Passivo fiscal diferido',example:'An asset carrying amount above tax base often creates a DTL.'},
  {term:'Deferred tax asset',meaning:'Future tax benefit from deductible differences or qualifying losses, recognised subject to recoverability.',pt:'Ativo fiscal diferido',example:'A deductible warranty difference may create a DTA.'},
  {term:'Substantively enacted rate',meaning:'Tax rate sufficiently enacted under the relevant legislative process by reporting date.',pt:'Alíquota substantivamente promulgada',example:'The closing deferred tax schedule uses the applicable future rate.'}
 ],
 visual:{title:'Basic deferred tax schedule',note:'Original schedule; fictional CU amounts and 25% enacted rate. Assume offset conditions are met.',headers:['Item','Temporary difference','Deferred tax'],rows:[['PPE: CA 600, tax base 420','Taxable 180','DTL 45'],['Warranty: CA 80, tax base 0','Deductible 80','DTA 20'],['Net closing position','180 − 80 = taxable 100','Net DTL 25'],['Opening net DTL','—','18']],question:'What is the profit-or-loss deferred tax movement when all underlying items were recognised in profit or loss?',answer:'The net deferred tax liability rises from CU18 to CU25, so recognise CU7 deferred tax expense.'},
 caseStudy:{title:'Current tax and deferred tax reconciliation',scenario:['Current tax for the year is CU120. Payments on account total CU90.','PPE has carrying amount CU600 and tax base CU420. A warranty provision has carrying amount CU80 and tax base zero because deductions arise when paid.','The enacted rate is 25%. Opening net deferred tax liability is CU18. Assume sufficient taxable profits for the DTA, offset conditions are met and all movements belong in profit or loss.'],task:'Calculate closing current tax liability, deferred tax balances, net closing deferred tax liability and total tax expense.',hints:['Payments on account reduce the current liability, not current tax expense.','Classify the PPE difference as taxable and the warranty difference as deductible.'],modelAnswer:'Current tax expense is CU120 and closing current tax liability is CU30 (120 − 90 paid). PPE creates a CU180 taxable temporary difference and CU45 DTL (180 × 25%). The warranty provision creates a CU80 deductible temporary difference and CU20 DTA (80 × 25%). With offset conditions met, closing net DTL is CU25. Compared with the opening net DTL of CU18, deferred tax expense is CU7. Total income-tax expense in profit or loss is CU127 (current CU120 + deferred CU7).',reviewChecks:['Current tax liability reconciles to CU30.','PPE creates CU45 DTL.','Warranty creates CU20 DTA subject to recoverability.','Net DTL CU25 and total tax expense CU127 reconcile.'],transfer:'Assume the PPE revaluation movement was recognised in OCI rather than profit or loss. Explain why the related deferred tax movement should follow it outside profit or loss.'},
 checkpoint:[
  {id:'acca-b8-q1',prompt:'Current tax for the year is CU100 and CU70 has been paid on account. What is the closing liability?',options:['CU170','CU100','CU70','CU30'],correctIndex:3,explanation:'Payments reduce the amount payable: CU100 − CU70 = CU30.',reviewSection:'acca-b8-current'},
  {id:'acca-b8-q2',prompt:'An asset has carrying amount CU500 and tax base CU380. What difference commonly arises?',options:['Taxable temporary difference CU120','Deductible temporary difference CU120','Permanent difference CU500','No difference'],correctIndex:0,explanation:'Recovering carrying amount above tax base commonly creates a taxable temporary difference.',reviewSection:'acca-b8-taxbase'},
  {id:'acca-b8-q3',prompt:'A CU60 liability will be deductible only when paid and has tax base zero. What difference commonly arises?',options:['Taxable CU60','Deductible CU60','Permanent CU60','No difference'],correctIndex:1,explanation:'Settlement gives a future deduction, creating a deductible temporary difference.',reviewSection:'acca-b8-taxbase'},
  {id:'acca-b8-q4',prompt:'When is a deferred tax asset recognised for deductible differences?',options:['Always without evidence','Only to the extent sufficient future taxable profit is probable, subject to requirements','Only after tax is paid','Never'],correctIndex:1,explanation:'Recoverability against probable future taxable profit is required.',reviewSection:'acca-b8-deferred'},
  {id:'acca-b8-q5',prompt:'Should deferred tax balances be discounted?',options:['Yes, always at the borrowing rate','Yes, only for liabilities','No','Only when management chooses'],correctIndex:2,explanation:'IAS 12 deferred tax balances are not discounted.',reviewSection:'acca-b8-deferred'}
 ],
 practiceExercises:[
  {id:'acca-b8-p1',question:'Equipment carrying amount is CU240, tax base CU180 and tax rate 25%. Calculate deferred tax.',hints:['Identify the asset difference direction.','Apply the enacted rate.'],answer:'The CU60 taxable temporary difference creates a CU15 deferred tax liability (60 × 25%).',explanation:'Recovery of carrying amount above tax base produces future taxable amounts.'},
  {id:'acca-b8-p2',question:'Repair: “Every non-deductible accounting expense creates a deferred tax asset.”',hints:['Distinguish permanent and temporary differences.','Ask whether the difference reverses.'],answer:'A permanently non-deductible expense does not create a future deduction and therefore does not create a deferred tax asset. Deferred tax arises from temporary differences or qualifying losses and credits.',explanation:'Deferred tax requires future tax consequences.'},
  {id:'acca-b8-p3',question:'Closing net DTL is CU42 and opening net DTL is CU35. All underlying items are in profit or loss. What is the deferred tax movement?',hints:['Compare closing with opening.','An increase in net liability is expense.'],answer:'Recognise CU7 deferred tax expense because the net deferred tax liability increased from CU35 to CU42.',explanation:'The balance-sheet movement reconciles the period charge.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ias-12',label:'IFRS Foundation · IAS 12 Income Taxes',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-12-income-taxes/',supports:'Current tax, tax bases, temporary differences and deferred tax recognition.',reviewedOn}
 ]
};
export function localModelB8For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='B8'?ACCA_B8_MODEL_MODULE:null;}
export {ACCA_B8_MODEL_ID,ACCA_B8_MODEL_SLUG};
