import type {LessonModule} from './lessonModules.ts';
import {ACCA_B10_MODEL_ID,ACCA_B10_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_B10_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'22–28',segments:['The IFRS 15 five-step model.','Point-in-time versus over-time recognition.','A narrated allocation and contract-cost schedule.','Principal-agent and special delivery arrangements.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_B10_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask what the customer has promised to pay and which distinct goods or services the entity has promised to transfer.',supportedPractice:'Move through all five steps in order, keeping transaction-price allocation separate from billing and cash.',misconception:'An invoice, cash receipt or signed contract does not by itself prove that revenue has been earned.',transfer:'Change whether a promise is distinct, when control transfers or whether consideration is variable and ask for one revised conclusion.',close:'Recap contract, obligations, price, allocation and satisfaction without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_B10_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_B10_MODEL_ID,title:'ACCA FR B10 · Revenue',
 goal:'Apply IFRS 15’s five-step model, determine timing and progress, account for qualifying contract costs, and analyse common special arrangements.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level B10 mapping must be checked against the exact selected exam sitting before publication. It is original teaching material, not ACCA approval, legal advice on contracts, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-b10-five-steps',title:'1. Apply the five-step revenue model in sequence',paragraphs:[
   'First identify a contract with a customer: approved rights and payment terms must be identifiable, the arrangement must have commercial substance and collection of consideration must be probable under the Standard’s criteria. Combine contracts when IFRS 15 requires a single commercial package. Next identify each performance obligation, which is generally a promise to transfer a distinct good or service, or a distinct series, rather than every activity used internally to fulfil the promise.',
   'Determine the transaction price, including fixed and estimated variable consideration, significant financing effects, non-cash consideration and amounts payable to the customer when relevant. Include variable consideration only to the extent it is highly probable that a significant revenue reversal will not occur when uncertainty is resolved. This constraint prevents optimistic recognition based solely on the maximum contractual bonus.',
   'Allocate the transaction price to performance obligations using relative stand-alone selling prices, estimating them when not directly observable. Then recognise revenue when or as each obligation is satisfied by transferring control. Billing schedules, deposits and cash collection can differ from performance: the accounting follows promised consideration, allocation and transfer, with receivable, contract-asset or contract-liability presentation as appropriate.'
  ],supportPt:'IFRS 15 segue cinco passos: contrato, performance obligations, transaction price, alocação por stand-alone selling prices e reconhecimento quando o controle é transferido. Caixa e faturamento não substituem essa análise.',sourceIds:['ifrs-15','acca-fr-syllabus']},
  {id:'acca-b10-timing',title:'2. Decide between over-time and point-in-time recognition',paragraphs:[
   'Recognise revenue over time when one of the specified conditions is met: the customer simultaneously receives and consumes benefits as the entity performs; performance creates or enhances an asset the customer controls as it is created; or performance creates an asset with no alternative use to the entity and the entity has an enforceable right to payment for performance completed to date. Otherwise recognise at the point in time when control transfers.',
   'For point-in-time transfer, indicators can include a present right to payment, legal title, physical possession, transfer of significant risks and rewards, and customer acceptance. No single indicator mechanically overrides the control assessment. Shipping terms and acceptance clauses matter because they can show whether the customer can direct use of and obtain substantially all remaining benefits from the asset.',
   'For an over-time obligation, recognise revenue only when progress can be measured reasonably. Output methods measure value transferred, such as surveys of work performed or units delivered; input methods measure effort or resources consumed, such as costs incurred relative to expected total costs. Choose a faithful measure, update estimates and exclude inputs that do not depict performance, including significant inefficiencies where appropriate.'
  ],supportPt:'Reconheça over time apenas se um dos critérios específicos for atendido; caso contrário, use point in time quando o controle passa. Para over time, escolha método de output ou input que represente fielmente o progresso.',sourceIds:['ifrs-15']},
  {id:'acca-b10-costs',title:'3. Account for contract costs and statement extracts',paragraphs:[
   'Recognise an asset for incremental costs of obtaining a contract when the entity expects to recover them. Incremental means the cost would not have been incurred without obtaining that contract, such as a qualifying success commission. A practical expedient permits immediate expense when the amortisation period would be one year or less. Costs incurred regardless of whether the contract is won are normally expensed unless explicitly chargeable to the customer.',
   'Costs to fulfil a contract that are outside another Standard become an IFRS 15 asset only when they relate directly to a specific or anticipated contract, generate or enhance resources used to satisfy future obligations, and are expected to be recovered. Amortise a recognised cost asset systematically in line with transfer of the related goods or services and test it for impairment using the applicable IFRS 15 comparison.',
   'Prepare extracts by separating cumulative performance from cumulative billings or unconditional rights. A contract asset arises when recognised consideration is conditional on something other than passage of time; a receivable is unconditional except for passage of time. A contract liability arises when consideration received or due precedes transfer. Do not describe every unbilled amount as a receivable or net unrelated contracts merely to simplify presentation.'
  ],supportPt:'Incremental contract costs recuperáveis podem virar ativo; fulfilment costs têm três critérios. Amortize conforme a transferência relacionada. Contract asset é direito ainda condicionado; receivable depende apenas do tempo; contract liability representa pagamento antes da performance.',sourceIds:['ifrs-15']},
  {id:'acca-b10-special',title:'4. Analyse principal-agent and special arrangements through control',paragraphs:[
   'A principal controls a specified good or service before transfer to the customer and recognises gross revenue; an agent arranges for another party to provide it and recognises its fee or commission. Indicators such as primary responsibility, inventory risk and pricing discretion support but do not replace the control assessment. Do not classify from the invoice’s gross amount alone.',
   'In a repurchase agreement, an obligation or right to repurchase can mean the customer never obtains control, producing lease or financing accounting depending on the terms rather than an ordinary sale. A call option held by the seller and a put option held by the customer require careful analysis of repurchase price, expected market value and the customer’s economic incentive. The contractual label “sale” is not decisive.',
   'Bill-and-hold revenue before physical delivery requires that the reason is substantive, the product is separately identified as the customer’s, ready for transfer and unavailable for use or redirection by the seller. In a consignment arrangement, control usually remains with the supplier until a specified event such as sale to an end customer; dealer possession and a requested invoice do not automatically create revenue.'
  ],supportPt:'Principal reconhece gross quando controla antes da transferência; agent reconhece fee. Repurchase, bill-and-hold e consignment dependem de controle e condições específicas, não apenas de contrato, posse ou invoice.',sourceIds:['ifrs-15']}
 ],
 terms:[
  {term:'Performance obligation',meaning:'Promise to transfer a distinct good or service, or qualifying series, to a customer.',pt:'Obrigação de desempenho',example:'A handset and monthly network service can be distinct promises.'},
  {term:'Transaction price',meaning:'Consideration the entity expects to be entitled to for transferring promised goods or services.',pt:'Preço da transação',example:'It can include constrained variable consideration.'},
  {term:'Stand-alone selling price',meaning:'Price at which a promised good or service would be sold separately.',pt:'Preço de venda individual',example:'Relative stand-alone prices drive allocation across obligations.'},
  {term:'Over time',meaning:'Recognition pattern used when an IFRS 15 over-time criterion is met.',pt:'Ao longo do tempo',example:'A customer may consume a routine service as it is provided.'},
  {term:'Contract asset',meaning:'Right to consideration conditional on something other than passage of time.',pt:'Ativo contratual',example:'Revenue can exceed unconditional billings during performance.'},
  {term:'Principal versus agent',meaning:'Assessment of whether the entity controls the specified item or merely arranges its provision.',pt:'Principal versus agente',example:'A principal reports gross revenue; an agent generally reports its fee.'}
 ],
 visual:{title:'Bundle allocation and first-quarter recognition',note:'Original schedule; fictional CU amounts. The service is a stand-ready obligation satisfied evenly over 12 months.',headers:['Promise','Relative allocation','Revenue after 3 months'],rows:[['Handset: SSP 600','540','540'],['12-month service: SSP 600','540','135'],['Total contract price','1,080','675'],['Remaining allocated service','—','405']],question:'Why is the handset allocated CU540 rather than its CU600 stand-alone selling price?',answer:'Both stand-alone prices total CU1,200, so the CU1,080 transaction price is allocated 50:50. The handset receives CU540.'},
 caseStudy:{title:'Device, service and incremental commission',scenario:['A customer signs a 12-month contract for a handset delivered immediately and network service provided evenly over the term. Total fixed consideration is CU1,080, billed CU90 monthly.','The handset and service are distinct. Each has a stand-alone selling price of CU600. At the reporting date, three months of service have been provided and CU270 has been billed and collected.','A CU108 sales commission was payable only because this contract was obtained, is expected to be recovered and is amortised over the 12-month service pattern. Ignore the one-year practical expedient.'],task:'Allocate the transaction price, calculate cumulative revenue and closing contract asset after three months, and account for the commission.',hints:['Allocate CU1,080 using the equal CU600 stand-alone prices.','Compare cumulative revenue with unconditional billings, then amortise the commission over 12 months.'],modelAnswer:'The equal stand-alone selling prices allocate CU540 to the handset and CU540 to service. Recognise CU540 when the handset control transfers and CU135 for three months of service (CU540 × 3/12), giving cumulative revenue CU675. With CU270 billed and collected, the remaining CU405 right is conditional on future service or billing conditions and is presented as a contract asset under the stated facts. Capitalise the CU108 incremental recoverable commission, amortise CU27 over three months and report a closing cost asset of CU81. Cash collection does not cap revenue already earned under the allocation.',reviewChecks:['The transaction price is allocated CU540 to each promise.','Cumulative revenue is CU675.','The contract asset is CU405 under the stated billing conditions.','Commission expense CU27 and closing cost asset CU81 reconcile.'],transfer:'Assume the handset is not distinct because it cannot function without a highly integrated service supplied by the entity. Reassess the number of obligations and revenue timing.'},
 checkpoint:[
  {id:'acca-b10-q1',prompt:'What is the correct IFRS 15 step order?',options:['Price, cash, invoice, tax, profit','Contract, obligations, transaction price, allocation, recognition','Invoice, contract, collection, allocation, recognition','Customer, cost, margin, tax, cash'],correctIndex:1,explanation:'The five-step model starts with the contract and ends with satisfaction of obligations.',reviewSection:'acca-b10-five-steps'},
  {id:'acca-b10-q2',prompt:'When is a performance obligation recognised over time?',options:['Whenever cash is received early','When at least one specified IFRS 15 over-time criterion is met','Whenever a contract lasts more than one year','Whenever management prefers smoother revenue'],correctIndex:1,explanation:'Duration or billing alone does not determine the recognition pattern.',reviewSection:'acca-b10-timing'},
  {id:'acca-b10-q3',prompt:'What distinguishes a receivable from a contract asset?',options:['A receivable is always cash','A receivable is unconditional except for passage of time','A contract asset can never become a receivable','There is no distinction'],correctIndex:1,explanation:'A contract asset remains conditional on something beyond passage of time.',reviewSection:'acca-b10-costs'},
  {id:'acca-b10-q4',prompt:'When is an incremental sales commission capitalised under the core rule?',options:['Whenever paid','When it would not have arisen without the contract and recovery is expected','Only when invoiced to the customer','Never'],correctIndex:1,explanation:'Incrementality and expected recovery support a contract-cost asset, subject to the practical expedient.',reviewSection:'acca-b10-costs'},
  {id:'acca-b10-q5',prompt:'How does an agent normally present revenue for arranging a specified service?',options:['Gross customer billing','Its fee or commission','The supplier’s entire cost','No amount'],correctIndex:1,explanation:'An agent does not control the specified service before transfer and generally recognises its fee.',reviewSection:'acca-b10-special'}
 ],
 practiceExercises:[
  {id:'acca-b10-p1',question:'A CU900 bundle contains distinct goods with stand-alone prices CU600 and CU400. Allocate the transaction price.',hints:['Total the stand-alone prices.','Apply each relative proportion to CU900.'],answer:'Allocate CU540 to the first good (600/1,000 × 900) and CU360 to the second (400/1,000 × 900).',explanation:'Allocation uses relative stand-alone selling prices.'},
  {id:'acca-b10-p2',question:'Repair: “Revenue equals invoices issued, so an advance invoice proves the obligation is satisfied.”',hints:['Separate billing from transfer of control.','Consider a contract liability.'],answer:'An invoice does not prove performance. If consideration is due before transfer, recognise a receivable as applicable and a contract liability; recognise revenue only when or as the obligation is satisfied.',explanation:'IFRS 15 follows performance, not the invoice date alone.'},
  {id:'acca-b10-p3',question:'A CU240 service is one over-time obligation satisfied evenly across eight months. Three months are complete. Calculate revenue.',hints:['Use a faithful time-based measure for the stated even service.','Apply 3/8 to the allocated price.'],answer:'Recognise CU90 revenue after three months: CU240 × 3/8.',explanation:'The even stand-ready service is measured by elapsed time under the stated facts.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ifrs-15',label:'IFRS Foundation · IFRS 15 Revenue from Contracts with Customers',url:'https://www.ifrs.org/issued-standards/list-of-standards/ifrs-15-revenue-from-contracts-with-customers/',supports:'Five-step model, timing, progress, contract costs and special arrangements.',reviewedOn}
 ]
};
export function localModelB10For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='B10'?ACCA_B10_MODEL_MODULE:null;}
export {ACCA_B10_MODEL_ID,ACCA_B10_MODEL_SLUG};
