import type {LessonModule} from './lessonModules.ts';
import {ACCA_B1_MODEL_ID,ACCA_B1_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_B1_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'22–28',segments:['Recognition and directly attributable cost.','Available-for-use depreciation and componentisation.','Cost versus revaluation model.','Derecognition and a narrated PPE schedule.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_B1_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask what condition and location management needs the asset to reach, then classify each cost before calculating depreciation.',supportedPractice:'Use a cost bridge, an available-for-use date and separate component lives; give one hint before revealing the full schedule.',misconception:'Invoice date, payment date and delivery date do not automatically determine when depreciation starts.',transfer:'Change one cost, residual value, available-for-use date, component life or revaluation fact and ask for the revised carrying amount.',close:'Recap recognition, cost, depreciation, revaluation and derecognition without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_B1_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_B1_MODEL_ID,title:'ACCA FR B1 · Property, plant and equipment',
 goal:'Build an IAS 16 cost and depreciation schedule, apply component accounting and explain revaluation and derecognition effects.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level B1 mapping must be checked against the exact selected exam sitting before publication. It focuses on core IAS 16 treatment and does not replace a complete disclosure, tax or specialist-asset analysis. It is original teaching material, not ACCA approval, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-b1-recognition',title:'1. Recognise PPE and construct initial cost',paragraphs:[
   'Recognise property, plant and equipment when future economic benefits are probable and cost can be measured reliably. PPE is held for production or supply, rental or administration and is expected to be used for more than one period. Apply the criteria to replacement parts and major inspections as well as an initial purchase.',
   'Initial cost includes purchase price net of discounts, directly attributable costs of bringing the asset to the location and condition necessary for management’s intended operation, and the initial estimate of qualifying dismantling or restoration obligations. Examples can include site preparation, delivery, installation, professional fees and testing net of proceeds from items produced while testing.',
   'Expense staff training, opening ceremonies, general administration, abnormal waste, initial operating losses and costs incurred after the asset is capable of operating as intended. Borrowing costs and restoration obligations follow their own applicable requirements; do not add them mechanically without the facts.'
  ],supportPt:'Capitalize custos necessários para levar o ativo ao local e condição de operação pretendida. Treinamento, desperdício anormal e perdas operacionais iniciais não viram PPE apenas por ocorrerem no projeto.',sourceIds:['ias-16','acca-fr-syllabus']},
  {id:'acca-b1-depreciation',title:'2. Depreciate from availability and review estimates',paragraphs:[
   'Depreciable amount is cost or revalued amount less residual value. Allocate it systematically over useful life, beginning when the asset is available for use—not necessarily when ordered, invoiced, paid or first used at full capacity. Depreciation normally continues while idle unless the asset is fully depreciated or classified under another applicable requirement.',
   'Review residual value, useful life and method at least at each financial year-end. A change in estimate is applied prospectively under IAS 8; it is not rewritten as though management knew the new estimate at acquisition. The method should reflect the consumption pattern and revenue-based depreciation is generally inappropriate.',
   'Time apportionment must follow the available-for-use date and the question’s policy. Show the depreciable base, annual charge, fraction of the period and closing accumulated depreciation. This makes a one-day date error or a mistaken inclusion in cost visible.'
  ],supportPt:'Valor depreciável é custo ou valor reavaliado menos residual. A depreciação começa quando o ativo está disponível para uso; mudanças de vida, residual ou método são estimativas prospectivas.',sourceIds:['ias-16']},
  {id:'acca-b1-components',title:'3. Separate significant components and later expenditure',paragraphs:[
   'Depreciate each significant part of an item separately when it has a different useful life or consumption pattern. The remainder may be grouped only when its parts are not individually significant or have similar patterns. Componentisation is not a cosmetic split: it affects replacement, depreciation and derecognition.',
   'Day-to-day servicing is expensed. A replacement or major inspection is capitalised when the recognition criteria are met, and the carrying amount of the replaced part or previous inspection is derecognised even if it was not separately identified at acquisition. A reasonable estimate may be needed to identify that old amount.',
   'Keep physical work and accounting unit distinct. A large overhaul does not automatically create a new asset if it merely repairs damage, while a qualifying inspection component can be recognised even when no physical part is added.'
  ],supportPt:'Componentes significativos com vidas diferentes são depreciados separadamente. Na substituição ou inspeção qualificável, reconheça o novo custo e dê baixa no valor do componente anterior.',sourceIds:['ias-16']},
  {id:'acca-b1-revaluation',title:'4. Apply the model consistently and account for disposal',paragraphs:[
   'After recognition, an entity chooses the cost model or revaluation model for an entire class of PPE. Under the revaluation model, carry assets at fair value at the revaluation date less later depreciation and impairment, with revaluations frequent enough to avoid material difference from fair value.',
   'A revaluation increase is normally recognised in other comprehensive income and accumulated in revaluation surplus, except to the extent it reverses a prior decrease on the same asset recognised in profit or loss. A decrease normally goes to profit or loss, except to the extent of an existing surplus for that asset. Depreciation then uses the revalued amount and remaining life.',
   'Derecognise PPE on disposal or when no future benefits are expected. The gain or loss is net disposal proceeds less carrying amount and is normally recognised in profit or loss, not revenue. Any transfer of revaluation surplus to retained earnings is a movement within equity, not recycling through profit.'
  ],supportPt:'Escolha o modelo por classe. Reavaliações passam por OCI ou resultado conforme histórico do mesmo ativo; após a reavaliação, recalcule depreciação. Na baixa, compare valor líquido recebido ao valor contábil.',sourceIds:['ias-16']}
 ],
 terms:[
  {term:'Directly attributable cost',meaning:'Cost directly caused by bringing an asset to the necessary location and condition.',pt:'Custo diretamente atribuível',example:'Installation needed before operation is included in initial cost.'},
  {term:'Available for use',meaning:'Asset is in the location and condition necessary for intended operation.',pt:'Disponível para uso',example:'Depreciation starts when installation and testing are complete.'},
  {term:'Depreciable amount',meaning:'Cost or revalued amount less residual value.',pt:'Valor depreciável',example:'CU550 less CU50 residual value gives CU500.'},
  {term:'Component accounting',meaning:'Separate depreciation of significant parts with different lives or patterns.',pt:'Contabilização por componentes',example:'An aircraft body and engine may have different useful lives.'},
  {term:'Revaluation surplus',meaning:'Equity accumulation of qualifying revaluation increases recognised in OCI.',pt:'Reserva de reavaliação',example:'A CU60 increase may enter OCI when no prior decrease applies.'},
  {term:'Derecognition gain or loss',meaning:'Difference between net disposal proceeds and carrying amount.',pt:'Ganho ou perda na baixa',example:'Net proceeds CU90 less carrying amount CU75 gives a CU15 gain.'}
 ],
 visual:{title:'PPE cost and first depreciation bridge',note:'Original fictional amounts in CU; assume straight-line depreciation and no restoration obligation.',headers:['Item','Treatment','Amount'],rows:[['Machine price','Capitalise','500'],['Delivery','Capitalise','20'],['Installation','Capitalise','30'],['Training','Expense','12'],['Abnormal testing waste','Expense','8'],['Capitalised cost','PPE','550'],['Annual depreciation','(550 − 50) / 10','50']],question:'If the machine is available for use on 1 April and the year ends 31 December, what is depreciation under monthly time apportionment?',answer:'Nine months: CU50 × 9/12 = CU37.5. Invoice and payment dates do not replace the available-for-use date.'},
 caseStudy:{title:'Component replacement followed by revaluation',scenario:['On 1 April 2026 an entity completes a production line: price CU900, delivery CU30, installation CU50, staff training CU20 and abnormal testing waste CU10. Residual value is CU80.','Of the CU980 capitalised cost, a furnace component is CU280 with a four-year life; the remaining CU700 has a ten-year life. Both are available for use on 1 April. Use monthly straight-line depreciation to 31 December.','At 31 December, after depreciation, the whole class is revalued to CU930. Assume no prior revaluation and allocate the increase proportionately to the two components.'],task:'Calculate initial cost, expenses, component depreciation, carrying amount before revaluation and the revaluation increase.',hints:['Exclude training and abnormal waste before splitting the capitalised cost.','Calculate nine months for each component, then compare total carrying amount with CU930.'],modelAnswer:'Capitalise CU980 (900 + 30 + 50) and expense CU30 (20 + 10). Furnace annual depreciation is CU70 (280 / 4) and nine months is CU52.5. Allocate the CU80 residual value to the remaining component under the supplied facts: its annual depreciation is CU62 ((700 − 80) / 10) and nine months is CU46.5. Total depreciation is CU99 and carrying amount before revaluation is CU881. The revaluation increase is CU49 (930 − 881), recognised in OCI and revaluation surplus because there is no prior decrease. Future depreciation uses the allocated revalued component amounts and remaining useful lives.',reviewChecks:['Initial cost is CU980 and CU30 is expensed.','The two components use different useful lives.','Nine-month depreciation totals CU99.','CU49 revaluation increase is separated from profit.'],transfer:'Assume a prior CU20 revaluation decrease on this asset had been recognised in profit or loss. Explain the split of the CU49 increase.'},
 checkpoint:[
  {id:'acca-b1-q1',prompt:'Which cost is normally excluded from initial PPE cost?',options:['Delivery needed to reach the site','Installation','Staff training','Site preparation'],correctIndex:2,explanation:'Training does not bring the asset itself to the necessary location and condition.',reviewSection:'acca-b1-recognition'},
  {id:'acca-b1-q2',prompt:'When does depreciation begin?',options:['On invoice date','When available for use','Only when paid','After the first profitable month'],correctIndex:1,explanation:'Depreciation begins when the asset is in the location and condition necessary for intended operation.',reviewSection:'acca-b1-depreciation'},
  {id:'acca-b1-q3',prompt:'How is a useful-life change applied?',options:['Retrospectively as an error','Prospectively as a change in estimate','Through share capital','Never changed'],correctIndex:1,explanation:'Useful life and residual value changes are normally changes in estimate applied prospectively.',reviewSection:'acca-b1-depreciation'},
  {id:'acca-b1-q4',prompt:'What happens when a qualifying major inspection is replaced?',options:['Keep both inspection amounts','Capitalise the new inspection and derecognise the old carrying amount','Expense every inspection automatically','Record revenue'],correctIndex:1,explanation:'The replacement is recognised when criteria are met and the previous inspection component is removed.',reviewSection:'acca-b1-components'},
  {id:'acca-b1-q5',prompt:'Where does a revaluation increase normally begin when no prior decrease exists?',options:['Revenue','OCI and revaluation surplus','Finance cost','Share premium'],correctIndex:1,explanation:'The increase is normally recognised in OCI and accumulated in revaluation surplus.',reviewSection:'acca-b1-revaluation'}
 ],
 practiceExercises:[
  {id:'acca-b1-p1',question:'Price CU400, delivery CU15, installation CU25, training CU10 and abnormal waste CU5. Calculate PPE cost.',hints:['Include only costs bringing the asset to location and condition.','Expense training and abnormal waste.'],answer:'PPE cost is CU440 (400 + 15 + 25). CU15 is expensed.',explanation:'Project proximity does not make every cost directly attributable.'},
  {id:'acca-b1-p2',question:'An asset cost CU600, residual value CU60 and life nine years. Calculate annual straight-line depreciation.',hints:['Find depreciable amount.','Divide by useful life.'],answer:'CU60 per year: (600 − 60) / 9.',explanation:'Depreciate the amount expected to be consumed, not gross cost automatically.'},
  {id:'acca-b1-p3',question:'Repair: “A CU25 disposal receipt is revenue.” Carrying amount is CU18 and selling cost CU2.',hints:['Use net proceeds.','Compare with carrying amount.'],answer:'Net proceeds are CU23, producing a CU5 disposal gain (23 − 18), normally recognised in profit or loss rather than revenue.',explanation:'Disposal proceeds are not operating revenue merely because cash was received.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ias-16',label:'IFRS Foundation · IAS 16 Property, Plant and Equipment',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-16-property-plant-and-equipment/',supports:'Recognition, cost, depreciation, components, revaluation and derecognition.',reviewedOn}
 ]
};
export function localModelB1For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='B1'?ACCA_B1_MODEL_MODULE:null;}
export {ACCA_B1_MODEL_ID,ACCA_B1_MODEL_SLUG};
