import type {LessonModule} from './lessonModules.ts';
import {ACCA_C2_MODEL_ID,ACCA_C2_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_C2_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'22–28',segments:['Profitability and efficient use of capital.','Liquidity and working-capital days.','Gearing, interest cover and investor signals.','An evidence-led interpretation using cash flow and non-financial information.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_C2_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask which stakeholder decision is being supported, which comparison is available and how each ratio is defined before calculating.',supportedPractice:'Calculate on a consistent basis, compare with a relevant benchmark, connect related ratios and explain a scenario-based cause plus the evidence needed to test it.',misconception:'A favourable movement in one ratio does not prove improved performance; margins, working capital, cash flow, financing risk and non-financial drivers must be reconciled.',transfer:'Change one underlying amount, valuation basis, comparator or stakeholder and ask which ratio and conclusion change.',close:'Recap calculation, comparison, cause, consequence and evidence without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_C2_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_C2_MODEL_ID,title:'ACCA FR C2 · Accounting ratios and trends',
 goal:'Calculate and interpret profitability, efficiency, liquidity, gearing and investor ratios, then combine trends with cash-flow, valuation and non-financial evidence for a named stakeholder.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level C2 mapping must be checked against the exact selected exam sitting before publication. Formula conventions are stated because valid alternatives exist. It is original teaching material, not ACCA approval, investment advice, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-c2-profitability',title:'1. Link profitability to the efficient use of capital',paragraphs:[
   'Gross profit margin is gross profit divided by revenue, while operating profit margin is profit before interest and tax divided by revenue. A falling gross margin can signal changes in selling prices, sales mix, input costs or inventory measurement. A different movement in operating margin points to distribution, administrative or other operating expenses. Reconcile the two margins before naming a cause, and use the scenario rather than a memorised explanation.',
   'Return on capital employed (ROCE) is operating profit divided by capital employed. This lesson defines capital employed as equity plus non-current interest-bearing debt, equivalent to total assets less current liabilities when the classifications reconcile. ROCE can be analysed as operating margin multiplied by asset turnover, where asset turnover is revenue divided by capital employed. That relationship shows whether return changed because of margin, use of the asset base or both.',
   'Use average capital employed when reliable opening and closing data are available and it better matches the period profit; otherwise state that closing capital employed is an approximation. A major acquisition late in the year, revaluation or asset held at old historical cost can distort comparisons. Calculate consistently, but do not hide a meaningful measurement difference merely to make two entities appear comparable.'
  ],supportPt:'Gross margin, operating margin, asset turnover e ROCE devem ser lidos em conjunto. Declare a base de capital employed e verifique se lucro do período e denominador representam períodos comparáveis.',sourceIds:['acca-fr-syllabus','acca-interpretation']},
  {id:'acca-c2-working-capital',title:'2. Read liquidity together with working-capital activity',paragraphs:[
   'The current ratio is current assets divided by current liabilities. The quick ratio removes inventory from current assets before division because inventory may take longer to convert into cash. Neither ratio is a cash forecast: collectability, inventory quality, payment timing, unused facilities and seasonal peaks matter. A very high current ratio can also reflect slow inventory or receivables rather than strength.',
   'Working-capital days explain part of the movement. Inventory days are average inventory divided by cost of sales multiplied by 365. Receivable days are average trade receivables divided by credit revenue multiplied by 365. Payable days are average trade payables divided by credit purchases multiplied by 365. If only closing balances or cost of sales are available, label the approximation and keep comparisons on the same basis.',
   'Interpret the operating sequence. Longer receivable days can absorb cash and signal collection problems, although deliberate credit terms supporting growth may explain them. Longer payable days preserve cash but may indicate supplier pressure or lost settlement discounts. Lower inventory days can improve efficiency or create stock-out risk. Compare ageing, write-downs, credit terms, supplier relationships and cash generated from operations before advising.'
  ],supportPt:'Current e quick ratios são fotografias, não previsões de caixa. Use inventory, receivable e payable days com bases consistentes e investigue qualidade, ageing, termos e sazonalidade.',sourceIds:['acca-fr-syllabus','acca-interpretation','acca-fr-technical']},
  {id:'acca-c2-financing',title:'3. Connect gearing, debt service and investor measures',paragraphs:[
   'This lesson defines gearing as interest-bearing debt divided by debt plus equity. Some questions or organisations use debt divided by equity, so state and apply the required convention consistently. Higher gearing can increase shareholder returns when operations perform well, but it also increases fixed financing commitments and exposure to covenant, refinancing and interest-rate risk.',
   'Interest cover is operating profit divided by finance costs. It estimates how many times operating profit covers the period charge, not whether enough cash is available on the payment date. A fall can arise from weaker operations, more debt or higher rates. Reconcile it with operating cash flow, debt maturity, fixed versus floating terms and any exceptional finance effects.',
   'Investor ratios answer different questions. Earnings per share uses earnings attributable to ordinary shareholders and the weighted-average number of ordinary shares; the price/earnings ratio relates market price to EPS. Dividend yield compares dividend per share with market price, while dividend cover compares earnings per share with dividend per share. Market price reflects expectations beyond the statements, so explain rather than assume why a high or low multiple exists.'
  ],supportPt:'Declare a convenção de gearing e combine-a com interest cover, caixa e vencimentos. EPS, P/E, dividend yield e cover trazem sinais diferentes e o preço incorpora expectativas externas.',sourceIds:['acca-fr-syllabus','acca-interpretation']},
  {id:'acca-c2-integrated',title:'4. Build a stakeholder-focused, evidence-led interpretation',paragraphs:[
   'A strong interpretation follows a traceable chain: calculate accurately, compare with the prior period, a similar entity or an industry benchmark, identify related movements, use scenario facts to propose a cause, explain the consequence for a named stakeholder and state what evidence would test the conclusion. Avoid lists of percentages without analysis and generic causes that could apply to any entity.',
   'Include the statement of cash flows. Profit growth with weak operating cash generation may reflect rising receivables or inventory; asset purchases explain investing outflows; new debt or share issues explain financing inflows. One year of cash flow does not prove a sustainable trend, but it can confirm or challenge conclusions drawn from accrual figures and year-end ratios.',
   'Measurement bases affect comparison. Current values can be more relevant for current economic capacity but may introduce estimation uncertainty and volatility; old historical costs can overstate asset turnover or ROCE relative to a recently acquired or revalued asset base. Add non-financial information such as volumes, market share, capacity use, customer retention, product quality, employee turnover, safety, emissions and order backlog. Disclose uncertainty and tailor advice: lenders emphasise liquidity and debt service, investors return and risk, suppliers payment capacity, and management operational drivers.'
  ],supportPt:'Uma interpretação forte liga cálculo, benchmark, relação entre ratios, causa do cenário, consequência para o stakeholder e evidência adicional. Inclua cash flow, base de mensuração e dados não financeiros.',sourceIds:['acca-fr-syllabus','acca-interpretation','conceptual-framework']}
 ],
 terms:[
  {term:'ROCE',meaning:'Operating profit divided by capital employed under a stated, consistent convention.',pt:'Retorno sobre capital empregado',example:'CU180,000 divided by CU1,200,000 gives 15.0%.'},
  {term:'Asset turnover',meaning:'Revenue generated per unit of capital employed.',pt:'Giro do ativo/capital',example:'Revenue CU1.5m divided by capital employed CU1.2m gives 1.25 times.'},
  {term:'Quick ratio',meaning:'Current assets excluding inventory divided by current liabilities.',pt:'Liquidez seca',example:'CU240,000 of quick assets divided by CU300,000 liabilities gives 0.80.'},
  {term:'Working-capital days',meaning:'Days measures relating inventory, receivables or payables to the relevant annual flow.',pt:'Dias de capital de giro',example:'Receivable days relate trade receivables to credit revenue.'},
  {term:'Gearing',meaning:'Relationship between interest-bearing debt and financing, using a stated convention.',pt:'Alavancagem financeira',example:'Debt divided by debt plus equity rises from 30% to 40%.'},
  {term:'Interest cover',meaning:'Operating profit divided by finance costs.',pt:'Cobertura de juros',example:'CU180,000 operating profit covers CU48,000 finance costs 3.75 times.'}
 ],
 visual:{title:'Ratio dashboard: signal, relationship and caution',note:'Original schedule; fictional amounts. All ratios use the stated conventions.',headers:['2026 movement','Related signal','Question before concluding'],rows:[['Revenue +25%; gross margin 35% from 40%','Volume growth with gross-margin pressure','Prices, mix or input cost?'],['ROCE 15% from 16%; turnover 1.25× from 1.14×','Efficiency rose but margin fell','Was new capacity fully productive?'],['Quick ratio 0.80 from 1.00','Less liquid cover','Are receivables collectible and facilities available?'],['Receivable days 43.8 from 36.5','More cash tied up','Growth terms or collection weakness?'],['Gearing 40% from 30%; cover 3.75× from 6.00×','Higher financing risk','Cash generation, rates and maturity?']],question:'Why is 25% revenue growth not enough to call 2026 a better year?',answer:'Both margins and ROCE fell, receivables slowed and financing risk rose, so the stakeholder needs causes, cash flow and non-financial evidence before concluding.'},
 caseStudy:{title:'Growth funded with more debt',scenario:['A company reports 2026 revenue CU1,500,000, cost of sales CU975,000, operating profit CU180,000 and capital employed CU1,200,000. For 2025 the figures were CU1,200,000, CU720,000, CU168,000 and CU1,050,000. Capital employed is defined consistently as debt plus equity.','Current assets are CU480,000 (2025: CU420,000), including inventory CU240,000 (CU180,000), and current liabilities are CU300,000 (CU240,000). Reliable average inventory is CU210,000 (CU160,000), and trade receivables are CU180,000 (CU120,000). Assume all revenue is on credit.','Interest-bearing debt is CU480,000 (CU315,000), equity CU720,000 (CU735,000), and finance costs CU48,000 (CU28,000). Operating cash flow and customer-retention data have not yet been provided.'],task:'Calculate the key profitability, efficiency, liquidity, receivable and financing ratios, then give a balanced interpretation for a lender.',hints:['Gross profit is revenue less cost of sales; use operating profit for ROCE and interest cover.','Use average inventory for inventory days and the stated debt/(debt + equity) gearing convention.'],modelAnswer:'Revenue grew 25.0%, but gross margin fell from 40.0% to 35.0% and operating margin from 14.0% to 12.0%. Operating profit grew only 7.1%. ROCE fell from 16.0% to 15.0%, even though asset turnover rose from 1.14 times to 1.25 times, so lower margins outweighed the improved use of capital. The current ratio fell from 1.75 to 1.60 and the quick ratio from 1.00 to 0.80. Inventory days improved slightly from 81.1 to 78.6 using reliable average inventory, but receivable days worsened from 36.5 to 43.8. Gearing rose from 30.0% to 40.0%, while interest cover fell from 6.00 to 3.75 times. For a lender, revenue growth and slightly faster inventory are positives, but weaker margins, collections, liquid cover and debt-service headroom increase risk. Obtain operating cash flow, receivables ageing, borrowing terms and customer-retention evidence before deciding whether the growth is sustainable and the facility affordable.',reviewChecks:['Gross and operating margins fall despite 25.0% revenue growth.','ROCE is 15.0% versus 16.0%; asset turnover is 1.25 times versus 1.14 times.','Current ratio is 1.60 and quick ratio 0.80; receivable days worsen to 43.8.','Gearing rises to 40.0% and interest cover falls to 3.75 times.'],transfer:'Assume CU120,000 of the 2026 debt is repaid one day after year end using cash included in current assets. Explain which ratios change and why a year-end-only conclusion may be fragile.'},
 checkpoint:[
  {id:'acca-c2-q1',prompt:'How can ROCE be decomposed under the lesson convention?',options:['Gross margin multiplied by current ratio','Operating margin multiplied by asset turnover','Quick ratio multiplied by gearing','EPS multiplied by dividend yield'],correctIndex:1,explanation:'Operating profit/revenue multiplied by revenue/capital employed equals operating profit/capital employed.',reviewSection:'acca-c2-profitability'},
  {id:'acca-c2-q2',prompt:'Why can a very high current ratio still require investigation?',options:['Liquidity ratios are prohibited','It may reflect slow inventory or receivables rather than strength','Current liabilities never affect cash','Inventory is always immediately convertible to cash'],correctIndex:1,explanation:'The quality and speed of conversion of current assets matter.',reviewSection:'acca-c2-working-capital'},
  {id:'acca-c2-q3',prompt:'Which denominator is appropriate for receivable days when available?',options:['Total assets','Credit revenue','Operating profit','Finance costs'],correctIndex:1,explanation:'Trade receivables are related to the credit revenue flow that generated them.',reviewSection:'acca-c2-working-capital'},
  {id:'acca-c2-q4',prompt:'What does a fall in interest cover directly indicate?',options:['Operating profit covers finance costs fewer times','Every debt payment has already defaulted','Cash must equal operating profit','Gearing has necessarily fallen'],correctIndex:0,explanation:'Interest cover is an accrual-profit measure of finance-cost headroom, not direct proof of cash or default.',reviewSection:'acca-c2-financing'},
  {id:'acca-c2-q5',prompt:'Which is the strongest interpretation of the worked case for a lender?',options:['Revenue growth alone proves stronger performance','Lower inventory days removes all liquidity risk','Growth is positive, but weaker margins, collections, liquid cover and debt service require cash-flow and other evidence','Higher gearing always benefits every stakeholder'],correctIndex:2,explanation:'The balanced conclusion connects related ratios to the lender decision and identifies missing evidence.',reviewSection:'acca-c2-integrated'}
 ],
 practiceExercises:[
  {id:'acca-c2-p1',question:'Revenue is CU800,000, operating profit CU96,000 and capital employed CU600,000. Calculate operating margin, asset turnover and ROCE, then reconcile them.',hints:['Use revenue as the margin denominator.','Check that margin multiplied by turnover equals ROCE.'],answer:'Operating margin is 12.0%, asset turnover is 1.33 times and ROCE is 16.0%. The unrounded relationship is 12.0% × 1.333 = 16.0%.',explanation:'The decomposition links profit per sale with revenue generated by the capital base.'},
  {id:'acca-c2-p2',question:'Repair: “Receivable days rose, so customers are definitely unable to pay.”',hints:['Distinguish a signal from a proven cause.','Request scenario and ageing evidence.'],answer:'Higher receivable days show slower collection on the stated basis, but could reflect changed credit terms, sales timing, mix or payment problems. Review ageing, subsequent receipts, customer concentration and policy before concluding.',explanation:'Ratio movements need contextual evidence and a stated degree of certainty.'},
  {id:'acca-c2-p3',question:'A business has current assets CU360,000, inventory CU150,000 and current liabilities CU240,000. Calculate current and quick ratios and explain the difference.',hints:['Current ratio includes all current assets.','Quick ratio removes inventory.'],answer:'The current ratio is 1.50 and the quick ratio is 0.88 (CU210,000 / CU240,000). Inventory accounts for the gap, so its quality and conversion cycle matter to the liquidity conclusion.',explanation:'Removing inventory highlights reliance on less immediately liquid current assets.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Current C2 outcomes for ratios, trends, stakeholders, cash flow, measurement bases and non-financial information.',reviewedOn},
  {id:'acca-interpretation',label:'ACCA · How to improve your answer to FR interpretation exam questions',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/technical-articles/interpretation-questions.html',supports:'Evidence-linked comparison, ratio relationships and scenario-specific analysis.',reviewedOn},
  {id:'acca-fr-technical',label:'ACCA · Financial Reporting technical articles',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/technical-articles.html',supports:'Official interpretation and statement-of-cash-flows study resources.',reviewedOn},
  {id:'conceptual-framework',label:'IFRS Foundation · Conceptual Framework for Financial Reporting',url:'https://www.ifrs.org/issued-standards/list-of-standards/conceptual-framework/',supports:'Users, useful information, measurement and presentation concepts.',reviewedOn}
 ]
};
export function localModelC2For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='C2'?ACCA_C2_MODEL_MODULE:null;}
export {ACCA_C2_MODEL_ID,ACCA_C2_MODEL_SLUG};
