import type {LessonModule} from './lessonModules.ts';
import {ACCA_B7_MODEL_ID,ACCA_B7_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-21';
export const ACCA_B7_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'20–26',segments:['Present obligation before probability.','Provision, contingent liability and contingent asset decision paths.','A narrated expected-value warranty estimate.','Adjusting versus non-adjusting events after the reporting period.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_B7_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask which past event created the present legal or constructive obligation.',supportedPractice:'Classify first, then measure; do not use a probability percentage as the provision amount without considering the population and evidence.',misconception:'A probable outflow alone does not create a provision when there is no present obligation from a past event.',transfer:'Change whether the condition existed at year end and ask whether a later event adjusts or only discloses.',close:'Recap recognition, measurement, contingencies and IAS 10 timing without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_B7_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_B7_MODEL_ID,title:'ACCA FR B7 · Provisions and events after the reporting period',
 goal:'Recognise and measure provisions, distinguish contingencies, and classify adjusting and non-adjusting events using IAS 37 and IAS 10.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level B7 mapping must be checked against the exact selected exam sitting before publication. It is original teaching material, not ACCA approval, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-b7-recognition',title:'1. Establish a present obligation before recognising a provision',paragraphs:[
   'Recognise a provision when a past event creates a present legal or constructive obligation, an outflow of resources is probable, and a reliable estimate can be made. Test the criteria in that order. Expected future expenditure, commercial pressure or management intention is not enough when the entity can still avoid the expenditure through its future actions.',
   'A legal obligation can arise from contract, legislation or other operation of law. A constructive obligation arises when an established pattern, published policy or sufficiently specific current statement creates a valid expectation in other parties that the entity will accept a responsibility. Internal plans alone do not normally create that expectation.',
   'The obligating event leaves the entity with no realistic alternative to settlement. A warranty attached to products already sold can create an obligation; a decision to repair equipment next year usually does not. Future operating losses are not provided because no past transaction has created a present obligation, although expected losses may indicate impairment under another Standard.'
  ],supportPt:'Reconheça provisão somente com obrigação presente de evento passado, saída provável e estimativa confiável. Intenção interna ou gasto futuro evitável não basta. A obrigação construtiva exige expectativa válida criada perante terceiros.',sourceIds:['ias-37','acca-fr-syllabus']},
  {id:'acca-b7-measurement',title:'2. Measure the best estimate and special cases consistently',paragraphs:[
   'Measure a provision at the best estimate of expenditure required to settle or transfer the present obligation at the reporting date. For a large population, expected value can weight possible outcomes by probability. For a single obligation, the individually most likely outcome may be a starting point, adjusted when other outcomes materially affect the best estimate.',
   'Reflect risks and uncertainties without double counting or deliberate overstatement. Discount when the time value of money is material, using a pre-tax rate consistent with risks not already built into cash flows. Unwinding the discount increases the provision as a finance cost. Recognise a reimbursement separately only when receipt is virtually certain, and do not present an asset above the related provision.',
   'An onerous contract has unavoidable fulfilment costs exceeding expected benefits and can require a provision after related assets are tested for impairment. A restructuring provision requires a sufficiently detailed formal plan and a valid expectation created in those affected; it excludes future operating losses, retraining, marketing and investment in new systems.'
  ],supportPt:'Mensuração usa a melhor estimativa: valor esperado para grandes populações, julgamento para obrigação única e desconto quando material. Reembolso é ativo separado apenas se virtualmente certo. Contrato oneroso e reestruturação têm testes próprios.',sourceIds:['ias-37']},
  {id:'acca-b7-contingencies',title:'3. Distinguish provisions from contingent liabilities and assets',paragraphs:[
   'A contingent liability can be a possible obligation whose existence depends on uncertain future events outside the entity’s full control, or a present obligation not recognised because outflow is not probable or measurement is not sufficiently reliable. Do not recognise it in the statement of financial position. Disclose it unless the possibility of outflow is remote.',
   'A contingent asset is a possible asset arising from past events whose existence depends on uncertain future events. Do not recognise a contingent asset, because doing so could recognise income that may never be realised. Disclose it when an inflow is probable. When inflow becomes virtually certain, recognise the asset because it is no longer contingent.',
   'Use probability language with care. A provision concerns a present obligation with probable outflow; a contingent liability can involve a possible obligation or a present obligation failing recognition. For assets, probable inflow leads to disclosure, not recognition. Update assessments at every reporting date as evidence changes.'
  ],supportPt:'Passivo contingente não é reconhecido e é divulgado salvo saída remota. Ativo contingente não é reconhecido; divulgue quando entrada provável e reconheça somente quando a entrada se tornar virtualmente certa.',sourceIds:['ias-37']},
  {id:'acca-b7-events',title:'4. Use IAS 10 to place later evidence in the correct period',paragraphs:[
   'Events after the reporting period are favourable or unfavourable events between the reporting date and the date financial statements are authorised for issue. An adjusting event provides evidence about a condition that existed at the reporting date. Update recognised amounts or recognise items to reflect that evidence.',
   'A non-adjusting event indicates a condition arising after the reporting date. Do not change year-end amounts for it. If the event is material, disclose its nature and an estimate of financial effect, or state that an estimate cannot be made. The event date alone does not decide classification; ask when the underlying condition arose.',
   'A customer bankruptcy after year end may confirm an existing credit problem and adjust a loss allowance, whereas destruction by a new post-year-end fire is usually non-adjusting but potentially material. Dividends declared after the reporting period are not year-end liabilities. A post-reporting event that destroys the going-concern basis affects preparation more fundamentally than ordinary non-adjusting disclosure.'
  ],supportPt:'Evento ajustável confirma condição existente no fechamento; evento não ajustável nasce depois. Materialidade pode exigir divulgação. A data da notícia não decide: identifique quando surgiu a condição econômica.',sourceIds:['ias-10']}
 ],
 terms:[
  {term:'Provision',meaning:'Liability of uncertain timing or amount meeting recognition criteria.',pt:'Provisão',example:'Expected warranty claims on products already sold may be provided.'},
  {term:'Present obligation',meaning:'Legal or constructive duty the entity has no realistic alternative to settling.',pt:'Obrigação presente',example:'A statutory clean-up duty can create a present obligation.'},
  {term:'Constructive obligation',meaning:'Obligation created by actions that establish a valid expectation in others.',pt:'Obrigação construtiva',example:'A specific announced refund policy may create an expectation.'},
  {term:'Contingent liability',meaning:'Possible obligation, or unrecognised present obligation, subject to IAS 37 disclosure rules.',pt:'Passivo contingente',example:'Litigation with a possible but not probable loss may be disclosed.'},
  {term:'Adjusting event',meaning:'Later event providing evidence of a condition existing at the reporting date.',pt:'Evento subsequente ajustável',example:'Settlement may confirm the year-end amount of an existing obligation.'},
  {term:'Non-adjusting event',meaning:'Later event indicating a condition arose after the reporting date.',pt:'Evento subsequente não ajustável',example:'A new post-year-end fire may require disclosure rather than adjustment.'}
 ],
 visual:{title:'Warranty provision and later evidence',note:'Original expected-value map; fictional CU amounts for a large population.',headers:['Outcome','Probability','Weighted CU'],rows:[['No repair','75% × 0','0'],['Minor repairs','20% × 100,000','20,000'],['Major repairs','5% × 400,000','20,000'],['Initial best estimate','Total weighted outcomes','40,000']],question:'If post-year-end claims confirm a year-end defect and revise the estimate to CU55,000 before authorisation, is the CU15,000 change ignored?',answer:'No. The later claims provide evidence about a condition existing at year end, so IAS 10 requires adjustment to the CU55,000 best estimate.'},
 caseStudy:{title:'Warranty estimate, year-end condition and later claims',scenario:['At 31 December, products already sold carry a warranty. Based on the population, 75% need no repair, 20% need CU100,000 total minor repairs and 5% need CU400,000 total major repairs.','On 20 January, before authorisation, claim analysis confirms a manufacturing defect existed before year end. Revised supportable expected repair cost is CU55,000.','A separate warehouse is destroyed by a fire caused by an electrical fault that first arose on 12 January. The loss is material.'],task:'Calculate the initial warranty estimate, determine the final provision and classify the warehouse fire under IAS 10.',hints:['Use expected value for the warranty population.','Ask when each underlying condition existed.'],modelAnswer:'The initial warranty best estimate is CU40,000: 75% × nil + 20% × CU100,000 + 5% × CU400,000. The warranty obligation arose when products were sold. The January evidence confirms a pre-year-end defect, so it is adjusting and the final provision is CU55,000. The warehouse fault first arose after year end, so the fire is non-adjusting. Do not adjust year-end amounts for the fire, but disclose its nature and estimated financial effect because the loss is material.',reviewChecks:['The warranty meets the present-obligation logic.','Expected value gives CU40,000 initially.','Confirming evidence adjusts the warranty to CU55,000.','The new fire condition is non-adjusting but materially disclosed.'],transfer:'Assume the warehouse wiring was damaged and unsafe before year end, but the fire occurred in January. Reassess whether the later event provides adjusting evidence.'},
 checkpoint:[
  {id:'acca-b7-q1',prompt:'Which combination supports provision recognition?',options:['Future intention, possible outflow and budget','Present obligation from a past event, probable outflow and reliable estimate','Board approval and remote outflow','Forecast loss and measurable amount'],correctIndex:1,explanation:'All three IAS 37 recognition criteria are needed.',reviewSection:'acca-b7-recognition'},
  {id:'acca-b7-q2',prompt:'How is a large population of warranty outcomes commonly measured?',options:['Highest possible amount','Expected value using probability-weighted outcomes','Lowest possible amount','Cash paid after year end only'],correctIndex:1,explanation:'Expected value is appropriate for a large population of similar obligations.',reviewSection:'acca-b7-measurement'},
  {id:'acca-b7-q3',prompt:'What is done with a contingent liability when outflow is not remote?',options:['Recognise it as revenue','Disclose it without recognising a liability','Ignore it permanently','Record it in equity'],correctIndex:1,explanation:'A contingent liability is disclosed unless outflow is remote.',reviewSection:'acca-b7-contingencies'},
  {id:'acca-b7-q4',prompt:'When is a contingent asset recognised?',options:['Whenever inflow is possible','When inflow is probable','When inflow is virtually certain and the asset is no longer contingent','Never under any circumstances'],correctIndex:2,explanation:'Probable inflow supports disclosure; virtual certainty supports recognition.',reviewSection:'acca-b7-contingencies'},
  {id:'acca-b7-q5',prompt:'What makes a post-reporting event adjusting?',options:['It is announced publicly','It provides evidence of a condition existing at the reporting date','It is favourable','It occurs within thirty days'],correctIndex:1,explanation:'Classification depends on when the underlying condition existed.',reviewSection:'acca-b7-events'}
 ],
 practiceExercises:[
  {id:'acca-b7-p1',question:'A law requires clean-up for contamination caused before year end. Outflow is probable and estimated reliably at CU300. What is recognised?',hints:['Identify the past event and present legal obligation.','Apply all three criteria.'],answer:'Recognise a CU300 provision. The pre-year-end contamination and law create a present obligation, outflow is probable and the estimate is reliable.',explanation:'Uncertain timing does not prevent provision recognition.'},
  {id:'acca-b7-p2',question:'Repair: “A board plan for next year’s retraining creates a restructuring provision.”',hints:['Ask whether third parties have a valid expectation.','Separate future operations from past obligations.'],answer:'An internal plan alone does not create a constructive obligation. Future retraining is also normally excluded from a restructuring provision because it relates to future operations.',explanation:'A detailed plan must create a valid external expectation, and only direct restructuring obligations qualify.'},
  {id:'acca-b7-p3',question:'A material factory fire arises from a new fault after year end but before authorisation. Adjust or disclose?',hints:['Locate the underlying condition in time.','Then apply materiality.'],answer:'It is a non-adjusting event because the condition arose after year end. Do not change year-end amounts, but disclose the nature and estimated financial effect if material.',explanation:'Materiality changes disclosure, not the event’s classification.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative current sitting landing page; exact outcome wording remains a publication gate.',reviewedOn},
  {id:'ias-37',label:'IFRS Foundation · IAS 37 Provisions, Contingent Liabilities and Contingent Assets',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-37-provisions-contingent-liabilities-and-contingent-assets/',supports:'Recognition, measurement, special provisions and contingencies.',reviewedOn},
  {id:'ias-10',label:'IFRS Foundation · IAS 10 Events after the Reporting Period',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-10-events-after-the-reporting-period/',supports:'Adjusting and non-adjusting events and material disclosure.',reviewedOn}
 ]
};
export function localModelB7For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='B7'?ACCA_B7_MODEL_MODULE:null;}
export {ACCA_B7_MODEL_ID,ACCA_B7_MODEL_SLUG};
