import type {LessonModule} from './lessonModules.ts';
import {ACCA_D2_MODEL_ID,ACCA_D2_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-22';
export const ACCA_D2_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'31–39',segments:['Define the group and split pre- from post-acquisition equity.','Build goodwill and NCI with fair-value adjustments.','Eliminate intragroup results and apply the equity method.','Handle acquisition timing, impairment and a total subsidiary disposal.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_D2_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask for the group structure, acquisition date, ownership, control facts and reporting date before accepting any consolidation calculation.',supportedPractice:'Build separate workings for net assets, goodwill, NCI, group retained earnings, associates and intragroup eliminations, then link them once.',misconception:'Consolidation does not add the parent’s investment to the subsidiary’s net assets; it replaces that investment with the controlled assets and liabilities and recognises goodwill and NCI where applicable.',transfer:'Change the NCI basis, seller, acquisition date, fair-value life or disposal status and ask which workings change.',close:'Recap control, acquisition analysis and group-only adjustments without claiming ACCA readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_D2_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_D2_MODEL_ID,title:'ACCA FR D2 · Consolidated financial statements',
 goal:'Prepare and explain simple-group consolidation workings for subsidiaries and an associate, including fair values, goodwill, NCI, intragroup adjustments, impairment and a total disposal.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level D2 mapping must be checked against the exact selected exam sitting before publication. It covers a simple parent with up to two subsidiaries and one associate, not complex groups, step acquisitions, partial retained interests, foreign operations or full disclosure requirements. It is not ACCA approval, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-d2-boundary',title:'1. Establish control, group structure and acquisition timing',paragraphs:[
   'A parent is generally required to present consolidated financial statements when it controls one or more subsidiaries, subject to the narrow exemption for a qualifying intermediate parent whose owners do not object, whose instruments are not publicly traded or being filed for public issue, and whose higher parent produces publicly available IFRS-compliant consolidated statements. Investment entities apply a distinct measurement exception to specified subsidiaries rather than a blanket conclusion that groups never consolidate.',
   'Group entities should use the same reporting date where practicable and uniform accounting policies for like transactions. If different reporting dates must be used within the permitted boundary, adjust for significant intervening transactions and events. Convert a subsidiary’s policies to group policies before aggregation; otherwise line-by-line totals would combine unlike measurements.',
   'Consolidate a subsidiary from the date the investor obtains control until the date control is lost. Control requires power over the investee, exposure or rights to variable returns and the ability to use power to affect those returns. A majority of voting rights often produces control but is not the definition itself; contractual arrangements and substantive rights can change the conclusion. Significant influence, normally associated with an associate, leads to equity accounting rather than line-by-line consolidation.',
   'Draw the group structure before calculating. Record ownership, acquisition and disposal dates, consideration, NCI basis and whether each investee is a subsidiary or associate. In the consolidated statement of financial position, add controlled assets and liabilities line by line, eliminate the parent’s investment and recognise goodwill and NCI. For an associate, present one investment balance and the investor’s share of post-acquisition results.',
   'Separate pre-acquisition from post-acquisition net assets. Pre-acquisition equity helps measure identifiable net assets acquired and goodwill; only post-acquisition movements contribute to group retained earnings and closing NCI. In consolidated profit or loss, include a subsidiary’s income and expenses only for the controlled portion of the reporting period and allocate profit and total comprehensive income between owners of the parent and NCI.'
  ],supportPt:'Defina a fronteira do grupo antes de somar números. Controle determina consolidação integral; influência significativa leva ao equity method. Separe rigorosamente períodos pré e pós-aquisição.',sourceIds:['acca-fr-syllabus','ifrs-10','ias-28']},
  {id:'acca-d2-goodwill',title:'2. Measure goodwill, NCI and acquisition-date fair values',paragraphs:[
   'At acquisition, goodwill is consideration transferred plus the measured NCI and, where relevant, previously held interest, less the fair value of identifiable net assets acquired. In a simple FR question, NCI may be measured at fair value (full-goodwill method) or as its proportionate share of identifiable net assets (partial goodwill). The chosen basis changes both goodwill and how a later goodwill impairment is allocated.',
   'Acquisition-date fair-value adjustments belong in the net-assets working even when the subsidiary has not recorded them. A plant uplift creates additional post-acquisition depreciation; an inventory uplift affects group cost of sales when the inventory is sold; recognised monetary liabilities reduce net assets; and qualifying previously unrecognised assets or liabilities, including certain contingencies, enter at the required acquisition-date measurement. Never add the uplift to goodwill without also tracing its subsequent effect.',
   'Test goodwill for impairment under the applicable requirements. With full goodwill, impairment is allocated between owners of the parent and NCI on the stated basis; with proportionate NCI, recognised goodwill belongs only to the parent, so the recorded impairment reduces the parent’s group retained earnings. If identifiable net assets exceed consideration plus NCI after reassessment, recognise a bargain-purchase gain in profit or loss rather than a negative goodwill asset.'
  ],supportPt:'Goodwill compara consideração mais NCI com ativos líquidos identificáveis a fair value. Todo fair-value uplift precisa de efeito posterior; impairment e NCI dependem do método informado.',sourceIds:['acca-fr-syllabus','ifrs-3','ias-36','acca-goodwill','acca-fair-value-goodwill']},
  {id:'acca-d2-adjustments',title:'3. Eliminate intragroup effects and equity-account an associate',paragraphs:[
   'A group reports as one economic entity, so eliminate intragroup receivables and payables, sales and purchases, dividends and other internal balances or transactions. Unrealised profit in closing inventory is removed from inventory and from the seller’s profit. Identify the seller because a subsidiary seller changes the post-acquisition profit shared with NCI, while a parent seller normally affects group retained earnings without changing subsidiary NCI.',
   'For an intragroup transfer of a non-current asset, eliminate the unrealised gain and correct depreciation to the amount the group would have charged without the transfer. The remaining unrealised amount falls over the asset’s use or is realised externally. Intragroup dividends are eliminated from group income and do not create group profit; a dividend paid to NCI is external to the group and affects the NCI reconciliation and cash where relevant.',
   'Under the equity method, begin with cost and add the group’s share of the associate’s post-acquisition profit and OCI, then deduct dividends received and impairment. Eliminate the investor’s share of unrealised profit on transactions with the associate, subject to the facts. Do not add the associate’s individual assets, liabilities, revenue and expenses line by line because the group does not control them.'
  ],supportPt:'Elimine tudo que o grupo fez consigo mesmo e todo lucro ainda não realizado externamente. Para associate, use uma linha de investimento e a parcela do resultado — não consolidação linha a linha.',sourceIds:['acca-fr-syllabus','ifrs-10','ias-28','acca-consolidation']},
  {id:'acca-d2-disposal',title:'4. Link consolidated performance, impairment and total disposal',paragraphs:[
   'For a mid-period acquisition, consolidate the subsidiary’s post-acquisition income and expenses and adjust for fair-value depreciation, intragroup items and impairment. For a total disposal that loses control, include results only to the disposal date, remove the subsidiary’s assets, liabilities, goodwill and NCI, recognise consideration received and calculate the group gain or loss using the carrying amounts at that date. The parent’s separate-statement result can differ from the group result.',
   'A disposed subsidiary is a discontinued operation only if it meets the relevant IFRS 5 definition, such as representing a separate major line of business or geographical area under the required conditions. Loss of control alone is not enough. When the conditions are met, present the post-tax result and disposal result in the required discontinued-operation presentation while preserving the consolidation period up to disposal.',
   'Use linked workings rather than one formula: structure and dates; subsidiary net assets; goodwill; NCI; group retained earnings; associate; intragroup eliminations; and disposal. Reconcile each adjustment to both the statement of financial position and performance statement. If consideration, fair values, dates or control evidence are missing, state what cannot be concluded rather than inventing a plug.'
  ],supportPt:'Aquisição e disposal mudam o período consolidado. Perda de controle exige retirada integral dos saldos; discontinued operation depende de critérios adicionais, não apenas da venda.',sourceIds:['acca-fr-syllabus','ifrs-10','ifrs-5','acca-consolidation']}
 ],
 terms:[
  {term:'Control',meaning:'Power over an investee, exposure or rights to variable returns and ability to use power to affect those returns.',pt:'Controle',example:'Control, not ownership percentage alone, determines subsidiary consolidation.'},
  {term:'Goodwill',meaning:'Residual acquisition amount after comparing consideration and NCI with identifiable net assets at fair value.',pt:'Ágio por expectativa de rentabilidade futura',example:'CU700 consideration + CU170 NCI − CU780 net assets = CU90 goodwill.'},
  {term:'Non-controlling interest',meaning:'Equity in a subsidiary not attributable directly or indirectly to the parent.',pt:'Participação de não controladores',example:'NCI receives its share of adjusted post-acquisition profit.'},
  {term:'Pre-acquisition profits',meaning:'Subsidiary reserves existing when control is obtained and included in acquisition net assets.',pt:'Lucros pré-aquisição',example:'They enter the goodwill working, not group retained earnings.'},
  {term:'Unrealised profit',meaning:'Profit on an internal transaction not yet realised through a transaction outside the group.',pt:'Lucro não realizado',example:'Profit in inventory still held within the group is eliminated.'},
  {term:'Equity method',meaning:'Method recognising an associate initially at cost and subsequently for the investor’s share of results and other movements.',pt:'Método da equivalência patrimonial',example:'The associate is one investment line, not line-by-line consolidation.'}
 ],
 visual:{title:'Simple-group consolidation worksheet',note:'Original workflow; each working feeds the consolidated statements once.',headers:['Working','Core calculation','Main destination'],rows:[['Net assets','Acquisition fair value + post-acquisition movement','Goodwill, NCI and group reserves'],['Goodwill','Consideration + NCI − acquired net assets','Non-current asset less impairment'],['NCI','Acquisition NCI + share of adjusted post-acquisition movement','Separate equity component'],['Group retained earnings','Parent + parent share post-acquisition − group adjustments','Equity attributable to parent'],['Associate','Cost + share of post-acquisition result − dividends − impairment','Single investment balance']],question:'Why is the parent’s investment eliminated rather than added to the subsidiary’s net assets?',answer:'The investment represents the parent’s claim on the subsidiary; consolidation replaces it with the controlled underlying assets and liabilities, plus goodwill and NCI where applicable.'},
 caseStudy:{title:'Goodwill, NCI, intragroup profit and an associate',scenario:['Parent acquired 80% of Subsidiary at the start of the year for CU700. Fair-value NCI was CU170. Subsidiary acquisition-date equity was share capital CU500 and retained earnings CU200. Acquisition fair values added CU40 land and CU60 plant, and recognised a CU20 monetary liability. The plant had five years remaining life.','At year end Subsidiary retained earnings are CU320 before consolidation adjustments. During the year Subsidiary sold a machine to Parent for CU140 when its carrying amount was CU100; four years of useful life remained and one full year of depreciation was charged by Parent. Parent also sold inventory costing CU100 to Subsidiary for CU150; half remains at year end. Full goodwill is impaired by CU30. Parent retained earnings before group adjustments are CU900.','Parent acquired 30% of Associate at the start of the year for CU200. Associate earned CU100, paid CU20 dividends and has a CU5 investment impairment. Parent’s retained earnings exclude any associate dividend income for this simplified case.'],task:'Calculate acquisition goodwill, closing goodwill, adjusted post-acquisition subsidiary profit, closing NCI, group retained earnings and the associate carrying amount.',hints:['Net assets at acquisition include both fair-value uplifts and the recognised liability.','Identify each intragroup seller before allocating the unrealised adjustment.'],modelAnswer:'Acquisition-date identifiable net assets are CU780: CU500 share capital + CU200 retained earnings + CU40 land + CU60 plant − CU20 liability. Full goodwill is CU90: CU700 consideration + CU170 fair-value NCI − CU780 net assets. After CU30 impairment, closing goodwill is CU60; the impairment is allocated CU24 to the parent and CU6 to NCI. Subsidiary reported post-acquisition retained earnings are CU120. Deduct CU12 additional depreciation on the plant uplift and CU30 net unrealised machine-transfer profit (CU40 gain less CU10 excess depreciation), giving adjusted post-acquisition profit CU78. Closing NCI is CU179.6: CU170 + 20% of CU78 − CU6. The parent-seller inventory unrealised profit is CU25: CU50 profit × 50% remaining. The associate carrying amount is CU219: CU200 + 30% of CU100 profit − 30% of CU20 dividend − CU5 impairment. The associate adds CU19 net to group retained earnings in this simplified working. Group retained earnings are therefore CU932.4: CU900 + 80% of CU78 − CU25 parent-seller inventory profit − CU24 parent goodwill impairment + CU19 associate movement.',reviewChecks:['Acquisition goodwill CU90 and closing goodwill CU60.','Adjusted subsidiary post-acquisition profit CU78.','Closing NCI CU179.6 and group retained earnings CU932.4.','Associate carrying amount CU219.'],transfer:'Assume NCI was measured proportionately instead of at fair value and the inventory sale was made by Subsidiary. Rebuild goodwill, impairment allocation, NCI and group retained earnings.'},
 checkpoint:[
  {id:'acca-d2-q1',prompt:'Which factor determines whether an investee is consolidated as a subsidiary?',options:['A dividend was received','Control under the relevant facts','The investment is profitable','The entities share an auditor'],correctIndex:1,explanation:'Control establishes the consolidation boundary; percentage is evidence but not the complete definition.',reviewSection:'acca-d2-boundary'},
  {id:'acca-d2-q2',prompt:'What is acquisition-date goodwill in the worked case?',options:['CU60','CU90','CU110','CU170'],correctIndex:1,explanation:'CU700 consideration + CU170 NCI − CU780 identifiable net assets = CU90.',reviewSection:'acca-d2-goodwill'},
  {id:'acca-d2-q3',prompt:'Why does the machine transfer reduce adjusted subsidiary post-acquisition profit by CU30 rather than CU40?',options:['The gain is external','CU10 excess depreciation has already realised part of the adjustment through group use','NCI pays the difference','Land is depreciated'],correctIndex:1,explanation:'Eliminate the CU40 internal gain but reverse CU10 excess depreciation, leaving CU30 unrealised at year end.',reviewSection:'acca-d2-adjustments'},
  {id:'acca-d2-q4',prompt:'How is an associate normally presented in a simple consolidated statement of financial position?',options:['Every asset and liability line by line','At zero after eliminating the investment','As one equity-accounted investment balance','As goodwill only'],correctIndex:2,explanation:'Significant influence leads to one equity-accounted investment rather than line-by-line consolidation.',reviewSection:'acca-d2-adjustments'},
  {id:'acca-d2-q5',prompt:'Does selling an entire subsidiary automatically create a discontinued operation?',options:['Yes, whenever control is lost','Yes, if cash is received','No; the IFRS 5 criteria must also be met','No subsidiary can be discontinued'],correctIndex:2,explanation:'Loss of control and discontinued-operation presentation are distinct assessments.',reviewSection:'acca-d2-disposal'}
 ],
 practiceExercises:[
  {id:'acca-d2-p1',question:'Consideration is CU500, proportionate NCI is 25% of identifiable net assets of CU560, and no previously held interest exists. Calculate goodwill.',hints:['Proportionate NCI is CU140.','Compare consideration plus NCI with net assets.'],answer:'Goodwill is CU80: CU500 + CU140 − CU560.',explanation:'The proportionate-NCI method recognises only the parent’s goodwill in this simple example.'},
  {id:'acca-d2-p2',question:'Parent sells inventory costing CU80 to Subsidiary for CU120 and 25% remains. Calculate unrealised profit and identify the reserve affected.',hints:['Total internal profit is CU40.','Apply the remaining-inventory percentage and identify the seller.'],answer:'Unrealised profit is CU10. Because Parent is the seller, reduce consolidated inventory and group retained earnings by CU10; subsidiary NCI is not adjusted.',explanation:'The seller determines whose recorded profit contains the unrealised amount.'},
  {id:'acca-d2-p3',question:'A private intermediate parent controls a subsidiary but wants exemption from consolidated statements. State the evidence it must establish and two preparation controls if no exemption applies.',hints:['Do not assume private status is enough.','Consider dates and policies before aggregation.'],answer:'It must establish all applicable exemption conditions, including owner consent or no objection, no public trading or filing for public issue, and publicly available IFRS-compliant consolidated statements from a higher parent. If it consolidates, it should align reporting dates or adjust significant intervening events and use uniform accounting policies for like transactions.',explanation:'The requirement, exemption and preparation controls are separate conclusions.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide (September 2026 to June 2027)',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Current D2 outcomes for simple-group consolidated statements, fair values, goodwill, impairment and disposal.',reviewedOn},
  {id:'ifrs-10',label:'IFRS Foundation · IFRS 10 Consolidated Financial Statements',url:'https://www.ifrs.org/issued-standards/list-of-standards/ifrs-10-consolidated-financial-statements/',supports:'Control, consolidation period and accounting on loss of control.',reviewedOn},
  {id:'ifrs-3',label:'IFRS Foundation · IFRS 3 Business Combinations',url:'https://www.ifrs.org/issued-standards/list-of-standards/ifrs-3-business-combinations/',supports:'Acquisition method, identifiable net assets, NCI, goodwill and bargain purchase.',reviewedOn},
  {id:'ias-28',label:'IFRS Foundation · IAS 28 Investments in Associates and Joint Ventures',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-28-investments-in-associates-and-joint-ventures/',supports:'Significant influence and equity-method accounting.',reviewedOn},
  {id:'ias-36',label:'IFRS Foundation · IAS 36 Impairment of Assets',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-36-impairment-of-assets/',supports:'Goodwill impairment principles.',reviewedOn},
  {id:'ifrs-5',label:'IFRS Foundation · IFRS 5 Non-current Assets Held for Sale and Discontinued Operations',url:'https://www.ifrs.org/issued-standards/list-of-standards/ifrs-5-non-current-assets-held-for-sale-and-discontinued-operations/',supports:'Discontinued-operation criteria and presentation boundary.',reviewedOn},
  {id:'acca-consolidation',label:'ACCA · Watch your step: consolidated financial statements',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/technical-articles/cons-fin-statements.html',supports:'FR consolidation workflow and common errors.',reviewedOn},
  {id:'acca-goodwill',label:'ACCA · Accounting for goodwill',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/technical-articles/accounting-for-goodwill.html',supports:'FR goodwill and NCI workings.',reviewedOn},
  {id:'acca-fair-value-goodwill',label:'ACCA · The use of fair values in the goodwill calculation',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/technical-articles/fair-value-goodwill.html',supports:'Acquisition-date fair-value adjustments and subsequent effects.',reviewedOn}
 ]
};
export function localModelD2For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='D2'?ACCA_D2_MODEL_MODULE:null;}
export {ACCA_D2_MODEL_ID,ACCA_D2_MODEL_SLUG};
