import type {LessonModule} from './lessonModules.ts';
import {ACCA_A1_MODEL_ID,ACCA_A1_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-21';
export const ACCA_A1_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'14–18',segments:['Why general purpose reporting exists and who uses it.','General reports compared with a private cash forecast.','Materiality by nature and magnitude.','Retrieval pauses on users, stewardship and missing evidence.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_A1_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask which decision the report supports and who makes it.',supportedPractice:'Offer one user contrast before explaining.',misconception:'Nature and circumstances can make a small item material.',transfer:'Change the user to a bank credit committee and ask what changes.',close:'Recap users, stewardship and one judgement without claiming saved mastery.',evidenceBoundary:'Local drafts, revealed answers and checkpoint choices must never enter a Professor or evaluator payload.'} as const;
export const ACCA_A1_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_A1_MODEL_ID,title:'ACCA FR A1 · Purpose and users of financial reporting',
 goal:'Explain why general purpose financial reports exist, identify their primary users and apply stewardship and materiality to a reporting judgement.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level A1 mapping must be checked against the exact syllabus wording for the selected exam sitting before publication. It is not an ACCA-approved course, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-a1-objective',title:'1. Begin with the decision, not the document',paragraphs:[
   'General purpose financial reporting provides information about a reporting entity that is useful to existing and potential investors, lenders and other creditors when they decide whether to provide resources. Those decisions include buying, selling or holding instruments, providing or settling loans and exercising rights that influence management. The objective is not to answer every question any stakeholder might ask.',
   'Start a scenario by identifying both the decision and the user. A shareholder considering whether to hold an investment, a bank considering a loan and a supplier considering credit may use the same statements but emphasise different information. Management also needs financial information, yet it can normally obtain tailored internal reports and is not the primary audience described by the Conceptual Framework.',
   'A private weekly cash forecast can be valuable without becoming a general purpose financial statement. Its specific purpose, audience and assumptions differ. Explain that distinction without suggesting internal information is unimportant.'
  ],supportPt:'Comece pela decisão e pelo usuário. Investidores, credores e outros financiadores normalmente não podem exigir relatórios sob medida. Um forecast interno pode ser útil sem se tornar demonstração de propósito geral.',sourceIds:['conceptual-framework']},
  {id:'acca-a1-stewardship',title:'2. Connect prospects with stewardship',paragraphs:[
   'Users need information about economic resources, claims and changes in both. They use that information to assess prospects for future net cash inflows. Financial reports do not predict one certain future; users combine them with other evidence, assumptions and risk judgements.',
   'Stewardship concerns how efficiently and effectively management has discharged its responsibilities for using the entity’s resources. Evidence about asset protection, financing choices, margins and accountability can affect confidence in management as well as decisions about providing resources.',
   'Avoid saying financial statements show the exact value of a business or guarantee future cash. Connect information to a decision. A deterioration in receivable collection may affect liquidity expectations and also raise questions about credit-control stewardship.'
  ],supportPt:'As demonstrações ajudam a avaliar perspectivas de caixa e o uso dos recursos pela administração. Elas fornecem evidência para decisões; não garantem o futuro nem determinam sozinhas o valor da empresa.',sourceIds:['conceptual-framework']},
  {id:'acca-a1-materiality',title:'3. Apply materiality in context',paragraphs:[
   'Information is material if omitting, misstating or obscuring it could reasonably be expected to influence decisions made by primary users. Materiality is entity-specific and depends on nature or magnitude, or both, in the context of the report.',
   'A percentage can be a starting point but is not a universal answer. A small related-party transaction, regulatory breach or change that turns profit into loss may matter because of its nature or effect. A large volume of immaterial detail can also obscure useful information.',
   'Identify the item, user and decision; assess magnitude and nature; then conclude which recognition, presentation or disclosure question needs consideration under the applicable requirement. Do not invent a threshold when none is supplied.'
  ],supportPt:'Materialidade depende do contexto, natureza e valor. Não invente percentual universal. Explique qual decisão pode ser influenciada e qual análise contábil ainda é necessária.',sourceIds:['materiality-practice']},
  {id:'acca-a1-exam',title:'4. Build an exam-quality explanation',paragraphs:[
   'For an explain requirement, a definition alone rarely earns the full available credit. State the principle, apply it to the facts and make a supported conclusion. If information is missing, name it rather than replacing it with an assumption.',
   'A lender requests a private weekly cash forecast while annual statements are prepared for general users. The forecast is tailored for a specific decision. If the entity is close to breaching a covenant, the uncertainty may be material because it can influence lending and liquidity decisions even before a final breach occurs.',
   'Separate what the facts establish from what needs more evidence. The case may show a tight covenant without establishing contractual consequences, forecast reliability or required disclosure. This discipline supports both ACCA technique and real reporting judgement.'
  ],supportPt:'Em explain, apresente princípio, aplicação e conclusão. Se faltar informação, identifique-a. Não transforme uma hipótese sobre covenant, caixa ou divulgação em fato.',sourceIds:['acca-fr-syllabus','conceptual-framework']}
 ],
 terms:[
  {term:'General purpose financial report',meaning:'A report meeting common needs of users who cannot require tailored reports.',pt:'Relatório de propósito geral',example:'Annual statements serve general users rather than one bank alone.'},
  {term:'Primary users',meaning:'Existing and potential investors, lenders and other creditors.',pt:'Usuários primários',example:'Primary users decide whether to provide resources.'},
  {term:'Stewardship',meaning:'Assessment of management’s use and protection of resources.',pt:'Prestação de contas',example:'Collection controls are relevant to stewardship.'},
  {term:'Economic resource',meaning:'A right with potential to produce economic benefits.',pt:'Recurso econômico',example:'A receivable is a right that may generate cash.'},
  {term:'Material',meaning:'Capable of influencing primary-user decisions.',pt:'Material',example:'Covenant uncertainty may be material to a lender.'},
  {term:'Entity-specific',meaning:'Assessed in the circumstances of the reporting entity.',pt:'Específico da entidade',example:'Materiality is not one fixed percentage.'}
 ],
 visual:{title:'Match information to the user decision',note:'Original teaching map; users may need evidence beyond the statements.',headers:['User','Decision','Relevant information'],rows:[['Potential investor','Buy or hold','Returns, risks and resources'],['Bank lender','Provide or renew credit','Liquidity, claims and covenant uncertainty'],['Trade creditor','Offer payment terms','Short-term payment capacity'],['Management','Run the entity','Tailored internal information']],question:'Does management’s need for a weekly forecast make it a general purpose statement?',answer:'No. The forecast can be useful tailored information while serving a specific audience and purpose.'},
 caseStudy:{title:'A small transaction with a governance question',scenario:['North Quay Ltd reports revenue of 80 million and bought consulting services of 18,000 from a company controlled by a director’s close family member.','The draft note omits it because the amount is small. The relationship, service and approval are confirmed; the disclosure conclusion is not.','A lender asks how governance-sensitive transactions are controlled.'],task:'Explain whether size alone resolves materiality, identify the user decision and distinguish facts from the accounting conclusion still required.',hints:['Consider nature as well as magnitude.','Do not claim disclosure is required before assessing the applicable requirement.'],modelAnswer:'The amount is small relative to revenue, but size alone does not resolve materiality. The director-related nature and lender’s governance assessment could influence a primary user. The confirmed facts are the relationship, service and approval; the disclosure conclusion still requires review. Document the evidence, assess the applicable requirement and materiality in context, and obtain independent review rather than relying only on a percentage.',reviewChecks:['The lender’s resource decision is identified.','Nature and magnitude are both considered.','Facts remain separate from the disclosure conclusion.','A proportionate evidence and review action is proposed.'],transfer:'Change the item to a routine customer balance that is large and explain how the reasoning changes.'},
 checkpoint:[
  {id:'acca-a1-q1',prompt:'Who are the primary users?',options:['Only management','Investors, lenders and other creditors','Only tax authorities','All stakeholders with identical needs'],correctIndex:1,explanation:'Existing and potential investors, lenders and other creditors generally cannot demand tailored reports.',reviewSection:'acca-a1-objective'},
  {id:'acca-a1-q2',prompt:'What does stewardship help assess?',options:['Management’s use of resources','A guaranteed share price','Only the tax return','Whether estimates are exact'],correctIndex:0,explanation:'Stewardship concerns management’s use of resources and supports decisions without guaranteeing value.',reviewSection:'acca-a1-stewardship'},
  {id:'acca-a1-q3',prompt:'A transaction is small. What next?',options:['Always ignore it','Always disclose it','Assess nature and magnitude in context','Apply a universal threshold'],correctIndex:2,explanation:'Materiality is entity-specific and can arise from nature, magnitude or both.',reviewSection:'acca-a1-materiality'},
  {id:'acca-a1-q4',prompt:'Which statement is accurate?',options:['Every forecast is a financial statement','A private forecast can serve a specific user and purpose','General reports answer every question','Tailored reports are useless'],correctIndex:1,explanation:'Usefulness does not make all information general purpose; audience and objective matter.',reviewSection:'acca-a1-objective'},
  {id:'acca-a1-q5',prompt:'What best answers explain?',options:['Definition only','Conclusion without facts','Principle, application and supported conclusion','A memorised threshold'],correctIndex:2,explanation:'An explanation connects the principle to the scenario and reaches an evidence-aware conclusion.',reviewSection:'acca-a1-exam'}
 ],
 practiceExercises:[
  {id:'acca-a1-p1',question:'Explain why a private thirteen-week bank cash forecast differs from annual general purpose statements.',hints:['Identify the audience.','Identify the decision.'],answer:'The forecast is tailored for a bank’s short-term lending decision and uses assumptions for that purpose. Annual statements provide general information for users who cannot normally demand a custom report.',explanation:'The distinction is purpose and audience, not whether the forecast is useful.'},
  {id:'acca-a1-p2',question:'A confirmed regulatory breach has a small direct cost. Analyse materiality without inventing a threshold.',hints:['Consider nature.','Connect to a user decision.'],answer:'The amount is small, but the breach may be material by nature if it affects compliance, cash-flow prospects or stewardship assessments. Apply the relevant requirement and entity context.',explanation:'Qualitative factors can matter in an entity-specific assessment.'},
  {id:'acca-a1-p3',question:'Repair: “Financial statements tell investors exactly what the company is worth and what cash it will earn.”',hints:['Reports provide information, not certainty.','Name the decisions supported.'],answer:'Financial statements provide information about resources, claims, performance and cash flows that helps users assess prospects and stewardship. They do not determine one exact value or guarantee future cash.',explanation:'Avoid overstating the objective and predictive power of reporting.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative syllabus landing page; exact selected-sitting outcome lettering remains a gate.',reviewedOn},
  {id:'conceptual-framework',label:'IFRS Foundation · Conceptual Framework',url:'https://www.ifrs.org/issued-standards/list-of-standards/conceptual-framework/',supports:'Objective, users, stewardship and conceptual foundation.',reviewedOn},
  {id:'materiality-practice',label:'IFRS Foundation · Materiality Practice Statement',url:'https://www.ifrs.org/issued-standards/list-of-standards/materiality-practice-statement/',supports:'Entity-specific nature and magnitude considerations.',reviewedOn}
 ]
};
export function localModelLessonFor(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='A1'?ACCA_A1_MODEL_MODULE:null;}
export {ACCA_A1_MODEL_ID,ACCA_A1_MODEL_SLUG};
