import type {LessonModule} from './lessonModules.ts';
import {ACCA_A2_MODEL_ID,ACCA_A2_MODEL_SLUG,localModelCodeFor} from './localModelLessonRegistry.ts';
import type {P1Track} from './p1RuntimeRegistry.ts';
const reviewedOn='2026-09-21';
export const ACCA_A2_PREMIUM_AUDIO_OUTLINE={status:'outline_only_no_generation',estimatedMinutes:'15–20',segments:['Why relevance and faithful representation are both fundamental.','A narrated comparison of two valuation methods.','Prudence without deliberate bias.','Retrieval pauses on enhancing characteristics and cost.'],preservation:'No existing Premium Audio asset, cache, budget or runtime is modified or invoked.'} as const;
export const ACCA_A2_PROFESSOR_GUIDE={status:'offline_authored_not_live',opening:'Ask what makes information useful before naming the characteristics.',supportedPractice:'Contrast one relevant but incomplete method with one transparent estimate.',misconception:'Estimation uncertainty is not automatically an error, and prudence does not permit hidden reserves.',transfer:'Change the evidence quality or reporting deadline and ask which characteristic becomes more important.',close:'Recap both fundamental characteristics, one enhancement and the cost constraint without claiming exam readiness.',evidenceBoundary:'Only actual integrated session turns may be evaluated; local drafts and revealed answers must never enter a Professor or evaluator payload.'} as const;
export const ACCA_A2_MODEL_MODULE:LessonModule={
 track:'finance',lessonId:ACCA_A2_MODEL_ID,title:'ACCA FR A2 · Qualitative characteristics and the cost constraint',
 goal:'Use the qualitative characteristics to compare reporting alternatives, explain uncertainty transparently and reach a cost-aware recommendation.',
 scope:'Local ACCA Financial Reporting model lesson. Category-level A2 mapping must be checked against the exact selected exam sitting before publication. It is original teaching material, not ACCA approval, complete syllabus coverage, persisted assessment or exam-readiness evidence.',
 sections:[
  {id:'acca-a2-fundamental',title:'1. Start with relevance and faithful representation',paragraphs:[
   'Useful financial information must be relevant and faithfully represent what it purports to represent. Relevant information can make a difference to decisions because it has predictive value, confirmatory value or both. Materiality is an entity-specific aspect of relevance; information does not become relevant merely because it is easy to calculate.',
   'A faithful representation aims to be complete, neutral and free from error. Free from error does not mean every estimate is perfectly accurate. It means the description and process are appropriate, with no errors or omissions in selecting and applying that process. Uncertainty should be explained rather than hidden.',
   'Formal compliance with IFRS Accounting Standards is necessary but does not by itself prove that a depiction is complete, neutral and free from error. Selective emphasis, obscured material information or biased assumptions can undermine faithful representation even when a checklist of explicit requirements appears to have been followed.',
   'The characteristics work together. A perfectly calculated number about the wrong phenomenon is not useful. A highly relevant estimate may also fail if important assumptions are omitted or selected to achieve a preferred result.'
  ],supportPt:'Informação útil precisa ser relevante e representar fielmente o fenômeno. Estimativa não precisa ser perfeitamente exata, mas o processo, as premissas e a incerteza precisam ser apresentados sem viés.',sourceIds:['conceptual-framework']},
  {id:'acca-a2-enhancing',title:'2. Enhance information that is already useful',paragraphs:[
   'Comparability helps users identify similarities and differences across entities or periods. It is not uniformity: unlike things should not be made to look alike. Consistency can support comparability, but a poor method should not be preserved merely because it was used last year.',
   'Verifiability means knowledgeable and independent observers could reach consensus that a depiction is faithfully represented. Verification may be direct, such as counting cash, or indirect, such as checking inputs and recalculating a model. It does not require every observer to produce one identical estimate.',
   'Timeliness means information is available while it can influence decisions. Understandability means classification, characterisation and presentation are clear for reasonably knowledgeable users. Neither characteristic justifies omitting a material complexity.',
   'When an accounting policy changes because a more reliable and relevant policy is required or permitted, comparability is protected by applying the applicable transition requirements, normally including retrospective information when required and practicable, and by explaining the nature and effects of the change. Comparability does not mean preserving a weaker policy forever; it means enabling users to understand like-for-like information across periods.'
  ],supportPt:'Comparabilidade não é uniformidade; verificabilidade não exige uma única estimativa; tempestividade e clareza não autorizam omitir complexidade material.',sourceIds:['conceptual-framework']},
  {id:'acca-a2-prudence',title:'3. Use prudence without introducing bias',paragraphs:[
   'Neutrality means information is not selected or presented to increase the chance of a preferred outcome. Prudence supports neutrality by applying caution when making judgements under uncertainty. It does not permit deliberate understatement of assets or income, overstatement of liabilities or expenses, or hidden reserves.',
   'Substance matters because a description should represent the economic phenomenon, not only its legal label. In an exam scenario, identify the rights, obligations and economic effects supplied before accepting management terminology.',
   'When uncertainty is high, improve the explanation: state the estimation technique, key assumptions, range or sensitivity where required, and evidence still missing. Do not replace a transparent estimate with zero simply because zero feels conservative.'
  ],supportPt:'Prudência é cautela sob incerteza e deve permanecer neutra. Não significa criar reservas ocultas ou escolher sempre o menor ativo. Represente a substância econômica e explique as premissas.',sourceIds:['conceptual-framework']},
  {id:'acca-a2-cost',title:'4. Resolve trade-offs and respect the cost constraint',paragraphs:[
   'Reporting information imposes costs on preparers, users and assurance processes. Benefits should justify those costs. The cost constraint is pervasive, but it is not a convenient excuse for omitting information required by an applicable Standard or material to users.',
   'Trade-offs are context-specific. A more precise method may arrive too late; a timely estimate may require stronger disclosure; an observable input may be verifiable but omit a material condition. First identify alternatives that remain relevant and faithfully represented, then use enhancing characteristics to compare them.',
   'An exam-quality recommendation names the decision, compares the alternatives against the characteristics, explains uncertainty and reaches a conclusion. If the applicable Standard determines the method, follow it and discuss presentation or disclosure rather than inventing a conceptual override.'
  ],supportPt:'Custos devem ser justificados pelos benefícios, mas a restrição de custo não autoriza ignorar requisito aplicável ou informação material. Compare alternativas viáveis e conclua com base no contexto.',sourceIds:['conceptual-framework','acca-fr-syllabus']}
 ],
 terms:[
  {term:'Relevance',meaning:'Capacity to make a difference to a user decision.',pt:'Relevância',example:'The estimate is relevant to the lending decision.'},
  {term:'Faithful representation',meaning:'A complete, neutral depiction produced without error in the selected process.',pt:'Representação fidedigna',example:'The assumptions are complete and neutrally applied.'},
  {term:'Comparability',meaning:'Ability to identify similarities and differences.',pt:'Comparabilidade',example:'Consistent definitions support period comparison.'},
  {term:'Verifiability',meaning:'Independent knowledgeable observers can reach consensus about the depiction.',pt:'Verificabilidade',example:'A reviewer can recalculate the model inputs.'},
  {term:'Prudence',meaning:'Caution when making judgements under uncertainty while remaining neutral.',pt:'Prudência',example:'Prudence does not justify a hidden reserve.'},
  {term:'Cost constraint',meaning:'The benefits of information should justify its reporting costs.',pt:'Restrição de custo',example:'The team compares the benefit of extra detail with its cost.'}
 ],
 visual:{title:'Compare two reporting methods',note:'Original decision map; first eliminate methods that are not relevant or faithfully represented.',headers:['Characteristic','Method X','Method Y'],rows:[['Relevant condition','Omitted','Included'],['Input evidence','Directly observable','Transparent estimate'],['Uncertainty disclosure','None','Assumptions explained'],['Timing','Immediate','Available before reporting deadline']],question:'Should Method X win solely because its input is observable?',answer:'No. Verifiability cannot rescue a method that omits a material condition. Assess relevance and faithful representation first, then compare enhancements and cost.'},
 caseStudy:{title:'Observable input or transparent estimate?',scenario:['A warranty obligation depends on failure rates and repair costs. Method X uses last year’s paid claims and omits a confirmed product defect.','Method Y includes the defect using engineering evidence and a probability-weighted estimate. Its assumptions and sensitivity can be disclosed.','Both methods can be completed before the reporting deadline; Method Y costs 12 additional staff-hours.'],task:'Recommend a method using fundamental and enhancing characteristics, address uncertainty and explain whether the extra cost changes the conclusion.',hints:['Test relevance and faithful representation before verifiability.','Uncertainty is not the same as an error.'],modelAnswer:'Method X is observable but omits the confirmed defect, so it is less relevant and incomplete. Method Y represents the current obligation more faithfully if the engineering evidence, probabilities and repair assumptions are neutrally selected and explained. Its estimate can be indirectly verified by checking inputs and method. Twelve staff-hours are a cost, but the facts do not show that this cost outweighs the benefit of representing a material condition. Use Method Y subject to the applicable Standard and disclose material uncertainty as required.',reviewChecks:['Both fundamental characteristics are applied.','Observability is not treated as automatically decisive.','Estimation uncertainty is explained without calling it an error.','The cost conclusion uses supplied facts and remains subject to the applicable Standard.'],transfer:'Assume Method Y would miss the reporting deadline. Explain how timeliness changes the comparison without making Method X complete.'},
 checkpoint:[
  {id:'acca-a2-q1',prompt:'Which characteristics are fundamental?',options:['Relevance and faithful representation','Comparability and timeliness','Prudence and consistency','Cost and verifiability'],correctIndex:0,explanation:'Relevance and faithful representation are fundamental; enhancing characteristics improve useful information.',reviewSection:'acca-a2-fundamental'},
  {id:'acca-a2-q2',prompt:'Does estimation uncertainty automatically mean an estimate contains an error?',options:['Yes, always','No, if the process and uncertainty are appropriately represented','Only when the number is large','Only when management dislikes it'],correctIndex:1,explanation:'An estimate can be faithfully represented when the process, assumptions and uncertainty are appropriately described.',reviewSection:'acca-a2-fundamental'},
  {id:'acca-a2-q3',prompt:'What is prudence?',options:['Always choosing the lowest asset','Creating hidden reserves','Caution under uncertainty consistent with neutrality','Ignoring positive evidence'],correctIndex:2,explanation:'Prudence supports neutral judgement; it does not permit deliberate understatement or overstatement.',reviewSection:'acca-a2-prudence'},
  {id:'acca-a2-q4',prompt:'What does comparability require?',options:['Uniform treatment of unlike items','Preserving a poor policy forever','Making similarities and differences visible','One estimate for all entities'],correctIndex:2,explanation:'Comparability reveals similarities and differences; consistency can help but is not the same as uniformity.',reviewSection:'acca-a2-enhancing'},
  {id:'acca-a2-q5',prompt:'How should the cost constraint be used?',options:['To ignore every difficult disclosure','To compare justified benefits and costs within applicable requirements','To override any Standard','To remove all estimates'],correctIndex:1,explanation:'Cost is a pervasive constraint, not permission to omit required or material information.',reviewSection:'acca-a2-cost'}
 ],
 practiceExercises:[
  {id:'acca-a2-p1',question:'Explain why a perfectly accurate count of an irrelevant item is not useful.',hints:['Name both fundamental characteristics.','Connect the item to a user decision.'],answer:'Accuracy of the process cannot make irrelevant information useful. The information must first be capable of affecting a user decision and must then faithfully represent the relevant phenomenon.',explanation:'Usefulness requires both fundamental characteristics.'},
  {id:'acca-a2-p2',question:'Repair: “Prudence means always recording the lowest possible asset value.”',hints:['Keep neutrality.','Distinguish caution from deliberate bias.'],answer:'Prudence is caution when making judgements under uncertainty while remaining neutral. It does not justify deliberate understatement or a hidden reserve.',explanation:'Conservatism that creates bias is not faithful representation.'},
  {id:'acca-a2-p3',question:'A timely estimate has transparent assumptions; a final invoice will arrive after the reporting deadline. Give a characteristic-based recommendation.',hints:['Consider relevance, representation and timeliness.','Name the uncertainty.'],answer:'Use the timely estimate if it follows the applicable requirement and faithfully represents the obligation using supportable assumptions. Explain estimation uncertainty and update later accounting when required rather than omitting relevant information until the invoice arrives.',explanation:'Timeliness and transparent estimation can coexist; the Standard remains authoritative.'}
 ],
 sources:[
  {id:'acca-fr-syllabus',label:'ACCA · Financial Reporting syllabus and study guide',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f7/syllabus-study-guide.html',supports:'Authoritative syllabus landing page; exact selected-sitting outcome lettering remains a publication gate.',reviewedOn},
  {id:'conceptual-framework',label:'IFRS Foundation · Conceptual Framework',url:'https://www.ifrs.org/issued-standards/list-of-standards/conceptual-framework/',supports:'Fundamental and enhancing qualitative characteristics, prudence and cost constraint.',reviewedOn}
 ]
};
export function localModelA2For(track:P1Track,lesson:{id:string;slug:string}):LessonModule|null{return localModelCodeFor(track,lesson)==='A2'?ACCA_A2_MODEL_MODULE:null;}
export {ACCA_A2_MODEL_ID,ACCA_A2_MODEL_SLUG};
