import {LOCAL_VIVIANE_ENGLISH_LESSONS,localVivianeEnglishCodeFor,type VivianeEnglishCode} from './vivianeEnglishLessonRegistry.ts';

export type VivianeEnglishCompanion={
 code:VivianeEnglishCode;
 grammarTarget:string;
 pronunciationTarget:string;
 professor:{status:'offline_authored_not_live';referenceMinutes:10;hardLimit:false;startingEnglishSharePct:55;openingQuestion:string;selectiveCorrection:string;transferPrompt:string;evidenceBoundary:string};
 premiumAudio:{status:'outline_only_no_generation';role:'core-contextual-listening';estimatedMinutes:10;segments:readonly [string,string,string,string];generationRequested:false};
};

type Seed={code:VivianeEnglishCode;grammar:string;pronunciation:string;opening:string;correction:string;transfer:string};
const seeds:readonly Seed[]=[
 {code:'VE1',grammar:'Past simple vs past continuous; sequencing with when, while, then and eventually.',pronunciation:'-ed endings, sentence stress and pausing in a short story.',opening:'Tell me about a small surprise that happened last weekend.',correction:'Correct only the target past contrast and one rhythm pattern after the first telling.',transfer:'Retell the same event as a 30-second voice message.'},
 {code:'VE2',grammar:'Present continuous for arrangements; will vs might for reactions and uncertain plans.',pronunciation:'Contractions and friendly rise-fall intonation in small talk.',opening:'What would you say if someone commented on today’s weather?',correction:'Prioritise arrangement language and one natural follow-up question.',transfer:'Change the plan because of rain and propose one alternative.'},
 {code:'VE3',grammar:'Indirect questions and future arrangements with present continuous.',pronunciation:'Spelling, dates, times and confirmation chunks.',opening:'You need to move a Tuesday appointment. How would you open the call?',correction:'Repair indirect-question word order and unclear time stress.',transfer:'Confirm the new day, time, name spelling and reference.'},
 {code:'VE4',grammar:'Present perfect for a continuing problem; passive forms for requested actions.',pronunciation:'Consonant clusters in repair, landlord and maintenance language.',opening:'How would you report a leak without guessing the cause?',correction:'Select one tense issue and one evidence-safe phrase.',transfer:'Arrange access and repeat back the agreed window.'},
 {code:'VP1',grammar:'Present perfect for career experience; past simple for one completed example.',pronunciation:'Word stress in payroll, personnel, responsibility and contribution.',opening:'Give me a 45-second headline about your Payroll and DP experience.',correction:'Correct the timeline and any overclaim about personal ownership or Irish experience.',transfer:'Answer why your previous experience is transferable to an Irish Payroll role.'},
 {code:'VE5',grammar:'Modals for obligation, recommendation and possibility.',pronunciation:'Polite question intonation and contrastive stress on required vs recommended.',opening:'How would you start a calm conversation about a child’s new routine?',correction:'Correct one modal choice and keep observation separate from interpretation.',transfer:'Agree one owner and one follow-up date.'},
 {code:'VE6',grammar:'Comparatives, superlatives and present perfect for recent purchase experience.',pronunciation:'Price, size and product-feature contrasts.',opening:'Compare two products and explain which feature matters most.',correction:'Correct an imprecise comparison and one stressed criterion.',transfer:'Describe a return problem and ask what remedy is available.'},
 {code:'VE7',grammar:'Stative verbs; countable and uncountable nouns in orders.',pronunciation:'Polite request chunks and ingredient names.',opening:'Describe the kind of meal you prefer without choosing a dish yet.',correction:'Correct one stative form and one service-register choice.',transfer:'Report a mismatch between the order and the dish.'},
 {code:'VE8',grammar:'First conditional for likely changes; future arrangements.',pronunciation:'Connected speech in invitations and time changes.',opening:'Invite another family to a simple weekend activity.',correction:'Correct the condition-result link and one unclear time expression.',transfer:'Announce a delay and offer two bounded alternatives.'},
 {code:'VP2',grammar:'Indirect questions; modal verbs for calibrated possibility and commitment.',pronunciation:'Calm chunking in employee-service responses.',opening:'An employee says a deduction is wrong. What can you safely say first?',correction:'Remove unsupported causes and repair one indirect question.',transfer:'Commit to an update time without promising the final result.'},
 {code:'VE9',grammar:'Reporting verbs and hedging with seems, appears, may and in my view.',pronunciation:'Disagreement intonation that stays engaged rather than dismissive.',opening:'Choose a current topic and separate one fact from your opinion.',correction:'Correct one overcertain claim and one abrupt disagreement pattern.',transfer:'Disagree, give a reason and ask a genuine follow-up.'},
 {code:'VE10',grammar:'Relative clauses and participle adjectives for descriptions and recommendations.',pronunciation:'Word stress in genre, character and recommendation language.',opening:'Recommend a film or hobby in three sentences without spoilers.',correction:'Correct one adjective choice and one overly long sentence.',transfer:'Respond naturally when the other person dislikes your recommendation.'},
 {code:'VE11',grammar:'Present perfect with since and for; past simple for a finished dose or event.',pronunciation:'Symptom words, dosage numbers and careful read-back.',opening:'Describe a fictional symptom, when it began and how it changed.',correction:'Correct since/for use and one unclear instruction repeat.',transfer:'Ask three questions and repeat back supplied instructions.'},
 {code:'VE12',grammar:'Indirect questions; comparatives for route options.',pronunciation:'Place names, route numbers and time contrasts.',opening:'Ask how to reach a station by a specific arrival time.',correction:'Repair indirect word order and stress the relevant arrival time.',transfer:'Choose between a direct route and a faster route with one change.'},
 {code:'VP3',grammar:'Present perfect for document status; passive voice for workflow steps.',pronunciation:'Dates, cut-off times and status-word stress.',opening:'Give a starter update using effective date, document status and cut-off.',correction:'Correct received vs validated and one date ambiguity.',transfer:'Adapt the update to a leaver and name each owner.'},
 {code:'VE13',grammar:'Would like and could for invitations and bounded requests.',pronunciation:'Friendly decline intonation and contrastive stress in boundary-setting.',opening:'Invite a neighbour to coffee and make it easy to decline.',correction:'Correct one vague answer and one accusatory formulation.',transfer:'Raise a small shared issue and agree a practical boundary.'},
 {code:'VE14',grammar:'Present perfect for troubleshooting completed with a result relevant now.',pronunciation:'Reference numbers and confirmation chunks.',opening:'Report a fictional internet problem and what you have already tried.',correction:'Correct tense choice and one unsupported technical diagnosis.',transfer:'Read back the reference, pending action and update channel.'},
 {code:'VE15',grammar:'Past simple for booking action; present perfect for an unresolved missing result.',pronunciation:'Names, alphanumeric references and luggage descriptions.',opening:'Report a missing fictional suitcase using only observable details.',correction:'Correct the timeline and one statement that turns an estimate into a promise.',transfer:'Confirm the report number and next update time.'},
 {code:'VE16',grammar:'Passive forms for administrative actions; present perfect for pending confirmation.',pronunciation:'Form fields, postcodes and deadline read-back.',opening:'Ask whether a form field is required, optional or not applicable.',correction:'Correct one status word and one unclear reference number.',transfer:'Follow up on a submitted form without assuming approval.'},
 {code:'VP4',grammar:'Present perfect and passive voice for status; modals for calibrated impact.',pronunciation:'Executive chunking, pause placement and blocker/owner emphasis.',opening:'Give a 30-second Payroll status headline with completed stage and open exceptions.',correction:'Correct any false completion claim and one uncalibrated impact statement.',transfer:'Ask a manager for a clear hold-or-proceed decision.'},
];

const titleByCode=new Map(LOCAL_VIVIANE_ENGLISH_LESSONS.map(lesson=>[localVivianeEnglishCodeFor('english',lesson)!,lesson.title]));

export const VIVIANE_ENGLISH_COMPANIONS:Readonly<Record<VivianeEnglishCode,VivianeEnglishCompanion>>=Object.fromEntries(seeds.map(seed=>{
 const title=titleByCode.get(seed.code)??seed.code;
 const item:VivianeEnglishCompanion={
  code:seed.code,grammarTarget:seed.grammar,pronunciationTarget:seed.pronunciation,
  professor:{status:'offline_authored_not_live',referenceMinutes:10,hardLimit:false,startingEnglishSharePct:55,openingQuestion:seed.opening,selectiveCorrection:seed.correction,transferPrompt:seed.transfer,evidenceBoundary:'Text and an offline guide do not establish listening, pronunciation or spontaneous-speaking performance. Only a live evaluated interaction can add that evidence.'},
  premiumAudio:{status:'outline_only_no_generation',role:'core-contextual-listening',estimatedMinutes:10,segments:[`Context and listening goal · ${title}`,'Natural model dialogue at B1+ speed, followed by a shorter second pass','Language clinic: target grammar, vocabulary and pronunciation contrast','Shadowing, retrieval questions and one transfer challenge'],generationRequested:false},
 };
 return [seed.code,item];
})) as Readonly<Record<VivianeEnglishCode,VivianeEnglishCompanion>>;
